### PR TITLE
Removed files from sig-security

### PR DESCRIPTION
**Pull request by chetak123**
**Which issue(s) this PR fixes**: https://github.com/kubernetes/sig-security/issues/9

Fixes # Removed and moved sig-security-docs/OWNERS,  sig-security-external-audit,  security-audit-2019,  security-audit-2021,  sig-security-tooling/OWNERS to sig-security

### CODE REVIEW

**Comment by PushkarJ** [comment]
/label tide/merge-method-squash

(Trying this label for squashing the commits)

**Comment by savitharaghunathan** [comment]
> /label tide/merge-method-squash
> 
> 
> 
> (Trying this label for squashing the commits)

Nice label magic!

**Comment by tabbysable** [comment]
/approve

Thanks for the help @chetak123

**Pull request merged**
