### PR TITLE
Tombstone security-release-process.md, point to sig-release

### PR DESCRIPTION
**Pull request by spiffxp**
The doc was copied over to sig-release a while ago but then that
copy was never made authoritative

This originally started as an attempt to remove the last reference to community/wiki, ref: kubernetes/community#116

/hold
This depends on kubernetes/sig-release#54 getting merged

### CODE REVIEW

**Comment by cblecker** [comment]
Is the sig-release repo the right place for this? The PST has been making their updates against the k/community location.

**Comment by spiffxp** [comment]
Ultimately I just want there to be one authoritative copy, no strong opinion where, I had just been trying to consolidate all release-related docs over to kubernetes/sig-release.

WDYT? @kubernetes/kubernetes-release-managers @cjcullen @jessfraz @philips @tallclair @liggitt

**Comment by cblecker** [comment]
Yeah, no strong opinion here either. Ultimately in the ball park of the PST :)

**Comment by spiffxp** [comment]
/hold cancel
the sig-release PR has been merged

**Pull request merged**
