### PR TITLE
Update dead sig-network meeting link

### PR DESCRIPTION
**Pull request by vllry**
Someone complained last week at the SIG intro that the meeting link was broken.

### CODE REVIEW

**Comment by cblecker** [comment]
Are we cool with putting zoom meetings back in sigs.yaml? I thought we removed them intentionally.

/hold
cc: @parispittman @castrojo

**Comment by vllry** [comment]
> Are we cool with putting zoom meetings back in sigs.yaml? I thought we removed them intentionally.
> 
> /hold
> cc: @parispittman @castrojo

Good question. I'd be happy to switch it to the meeting doc link or no link.

**Comment by parispittman** [comment]
@cblecker all good now.

**Pull request merged**
