### PR TITLE
Updating sig-aws pages

### PR DESCRIPTION
**Pull request by chrislovecnm**
General updates for meeting times.  

Removing myself, for the time being, as a sig leader, as I am running out of time, focusing on my other passions.

### CODE REVIEW

**Comment by philips** [comment]
conflicts, can't merge.

**Comment by sarahnovotny** [comment]
@chrislovecnm, please fix the conflicts.  then we'll merge it.

**Comment by sarahnovotny** [comment]
@chrislovecnm could you fix the conflicts on this?

**Comment by chrislovecnm** [comment]
Let me close this and redo. I have a reminder set for Thursday

**Pull request closed without merging**
