### PR TITLE
change sig-windows contact details

### PR DESCRIPTION
**Pull request by michmike**
updated my github account (the lead of sig-windows) to the accurate one and also slightly updated our mission statement

### CODE REVIEW

**Comment by michmike** [comment]
cc @jamiehannaford

**Comment by jamiehannaford** [comment]
@michmike You always need to build the docs after editing `sigs.yaml`. You can do so by running `make all` from the project root :)

**Comment by jamiehannaford** [comment]
@idvoretskyi Not a big deal but the README hasn't been generated. I can follow up with a PR tomorrow if it's too late to fix.

**Comment by idvoretskyi** [comment]
@jamiehannaford ah, ok

**Comment by cblecker** [comment]
I'm going to merge this to get it in.

@jamiehannaford would you mind regenerating the docs after this is done?

/lgtm

**Pull request merged**
