### PR TITLE
Update provider-openstack project co-leads

### PR DESCRIPTION
**Pull request by ramineni**
This PR updates provider-openstack project co-leads

**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Comment by ramineni** [comment]
cc @adisky @lingxiankong

**Comment by ramineni** [comment]
cc @chrigl

**Comment by adisky** [comment]
@ramineni Please remove my name too :)

**Comment by nikhita** [comment]
@ramineni can you also squash the commits into a single commit? thanks!

**Comment by ramineni** [comment]
> @ramineni can you also squash the commits into a single commit? thanks!

done

**Pull request merged**
