### PR TITLE
sig-cl: change ML to kubernetes.io

### PR DESCRIPTION
**Pull request by neolit123**
use the new sig ml in all locations in k/community:
https://groups.google.com/a/kubernetes.io/g/sig-cluster-lifecycle

also link our calendar in various places.

xref
https://groups.google.com/a/kubernetes.io/g/sig-cluster-lifecycle/c/vlF7K8XO3QU

### CODE REVIEW

**Comment by neolit123** [comment]
/assign @mrbobbytables @palnabarun 

PTAL for lgtm/approve

**Review by fabriziopandini — COMMENTED** [review]
Thanks for taking care of this Lubomir!
/lgtm

**Review by mrbobbytables — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
