### PR TITLE
WG-Batch leads update

### LINKED ISSUE #7618: WG Batch: Leadership Change
### SIG/WG name:

WG Batch

### Onboarding Lead(s):

alculquicondor, asm582, mwielgus

### Offboarding Lead(s):

ahg-g, Huang-Wei, endocrimes

### Link to discussion:

https://groups.google.com/a/kubernetes.io/g/dev/c/GO3VWQ8uqtU and https://groups.google.com/a/kubernetes.io/g/dev/c/31myk7gouvA

### Prerequisites for new leads:

- [X] Are a [Kubernetes Org member](https://git.k8s.io/community/community-membership.md)
- [ ] Have completed the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Onboarding / Offboarding tasks:

- [x] Updated [sigs.yaml](https://git.k8s.io/community/sigs.yaml) and associated [generated files](https://git.k8s.io/community/generator) (ran `make`). **NOTE:** If offboarding, remember to add to emeritus. https://github.com/kubernetes/community/pull/7619 
- [x] Updated [OWNERS_ALIASES](https://git.k8s.io/org/OWNERS_ALIASES) in [kubernetes/org](https://git.k8s.io/org/). https://github.com/kubernetes/org/pull/4634
- [x] ~~Updated [milestone maintainers team](https://git.k8s.io/org/config/kubernetes/sig-release/teams.yaml) in [kubernetes/org](https://git.k8s.io/org/).~~
- [x] Checked for and updated any other potential teams in [kubernetes/org](https://git.k8s.io/org/).
- [x] Updated [OWNERS_ALIASES](https://git.k8s.io/enhancements/OWNERS_ALIASES) in [kubernetes/enhancements](https://github.com/kubernetes/enhancements). https://github.com/kubernetes/enhancements/pull/4372
- [x] Updated [OWNERS_ALIASES](https://git.k8s.io/k8s.io/OWNERS_ALIASES) in [kubernetes/k8s.io](https://git.k8s.io/k8s.io/). https://github.com/kubernetes/k8s.io/pull/6217
- [x] Updated [membership](https://git.k8s.io/k8s.io//groups/groups.yaml) of the [leads mailing list](https://groups.google.com/a/kubernetes.io/g/leads) https://github.com/kubernetes/k8s.io/pull/6217
- [x] Updated membership for any other [mailing list / groups](https://git.k8s.io/k8s.io//groups/). https://github.com/kubernetes/k8s.io/pull/6217
- [x] Added to `#chairs-and-techleads` slack channel.
- [x] Updated ownership of group leads mailing list. https://github.com/kubernetes/k8s.io/pull/6217
- [x] Updated ownership of group mailing list. 
- [x] Updated ownership of group calendar. https://github.com/kubernetes/k8s.io/pull/6217
- [x] Updated access/teams in 1password. (Contact ContribEx leads to complete)

### Additional information:

_No response_

### Labels:

_No response_

### PR DESCRIPTION
**Pull request by soltysh**
**Which issue(s) this PR fixes**:
Ref #7618

/assign @mwielgus @swatisehgal @Huang-Wei @endocrimes

### CODE REVIEW

**Comment by swatisehgal** [comment]
@asm582 It is a prerequisite to be a Kubernetes org member before you can be added as a lead. Can you review the [membership-requirements](https://github.com/kubernetes/community/blob/master/github-management/new-membership-procedure.md#membership-requirements) and [open an issue](https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-membership&template=membership.yml&title=REQUEST%3A+New+membership+for+%3Cyour-GH-handle%3E) in the community repo to be added as a Kubernetes member. Thanks!

**Comment by soltysh** [comment]
/hold
this is being discussed

**Comment by soltysh** [comment]
Based on the discussions with the rest of the leads and with our steering liaison we've decided not to promote @asm582 to lead until he earns the necessary recognition 

/hold cancel

**Review by swatisehgal — APPROVED** [review]
/lgtm

**Pull request merged**
