### PR TITLE
Add project `kro` to slack channels

### PR DESCRIPTION
**Pull request by a-hilaly**
Add a new slack channel 'kro' to facilitate discussions around Kube Resource Orchestrator implementation and usage.

Link: https://kro.run/

### CODE REVIEW

**Comment by jberkus** [comment]
Seems legit, but want approval by 2nd admin.

/lgtm

**Comment by csantanapr** [comment]
Thank you @jberkus 👍

**Comment by csantanapr** [comment]
Thank you @jeefy

**Pull request merged**
