### PR TITLE
Added Developer notes in a subfolder

### PR DESCRIPTION
**Pull request by jberkus**
Changes in this PR:

* Created a subfolder, developer_summit_2016, to hold all developer summit materials.
* Moved three documents to that subfolder.
* Added raw notes on three sessions: Cluster Federation, StatefulSets, and Application/Service Definition.

### CODE REVIEW

**Comment by jberkus** [comment]
I signed it!

**Comment by philips** [comment]
@jberkus nit: this repo uses `-` instead of `_` as whitespace in folder names.

cc @sarahnovotny

**Comment by jberkus** [comment]
Folder name fixed.

**Comment by philips** [comment]
@jberkus filenames too but it is OK. Merging.

**Comment by jberkus** [comment]
@philips most of the filenames aren't actually mine.

**Pull request merged**
