### PR TITLE
updated SIG Windows leads

### PR DESCRIPTION
**Pull request by sarahnovotny**
new version of un-rebased kubernetes/community/pull/67

### CODE REVIEW

**Comment by sarahnovotny** [comment]
@michmike and @asultan001, PTAL?

**Comment by michmike** [comment]
@sarahnovotny , i still see the old contacts (patrick and sinclair) on this page. https://github.com/kubernetes/community/blob/master/README.md#special-interest-groups-sig

is there an update delay?

**Comment by sarahnovotny** [comment]
@michmike this is the pull request to fix that.  the older PR from @josephjacks was stuck waiting for a rebase.  I closed it and then made this one.  that link should be set now.

**Comment by josephjacks** [comment]
Thanks @sarahnovotny - sorry for the delay.

**Pull request merged**
