### PR TITLE
Add devfile channel

### PR DESCRIPTION
**Pull request by elsony**
Signed-off-by: eyuen <eyuen@redhat.com>

**Which issue(s) this PR fixes**:
N/A

Hi! This request is to create a slack channel for discussing things related to the devfiles. 

**Information about us:**
Devfile is an open-source project that provides an open standard defining containerized development environments that enable developer tools to simplify and accelerate workflows. It helps to make the development environment easily reproducible as well.

Our project has a strong tie to Kubernetes. Some of the existing Kubernetes-specific tools are using the devfile support, e.g. odo (https://odo.dev/), Eclipse Che (https://eclipse.org/che/), Dev Workspace (https://github.com/devfile/devworkspace-operator), and OpenShift Developer Console. 
If you want to know more about the devfile project, here are some starting points:
* Project page: https://devfile.io/
* GitHub org: https://github.com/devfile
* Main GitHub repo for issue tracking is here: https://github.com/devfile/api

**Purpose of the channel:**
In the past, we've been using Gitter for the communication channel but most of the project members are on slack. Amazon AWS, JetBrains, and IBM have also joined the devfile project. Moving to slack will make it much easier to discuss the devfile related topics. And many of our existing members are already on the Kubernetes slack so we are hoping to use Kubernetes slack as our main chatting channel.

**Criteria:**
I believe we fit all the criteria, we're:
* An open-source project
* Strong tie to Kubernetes
* Not product focused / proprietary

**Chatroom name requested:**
devfile

If you have any questions on this request, feel free to reach out to us!

### CODE REVIEW

**Comment by Debanitrkl** [comment]
@elsony could you please sign the CLA as mentioned here  
https://github.com/kubernetes/community/pull/6300#issuecomment-996006045 for this PR to be reviewed

**Comment by coderanger** [comment]
/ok-to-test
/lgtm

Once you get the CLA sorted we can merge this.

**Comment by elsony** [comment]
@Debanitrkl I have signed the CLA already. Is there anything else that I need to do to unblock this? Thanks!

**Review by Debanitrkl — APPROVED** [review]
LGTM

**Review by mrbobbytables — COMMENTED** [review]
/approve

**Pull request merged**
