### PR TITLE
categorize and expand api machinery projects

### PR DESCRIPTION
**Pull request by lavalamp**

### CODE REVIEW

**Comment by lavalamp** [comment]
@pwittrock

**Comment by lavalamp** [comment]
will fix test after I repair my local go stack (had to reimage my machine not long ago and 'make generate' makes very poor assumptions about the environment).

**Comment by cblecker** [comment]
@lavalamp `make generate-dockerized` runs the same within a golang docker container

**Comment by lavalamp** [comment]
too late, already fixed my computer ;)

**Comment by lavalamp** [comment]
Filed https://github.com/kubernetes/community/issues/1913 since I'm definitely never going to find time to maintain this list after this PR merges.

**Comment by bgrant0607** [comment]
@lavalamp Yes, we plan to eventually generate these lists bottom-up from the OWNERS files, but we don't have that machinery yet.

**Comment by bgrant0607** [comment]
Cool. Thanks for adding the additional directories and rationalizing the categories.

/lgtm

**Pull request merged**
