### PR TITLE
Update files in the community repo to point to multicluster rather than federation.

### PR DESCRIPTION
**Pull request by perotinus**

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
sub-dir `contributors/design-proposals/federation` should also be renamed :)

**Comment by perotinus** [comment]
@xiangpengzhao Good point, I hadn't looked closely and thought that directory was named after the feature and not the sig. Should be fixed now.

**Comment by perotinus** [comment]
Should be rebased now.

**Comment by nikhiljindal** [comment]
Thx @perotinus

**Pull request merged**
