### PR TITLE
Update a lot of typos

### PR DESCRIPTION
**Pull request by zhxcai**

### CODE REVIEW

**Comment by stp-ip** [comment]
Thanks for bundling typos up. So helpful not to review one PR per typo.

LGTM

**Comment by stp-ip** [comment]
If it's still WIP, please add a [WIP] as prefix in the title. That helps people not review it after you feels it's done.
For the latest changes: LGTM

**Comment by stp-ip** [comment]
As a sidenote on git commit messages: https://chris.beams.io/posts/git-commit/

**Comment by zhxcai** [comment]
I don't need update it later, thanks

**Comment by zhxcai** [comment]
@stp-ip thanks for your suggest, i will put it into practice next times

**Pull request merged**
