### PR TITLE
Update channels.yaml to add AWS VPC CNI

### PR DESCRIPTION
**Pull request by jayanthvn**
**Which issue(s) this PR fixes**: N/A

Proposal for new channel dedicated to discussion of AWS VPC CNI - https://github.com/aws/amazon-vpc-cni-k8s

### CODE REVIEW

**Review by markyjackson-taulia — APPROVED** [review]
Adding the lgtm and a hold for other slack admins to review
/lgtm
/hold

**Comment by jdumars** [comment]
Looks active and healthy!
/approve

**Pull request merged**
