### PR TITLE
Fix typo in resource-qos.md

### PR DESCRIPTION
**Pull request by davidxia**

### CODE REVIEW

**Comment by davidxia** [comment]
@errordeveloper does the tide bot need something to be able to merge?

**Comment by nikhita** [comment]
/assign @cblecker 
for approval

**Comment by cblecker** [comment]
/unassign
/assign @derekwaynecarr 

sig-node can approve this themselves

**Comment by davidxia** [comment]
@cblecker Is there anything I can do to nudge this along?

**Comment by nikhita** [comment]
ping @derekwaynecarr can you approve this?

**Pull request merged**
