### PR TITLE
Adding Bart Smykla as co-chair for wg-k8s-infra

### PR DESCRIPTION
**Pull request by dims**
Email Thread : https://groups.google.com/d/msg/kubernetes-wg-k8s-infra/foHmM_g1-UA/GHyWIVgtAQAJ

### CODE REVIEW

**Comment by dims** [comment]
cc @cblecker @bartsmykla @spiffxp @thockin @listx @BenTheElder @hh

**Comment by cblecker** [comment]
/lgtm
/approve
/hold

Holding for Wednesday when lazy consensus closes :)

**Comment by dims** [comment]
It's wednesday! @cblecker please do the honors when appropriate.

**Pull request merged**
