### PR TITLE
Clean up & add new members to contributor-comms slack usergroup

### PR DESCRIPTION
**Pull request by rajula96reddy**

### CODE REVIEW

**Comment by chris-short** [comment]
It's easy to add folks back if they need it.

/lgtm

/approve

**Comment by chris-short** [comment]
It's early... I don't have approve perms in this repo.

/assign @coderanger

**Comment by markyjackson-taulia** [comment]
I think to be safe we should have people who are being added and removed to +1 this pr
/hold

**Review by Debanitrkl — APPROVED** [review]
+1 glad to be a part of contrib-comms :)

**Comment by Atharva-Shinde** [comment]
+1 from my side as well, would love to be a part of contributor-comms <3

**Review by Debanitrkl — APPROVED** [review]
All the folks involved here are made aware of this
/remove-hold
/lgtm

**Pull request merged**
