### PR TITLE
slack config: add Capsule channel

### PR DESCRIPTION
**Pull request by maxgio92**
Hi, I'd like to propose a Slack channel for [Capsule](https://capsule.clastix.io/docs/).

Capsule implements a multi-tenant and policy-based environment in your Kubernetes cluster. It is designed as a micro-services-based ecosystem with the minimalist approach, leveraging only on upstream Kubernetes.
Currently is the soft multi-tenancy solution that [Clastix](https://clastix.io/) provides.

- [Capsule](https://github.com/clastix/capsule/)
- [Capsule Community](https://github.com/clastix/capsule-community)

We would like to make growing the community on the Kubernetes workspace, in order to make it easier the access to the cloud native community and be present also for other cloud native projects, on the same workspace.

For example we contributed to other cloud native proejcts like Kubespray and Falco.

Thank you!

### CODE REVIEW

**Review by markyjackson-taulia — APPROVED** [review]
This looks fine. Holding for other moderators to review.
/lgtm
/hold

**Comment by maxgio92** [comment]
Thank you very much @markyjackson-taulia. Appreciate this a lot! <3

**Comment by castrojo** [comment]
/approve

Remove the hold at your convenience @markyjackson-taulia!

**Comment by maxgio92** [comment]
Thank you all <3

**Pull request merged**
