### PR TITLE
add Saiyam Pathak bio

### LINKED ISSUE #6093: Steering Committee Nomination: Saiyam Pathak (@saiyam1814)
Hello everyone!
I would like to self nominate for the 2021 Steering Committee election.
I have been part of the Kubernetes community in different ways for many years now- first as an end-user trying to understand how K8s worked. Today, I spend much of my time welcoming and educating new users to the k8s and cloud native community.
I've also been a heavy Kubernetes user for many years at different organizations (Oracle, Walmart Labs, Civo). Most recently I have been involved in shaping up the Chaos Engineering WG.
I'm interested in giving more back to the community and project as a part of the steering community.

/committee steering

### PR DESCRIPTION
**Pull request by saiyam1814**
Fixes #6093

### CODE REVIEW

**Comment by coderanger** [comment]
@saiyam1814 As the bot mentioned above, we don't allow github references in the commit messages themselves because it creates a lot of noise when our repos are vendored (which they frequently are). You'll need to `git rebase -i` and change the commit message, and then force update the branch on your side.

**Comment by jberkus** [comment]
Please rename the file `candidate-saiyam1814`

**Comment by MadhavJivrajani** [comment]
@saiyam1814  - from the [test logs](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/community/6151/pull-community-verify/1448622449020112896):
>  1 invalid Steering Committee election bio(s) detected.
Bios should be limited to around 300 words, excluding headers. 

Please see the `Running` section [here](https://github.com/kubernetes/community/tree/master/events/elections/2021#candidacy-process) for more information.

**Comment by jberkus** [comment]
@saiyam1814 it's 450 in order to allow for links and headers, since wc kinda counts everything.

**Pull request merged**
