### PR TITLE
SIG-Autoscaling charter

### PR DESCRIPTION
**Pull request by mwielgus**
Charter for SIG-Autoscaling. Used SIG-Architecture charter as a template and earlier drafts of the charter as reference.

cc: @DirectXMan12 @MaciekPytel

### CODE REVIEW

**Comment by DirectXMan12** [comment]
We already have a charter PR open that's under review (#2425 )

**Comment by DirectXMan12** [comment]
was there something wrong with that one?

**Comment by mwielgus** [comment]
Nothing, I was pinged recently to do it and forgot about that you had a PR with it.

**Comment by DirectXMan12** [comment]
cool, I figured that's what happened, just wanted to double check :-)

**Pull request closed without merging**
