### PR TITLE
sig-list: update multitenancy wg meeting schedule

### PR DESCRIPTION
**Pull request by egernst**
The multitenancy working group now meets on Tuesdays.  Updating the
resulting .mds to take this into account.

Fixes: #3250

Signed-off-by: Eric Ernst <eric.ernst@intel.com>

### CODE REVIEW

**Comment by nikhita** [comment]
@tashimi You can apply for @kubernetes org membership by creating an issue [here](https://github.com/kubernetes/org/issues/new?template=membership.md&title=REQUEST%3A%20New%20membership%20for%20%3Cyour-GH-handle%3E). This will allow you to use your approval powers. :)

**Comment by davidopp** [comment]
/lgtm
/approve

(though I'm not sure I have any useful permissions

**Comment by nikhita** [comment]
/assign @cblecker 
for approval

**Pull request merged**
