### PR TITLE
Update a few OWNERS files

### PR DESCRIPTION
**Pull request by cblecker**
- alpha sort steering-committee alias
- Update top-level OWNERS with steering-committee alias
- Update sig docs generator OWNERS

### CODE REVIEW

**Comment by grodrigues3** [comment]
I don't know the generator code that well.  I"d be ok just being a reviewer in that directory.  Other than that lgtm

/lgtm
/hold

**Comment by cblecker** [comment]
@grodrigues3 I mostly updated it this way because contribex "owns" the code as it were.

**Pull request merged**
