### PR TITLE
Add multi-network channel.

### LINKED ISSUE #6751: REQUEST: New Slack channel multi-network
### GitHub Username

mskrocki

### Slack Username

mskrocki

### What Type of Request is it (Channel, User Group, Bot, Token, or Webhook)?

Channel

### Name of Requested Resource

multi-network

### Description of Request

We have formed a workgroup to work on introducing multi network concept and a Network construct into Kubernetes. We would like to have a slack channel where we can easily discuss our ideas.

### PR DESCRIPTION
**Pull request by mskrocki**
This PR adds multi-network channel where community will discuss on introducing multi network concept and a Network construct into Kubernetes.

Fixes #6751

### CODE REVIEW

**Comment by coderanger** [comment]
Is this something run by a SIG? If so can it be under that SIG namespace?

**Comment by mskrocki** [comment]
It is network related so I think it would fall under the network SIG, and yeah it could be under that namespace.
/Cc @dcbw @thockin @aojea

**Comment by aojea** [comment]
/ok-to-test
LGTM

@thockin for the naming, he loves that :smile:

**Review by markyjackson-taulia — APPROVED** [review]
This looks good. Adding the lgtm label and holding for another slack admin to review as well.
Once that is reviewed and the approved label added, the hold will be canceled and this will merge automagically.

/lgtm
/hold

**Comment by markyjackson-taulia** [comment]
Cc @coderanger

**Comment by coderanger** [comment]
"under the SIG namespace" means make the channel name something like `#sig-networking-multinetwork` or similar, so it's clearly associated with the SIG.

**Comment by jellonek** [comment]
@dcbw ping. can you take a quick look there?

**Comment by jberkus** [comment]
Channel has been renamed properly.

/lgtm
/approve

@dcbw @thockin @aojea if you have no objections, I'll remove the hold in a day or so.

**Comment by aojea** [comment]
> Once that is reviewed and the approved label added, the hold will be canceled and this will merge automagically.

/lgtm

Thanks Josh,

**Pull request merged**
