### PR TITLE
updated docs-channels.yaml for bengali language.

### PR DESCRIPTION
**Pull request by rajibmitra**
Coordinating Bengali language localization of Kubernetes documentation, 
https://en.wikipedia.org/wiki/Bengali_language

### CODE REVIEW

**Comment by rajibmitra** [comment]
cc @nikhita

**Comment by palnabarun** [comment]
Wonderful! Sign me up for anything required. :)
/cc

**Comment by palnabarun** [comment]
/uncc

My bad! I was confused about the usage of `/cc`.

**Comment by rajibmitra** [comment]
Thanks @palnabarun ! :)

**Comment by jdumars** [comment]
/lgtm
leaving approve for SIG-docs, or I can proxy approve later

**Pull request merged**
