### PR TITLE
added a playlist for WG Serving

### PR DESCRIPTION
**Pull request by SergeyKanzhelev**
/wg serving

related to https://github.com/kubernetes/community/issues/7850

### CODE REVIEW

**Review by terrytangyuan — APPROVED** [review]
/lgtm

**Comment by terrytangyuan** [comment]
Looks like https://github.com/kubernetes/community/pull/7904 got merged faster than this one. 

@SergeyKanzhelev Would you like to close this and update https://github.com/kubernetes/community/issues/7850?

**Comment by ArangoGutierrez** [comment]
> Looks like #7904 got merged faster than this one.
> 
> @SergeyKanzhelev Would you like to close this and update #7850?

I created https://github.com/SergeyKanzhelev/community-1/pull/2 to help with this

**Comment by terrytangyuan** [comment]
> > Looks like #7904 got merged faster than this one.
> 
> > 
> 
> > @SergeyKanzhelev Would you like to close this and update #7850?
> 
> 
> 
> I created https://github.com/SergeyKanzhelev/community-1/pull/2 to help with this 

This change is no longer needed since another same change has been merged

**Comment by ArangoGutierrez** [comment]
> > > Looks like #7904 got merged faster than this one.
> > 
> > 
> > > 
> > 
> > 
> > > @SergeyKanzhelev Would you like to close this and update #7850?
> > 
> > 
> > I created [SergeyKanzhelev#2](https://github.com/SergeyKanzhelev/community-1/pull/2) to help with this
> 
> This change is no longer needed since another same change has been merged

Yeah I saw that, but noticed the links are different

**Comment by terrytangyuan** [comment]
The links look the same to me

**Comment by ArangoGutierrez** [comment]
> The links look the same to me

`PL69nYSiGNLP30qNanabU75ayPK7OPNAAS&si=XUgX-PkFahKEVxPg` vs `PL69nYSiGNLP30qNanabU75ayPK7OPNAAS `

**Comment by terrytangyuan** [comment]
Hmm I see. They both lead to the same playlist though.

**Comment by ArangoGutierrez** [comment]
> `PL69nYSiGNLP30qNanabU75ayPK7OPNAAS&si=XUgX-PkFahKEVxPg` vs `PL69nYSiGNLP30qNanabU75ayPK7OPNAAS `

The additional parameter `si` stands for session identifier or session info. This parameter is typically used by YouTube to track certain metadata about the user's session. It might include information for improved tracking, personalization, or analytics purposes.

I think CNCF users prefer links without data trackers

**Comment by SergeyKanzhelev** [comment]
thank you for noticing and fixing this PR!

**Review by terrytangyuan — APPROVED** [review]
/lgtm

**Comment by SergeyKanzhelev** [comment]
/assign @pacoxu 

Can you please help merge this?

**Pull request merged**
