### PR TITLE
Add #garden and #garden-dev Slack Channels

### PR DESCRIPTION
**Pull request by ellenkorbes**
Hi! I work at [Garden.io](https://garden.io/), we're responsible for the eponymous development tool, [Garden](https://github.com/garden-io/garden). 

We'd like to be more easily accessible to the Kubernetes community, and since Garden is completely OSS, we'd like to have our development channel on Kubernetes Slack as well.

### CODE REVIEW

**Comment by jeefy** [comment]
@ellenkorbes Heya! Quick nit, could you change the `garden` entry to `garden-users`? This is a pattern that is followed by a lot of similar projects. :) Once you do that (and make sure it's alphabetized after the change) we can push this through.


Thanks!

**Comment by ellenkorbes** [comment]
@jeefy Is this a hard requirement? I see some entries that just omit the `-users` prefix, e.g. cert-manager, kubespray, and minikube.

**Comment by jeefy** [comment]
@ellenkorbes Nah, not a hard requirement. You're 💯 right. When I was glancing through the channel list I saw a few that followed the -users/dev pattern. :)

/retest
/approve

**Pull request merged**
