### PR TITLE
Add sig-network-service-apis slack channel.

### PR DESCRIPTION
**Pull request by bowei**
Adds the sig-network-service-apis slack channel.
As this is the first time, also adds OWNERS file
to the sig-network/ directory.

### CODE REVIEW

**Comment by bowei** [comment]
@thockin @caseydavenport

**Comment by thockin** [comment]
Thanks!

/lgtm

**Comment by mrbobbytables** [comment]
@bowei looks like theres a conflict 😬 should be a quick fix though.

**Comment by bowei** [comment]
Fixed -- let's see if it passes

**Pull request merged**
