### PR TITLE
Fix link to contributor cheatsheet in guide

### PR DESCRIPTION
**Pull request by askervin**

### CODE REVIEW

**Comment by askervin** [comment]
Good point. Link in ``sig-cli/CONTRIBUTING.md`` link is now absolute - and only to the directory

**Comment by mrbobbytables** [comment]
Sorry for the small bits of back and forth -- but for uniformity sake, would you mind updating all of them to either point to the readme directly or to the directory?

After that if you can squash your commits down I'll lgtm :)

Thank you for catching all this and taking the time to update the links. It's definitely appreciated.

**Comment by askervin** [comment]
No problem, @mrbobbytables :)
Links harmonized, commits squashed for cleaner merge.

**Comment by mrbobbytables** [comment]
Awesome, thanks! :)
/lgtm
/assign @idvoretskyi

**Pull request merged**
