### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Henrywu573**
**Which issue(s) this PR fixes**:

Fixes the broken link for sig etcd slack channel.

### CODE REVIEW

**Comment by wenjiaswe** [comment]
/lgtm
/approve
Thanks!

**Comment by wenjiaswe** [comment]
Ah, that's right, you will want to change the sig metadata in https://github.com/kubernetes/community/blob/ff2666136fa6ff3e561ef73e9eff8c0d76db1c38/sigs.yaml#L1728

**Comment by ahrtr** [comment]
> Ah, that's right, you will want to change the sig metadata in
> 
> https://github.com/kubernetes/community/blob/ff2666136fa6ff3e561ef73e9eff8c0d76db1c38/sigs.yaml#L1728

Right, you need to update sigs.yaml, then execute "`make generate`".

Thanks both.

**Comment by ahrtr** [comment]
Looks good, but can you please squash the commits?

**Comment by Henrywu573** [comment]
> Looks good, but can you please squash the commits?

Done.

**Comment by ahrtr** [comment]
/lgtm
/approve

Thanks!

**Review by mrbobbytables — COMMENTED** [review]
/approve

**Pull request merged**
