### PR TITLE
Refactor governance docs

### PR DESCRIPTION
**Pull request by pwittrock**
- Split governance.md into multiple documents
- Merge sig governance section with sig-creation-process

### CODE REVIEW

**Comment by jbeda** [comment]
This looks great to me.  Makes it much more readable and approachable, IMO.  It also let's us evolve the parts without having to rethink all the things.  Thanks for doing it!

**Comment by pwittrock** [comment]
@jbeda Thanks :)  Once this is merged, I will start working on evolving the org membership requirements.

Is there anything you would like to see before merging this?

**Comment by jbeda** [comment]
If this is just a refactor (looks like it but didn't check every line) then ship it!

**Comment by pwittrock** [comment]
@jbeda FYI.  I actually ended up deleting most of the content about "roles" at Brian's suggestion.  I am going to merge this.  Let me know if you would like me to add it back in.

**Pull request merged**
