### PR TITLE
Add a slack group for Velero maintainers

### PR DESCRIPTION
**Pull request by carlisia**
Please add a slack group for the [Velero](https://velero.io) maintainers.

### CODE REVIEW

**Comment by carlisia** [comment]
@ashish-amarnath 
@skriss 
@nrb 
@stephbman 

Please approve.

**Comment by markyjackson-taulia** [comment]
@carlisia stephbman does not appear to be a valid slack user. This caused the test to fail.

**Comment by carlisia** [comment]
Hm. Odd. I doubled checked just now and that's her ID on the Kubernetes Slack.

image

**Comment by markyjackson-taulia** [comment]
I think the slack user name is `@Stephanie Bauman` not `@stephbman` in slack

**Comment by carlisia** [comment]
That is correct. Is this supposed to be a slack user name or a GH user name: https://github.com/kubernetes/community/pull/4783/files#diff-be06569e21dea8f049b92576b3e02733R52

That is the GH user name. If it's supposed to the their slack's I'll change it. :)

**Comment by markyjackson-taulia** [comment]
oh my, you're right! I apologize. Let me see here

**Comment by markyjackson-taulia** [comment]
@carlisia can you remove @stephbman from the PR for now? This will make the test pass. We identified the core of the issue but before we can fix it, we want to verify an item on the slack side with regards to the unique user identifier, more specifically to the number of digits of that identifier. We have a limit of 9 characters but it seems this user has 11, that is the root cause. The fix is easy but we want to be sure that 11 is the new limit.

**Pull request merged**
