### PR TITLE
sig-contribex apac coordinator handbook august update

### PR DESCRIPTION
**Pull request by idealhack**
- added new members to sig-contribex apac coordinator team
- updated the time of sig-contribex apac coordinator team meeting, and added a note on how to join the meeting
- added sig-contribex apac coordinator team meeting to sigs.yaml (addressed https://github.com/kubernetes/community/pull/3804/files#r296273431); also removed outdated sig-contribex apac meeting

/cc @nikhita @parispittman

### CODE REVIEW

**Comment by idealhack** [comment]
/hold

for discussing meeting time change: https://kubernetes.slack.com/archives/C1TU9EB9S/p1564651617313200?thread_ts=1564638696.311200&channel=C1TU9EB9S&message_ts=1564651617.313200

**Comment by nikhita** [comment]
Lgtm pending time change

**Comment by idealhack** [comment]
Given that most of the team members have agreed on the time change, I have pushed the new time here.

/hold cancel

cc @aravindputrevu @alisondy @saiyam1814 @Pensu @tao12345666333

**Comment by parispittman** [comment]
/approve

thanks team!! this is so great!

**Pull request merged**
