### PR TITLE
Initial commit for Contrib Summit 2018 EU

### PR DESCRIPTION
**Pull request by castrojo**
This is mostly a placeholder for now but will let us announce and socialize the event early.

### CODE REVIEW

**Comment by idvoretskyi** [comment]
@castrojo looks great, thank you for starting this.

**Comment by idvoretskyi** [comment]
/hold cancel

Let's move on now.

**Comment by jberkus** [comment]
hmmm ... is there going to be any time for discussions of meta issues?  for example, I wanted to propose a session on "growing the senior reviewer pool".

**Pull request merged**
