### PR TITLE
Update meeting time to correct time.

### PR DESCRIPTION
**Pull request by josepalafox**

### CODE REVIEW

**Comment by idvoretskyi** [comment]
@josepalafox please, sign the CLA to proceed with the PR.

Also, please, don't change the file directly, we have a specific procedure to edit SIG-related information in this repo - https://github.com/kubernetes/community/blob/master/generator/README.md

**Comment by josepalafox** [comment]
CLA is completed via Intel corp CCLA with CNCF

**Comment by spiffxp** [comment]
@josepalafox This README is generated.  You're going to need to make this change in [`sigs.yaml`](/sigs.yaml) and re-run `make` to update the appropriate docs.  See [generator docs](https://github.com/kubernetes/community/blob/eda1515795e583521b3395ec5c9ebf620e44942a/generator/README.md) for more info

**Comment by josepalafox** [comment]
Completed proper steps. New PR:https://github.com/kubernetes/community/pull/1678

@spiffxp thanks for the pointer.

**Pull request closed without merging**
