### PR TITLE
Adding Service APIs office hours meeting, removing Ingress meeting

### PR DESCRIPTION
**Pull request by robscott**
This adds the weekly Service APIs office hours meeting and removes the no longer necessary biweekly Ingress meeting. This matches what is currently represented on our community page here: https://kubernetes-sigs.github.io/service-apis/community/.

It sounds like we need to use a separate Zoom link for the sake of YouTube auto upload titles, so for now I'm reusing what we had for the Ingress GA meeting. If you can update the title of that call in Zoom that would be great (or provide a different Zoom link we should use).

/cc @bowei 
/assign @mrbobbytables

### CODE REVIEW

**Comment by robscott** [comment]
Hey @nikhita, thanks for approving this! Just to clarify since I don't have access to the sig-network Zoom account directly, has the "Ingress GA meeting" that's now being used for "Service APIs Office Hours" been renamed in Zoom as well?

**Comment by mrbobbytables** [comment]
@robscott -- It's not, but I can update it. In general that's going to be up to the sig leads to do that sort of thing. The zoom admins don't have direct access to the account except when automation is being configured.

**Comment by robscott** [comment]
Woops, that makes sense, should have thought that through. Thanks for the help!

**Comment by mrbobbytables** [comment]
Just to update -- I did make the change 👍

**Pull request merged**
