### PR TITLE
Archive 2020 SIG Node meeting notes

### PR DESCRIPTION
**Pull request by stmcginnis**
Archive 2020 meeting logs from the active working document.

Also adds a simple README landing page for the archive to help in navigation.

### CODE REVIEW

**Comment by stmcginnis** [comment]
@ehashman - I know you've said everything needs a tracking issue. This is a "paperwork" PR, so doesn't really need to be targeted to any milestones. But still would be nice to get in. Anything I should do to help move this along? Thanks!

**Comment by ehashman** [comment]
@stmcginnis that's just for net new features/enhancements! This PR needs no such thing :)

**Review by ehashman — APPROVED** [review]
/lgtm

**Pull request merged**
