### PR TITLE
add grafana operator maintainer groups

### PR DESCRIPTION
**Pull request by HubertStefanski**
Signed-off-by: Hubert Stefanski <hstefans@redhat.com>

**Which issue(s) this PR fixes**:
NA
- This PR adds a user group for grafana-operator maintainers/support

Fixes # NA

### CODE REVIEW

**Comment by mrbobbytables** [comment]
@HubertStefanski would you mind rebasing? After that we can merge it^^;;;

**Comment by HubertStefanski** [comment]
@mrbobbytables Rebased!, thanks :wink:

**Pull request merged**
