### PR TITLE
Notes from the Cluster Lifecycle Deployment & Upgrade Roadmap session at Kubernetes Dev Summit 2016

### PR DESCRIPTION
**Pull request by roberthbailey**
Original notes were at https://docs.google.com/document/d/11kK39Zz3zxIY9-GFa8buqqWYOrctFQ7hvOw5NBFwJL0/edit#

### CODE REVIEW

**Comment by roberthbailey** [comment]
ping @sarahnovotny

**Comment by chrislovecnm** [comment]
Sarah's on leave ;) You need a proof read or just a merge?

**Comment by roberthbailey** [comment]
She asked folks who took notes to add them here so I sent her a PR. It can wait until she's back.

**Comment by bgrant0607** [comment]
Merge and iterate. LGTM

**Pull request merged**
