### PR TITLE
Slack channel for discussion of the PureLB load balancer

### PR DESCRIPTION
**Pull request by acnodal-tc**
[PureLB](https://gitlab.com/purelb/purelb) is a new open source load
balancer controller for Kubernetes.  May we please have a slack
channel for user discussion?

Thank you

### CODE REVIEW

**Comment by jdumars** [comment]
I looked over the project and it seems like you've got a good start. Please resolve the CLA issue and we'll move forward from there.

/ok-to-test

**Comment by acnodal-tc** [comment]
I signed it

**Comment by acnodal-tc** [comment]
Thank you @jdumars for your speedy response! It took a minute to get our company signed up but I think we're all set now.

**Review by markyjackson-taulia — APPROVED** [review]
/lgtm

**Comment by acnodal-tc** [comment]
@adamdunstan

**Comment by acnodal-tc** [comment]
Thank you to everyone involved; I appreciate the speedy response!

**Pull request merged**
