### PR TITLE
governance: Dissolution of WG Naming

### PR DESCRIPTION
**Pull request by justaugustus**
Includes transfer of existing documentation to SIG Arch.

Signed-off-by: Stephen Augustus <foo@auggie.dev>

ref: https://groups.google.com/a/kubernetes.io/g/steering/c/8fy8omuKdpM
/hold for discussion
cc: @kubernetes/wg-naming-leads

Stakeholder governance groups:
@kubernetes/sig-architecture-leads @kubernetes/sig-contributor-experience-leads @kubernetes/sig-docs-leads @kubernetes/steering-committee @kubernetes/code-of-conduct-committee  

For WG Naming:
/assign @celestehorgan @jdumars

For SIG Architecture:
/assign @dims @johnbelamaric @derekwaynecarr

### CODE REVIEW

**Comment by liggitt** [comment]
the sig-architecture/naming/workflow.md file describes wg-naming mailing lists, etc... what is the expected change and staffing with the reparenting to sig-arch?

**Comment by justaugustus** [comment]
> the sig-architecture/naming/workflow.md file describes wg-naming mailing lists, etc... what is the expected change and staffing with the reparenting to sig-arch?

@liggitt -- Will peruse the WG Naming docs and do some updates there this week & include actions/questions for SIG Arch.

**Comment by justaugustus** [comment]
Placeholder enhancement tracking issue for `kubernetes/kubernetes` repo: https://github.com/kubernetes/enhancements/issues/2853

**Comment by justaugustus** [comment]
@kubernetes/sig-architecture-leads @kubernetes/wg-naming-leads -- references to WG Naming have been updated

**Comment by liggitt** [comment]
> @kubernetes/sig-architecture-leads @kubernetes/wg-naming-leads -- references to WG Naming have been updated

thanks, that resolves my question at https://github.com/kubernetes/community/pull/5938#issuecomment-895435731

**Comment by justaugustus** [comment]
> thanks, that resolves my question at [#5938 (comment)](https://github.com/kubernetes/community/pull/5938#issuecomment-895435731)

Thanks for confirming, Jordan!

**Comment by dims** [comment]
+1 wearing my sig-arch hat.

**Comment by johnbelamaric** [comment]
+1

**Comment by justaugustus** [comment]
@kubernetes/steering-committee -- for `/approve`-al
(this has been approved by SiG Arch + WG Naming leads)

**Comment by liggitt** [comment]
/lgtm
with steering hat

**Comment by mrbobbytables** [comment]
/lgtm
thanks!

**Comment by cblecker** [comment]
LGTM with both my Steering and ContribEx hats on.

Thank you so much for your work @kubernetes/wg-naming-leads !

**Comment by justaugustus** [comment]
Thanks everyone!
(Needs `/approve` to merge :))

/hold cancel

**Pull request merged**
