### PR TITLE
Changing Jay Vays to Amim Knabben as SIG-Windows tech lead

### LINKED ISSUE #7614: Leadership change: amim sig-windows
Hi folks! My personal laptop is dead so filing this issue for someone else (amim?) To help me with following up on the email to sig-windows for transitioning amim to replace me as sig windows lead!

,cc @knabben  @marosset @jsturtevant @aravindhp @claudiubelu

### PR DESCRIPTION
**Pull request by knabben**
Adding Amim Knabben as SIG-Windows TL and moving Jay Vyas to Emeritus lead 

**Which issue(s) this PR fixes**:

Fixes #7614

### CODE REVIEW

**Comment by jsturtevant** [comment]
LGTM 

Thanks @jayunit100 for all the work you've done in the community.  @knabben excited to have you on board to continue the work you've been leading

**Comment by knabben** [comment]
> LGTM
> 
> Thanks @jayunit100 for all the work you've done in the community. @knabben excited to have you on board to continue the work you've been leading

Count me in to help move the SIG Windows vision forward!

**Review by aravindhp — APPROVED** [review]
/lgtm 

Thank you for all your hard work with #sig-windows @jayunit100. Welcome on board @knabben

**Pull request merged**
