### PR TITLE
Rename slack channel seccomp-operator to security-operator

### PR DESCRIPTION
**Pull request by pjbgf**
This is part of rebranding of seccomp-operator to security-operator.

**Which issue(s) this PR fixes**:

Relates to # https://github.com/kubernetes-sigs/seccomp-operator/issues/127

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
/lgtm
/approve

**Comment by coderanger** [comment]
It seems like the project hasn't actually been renamed yet, so I think we should let the project team work that out first :)

/hold

**Comment by pjbgf** [comment]
A new name (`security-profiles-operator`) has emerged, we will present it on next SIG Node and will update this thread accordingly.

**Comment by saschagrunert** [comment]
This change is now included in https://github.com/kubernetes/community/pull/5195, too.

**Comment by coderanger** [comment]
Closing in favor of #5195.

/close

**Pull request closed without merging**
