### PR TITLE
Adding SIG CLI info

### PR DESCRIPTION
**Pull request by fabianofranz**
SIG CLI basic info with links to the needed resources. @pwittrock @AdoHe let me know if you want to tweak anything.

### CODE REVIEW

**Comment by fabianofranz** [comment]
cc @sarahnovotny

**Comment by AdoHe** [comment]
@fabianofranz I just add my working company info.

**Comment by fabianofranz** [comment]
@AdoHe Fixed, thanks!

**Comment by AdoHe** [comment]
LGTM. @pwittrock any more comments?

**Comment by pwittrock** [comment]
LGTM

**Comment by fabianofranz** [comment]
@sarahnovotny how do we get the mtg time added to the sig calendar?

**Comment by sarahnovotny** [comment]
@fabianofranz , there's an email address to invite to all your meetings in the "[starting a SIG](https://github.com/kubernetes/community/blob/master/README.md#how-to-start-a-sig)" section of the community repo.

- Add the meeting to the community meeting calendar by inviting cgnt364vd8s86hr2phapfjc6uk@group.calendar.google.com.

**Comment by fabianofranz** [comment]
@sarahnovotny nice, thanks!

**Pull request merged**
