### PR TITLE
Change ns-sameness position statement to RELEASED

### PR DESCRIPTION
**Pull request by JeremyOT**
Follows the example of
https://github.com/kubernetes/community/blob/master/sig-api-machinery/api-extensions-position-statement.md

/assign @pmorie

### CODE REVIEW

**Comment by jdumars** [comment]
/approve
/hold
hold can be lifted after any additional needed review @pmorie

**Comment by krmayankk** [comment]
what does released mean ?

**Comment by JeremyOT** [comment]
The wording comes from https://github.com/kubernetes/community/blob/master/sig-api-machinery/api-extensions-position-statement.md which seems to be the best example of prior art for a position statement like this.

It's meant to signify that it is no longer a draft, and that this is a position that sig-multicluster agrees with and recommends following

**Pull request merged**
