### PR TITLE
Changed company affiliation for jdumars

### PR DESCRIPTION
**Pull request by jdumars**
Updated my company affiliation from Microsoft to Google

### CODE REVIEW

**Comment by krzyzacy** [comment]
/lgtm
:100:

**Comment by cblecker** [comment]
:left-shark:
/woof shark
/approve

**Comment by krzyzacy** [comment]
lol there's no `/woof shark` yet :-)
/woof

**Comment by cblecker** [comment]
Aww man! I wanted to have a dog dressed like a shark!
I wonder if there is a cat 🤔 
/meow shark

**Comment by cblecker** [comment]
Nope. Just categories. One day... lol 🐶

**Comment by krzyzacy** [comment]
lolol, if you can give us the image, we can hook it up :-)

**Comment by jdumars** [comment]
This PR totally jumped the shark.

**Comment by krzyzacy** [comment]
image

**Pull request merged**
