### PR TITLE
Add affiliation requirements

### PR DESCRIPTION
**Pull request by castrojo**
First stab at adding some clarity to steering committee diversity requirements.

/sig contributor-experience
cc @jdumars @spiffxp

### CODE REVIEW

**Comment by spiffxp** [comment]
One meta comment before I review:

From elections/README.md:

>The voter’s guide is the single source of truth for the election that year! All announcements and notices should link to this document.

If this document is supposed to be the single source of truth, then [kubernetes/steering/elections.md](https://github.com/kubernetes/steering/blob/master/elections.md) should be removed, and the necessary language merged into this doc.  

I'd like to ask @kubernetes/steering-committee about this during our meeting today.

**Comment by jdumars** [comment]
any steering update on this @spiffxp ?

**Comment by spiffxp** [comment]
Yeah I'm going to get started on review/content in a moment.  Steering consensus is we shouldn't be duplicating content.  Policies should be a living document located in a place covered by a steering-committee OWNERS file.

I'm going to update the kubernetes/steering doc, and this doc should become voter-facing.  Aka what are the dates, who's running etc.

**Comment by spiffxp** [comment]
PTAL at https://github.com/kubernetes/steering/pull/68, I'm writing a PR to supersede this by referencing that more explicitly

**Pull request closed without merging**
