### PR TITLE
Update SIG network meeting time to be EU friendly

### PR DESCRIPTION
**Pull request by caseydavenport**
Per the discussion at the last SIG network meeting, this PR moves the
bi-weekly meeting to 9AM Pacific time in order to be more friendly to EU
timezones.

**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Comment by thockin** [comment]
Thanks!

/lgtm
/approve

**Review by thockin — COMMENTED** [review]
/lgtm

**Review by mrbobbytables — COMMENTED** [review]
/approve

**Pull request merged**
