### PR TITLE
Add evented-pleg Slack channel

### PR DESCRIPTION
**Pull request by ruiwen-zhao**
Adding a new channel for communication around sig node's project Evented PLEG. 

See [Evented PLEG doc](https://docs.google.com/document/d/1GfWDoKAYiaXApxayXmPl9bcK5ewyiimFDJ966r28TUE/edit#).

### CODE REVIEW

**Review by markyjackson-taulia — APPROVED** [review]
This looks fine. I will add an lgtm and hold for further moderation review
/lgtm
/hold

**Review by harche — APPROVED** [review]
/lgtm

**Comment by castrojo** [comment]
/approve

Remove hold at your convenience @markyjackson-taulia

**Comment by markyjackson-taulia** [comment]
Thank you
/hold cancel

**Pull request merged**
