### PR TITLE
add openebs slack channel

### PR DESCRIPTION
**Pull request by davidkarlsen**
It would be great to have a channel for OpenEBS: https://openebs.io/ in slack.
OpenEBS is developed under Apache License 2.0 license at the project level. Some components of the projects are derived from the other Open Source projects and are distributed under their respective licenses.
OpenEBS is a sandbox CNCF project and provides storage-integration for Kubernetes.

Signed-off-by: David Karlsen <david@davidkarlsen.com>

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/community/4528)

### CODE REVIEW

**Comment by mrbobbytables** [comment]
/hold
OpenEBS has a slack workspace already - https://slack.openebs.io/

We usually don't want to create a channel for a project within the Kubernetes slack when they have one they run themselves unless it is something explicitly expressed interest in from the general maintainers of the project. Fracturing a community can do more harm than good. =/

**Comment by kmova** [comment]
@mrbobbytables since OpenEBS is only Kubernetes focused storage, there have been multiple requests from the community to have a channel under k8s slack. Once OpenEBS slack is created, we will gradually migrate here and it should be seamless.

Thanks @davidkarlsen for putting in this issue.

**Comment by mrbobbytables** [comment]
@kmova Thanks for weighing in. We're pretty hesitant about doing that sort of thing without backing support from the project. Some have made very specific requests **NOT** to create channels here and to steer folk towards theirs.

/hold cancel
/lgtm

**Pull request merged**
