### PR TITLE
Add SIG Docs Spanish team meeting schedule

### PR DESCRIPTION
**Pull request by raelga**
Adds the SIG Docs Spanish localization team weekly meeting schedule.

### CODE REVIEW

**Review by irvifa — COMMENTED** [review]
/lgtm

**Comment by mrbobbytables** [comment]
@raelga do you want to hold off merging this till you have a zoom ID? Once sigs.yaml is updated you can run `make` and it'll regenerate all the docs.

**Comment by raelga** [comment]
@mrbobbytables I just added the zoom link to the agenda as the rest of the sig-docs meetings :)

Thanks to @jimangel :) for the help setting up the zoom meeting! ✨

**Comment by raelga** [comment]
@mrbobbytables as discussed over slack, the zoom link has been added to the `sigs.yaml`. I think we are good to go!

**Comment by mrbobbytables** [comment]
/approve
/hold
for sign off from sig-docs lead 👍

**Comment by jimangel** [comment]
/hold cancel
/lgtm
/approve
🎉

**Pull request merged**
