### PR TITLE
Add WG Service Mesh

### PR DESCRIPTION
**Pull request by keithmattix**
Signed-off-by: Keith Mattix II <keithmattix2@gmail.com>

Full proposal can be found [here](https://docs.google.com/document/d/1Qt3N1RLnRom7jKNhcnNLg_xaPn0TwKGuxxgXLOguNvE/edit?usp=sharing). 

sig-network has agreed to sponsor this working group. If I'm missing anything in the process, please let me know!

#### Notes for reviewer
- ~~2 WG chairs are [currently](https://github.com/kubernetes/org/issues/3530) [awaiting](https://github.com/kubernetes/org/issues/3529) k8s org membership (sponsors have already confirmed) and the other chair is a [member](https://github.com/kubernetes/org/issues/3470) of kubernetes-sigs. Please advise on next steps~~
- Meeting times and links are TBD
- We have yet to be assigned a liason from the Steering Committee

### CODE REVIEW

**Comment by thockin** [comment]
The counter-argument to be considered here is whether this "naturally" falls under the purvey of the existing Gateway sub-project (https://github.com/kubernetes/community/tree/master/sig-network#gateway-api).

My initial feeling is that Gateway should have right of first refusal on the topic?

@bowei
@hbagdi
@robscott
@shaneutt
@youngnick

**Comment by robscott** [comment]
@thockin Thanks for checking with us! The way this has been described to me is a working group that reports to Gateway API and that makes sense to me. The working group would make proposals to the broader Gateway API community for how mesh could be modeled + any related API changes necessary to enable that approach, but the WG would not directly be able to make API changes. I know there's not really any prior art for a working group within the scope of a subproject, but I think that's effectively what this would be.

@keithmattix @mikemorris @howardjohn Does my understanding of the scope of this WG make sense to you?

**Comment by youngnick** [comment]
I'm also +1, I think that the Mesh work really needs to be done, but can't be the focus of the main Gateway effort right now, this is a great solution.

**Comment by tomkerkhove** [comment]
How does this WG relate to the existing open standards such as SMI?

/cc @leecalcote

**Comment by gyohuangxin** [comment]
There is already a similar CNCF working group: [CNCF Service Mesh Working Group](https://github.com/cncf/tag-network/tree/master/service-mesh-wg), can we make some connections between these two WGs?

**Comment by craigbox** [comment]
> How does this WG relate to the existing open standards such as SMI?

Members of the SMI community have been discussing moving to support the Gateway API for some time, and this WG is the proposed place for that to happen. More context is linked in the [full proposal doc](https://docs.google.com/document/d/1Qt3N1RLnRom7jKNhcnNLg_xaPn0TwKGuxxgXLOguNvE/edit?usp=sharing)

> There is already a similar CNCF working group: [CNCF Service Mesh Working Group](https://github.com/cncf/tag-network/tree/master/service-mesh-wg), can we make some connections between these two WGs?

There is a TAG Network in CNCF and a SIG Network in Kubernetes; they serve different purposes. A goal of WG Mesh is to propose code changes to the Gateway API, which is a Kubernetes project, therefore we believe that creating a Kubernetes working group is the correct path.  We welcome contribution from people involved in TAG Network.

**Comment by lauralorenz** [comment]
Hi, I'd like to suggest that SIG-Multicluster also be represented in some way here (possibly as a stakeholder SIG); in particular, one of its flagship projects, the MCS API, has integrations with some Gateway API and service mesh implementations ([GKE](https://cloud.google.com/kubernetes-engine/docs/how-to/deploying-multi-cluster-gateways#mcs), [Istio](https://github.com/istio/istio/issues/33949)). As an upstream standard intersecting with service meshes, MCS API has similar scope and intent as the suggested purview of this WG. cc @pmorie @JeremyOT @thockin

**Comment by keithmattix** [comment]
@thockin @lauralorenz 
While I'm happy to work directly with the Gateway community, it sounds like Sig Multicluster does perhaps need the cross-SIG WG structure. Shall we add this to the agenda for a future meeting, or does Steering want to see the WG proposal reformulated to include SIG-Multicluster?

**Comment by thockin** [comment]
We don't NEED a WG charter just to talk to our friends in another SIG.

**Comment by lauralorenz** [comment]
FWIW I am 100% out of the loop on any IRL / steering committee discussions. /If/ the WG was going to be the way forward I didn't want SIG-MC to be left out, but if responsibility is staying within the Gateway subproject (and analogously, the MCS API subproject in SIG-MC) that is totally fine. Happy to be friends though :)

**Comment by keithmattix** [comment]
Sounds like we're all agreed then that the WG isn't needed at this point and that we'll work in the existing subprojects in the interests of simplicity for as long as we can. Thanks all; closing this now.

**Pull request closed without merging**
