### PR TITLE
Slack: adding new memebers of contrib-comms

### LINKED ISSUE #5704: Update Slack Group for @contrib-comms
We have a lot of new regular members to add to [usergroups.yaml](https://github.com/kubernetes/community/blob/e04cba9f46da3577b33e1a58834b1186c1843199/communication/slack-config/usergroups.yaml).

```
@Sladyn Nunes
@Kunal Kushwaha
@Bart Farrell
@Pensu91 
@Joel Barker
@Jason
```

Wow, that's a lot of great people 😅. 

I'll complete this by following the instructions [here](https://github.com/kubernetes/community/tree/e04cba9f46da3577b33e1a58834b1186c1843199/communication/slack-config)

/sig contributor-experience
/area contributor-comms

### PR DESCRIPTION
**Pull request by mbbroberg**
Signed-off-by: Matthew Broberg <matt@opensource.com>

**Which issue(s) this PR fixes**:

Fixes #5704

/sig contributor-experience
/area contributor-comms

### CODE REVIEW

**Comment by mbbroberg** [comment]
Huh, seeing the error: `2021/04/14 16:41:20 Error 1: Upstream Marketing: unknown user names: Sladyn Nunes, Kunal Kushwaha, Bart Farrell, Pensu91, Joel Barker, Jason.`

I confirmed those are their usernames in Slack. What am I missing? cc @mrbobbytables in case you can guide me.

**Comment by mbbroberg** [comment]
Oh I see -- I need to add the new users to `users.yaml` and be careful of capitalization. Fixing now.

**Review by markyjackson-taulia — APPROVED** [review]
/lgtm

**Pull request merged**
