### PR TITLE
Add SIG Node weekly CI meeting to charter

### PR DESCRIPTION
**Pull request by ehashman**
**Which issue(s) this PR fixes**:

This meeting is currently missing from the SIG Node charter.

/sig node
/cc @SergeyKanzhelev @dchen1107 @derekwaynecarr

### CODE REVIEW

**Comment by mrbobbytables** [comment]
verified vs the  doc 👍 
/approve
/hold
for sign off from @SergeyKanzhelev @dchen1107 or @derekwaynecarr

**Review by markyjackson-taulia — APPROVED** [review]
/lgtm

**Comment by SergeyKanzhelev** [comment]
Thank you!

/lgtm

**Pull request merged**
