### PR TITLE
slack config: add jenkins-operator channel

### PR DESCRIPTION
**Pull request by brokenpip3**
Hi, I'd like to propose a Slack channel for the [jenkins kubernetes operator](https://github.com/jenkinsci/kubernetes-operator)

Like the name is already explain the Jenkins Operator is a k8s operator which manages operations for Jenkins on Kubernetes. It has been built with Immutability and declarative Configuration as Code in mind.

Our previous slack channel (in a separated slack instance) will be not available anymore because the company that initially developed the operator stepped down and we are moving to a community model to continue to support and develop the operator, that's why we need a new chat home and the kubernetes slack seems the perfect match :) 

Thanks in advance!

### CODE REVIEW

**Comment by markyjackson-taulia** [comment]
@brokenpip3 have you reached out to the CDF in their slack for a channel? I feel that would be more appropriate for this type of channel.
/hold

**Review by markyjackson-taulia — COMMENTED** [review]
/hold

**Comment by brokenpip3** [comment]
Hi @markyjackson-taulia thanks for the reply! 
can you clarify what you mean with `CDF`?

**Comment by markyjackson-taulia** [comment]
> Hi @markyjackson-taulia thanks for the reply! 
> 
> can you clarify what you mean with `CDF`?

@brokenpip3 my apologies. The [CDF](https://cd.foundation) continuous delivery foundation and the Jenkins project is part of that project.

**Comment by brokenpip3** [comment]
No need to apologize at all :) 
Yep make sense, let me ask there. Can you take this on old without closing it until I get back from them? 
thanks!

**Comment by markyjackson-taulia** [comment]
Let's leave it open for now, there is a hold. Take your time

**Comment by brokenpip3** [comment]
Hi @markyjackson-taulia I asked in the CDF community and they said that they think a matrix channel or the kubernetes slack should be a better home for the project: ([here](https://cdeliveryfdn.slack.com/archives/CJQU6EHHP/p1679005181808289) if you want to take a look). They also suggested to use the already present in k8s space `jenkins-ci` channel but I believe that channel is more about general jenkins questions and pipeline support/discussion (looking on the historical discussions there)

I still believe that since this is the _kind-official_ kubernetes operator for jenkins having the `jenkins-operator` slack channel in the kubernetes slack space will be the best fit for the community, what do you think? :) 
Thanks!

**Comment by markyjackson-taulia** [comment]
@brokenpip3 

Hey there,

Thank you for providing that information.
I still do feel that the CDF Slack would be a better fit for this channel rather then the Kubernetes Slack for a couple of reasons.

Firstly, there is some history with this operator that the Jenkins project is aware of and should handle accordingly. I also noted this in the CDF thread, and I think it's important for the Jenkins project to take the lead on any related issues.

Secondly, I believe that the main driver for this operator is Jenkins, and Kubernetes plays a supporting role. As a CDF foundational project, it would make sense to keep all communication within this Slack or Gitter to ensure transparency and that everyone stays up-to-date.

I understand that open-source projects rely on collaboration and communication, and I think it's important for us to have a friendly and empathetic environment where everyone's voice is heard. I hope you'll consider my perspective, and thank you for your attention to this matter.

**Comment by brokenpip3** [comment]
Hi Marky, thanks for you kind reply, really appreciate your way of discussing and also the reply in the CDF slack.
Make sense to me, will create a channel there or will use gitter.

Thanks for your support, have a nice weekend
Luigi

**Pull request closed without merging**
