### PR TITLE
Request for adding a Slack channel to focus on Velero Data Mover.

### PR DESCRIPTION
**Pull request by blackpiglet**
Request to add a Slack channel, which will focus on Velero Data Mover design, developing and future supporting topics.

Signed-off-by: Xun Jiang <jxun@vmware.com>

**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Review by markyjackson-taulia — CHANGES_REQUESTED** [review]
I think this needs to be two pr's because the error is that the new channel isn't found.

**Comment by blackpiglet** [comment]
@markyjackson-taulia 
Thanks. I removed new channel reference in `usergroups.yaml`.

**Review by markyjackson-taulia — APPROVED** [review]
This looks good. Going to lgtm and hold for one more moderator to review.
/lgtm
/hold

**Comment by blackpiglet** [comment]
@jeefy @jdumars 
Could you please take a look?

**Comment by markyjackson-taulia** [comment]
@blackpiglet review can take a few days. Kindly be patient

**Comment by markyjackson-taulia** [comment]
Cc @coderanger for review

**Review by mrbobbytables — COMMENTED** [review]
/approve

**Pull request merged**
