### PR TITLE
Update SIG Service Catalog Chairs 

### PR DESCRIPTION
**Pull request by carolynvs**
* Emeritus: Ville Aikas 👋 
* Emeritus: Aaron Schlesinger 👋 
* New Chair: Carolyn Van Slyck 🎉
* New Chair: Michael Kibbe 🎉

### CODE REVIEW

**Comment by cblecker** [comment]
@carolynvs Do you have a record of where this was decided? I can't see anything skimming your meeting notes or the mailing list.

**Comment by carolynvs** [comment]
I'm not sure how to point to a record, it was a decision made amongst the existing chairs over email. Should we have @duglin or someone post to our mailing list to announce it officially?

**Comment by duglin** [comment]
seem to me that this PR has the same effect if the current chairs LGTM it

**Comment by carolynvs** [comment]
I have posted an announcement of the nominations (and that the other chairs have decided to step down) to our SIG mailing list and set the deadline for lazy consensus for 3 business days from now.

https://groups.google.com/forum/#!topic/kubernetes-sig-service-catalog/R5--6g3R77w

**Comment by MHBauer** [comment]
https://github.com/kubernetes/community/pull/2398#issuecomment-406704013
I agree, but this is how the sig is currently run.

**Comment by carolynvs** [comment]
@michelleN @cblecker Alrighty! Lazy consensus is the best consensus. 💯  The deadline for someone objecting to the new chairs has passed.

https://groups.google.com/d/msg/kubernetes-sig-service-catalog/R5--6g3R77w/qVra42yUDQAJ

**Comment by cblecker** [comment]
/approve
/hold cancel

:shipit: 🚀

**Pull request merged**
