### PR TITLE
update odo-devs slack group

### PR DESCRIPTION
**Pull request by kadel**
- add @rm3l - new odo contributor
- remove @mik-dass - no longer works on odo project

### CODE REVIEW

**Review by markyjackson-taulia — APPROVED** [review]
Holding for other slack admins to review.
/lgtm
/hold

**Comment by valaparthvi** [comment]
@kadel Can you add me as well?

**Comment by kadel** [comment]
> @kadel Can you add me as well?

oh, sorry, I haven't noticed that you were not there. fixed.

**Comment by castrojo** [comment]
/approve

LGTM, unhold at your convenience @markyjackson-taulia, thanks!

**Comment by markyjackson-taulia** [comment]
Thank you
/lgtm
/hold cancel

**Pull request merged**
