### PR TITLE
sig-etcd: add triage meeting

### PR DESCRIPTION
**Pull request by jmhbnz**
Adds missing sig-etcd triage meeting.

/assign @serathius, @ahrtr

### CODE REVIEW

**Comment by ahrtr** [comment]
Thanks @jmhbnz .  Please ping me when the workflow is green.

One related comment, we should encourage users & contributors to add issues, which they want to discuss, to the list. We need to document it somewhere.

**Comment by MadhavJivrajani** [comment]
> Agree we should encourage community participation as much as possible. Unfortunately the README.md in this repo is generated from the sigs.yaml file so it's a bit awkward trying to inject it here. I'm also not sure how many people view these files.

@jmhbnz please see https://github.com/kubernetes/community/tree/master/generator#adding-custom-content

**Review by MadhavJivrajani — APPROVED** [review]
/approve
please remove hold when you see fit!

**Comment by MadhavJivrajani** [comment]
> I'm also not sure how many people view these files.

In all getting-starting-with-contributing-to-k8s content out there, this repo and the file structure is mentioned ~first. So these READMEs are fairly well known to a good percentage of folks coming into the community.

**Comment by ahrtr** [comment]
/lgtm
/approve


Thanks

**Pull request merged**
