### PR TITLE
Add cloud-provider repo to sig-cloud-provider subprojects

### PR DESCRIPTION
**Pull request by spiffxp**
ref: https://github.com/kubernetes/org/issues/147

### CODE REVIEW

**Comment by dims** [comment]
cc @jagosan @hogepodge @andrewsykim

**Comment by hogepodge** [comment]
I'll give it just a bit of time for @andrewsykim and @jagosan to have eyes on it, but it lgtm.

**Comment by spiffxp** [comment]
I took a total guess that it should be included in the existing subproject rather than creating a new one for it.  Happy to correct if it belongs somewhere else

**Comment by andrewsykim** [comment]
/lgtm

Thank you @spiffxp

**Pull request merged**
