### PR TITLE
Cluster API issue5506 - Links to owners files should be updated to use the main branch

### PR DESCRIPTION
**Pull request by sayantani11**
**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes-sigs/cluster-api/issues/5506

### CODE REVIEW

**Review by juzhiyuan — APPROVED** [review]
When visit OWNERS under the master branch, it will redirect to the default main branch 😄

**Review by vincepri — APPROVED** [review]
/lgtm

**Comment by palnabarun** [comment]
/assign @nikhita @mrbobbytables
(for approval)

**Pull request merged**
