### PR TITLE
keps/sig-aws: create KEP for "aws-k8s-tester"

### PR DESCRIPTION
**Pull request by gyuho**
/cc @d-nishi @shyamjvs

### CODE REVIEW

**Comment by M00nF1sh** [comment]
umm, you used two kep number in one pr(32 and 33)

**Comment by gyuho** [comment]
@d-nishi @M00nF1sh Good catch. Just fixed. PTAL.

**Comment by justaugustus** [comment]
Looks like this is good to go...
/hold cancel

**Pull request merged**
