### PR TITLE
sig-cluster-lifecycle: add cluster-bootstrap under the kubeadm subproject

### PR DESCRIPTION
**Pull request by nikhita**
Ref:

- https://github.com/kubernetes/org/issues/137
- https://github.com/kubernetes/kubernetes/blob/master/staging/README.md#creating-the-published-repository

/cc @yliaog @timothysc @roberthbailey @luxas

### CODE REVIEW

**Comment by spiffxp** [comment]
/approve
I leave the /lgtm to one of the requested reviewers

**Comment by roberthbailey** [comment]
What is the cluster-bootstrap repository intended for (it looks like it was recently created)? Why it is in the kubernetes org instead of the kubernetes-sigs org? I don't recall it being discussed at a sig cluster lifecycle meeting, so why does it belong to sig cluster lifecycle?

**Comment by yliaog** [comment]
https://github.com/kubernetes/org/issues/137

the following two threads had discussions about it. it holds constants and helper functions for https://github.com/kubernetes/community/blob/master/contributors/design-proposals/cluster-lifecycle/bootstrap-discovery.md, kubeadm uses it.

https://groups.google.com/forum/#!searchin/kubernetes-sig-architecture/cluster-bootstrap%7Csort:date/kubernetes-sig-architecture/d_E7JOyA4EM/IrlH5y1uBgAJ

https://groups.google.com/forum/#!searchin/kubernetes-sig-architecture/cluster-bootstrap%7Csort:date/kubernetes-sig-architecture/x_-L4dlwbeU/psObQDpuBgAJ

**Comment by timothysc** [comment]
@nikhita - please come to the next sig-cluster-lifecycle meeting to discuss.  Cluster-API was probably the best example that we follow for trying to create new subprojects.  

/hold

**Comment by timothysc** [comment]
Is this for the bootstrap tokens split-up?

**Comment by nikhita** [comment]
> @nikhita - please come to the next sig-cluster-lifecycle meeting to discuss. 

I don't really have any idea about the cluster-bootstrap repo :)

I just created this PR because we noticed a bug related to cluster-bootstrap in the publishing bot and also noticed that there were some other process-related PRs that hadn't been created (like this one).
Ref: https://github.com/kubernetes/org/issues/137#issuecomment-426981734

I think @yliaog would be the right person to talk about this. :)

**Comment by timothysc** [comment]
k, it's not really a sub-project.. It's just a dependency of sig-cluster-lifecycle / kubeadm split into a different location. 

I believe api-machinery has a similar setup.

**Comment by roberthbailey** [comment]
It would be nice to distinguish between subprojects vs. repositories that we own. This would be in the later camp, since it isn't a project on it's own.

**Comment by spiffxp** [comment]
Repositories ultimately need to be part of some subproject.  There are multi-repo subprojects, maybe this falls back under the kubeadm subproject.

**Comment by nikhita** [comment]
Bumping this. What are the items that need to be done to get this merged?

>  maybe this falls back under the kubeadm subproject.

Should I add it to the kubeadm subproject?

**Comment by timothysc** [comment]
> Should I add it to the kubeadm subproject? 

@nikhita - yes, please

**Comment by nikhita** [comment]
@timothysc done.

**Pull request merged**
