### PR TITLE
request to add kubestellar-dev channel

### PR DESCRIPTION
**Pull request by clubanderson**
changes to the ownership of kcp have required the KubeStellar (fka kcp-edge) community to establish our own slack channel, mailing list, cicd, and other items that were once shared between kcp and KubeStellar (fka kcp-edge).

**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Comment by clubanderson** [comment]
@jdumars @markyjackson-taulia can I get an update on this?

**Comment by markyjackson-taulia** [comment]
@clubanderson 5the errors have not been fixed (I think)

**Comment by clubanderson** [comment]
Where is the error?  I don't see an error listed from the CI but I do see a removal of "ok-to-test"

**Comment by markyjackson-taulia** [comment]
My bad, I am adding the lgtm label. Given it a few days for one more admin to review and add the approve label.
/hold
/lgtm

**Comment by clubanderson** [comment]
@markyjackson-taulia can I get an update on this?

**Review by markyjackson-taulia — APPROVED** [review]
/lgtm

**Comment by clubanderson** [comment]
@MadhavJivrajani

**Review by markyjackson-taulia — APPROVED** [review]
/approve

**Comment by clubanderson** [comment]
@markyjackson-taulia can you release the 'hold'?

**Pull request merged**
