### PR TITLE
sig-cloud-provider: move andrewsykim and nckturner to emeritus status add elmiko as TL

### PR DESCRIPTION
**Pull request by andrewsykim**
move andrewsykim and nckturner to emeritus status add elmiko as TL

### CODE REVIEW

**Comment by elmiko** [comment]
cc @bridgetkromhout @cheftako

**Comment by cblecker** [comment]
/hold
/committee steering

The process for leadership changes is here (and does include some email steps): https://github.com/kubernetes/community/blob/master/contributors/chairs-and-techleads/leadership-changes.md

There's also a handy issue template with a checklist: https://github.com/kubernetes/community/issues/new/choose

**Comment by elmiko** [comment]
thanks @cblecker , i seem to remember us missing some steps on this the last time, so i wanted to make sure we observe the proper process.

**Comment by elmiko** [comment]
i started adding some links to help with the checklist, but then i realized that Bridget had created this issue with all the info, https://github.com/kubernetes/community/pull/7815

apologies for the noise =)

**Comment by pacoxu** [comment]
#7912 was merged for the same change.
/close

**Pull request closed without merging**
