### PR TITLE
SIG List: rotate SIG Release tech leads and chairs

### PR DESCRIPTION
**Pull request by tpepper**
Periodic rotation of new folks up and into leadership roles and existing
chair out to emeritus.

Signed-off-by: Tim Pepper <tpepper@vmware.com>

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
/lgtm

Yay! :partying_face:

**Comment by tpepper** [comment]
Could be approved by any steering or https://github.com/kubernetes/community/blob/master/OWNERS but since it's SIG Release context and they're some of the key folks who inspired me and I followed into this space:

/assign @jdumars @calebamiles

**Comment by nikhita** [comment]
@tpepper this is a little last minute, but could you also send an email to k-dev+ other steps as mentioned in https://github.com/kubernetes/community/pull/5291? It still needs to be merged but we want to follow that process for leadership changes going forward.

**Comment by nikhita** [comment]
/hold
for https://github.com/kubernetes/community/pull/5286#issuecomment-721269002

**Comment by tpepper** [comment]
Will do!

**Comment by tpepper** [comment]
For the record in this PR I want to note that Sascha is:
 * a GitHub org member
 * has completed the inclusivity training

**Comment by saschagrunert** [comment]
> * has completed the inclusivity training

Yep, this is the certificate for reference: [cert.pdf](https://github.com/kubernetes/community/files/5483410/cert.pdf)

**Comment by justaugustus** [comment]
@tpepper -- Thank you immensely for all of the work you've done for SIG Release and the calm and thoughtful leadership you've shown throughout. It was an absolute honor to serve together with you as a Chair and we welcome you into the revered Emeritus halls of SIG Release. :two_hearts: 

@saschagrunert @hasheddan -- It's been such a pleasure to see you both learn and grow as a leaders in SIG Release and I'm looking forward to going even further with you in 2021!

For SIG Release:
/lgtm
/approve

cc: @kubernetes/sig-release

**Comment by tpepper** [comment]
Since there's a lot going on at the moment, I'm proposing a lazy consensus on this PR of EOD Friday November 13, slightly more than the one week minimum required in https://github.com/kubernetes/community/pull/5291.

**Review by hasheddan — APPROVED** [review]
/lgtm

Thanks for all of the work you have done @tpepper!

I have completed the training and my certificate number is `LF-atf7f043jq`.

**Comment by justaugustus** [comment]
I've opened two tracking issues (since there are some additional things that SIG Release looks after that we need to account for):
- offboarding Tim (which includes the newly proposed Steering checklist in https://github.com/kubernetes/community/pull/5291): https://github.com/kubernetes/sig-release/issues/1321
- onboarding Dan and Sascha: https://github.com/kubernetes/sig-release/issues/1322

**Comment by justaugustus** [comment]
We've hit the lazy consensus deadline on this leadership rotation.
Thank you again, @tpepper! :two_hearts: 
/lgtm
/approve
/hold cancel

**Review by cblecker — APPROVED** [review]

**Pull request merged**
