### PR TITLE
Add slack channel for csi-windows working group

### PR DESCRIPTION
**Pull request by jingxu97**
The purpose of this channel is to set up a shared communication place
for the working group on supporting CSI windows

The proposal for enhancements to support CSI plugins on Windows nodes is
here https://github.com/kubernetes/enhancements/pull/1141

### CODE REVIEW

**Comment by jingxu97** [comment]
cc @ddebroy @pjh

**Comment by pjh** [comment]
LGTM!
cc @wk8

**Comment by mrbobbytables** [comment]
/hold
Holding for sig-storage channel delegation / csi channel rename 👍 
ref: https://github.com/kubernetes/community/pull/4060

**Comment by mrbobbytables** [comment]
Now that https://github.com/kubernetes/community/pull/4060 has merged. Would you mind adding it to the [sig-storage config](https://github.com/kubernetes/community/blob/master/communication/slack-config/sig-storage/config.yaml) as `csi-windows`? 😄

**Comment by mrbobbytables** [comment]
Ah, sorry -- I should have been more clear -- it should now be added to:
 `communication/slack-config/sig-storage/config.yaml`
The csi-* channels have been delegated so that the sig-storage-leads can approve 👍

**Comment by jingxu97** [comment]
close this one, please review the new one https://github.com/kubernetes/community/pull/4064

**Pull request closed without merging**
