### PR TITLE
Add cluster-api* git repositories under sig-cluster-lifecycle

### PR DESCRIPTION
**Pull request by dims**
Change-Id: Idf9b661fcf7a8f5aa353ca72134ef786b5c58b45
Signed-off-by: Davanum Srinivas <davanum@gmail.com>

### CODE REVIEW

**Comment by cblecker** [comment]
/unassign spiffxp
/uncc cblecker parispittman
/assign @lukemarsden @luxas @timothysc @roberthbailey

Should be LGTM'd by sig first.

**Comment by dims** [comment]
@kubernetes/sig-cluster-lifecycle-pr-reviews PTAL

**Comment by roberthbailey** [comment]
@parispittman - can you approve this change?

**Pull request merged**
