### PR TITLE
Updated with few changes in wording to reflect the k8s graduation state

### PR DESCRIPTION
**Pull request by krishna-mk**
Added - (Cloud Native Computing Foundation)
Removed - currently in incubation. 
Removed - aims to satisfy the CNCF graduation criteria, but
Aligned - spaces/lines after the above.

### CODE REVIEW

**Comment by smarterclayton** [comment]
LGTM

**Comment by smarterclayton** [comment]
Needs rebase

**Comment by xiangpengzhao** [comment]
ping @krishna-mk 

/committee steering

**Comment by bgrant0607** [comment]
Kubernetes is still in incubation

**Comment by bgrant0607** [comment]
Also, this file moved to the steering repo

**Pull request closed without merging**
