### PR TITLE
Remove jbeda as lead of SIG-scalability

### PR DESCRIPTION
**Pull request by jbeda**
I'm not super involved anymore so let's call it what it is :)

Signed-off-by: Joe Beda <joe.github@bedafamily.com>

### CODE REVIEW

**Comment by idvoretskyi** [comment]
cc @kubernetes/sig-scalability-pr-reviews @countspongebob @wojtek-t

**Comment by wojtek-t** [comment]
This is a big loss for sig-scalability. But obviously it's your choice Joe.

/lgtm

**Comment by jbeda** [comment]
@wojtek-t Reach out if you need me regardless!

**Comment by countspongebob** [comment]
@jbeda Thanks for all the guidance!

**Pull request merged**
