### PR TITLE
wg-iot-edge: Edge Security Challenges Whitepaper

### PR DESCRIPTION
**Pull request by dejanb**

### CODE REVIEW

**Comment by mattgreg** [comment]
This is a fantastic paper. Thank you for writing this!
We are working to solve many of these problems in the [Ockam project](https://github.com/ockam-network/ockam)
We'd love your thoughts and welcome you to join our community.

**Comment by jonoberg** [comment]
👍

**Comment by girishkumarbk** [comment]
Very well written and highlights the key issues in establishing root of trust and then propagating the same to upward software layers.

**Pull request merged**
