### PR TITLE
Update leads for SIG service catalog

### PR DESCRIPTION
**Pull request by pmorie**
cc @arschles @bmelville @duglin

### CODE REVIEW

**Comment by philips** [comment]
@pmorie @sarahnovotny  probably the right process for these things is to have an email go out to the SIG mailing list announcing the changes then we can mirror them here.

**Comment by pmorie** [comment]
@philips We have already discussed them in a SIG meeting.  I'll send an email to the list if that is desired.

**Comment by chrislovecnm** [comment]
Merge?

**Comment by bgrant0607** [comment]
LGTM.

We should document the recommended procedure somewhere.

**Pull request merged**
