### PR TITLE
docs: update the checklist on the event awards playbook

### PR DESCRIPTION
**Pull request by salaxander**
As part of the contributor awards at an event, the contributor site needs to be updated. This is currently missing from the playbook

### CODE REVIEW

**Comment by Priyankasaggu11929** [comment]
/lgtm
/approve

/hold
(holding for review from additonal folks)

**Comment by jberkus** [comment]
Looks good, but somewhere else in the playbook it would be great to have something about preparing the PR ahead of time.  Ideally, the website gets updated the very next day after the contributor summit.  Same with the blog post.

**Review by jrsapi — APPROVED** [review]

**Comment by stmcginnis** [comment]
/remove-lifecycle rotten

/lgtm

I think this update is good as is. A note about timing of the PR creation might be nice, but I don't think we should block on that.

**Comment by jberkus** [comment]
ok, then

/approve

**Pull request merged**
