### PR TITLE
Promote CecileRobertMichon as SIG Cluster Lifecycle Lead

### PR DESCRIPTION
**Pull request by vincepri**
**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Comment by cblecker** [comment]
ref: https://groups.google.com/g/kubernetes-sig-cluster-lifecycle/c/3UsZoVAcyUU
/approve

**Comment by fabriziopandini** [comment]
+1 Congrats!

**Comment by justinsb** [comment]
+1 from me - congrats & thank you @CecileRobertMichon

**Comment by justinsb** [comment]
/lgtm

(Trying on its own line)

**Pull request merged**
