### PR TITLE
Remove and redirect of release process information

### PR DESCRIPTION
**Pull request by guineveresaenger**
Release doc information is being maintained in k8s/sig-release repository. Any
duplicate files should be removed to avoid documentation drift.
/sig contributor-experience
/sig release

### CODE REVIEW

**Comment by guineveresaenger** [comment]
fwiw, upon eearching the repository, there seem to be no links pointing to either of these files, so complete removal without removal notice stub is an option as well.

**Comment by cblecker** [comment]
/lgtm
/approve
/hold

Holding for any objections. Can remove and merge tomorrow if none.

**Comment by tpepper** [comment]
/lgtm
k/sig-release repo docs are becoming more authoritative and up to date on release process related topics

**Comment by idvoretskyi** [comment]
@guineveresaenger fine with me, thanks for doing this.

@cblecker we may unhold this.

**Pull request merged**
