### PR TITLE
[WIP] Support union in API server

### PR DESCRIPTION
**Pull request by mengqiy**
Originally discussed in #278 as an alternative. 

We will revisit this in 1.8.

### CODE REVIEW

**Comment by mengqiy** [comment]
/reopen
reopening this since we still want to support union eventually.

**Comment by gkarthiks** [comment]
@mengqiy Since we have a KEP process, can we please merge this soon or close this and create a KEP?

**Comment by apelisse** [comment]
This is tracked in other places and there are a zillion open issues for that already. I don't think we need this one specifically.
/close

**Pull request closed without merging**
