### PR TITLE
updating with the new sig-windows TLs

### PR DESCRIPTION
**Pull request by michmike**
I am leaving VMware to join a Nuvalence.io and as a result I am scaling down my involvement in Kubernetes and Open Source. I have been the chair in Sig-Windows since inception for the past 5 years and it has been a blast. This community has been great and welcomed Windows, enabling us to get to Alpha, Beta, and to a Stable release.

I will definitely be a huge Kubernetes and CNCF ecosystem user moving forward.

Congratulations to @jayunit100 and @jsturtevant on being the two new TLs on SIG-Windows.
@benmoss thank you for your contributions getting us to stable. you will be missed.
cc: @marosset

### CODE REVIEW

**Comment by benmoss** [comment]
Congrats @michmike!

**Comment by cblecker** [comment]
Hello everyone!

I don't see any mention of leadership changes out to the sig-windows mailing list. Where was this discussed?

For reference, there's a checklist of steps [here](https://github.com/kubernetes/community/blob/master/contributors/chairs-and-techleads/leadership-changes.md).

/hold

**Comment by michmike** [comment]
@cblecker I had asked Jorge if there was a process and he was not aware of one. we didn't know. i will email the right aliases
we did do a lazy consensus for the two new TLs

**Comment by cblecker** [comment]
@michmike Sounds great! Thank you!

**Review by ddebroy — COMMENTED** [review]
/lgtm
we will miss you @michmike . Thanks for your leadership and contributions!

**Comment by jayunit100** [comment]
Thanks mike will miss you homie

**Comment by michmike** [comment]
@cblecker lazy consensus deadline is over. can we merge this PR?

**Comment by michmike** [comment]
@marosset  can you please review?

**Comment by marosset** [comment]
> @marosset can you please review?

I did 9 days ago  :)

happy to again
/lgtm
/approve

**Comment by marosset** [comment]
@cblecker Do you mind if we remove the hold and merge this now that  we've followed the following the steps in the doc you linked?

**Comment by mrbobbytables** [comment]
It's been long enough 👍 
I forgot to remove the hold earlier

/hold cancel

**Pull request merged**
