### PR TITLE
Adding krisnova.md for election

### PR DESCRIPTION
**Pull request by kris-nova**
Adding my bio for the 2018 steering committee election
Also adding my name to the list in the README.md

---

Hey @castrojo can you take a look at tell me if this all looks kosher? Unsure about if the picture is allowed or not, etc.

Happy to change anything as needed!

### CODE REVIEW

**Comment by idvoretskyi** [comment]
@kris-nova exactly 300 words. How did you do that? :)

**Comment by kris-nova** [comment]
```
wc -w
```

**Comment by kris-nova** [comment]
Hrmm -

**Comment by kris-nova** [comment]
Sorry - the case of the bad airline WiFi strikes again. Someone pointed out to me that we needed company information to ensure we had a healthy balance on the committee - makes sense so updating to Heptio.

**Pull request merged**
