### PR TITLE
archive wg-reliability

### PR DESCRIPTION
**Pull request by mrbobbytables**
ref: https://groups.google.com/g/kubernetes-sig-architecture/c/F5Ekr1Tg768/m/tBl2KlxzAwAJ

/hold

cc @kubernetes/steering-committee

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by mrbobbytables** [comment]
/hold

forgot to archive the channel

**Review by BenTheElder — COMMENTED** [review]
/lgtm

**Pull request merged**
