### PR TITLE
Migrating k8s-testgrid.appspot.com link to testgrid.k8s.io

### PR DESCRIPTION
**Pull request by Ritikaa96**
What this PR does / why we need it:
Fixes a bunch of broken links to testgrid dashboard.

Which issue(s) this PR fixes:
This is related to an umbrella issue and fixes a task of the same:
https://github.com/kubernetes/test-infra/issues/30370

### CODE REVIEW

**Comment by Ritikaa96** [comment]
Noted . I'll revert the changes from archive folder.

**Comment by Ritikaa96** [comment]
> In general we consider anything in an archive folder for historical purposes only and they should not be updated.
> 
> The readmes, charters, and the e2e-tests doc are the only ones that should be updated 👍

Hi @mrbobbytables PTAL, i have reverted the changes from Archive folder

**Comment by Ritikaa96** [comment]
> s

**Comment by Ritikaa96** [comment]
> In general we consider anything in an archive folder for historical purposes only and they should not be updated.
> 
> The readmes, charters, and the e2e-tests doc are the only ones that should be updated 👍

Is this resolved now @mrbobbytables ?

**Comment by mrbobbytables** [comment]
Ah, sorry - missed the ping. 
You can omit:
- `communication/meeting-notes-archive/*`
- `sig-contributor-experience/meeting-notes-archive/2018-meeting-notes.md`
- `sig-release/meeting-notes-archive/*`

those are all archives of old meeting notes.

It does look like the sig-scalability doc needs to be rebased as well.

**Comment by Ritikaa96** [comment]
> Ah, sorry - missed the ping. You can omit:
> 
> * `communication/meeting-notes-archive/*`
> * `sig-contributor-experience/meeting-notes-archive/2018-meeting-notes.md`
> * `sig-release/meeting-notes-archive/*`
> 
> those are all archives of old meeting notes.
> 
> It does look like the sig-scalability doc needs to be rebased as well.

Noted. I'll omit them and resolve the conflicts, thanks for the reviews :)

**Comment by Ritikaa96** [comment]
Hi @mrbobbytables PTAL!

**Comment by mrbobbytables** [comment]
Thanks!
/lgtm
/approve

**Pull request merged**
