### PR TITLE
Update buildcop instructions with how to force a build.

### PR DESCRIPTION
**Pull request by mml**
Update buildcop instructions with how to force a build.

### CODE REVIEW

**Comment by krousey** [comment]
/lgtm

@spxtr Why isn't this job on a timer as well?

**Comment by spxtr** [comment]
We don't actually want to give most build cops access to Jenkins. Really, if the build breaks then ping the test-infra oncall to kick it.
cc @fejta

> @spxtr Why isn't this job on a timer as well?

It might be because it will reupload to the same place which might race with e2e jobs that are pulling the latest build.

**Comment by krousey** [comment]
@spxtr Is there a way to trigger a build if the previous one failed? I don't like that this job won't auto-recover from a failure like this. It's especially problematic on the weekend when build cop won't be watching this.

**Comment by spxtr** [comment]
> Is there a way to trigger a build if the previous one failed?

Only Googlers can access Jenkins and manually trigger a build. This is bad, and we're moving towards a better world. Until we're there, just ask the test-infra oncall to kick it.

**Pull request merged**
