### PR TITLE
sig-release: add tejolote repo

### PR DESCRIPTION
**Pull request by ameukam**
Ref:
  - https://github.com/kubernetes/org/issues/3656

Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
/lgtm

**Review by saschagrunert — APPROVED** [review]

**Review by puerco — COMMENTED** [review]
/lgtm

**Review by puerco — APPROVED** [review]

**Pull request merged**
