### PR TITLE
adding nais as slack channel

### PR DESCRIPTION
**Pull request by audunstrand**
[NAIS](nais.io) is a platform that adds PaaS like functionality on top of Kubernetes. It is developed and used by the Norwegian Labour and Welfare Administration(NAV). This platform has been open source from day one, and are used heavenly inside NAV, and has influenced several other platforms in the public sector in Norway. We think this can be used more broadly.

As part of that process, we would like a project channel on the Kubernetes Slack, so that our users can reach out to us and discuss our project.

### CODE REVIEW

**Comment by audunstrand** [comment]
CLA signed

**Comment by audunstrand** [comment]
cla signed and registered

**Comment by audunstrand** [comment]
another try with cla

**Comment by alejandrox1** [comment]
@audunstrand could you please provide a link to nais?
/hold

**Comment by audunstrand** [comment]
https://nais.io and https://github.com/nais
@alejandrox1

**Comment by mrbobbytables** [comment]
+1

**Pull request merged**
