### PR TITLE
Adding request for #konveyor slack channel.

### PR DESCRIPTION
**Pull request by tsanders-rh**
This channel request is for a project that we are starting called Konveyor.  The goal of the Konveyor project is to provide migration assistance for Kubernetes. This includes the ability to discover, assess, and migrate existing applications between Kubernetes clusters and migrate applications and infrastructure running in traditional environments to Kubernetes.

See: https://github.com/konveyor and https://konveyor.github.io/

### CODE REVIEW

**Comment by jeefy** [comment]
All for open source enablement! 

Is this going to be a completely open source project and do you already have a group going?

**Comment by tsanders-rh** [comment]
@jeefy Yes, this will be completely open source.  No group yet; as we are just getting started.  I could see a need for a Migration SIG as we go forward.

**Comment by jeefy** [comment]
AWESOME!!
/approve
/assign @mrbobbytables

**Comment by mrbobbytables** [comment]
/hold
I don't want to be a party pooper -- we do support open source projects, but it doesn't look like there's anything in the repo other than the github pages -- and theres nothing under the get-started etc on there yet. 

Do you plan to add that soon?

**Comment by tsanders-rh** [comment]
@mrbobbytables 

Yes.  We are migrating our container migration tooling from https://github.com/fusor to our newly formed konveyor org in the next week.  The repos moving are:

https://github.com/fusor/mig-operator
https://github.com/fusor/velero-plugin-for-microsoft-azure
https://github.com/fusor/velero-plugin-for-gcp
https://github.com/fusor/mig-e2e
https://github.com/fusor/velero-plugin-for-aws
https://github.com/fusor/mig-ui
https://github.com/fusor/mig-controller
https://github.com/fusor/migpvbenchmarks
https://github.com/fusor/mig-ci
https://github.com/fusor/cpma
https://github.com/fusor/openshift-migration-plugin
https://github.com/fusor/mig-demo-apps
https://github.com/fusor/ocp-velero-plugin
https://github.com/fusor/mig-agnosticd

This will grow as we expand on the expanded vision of konveyor.

**Comment by tsanders-rh** [comment]
@mrbobbytables 

What can I do to move this forward?

**Comment by mrbobbytables** [comment]
Ah sorry, lost track. -- Do you have an ETA of when you plan to move things over?
/hold cancel

**Comment by tsanders-rh** [comment]
We have a release that is planned for next week.   In order to not put any risk on that schedule, we will wait till that is out before we migrate the repos.  I am hopeful this will be within the next two weeks.   -Todd

**Comment by mrbobbytables** [comment]
Cool 👍 
Just wanted to make sure there was a plan in place.
/lgtm

**Pull request merged**
