### PR TITLE
adding kubemove slack channel

### PR DESCRIPTION
**Pull request by vishnuitta**
[KubeMove](http://www.github.com/kubemove/kubemove) is a opensource project providing framework for applications running on Kubernetes to migrate across clusters in different cloud providers, on-prem along with data. This is under active development and licensed under Apache 2.0. This project, being providing framework, is having contributions from more than one company and expected to be interested by multiple applications.

To help multiple companies coordinate on this opensource project, we would like to have a slack channel for open discussions and to reach out to interested parties.

Signed-off-by: Vitta <vitta@mayadata.io>

### CODE REVIEW

**Comment by vishnuitta** [comment]
does any more info need to be provided? cc: @idvoretskyi

**Comment by tamalsaha** [comment]
Just want to add that my team from AppsCode will be also contributing to this project. Looking forward to build a community around data mobility pattern for Kubernetes with OpenEBS/MayaData team.

**Comment by mrbobbytables** [comment]
Bringing in another slack admin to take a look -- I think everything looks fine, it likely just got missed with the holidays.

/assign @jeefy

**Comment by mrbobbytables** [comment]
/approve

(thought I did that earlier)

**Comment by idvoretskyi** [comment]
All good!

**Comment by vishnuitta** [comment]
Thanks to everyone for getting this merged. Thanks to @tamalsaha for the message and looking forward for collaboration.

**Pull request merged**
