### PR TITLE
Remove SIG on-premise since its now a slack channel

### PR DESCRIPTION
**Pull request by dghubble**

### CODE REVIEW

**Comment by cblecker** [comment]
Is it worth moving these docs as they are to `archive/` and removing the sigs.yaml entry completely?

**Comment by dghubble** [comment]
@cblecker yes, agreed. I didn't realize there was a precedent we could follow with SIG Configuration.

**Comment by dghubble** [comment]
Moved page as-is to `archive`, removed OWNERS, removed from `sigs.yaml`.

**Pull request merged**
