### PR TITLE
generator: enable validation for sigs.yaml

### PR DESCRIPTION
**Pull request by nikhita**
Existing errors are:

```
go run ./generator/app.go
Validating sigs.yaml
NOTICE: sig-usability: has no subprojects
NOTICE: wg-multitenancy: chairs: expected person: {tashimi Tasha Drew VMWare}, got: {tashimi Tasha Drew VMware}
NOTICE: committee-code-of-conduct: expected label: code-of-conduct, got: conduct
```

- The 1st commit enables validation in the generator.
- The 2nd commit updates the CoCC label from `committee/conduct` to `committee/code-of-conduct`. Related - https://github.com/kubernetes/test-infra/pull/13682.
- The 3rd commit fixes the VMware typo - s/VMWare/VMware.
- The 4th commit fixes GitHub usernames to properly include uppercased letters. This is not caught by validation (since we don't use the GitHub API to validate it) but having the correct case is useful while running (external) scripts.
- The `sig-usability: has no subprojects` will be fixed by https://github.com/kubernetes/community/pull/3940.

/assign @spiffxp @cblecker

### CODE REVIEW

**Comment by nikhita** [comment]
/hold
until https://github.com/kubernetes/test-infra/pull/13682 and https://github.com/kubernetes/community/pull/3940 are merged (tests won't pass until #3940 is merged anyway)

**Comment by spiffxp** [comment]
yessssss, thank you for closing this out
(ref: https://github.com/kubernetes/community/pull/3680, https://github.com/kubernetes/community/pull/3671 for earlier work to get us here)

**Comment by spiffxp** [comment]
/hold cancel
necessary PR's have merged, tests now pass
/lgtm

**Pull request merged**
