### PR TITLE
Updating ways to deploy to include EKS and eksctl

### PR DESCRIPTION
**Pull request by christopherhein**
There are probable more documented ways to deploy k8s on AWS as this point, but this PR adds eks and eksctl.

Signed-off-by: Christopher Hein <me@christopherhein.com>

### CODE REVIEW

**Comment by d-nishi** [comment]
@christopherhein -- when we set the charter, we were specifically asked not to references managed kubernetes solutions such as EKS or mention tools that connected to these manages services

@justinsb @kris-nova -- thoughts?

**Comment by christopherhein** [comment]
Fair, I will close this for now. @justinsb @kris-nova if you have thoughts we can reopen.
/close

**Pull request closed without merging**
