### PR TITLE
Add subprojects for sig-aws

### PR DESCRIPTION
**Pull request by justinsb**
Specifically: cloudprovider, credentialprovider (for ECR), volume
provider for EBS.

### CODE REVIEW

**Comment by castrojo** [comment]
This seems fine to me, but not sure why I was assigned, seems like this can be handled within sig-aws' OWNERS?

**Comment by justinsb** [comment]
Sorry for delay on the rebase here.  Added aws-encryption-provider as well.

Not sure of the protocol for approval, to be honest @castrojo .  I guess if one of the other sig-leads concur we can merge? cc @countspongebob @kris-nova

**Comment by parispittman** [comment]
there are a few options for subproject formation in the [new governance template doc](https://github.com/kubernetes/community/blob/master/committee-steering/governance/sig-governance-template-short.md) @justinsb

**Comment by justinsb** [comment]
Thanks @parispittman - I believe this PR is just enumerating the existing areas of sig-aws responsibility, not adding new ones.  (This list is something we have to do before we can get new subprojects approved)

**Pull request closed without merging**
