### PR TITLE
Update social media role handbook

### PR DESCRIPTION
**Pull request by kaslin**
The role handbook for social media hadn't been updated since its initiation. Now that I have been in the role of social media lead for a while, I'm using this space to record what I've learned about the role, and my expectations for how this team should operate.

Please review and make any edits you see fit, @chris-short & @parispittman! (<Current social media advisors)

### CODE REVIEW

**Comment by mbbroberg** [comment]
Looking at this with fresh eyes and I see that 62b0b8460aa159588de80a1c429457871f7106ff has @ messages in it. If we're both on the team call today let's rebase these few and get this lovely addition added!

**Comment by kaslin** [comment]
This got very borked and dropped. Needs to be reworked. Closing.

**Pull request closed without merging**
