### PR TITLE
import devel, design, and proposals from kubernetes

### PR DESCRIPTION
**Pull request by michelleN**

### CODE REVIEW

**Comment by bgrant0607** [comment]
Thanks! I'm going to merge and we can iterate from there.

The original authors signed the Google CLA at the time those commits were contributed.

**Comment by michelleN** [comment]
Thanks @bgrant0607 !

**Comment by eparis** [comment]
for repos which use the bot to merge (do we do that here?) `cla: human-approved` will overwrite that check.

**Comment by bgrant0607** [comment]
@eparis This repo doesn't yet have bot automation.

**Pull request merged**
