### PR TITLE
Promote Tabitha to full PSC member

### PR DESCRIPTION
**Pull request by tallclair**
/hold

Wait for https://github.com/kubernetes/security/pull/124 to merge

### CODE REVIEW

**Comment by tabbysable** [comment]
/lgtm

Delighted to be here

**Review by cblecker — APPROVED** [review]

**Comment by tallclair** [comment]
@cblecker mind throwing a `/approve` on this?

**Comment by dims** [comment]
@cblecker is probably out .. i am happy to.

/approve

**Pull request merged**
