### PR TITLE
Dissolve WG Component Standard

### PR DESCRIPTION
**Pull request by mtaufen**
Per the recent announcement \[1\], update sigs.yaml to mark the dissolution
of the Component Standard Working Group.

\[1\]: https://groups.google.com/g/kubernetes-dev/c/_IN6H0m_QHk

### CODE REVIEW

**Comment by mtaufen** [comment]
Some questions about archival (google group, youtube hosted meeting recordings, slack channel) remain.

**Comment by Debanitrkl** [comment]
I hav opened a tracking issue here #6039 related to this, which will be helpful in the process

**Review by Debanitrkl — APPROVED** [review]
This PR looks fine to me 
/lgtm

**Comment by Debanitrkl** [comment]
/cc @mrbobbytables this is regarding removing all instances of wg component standard.
PTAL

**Review by mrbobbytables — CHANGES_REQUESTED** [review]
/lgtm-cancel
@mtaufen thanks for helping with the archival tasks - If you could, please  remove it  from sigs.yaml and move the directory into the [archive dir](https://github.com/kubernetes/community/tree/master/archive) at the root of k/community.

Here is an example of when wg-lts was retired: https://github.com/kubernetes/community/pull/5240/files

If you need help with any of the tasks, please feel free to reach out 👍

**Comment by mrbobbytables** [comment]
woops, no `-` in lgtm cancel
/lgtm cancel

**Comment by mtaufen** [comment]
@mrbobbytables updated, thanks!

**Pull request merged**
