### PR TITLE
New channel for security assessment of cluster api

### PR DESCRIPTION
**Pull request by PushkarJ**
From SIG-Security's last weekly [meeting](https://docs.google.com/document/d/1GgmmNYN88IZ2v2NBiO3gdU8Riomm0upge_XNVxEYXp0/edit#heading=h.7u1tzh1qn1z4) an action item was to create a new channel in order to facilitate a focussed discussion on security assessment of cluster-api (a sub project of kubernetes). This is a first attempt of a security assessment of a sub-project performed in collaboration with sig-security of the parent graduated project. 

Since we are breaking new ground here, I am happy to revisit if this channel should be prefixed as `wg` or `sig`.  We intend to periodically revisit the results from our assessments, so I do not see this as a time-bound effort but more of a continuous improvement cycle.

### CODE REVIEW

**Comment by coderanger** [comment]
On the Slack admins side: putting this under sig-security delegated control seems like the most logical choice, if there will be a formal WG for this project then we should use that name but I don't think I've seen any WG creation requests for it so I'm guessing it's more of an ad hoc collaboration? Seems good to go from my PoV but will leave final approve to the sig-security approvers.

/lgtm

**Comment by PushkarJ** [comment]
> On the Slack admins side: putting this under sig-security delegated control seems like the most logical choice, if there will be a formal WG for this project then we should use that name but I don't think I've seen any WG creation requests for it so I'm guessing it's more of an ad hoc collaboration? Seems good to go from my PoV but will leave final approve to the sig-security approvers. As a small nit, we do try to keep the files in alpha order so maybe shuffle that :)
> 
> /lgtm

Thanks @coderanger . Changed the ordering to make it alphabetical. And yes, this will be a case of ad hoc collaboration

**Comment by tabbysable** [comment]
Yeah, deffo a lower-intensity effort than would require a formal WG. I suspect that once the intense collaboration has completed, we'll probably deprecate this channel and follow up via normal inter-SIG messaging, but also no harm if it hangs around for a while.

/approve

Thanks a lot for organizing this!

**Pull request merged**
