### PR TITLE
upstream-marketing is now contributor-comms

### PR DESCRIPTION
**Pull request by chris-short**
Name change PR'd into community.

**Which issue(s) this PR fixes**:

Fixes # N/A

### CODE REVIEW

**Comment by jdumars** [comment]
Is there any documented context on this change? @chris-short

**Comment by chris-short** [comment]
Lots of conversation during meetings, the meeting notes themselves, and various Slack conversations. The problem we are addressing is one of consistency. No official doc but here's the context:

We started off as upstream-marketing as we couldn't think of anything better at the time. As our work and team has evolved we've morphed into contributor-comms (and most people refer to us as such). You can see this potentially confusing naming in our @contributor-comms Slack handle (the "name" is Upstream Marketing the alias is contributor-comms).

We've talked about this for months now and the work is finally done. If you want me to put all the notes and such together into a doc I can but, there has been ample team discussion on the topic. cc @kaslin

**Pull request merged**
