### PR TITLE
Fixes broken hyperlinks in the contributor guide

### PR DESCRIPTION
**Pull request by JasonvanBrackel**
Fixes https://github.com/kubernetes/community/issues/5220

### CODE REVIEW

**Comment by JasonvanBrackel** [comment]
@mrbobbytables I wasn't sure how to fix the mentoring initiatives link, here

image

My hugo fu is only so good.  I'd be happy to update this as part of this, once I figure that part out.

**Comment by mrbobbytables** [comment]
@JasonMorgan thanks for this! Honestly had no idea the ToC links were broken :(
The mentoring one I'll need to take a look at..it should have been expanded by the ingestion script.

Can you remove the WIP and squash the commits down? - We can at least get this fix in quick and get the site rebuilt.

/ok-to-test

**Comment by JasonvanBrackel** [comment]
@mrbobbytables squashed WIP removed

**Comment by mrbobbytables** [comment]
One last little thing - the `fixes #<foo>` in the commit message are still blocking merge. >_<

**Comment by JasonvanBrackel** [comment]
Thanks @mrbobbytables I had just figured that out, thanks to the great docs!  I'll be working through the contributor site as part of my twitch stream, so I'll fix as I go.

**Comment by mrbobbytables** [comment]
oh, awesome! got a link?

**Comment by mrbobbytables** [comment]
In anycase :P 
thank you for taking care of that!
/approve

**Comment by castrojo** [comment]
/lgtm

Thanks for your attention to detail!

**Comment by JasonvanBrackel** [comment]
@mrbobbytables Sorry missed your note yesterday.  https://twitch.tv/helloimjvb.

@castrojo My pleasure!

**Pull request merged**
