### PR TITLE
remove deprecated sig testing groups

### PR DESCRIPTION
**Pull request by BenTheElder**
**Which issue(s) this PR fixes**:

/kind cleanup
/sig testing

Second part of https://github.com/kubernetes/test-infra/pull/33083

/hold

### CODE REVIEW

**Comment by mrbobbytables** [comment]
/lgtm
should be good to release the hold :)

**Comment by BenTheElder** [comment]
FYI we have some failing configs: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-community-tempelis-apply/1815915907248033792

But the job is just passing

**Pull request merged**
