### PR TITLE
rename #ship to #kots in Slack config

### PR DESCRIPTION
**Pull request by fshot**
Ship has been superseded by the KOTS project -- see https://github.com/replicatedhq/ship#replicated-ship-has-been-superseded-by-kots

### CODE REVIEW

**Comment by mrbobbytables** [comment]
@fshot can you sign the cla? Will approve once that's taken care of. 👍 

Thanks!

**Comment by fshot** [comment]
I've signed the CCLA

**Comment by mrbobbytables** [comment]
@fshot are you sure it's associated with the email that signed the commit? It should replace the label `cncf-cla:no` with `cncf-cla:yes`. For a little more info:
https://github.com/kubernetes-sigs/contributor-playground/blob/master/exercises/cla-vs-git-author.md

**Comment by fshot** [comment]
Hi @mrbobbytables, thanks in advance for your help.

The commit has the correct email:
```
commit da4cbbb1af71e1b8e28ab8caac924da943052097 (HEAD -> patch-1, origin/patch-1, master)
Author: Frank Shotwell <frank@replicated.com>
Date:   Mon Nov 25 11:50:19 2019 -0800

    rename #ship to #kots
...
```

But I signed the agreement on behalf of my organization, and that might be a factor.

I just now updated my Role to be a 'contributing employee' as well as an admin.  Perhaps this will satisfy the bot?

I _think_ anyone with an @replicated.com address should now be covered by my agreement.

Here's our signed org agreement: https://identity.linuxfoundation.org/system/files/clas/signed/cla_corporate-660b6432396d3f887f44c4e15ec479dd29c34b4b.pdf

**Comment by mrbobbytables** [comment]
That took care of it 👍 
Thanks!
/approve

**Pull request merged**
