### PR TITLE
provider-azure: Update references to cloud-provider-azure repo

### PR DESCRIPTION
**Pull request by justaugustus**
ref: #1247

Pending repo migration:
/hold

/assign @andrewsykim @cblecker @mrbobbytables

Signed-off-by: Stephen Augustus <saugustus@vmware.com>

### CODE REVIEW

**Comment by justaugustus** [comment]
Repo has migrated: https://github.com/kubernetes/org/issues/1247#issuecomment-549567578
/hold cancel

**Comment by mrbobbytables** [comment]
we have sign off from one of the leads 👍 
/approve

**Pull request merged**
