### PR TITLE
Add Fury slack channel

### PR DESCRIPTION
**Pull request by angelbarrera92**
From SIGHUP.io we want to include a new channel in the Kubernetes slack group.

The channel will be used to share experiences between Fury Distribution users.

Fury is a CNCF certified Kubernetes distribution crafted by SIGHUP -> https://landscape.cncf.io/selected=fury-distribution

In addition to the Distribution, the team is building OSS tools around Kubernetes.

https://github.com/sighupio

Thanks!

### CODE REVIEW

**Comment by angelbarrera92** [comment]
@jeefy @parispittman 
Is everything ready? Do you need anything else?

**Comment by mrbobbytables** [comment]
@angelbarrera92 We had to revert the change, there is a user of the same name as the channel. They share the same namespace and can't coexist =/

**Comment by angelbarrera92** [comment]
> @angelbarrera92 We had to revert the change, there is a user of the same name as the channel. They share the same namespace and can't coexist =/

No worries, i wll create a new one. Thanks

**Pull request merged**
