### PR TITLE
Add Stephanie + Bridget to the Velero user group

### PR DESCRIPTION
**Pull request by carlisia**
Please add Stephanie Bauman to our Velero user group.

c/c @stephbman

Signed-off-by: Carlisia <carlisia@vmware.com>

### CODE REVIEW

**Comment by markyjackson-taulia** [comment]
I am opening a [PR](https://github.com/kubernetes-sigs/slack-infra/pull/31) to fix the len count from 9 to 11

**Comment by mrbobbytables** [comment]
@carlisia Once this is rebased, it should work now.

**Comment by carlisia** [comment]
+ c/c @zubron.

**Comment by carlisia** [comment]
@mrbobbytables the test is still failing for Stephanie.

**Pull request merged**
