### PR TITLE
Fix scheduling-framework link.

### LINKED ISSUE #5297: Wrong scheduling-framework KEP link
The scheduling framework design has moved to https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/624-scheduling-framework/README.md

### PR DESCRIPTION
**Pull request by warmchang**
The scheduling framework design has moved to https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/624-scheduling-framework/README.md

**Which issue(s) this PR fixes**: 

Fixes #5297

### CODE REVIEW

**Review by nikhita — APPROVED** [review]
Thanks for catching that!

/lgtm
/approve

**Comment by nikhita** [comment]
@warmchang Ah, it's in a blocked path!

Design proposals are deprecated and not generally being updated. For more information please see the note at the root of the design proposals dir:
https://github.com/kubernetes/community/tree/master/contributors/design-proposals#kubernetes-design-documents-and-proposals

Closing but thanks for the PR!

**Comment by warmchang** [comment]
@nikhita  Understand, thank you for reply.

**Pull request closed without merging**
