### PR TITLE
Updating doc & contributing links for SIG-Windows

### PR DESCRIPTION
**Pull request by PatrickLang**
We had a lot of interest in the SIG-Windows meetup at Kubecon last week, and a few people pointed out that the SIG-Windows page doesn't have what they need to get started or look for ways to contribute. I added some clarifications into a `CUSTOM CONTENT` section to help out.

### CODE REVIEW

**Comment by PatrickLang** [comment]
cc @jimzim

**Comment by cblecker** [comment]
/ok-to-test
@PatrickLang Please review and sign the CLA as noted by the bot :) (you likely just need to get added to your corporate CLA)

**Comment by michmike** [comment]
@PatrickLang  it seems the last step to get this approved is your CLA requirement

**Comment by PatrickLang** [comment]
CLA should be approved - need to bump the bot

**Pull request merged**
