### PR TITLE
sig-testing: add new chair and tech leads

### PR DESCRIPTION
**Pull request by spiffxp**
Related:
- Part of: https://github.com/kubernetes/community/issues/6913
- Followup to: https://github.com/kubernetes/community/pull/6907

Running `make` to pickup the sig-testing changes was reverting changes to steering liaisons, so I added a commit to address that first. Not quite sure why that didn't get caught in presubmit.

### CODE REVIEW

**Comment by cblecker** [comment]
/approve
/hold

Approving for top-level and steering changes (thanks for fixing!). Hold can be removed once sig-testing is signed off and ready :)

**Review by BenTheElder — COMMENTED** [review]
/lgtm
/approve
🎉🎉🎉

**Comment by aojea** [comment]
🙇 Thanks

**Pull request merged**
