### PR TITLE
Set jeefy to emeritus status for sig-ui

### PR DESCRIPTION
**Pull request by jeefy**
Context: https://groups.google.com/g/kubernetes-dev/c/_sGC7W4YiVc

Time for me to step down from SIG-UI leadership. <3

### CODE REVIEW

**Comment by nikhita** [comment]
Same question as https://github.com/kubernetes/org/pull/2781#issuecomment-859271657:

@jeefy do you want to add @shu-mutou in this PR or do that in a follow-up?

**Comment by jeefy** [comment]
I think it makes sense to do it all in one, so I'm happy to update all the PRs (there are also a couple others that need to be cut)

**Pull request merged**
