### PR TITLE
Update LF course for inclusive training

### PR DESCRIPTION
**Pull request by nikhita**
Ref: https://lists.cncf.io/g/cncf-toc/topic/78231677#5503, https://github.com/cncf/toc/pull/570

LF has launched a new course for inclusive training in an open source
context - https://training.linuxfoundation.org/announcements/linux-foundation-and-ncwit-release-free-training-course-on-diversity-in-open-source/

All CNCF maintainers are also required to take this course.

/hold
steering review

cc @kubernetes/steering-committee

### CODE REVIEW

**Comment by idvoretskyi** [comment]
FYI - https://github.com/cncf/toc/pull/570

**Comment by nikhita** [comment]
@kubernetes/steering-committee -- can you please take a look?

**Pull request merged**
