### PR TITLE
Pass the torch in ContribEx

### PR DESCRIPTION
**Pull request by cblecker**
This PR moves myself, @jberkus, @mrbobbytables, and @nikhita to emeritus leads of SIG Contributor Experience.

@palnabarun, @kaslin, @Priyankasaggu11929, and @MadhavJivrajani have been doing an amazing job running the SIG, and at this point we want to fully recognize those doing the work.

I can speak for Josh, Bob, and Nikhita in saying that none of us are going far, and we will all be around to support you in any way you all need. ContribEx was my first home in this project and it means so much that we have such a talented, passionate, and caring group of folks to carry the values of the SIG forward.

### CODE REVIEW

**Comment by cblecker** [comment]
/area community-management
/hold
/cc @jberkus @mrbobbytables @nikhita 

Holding for review/consensus.

**Comment by mrbobbytables** [comment]
LGTM :)
I have full confidence in @palnabarun @kaslin @MadhavJivrajani and @Priyankasaggu11929 <3

**Comment by jimangel** [comment]
@cblecker, @jberkus, @mrbobbytables, and @nikhita: A HUGE thank you for all the work you've done in contribex (and continue to do). Y'all are wonderful people and I'm glad to have worked with you! ❤️ 

@palnabarun, @kaslin, @Priyankasaggu11929, and @MadhavJivrajani: Congratulations! It's good to know contribex is in good hands! Best of luck as we move forward!

This PR has too many awesome people, lgtm and thank you all again! 🙏

**Comment by MadhavJivrajani** [comment]
Thank you @nikhita @cblecker @mrbobbytables and @jberkus for everything you have done for our community in your role as ContribEx leads, the work you've done has been truly foundational in the success of our project and I hope we can continue to improve it and leave it better than we found it for the leads that come in after us as well. Congratulations! Emeritus truly is the goal ❤️

**Comment by castrojo** [comment]
Emeritus party time!

🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉

**Review by nikhita — APPROVED** [review]
LGTM :)

**Comment by cblecker** [comment]
All the outgoing folks have ack'd, so:
/hold cancel

**Pull request merged**
