### PR TITLE
Initial commit of summit notes

### PR DESCRIPTION
**Pull request by castrojo**
This will be an ongoing PRfest! Fixes to formatting and general copyediting would be most appreciated.

### CODE REVIEW

**Comment by BenTheElder** [comment]
Thanks for posting these!
One comment: `community/2017-events/12-contributor-summit/feature-roadmap-2018.jpg` appears to be an HTML file, or at least the version in master right now appears to be 🙃

**Comment by cblecker** [comment]
Thanks for noticing @BenTheElder ! Opened #1479 to fix.. just want @castrojo to verify I grabbed the intended image.

**Pull request merged**
