### PR TITLE
wg-k8s-infra: lead rotation

### PR DESCRIPTION
**Pull request by spiffxp**
Per https://groups.google.com/g/kubernetes-wg-k8s-infra/c/AF2Re3AE1r8

> I’d like to thank Bart Smykla (@bartsmykla) for all that he has done for this group over the past few years: getting the group more organized, running our meetings, automating DNS changes, and more.
>
> Bart’s availability has diminished, and for the health of the group has asked to move to emeritus. I appreciate the courage it took to admit this, and commend Bart for thinking of the community.
>
> I have discussed with the WG leads and @thockin, and we would like to promote Arnaud Meukam (@ameukam) to WG K8s-infra lead. Arnaud has consistently shown up and done good work: keeping aaa healthy, setting up triage-party, maintaining prow-related infrastructure, setting up tests for our infrastructure as a whole, and more.
>
> Congratulations to both Arnaud and Bart, and thanks again for all your efforts to make this project and its community self-sustaining!

### CODE REVIEW

**Comment by spiffxp** [comment]
/cc @dims @bartsmykla @ameukam 
FYI @thockin

**Comment by dims** [comment]
/approve
/lgtm
/hold

@spiffxp please feel free to remove hold when appropriate.

**Comment by spiffxp** [comment]
Thanks. Will Remove hold when I've opened and linked other PRs to this

**Comment by spiffxp** [comment]
Related PRs:
- OWNERS/groups changes in k8s.io: https://github.com/kubernetes/k8s.io/pull/1795
- GitHub team changes: https://github.com/kubernetes/org/pull/2581

**Comment by spiffxp** [comment]
Needs a re-LGTM, updated this with the teams created/renamed in https://github.com/kubernetes/org/pull/2581

**Comment by spiffxp** [comment]
/hold cancel
this is well past default lazy consensus 72h deadline

**Comment by spiffxp** [comment]
Note to self: there are test-infra changes I need to make too

**Comment by justaugustus** [comment]
Post-merge +1 from @kubernetes/sig-release-leads!
/lgtm
/approve

Congrats @ameukam! 💕

**Comment by bartsmykla** [comment]
Thank you everyone for the time I could serve as a co-chair of our WG. It was awesome experience and I hope I'll be able to contribute more again in the near future! :-)

**Comment by spiffxp** [comment]
test-infra changes: https://github.com/kubernetes/test-infra/pull/21487

**Pull request merged**
