### PR TITLE
sig-testing annual-report-2022.md

### LINKED ISSUE #7117: 2022 Annual Report: SIG Testing
Chairs: @BenTheElder @michelle192837 @spiffxp @stevekuznetsov 
Liaison: @cpanato

Actions for the chair/organizer of the community group:
- [ ] Consult your community group to complete draft of report
- [ ] If needed, consult with Steering Committee liaison on any private issues or concerns that arrise while completing report
- [ ] Submit PR to git.k8s.io/community repo with copy of report, assigning your Steering Committee liaison for review
- [ ] Steering Committee reviews report, and may make comments/ask questions
- [ ] Once all comments are addressed, Steering Committee will approve report to merge
- [ ] If needed, any follow up items may be brought to the "Chairs, Tech Leads, and Organizers" meeting in April

Once all the above items are complete, this issue may be `/close`'d

A template has already been generated for your group, and is available [here](https://git.k8s.io/community/sig-testing/annual-report-2022.md).

Key dates:
- Initial PR to communtiy repo should be opened by March 24th, 2023
- PR should be reviewed and merged by April 7th, 2023

More detailed information on the annual reports process is available [here](https://git.k8s.io/community/committee-steering/governance/annual-reports.md).

Your group's report template is available here: https://git.k8s.io/community/sig-testing/annual-report-2022.md

If you have any questions or concerns about this process, you may reach the Steering Committee via the following methods:
- Slack/E-mail your liaison directly
- The public #steering-committee channel in Slack
- The public mailing list steering@kubernetes.io
- The private mailing list steering-private@kubernetes.io for any private or sensitive issues.

/sig testing
/committee steering
/area annual-reports

### PR DESCRIPTION
**Pull request by michelle192837**
Initial draft for the 2022 sig-testing report, to be fleshed out by leads + members next week.

**Which issue(s) this PR fixes**:

Fixes #7117

### CODE REVIEW

**Comment by michelle192837** [comment]
/assign @cpanato

This should be ready for review! Let me know if there are any issues, thanks!

**Comment by xmcqueen** [comment]
ack. Thanks

**Comment by cpanato** [comment]
thanks
/lgtm

**Pull request merged**
