### PR TITLE
Add reddit-mods Slack channel

### PR DESCRIPTION
**Pull request by gtaylor**
The r/kubernetes subreddit has grown to over 45k subscribers and is loosely maintained by a small set of moderators that largely overlap with the Kubernetes Slack org.

This channel is being created to get our mod team organized about policies and enforcement, and to work towards sufficient quality and Code of Conduct enforcement to eventually become an "official" subreddit (should the community will it).

Signed-off-by: Greg Taylor <greg@gctaylor.com>

### CODE REVIEW

**Comment by thockin** [comment]
+1, thanks

/lgtm
/approve

**Comment by coderanger** [comment]
Just keep in mind the channel will be public and the history is retained forever by default. So discussion of specific moderation actions might be best left to modmail.

**Comment by thockin** [comment]
This is more for establishing policies and syncronizing efforts.  And
frankly, I kind of like the idea that most mod actions be done in the open
:)

**Comment by mrbobbytables** [comment]
/ok-to-test
/approve
/hold
For ack from 2nd slack admin :+1:

**Comment by coderanger** [comment]
/hold cancel

(grumble prow commands)

**Pull request merged**
