### PR TITLE
Add wg apply

### PR DESCRIPTION
**Pull request by apelisse**
Adding wg-apply in the sigs list. We probably don't have all the information (leads? calendar?) yet, but this is still better than nothing.

### CODE REVIEW

**Comment by apelisse** [comment]
@lavalamp

**Comment by lavalamp** [comment]
LGTM but I don't know what the requirements are for this :)

**Comment by cblecker** [comment]
also, is this a separate working group, or would this be a subproject of an existing sig?

**Comment by lavalamp** [comment]
TBH I just made a mailing list so I could have a group to email without spamming everyone.

The work we'll be doing has a green light from SIG Architecture. Members of SIG API Machinery and (at least) SIG CLI will be working on this.

**Comment by cblecker** [comment]
probably best to classify it as a subproject then, but cc: @kubernetes/steering-committee for guidance.

**Comment by bgrant0607** [comment]
WG kind of makes sense because it involves 2 SIGs for now: API machinery and CLI.

Eventually, it will be just API machinery, I assume. It's up to API machinery whether it makes sense to be permanently broken out as a subproject. If not, that reaffirms the WG direction.

**Comment by lavalamp** [comment]
I imagine this group will dissolve after we are "done" if that makes a
difference.

**Comment by bgrant0607** [comment]
Yes, that suggests not a subproject.

**Comment by apelisse** [comment]
OK, Thanks everyone. Looks like we know where we're going. I'll make sure we get there and fill the gaps. I'll ping here when ready.

**Comment by apelisse** [comment]
Proposal has been sent, and I've updated the document with the regular meeting description. Please proceed.

**Pull request merged**
