### PR TITLE
tpepper standing for steering election

### PR DESCRIPTION
**Pull request by tpepper**
I'm adding my bio here.  Also noted Aaron's was added, but not linked in
the README.md, so added him there in addition to me.

Signed-off-by: Tim Pepper <tpepper@vmware.com>

### CODE REVIEW

**Comment by cblecker** [comment]
```
$ curl -s https://raw.githubusercontent.com/kubernetes/community/658e6e5c274afe87da1721711a6530cc69de4802/events/elections/2018/timpepper.md | wc
      45     282    1895
```

**Comment by neolit123** [comment]
>$ curl -s https://raw.githubusercontent.com/kubernetes/community/658e6e5c274afe87da1721711a6530cc69de4802/events/elections/2018/timpepper.md | wc
> 45     282    1895

:this_is_fine:

**Pull request merged**
