### PR TITLE
fix broken link : https://github.com/kubernetes/community/blob/master…

### PR DESCRIPTION
**Pull request by CriaHu**
…/contributors/devel/release.md

### CODE REVIEW

**Comment by CriaHu** [comment]
@nikhita

**Comment by CriaHu** [comment]
@tanjunchen

**Comment by CriaHu** [comment]
@tanjunchen ，squash five commits to one commit in this pr.I don't know why five commits have been revoked and PR has been closed

**Comment by jeefy** [comment]
Ugh I keep forgetting I'm not an approver in this one but one down.

**Comment by mrbobbytables** [comment]
Thanks for fixing the links 👍 
/approve

**Pull request merged**
