### PR TITLE
Update capi v1.8 release team members

### PR DESCRIPTION
**Pull request by adilGhaffarDev**
**Which issue(s) this PR fixes**:
This PR updates the slack user groups for the new Cluster API release v1.7 team.

### CODE REVIEW

**Comment by adilGhaffarDev** [comment]
@jdumars @jeefy please check.

**Comment by adilGhaffarDev** [comment]
@fabriziopandini @chrischdi please check this one too.

**Review by fabriziopandini — COMMENTED** [review]
Looks in line with https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/releases/release-1.8.md
/lgtm

**Pull request merged**
