### PR TITLE
Add terranetes channel

### PR DESCRIPTION
**Pull request by myjaffoo**
Terranetes enables application developers to self-serve cloud resources with minimal user input using Helm packages. You can either choose from our list of packages available on [artifacthub.io](https://artifacthub.io/packages/search?ts_query_web=appvia) or adopt our pattern and use [tf2helm](https://github.com/appvia/tf2helm) to build out your own packages. The solution leverages [Terraform](https://www.terraform.io/) and [Helm](https://helm.sh/) to create a Kubernetes Custom Resource Definition (CRD) Object watched and understood by a [terraform controller](https://github.com/appvia/terraform-controller) which then triggers a workflow that applies a referenced Terraform module.

Kubernetes / Community Projects:
-  [terraform controller](https://github.com/appvia/terraform-controller)
- [tf2helm](https://github.com/appvia/tf2helm)

### CODE REVIEW

**Comment by coderanger** [comment]
None of your projects appear to actually be called "terranetes" so I don't think this would be a good choice. Channel names are not the place for puns. If you want to make a space to talk about Terraform in a Kubernetes context, maybe just `#terraform`?

**Comment by myjaffoo** [comment]
@coderanger @jdumars @parispittman are you able to review this please? Or do you require further info?

**Review by markyjackson-taulia — APPROVED** [review]
Adding an lgtm and also holding for other moderators to review
/lgtm
/hold

**Pull request merged**
