### PR TITLE
Add CAPO Office Hours meeting

### PR DESCRIPTION
**Pull request by mdbooth**

### CODE REVIEW

**Review by fabriziopandini — COMMENTED** [review]
Thanks for updating this page!
/lgtm

**Review by fabriziopandini — COMMENTED** [review]
Thanks for updating this page!
/lgtm

**Review by neolit123 — COMMENTED** [review]
- changes must be in the sigs.yaml file
- run 'make generate'
- commit all changes

**Comment by mdbooth** [comment]
> * changes must be in the sigs.yaml file
> * run 'make generate'
> * commit all changes

Apologies! I did read the first time contributor doc, but I missed this.

**Review by MadhavJivrajani — APPROVED** [review]
/lgtm
/approve
/hold
in case you want to change something, feel free to remove when ready!

**Pull request merged**
