### PR TITLE
Change 'master' to 'main' in github-workflow markdown

### PR DESCRIPTION
**Pull request by wiggitywhitney**
ᕕ(ᐛ)ᕗ New contributor here!

I have been using this very helpful github-workflow guide while I make my first contributions- thank you!

With this PR I am changing all references to 'master' and replacing them with 'main'.  I am so pleased that the default branch is now called 'main'!

The diagram on the page is now out-of-date and if you accept these changes it will be inconsistent with the text.  But we have to start somewhere!

\(^-^)/  Have a great day!

### CODE REVIEW

**Comment by wiggitywhitney** [comment]
@idvoretskyi \(^-^)/ Thanks for the link!  I'm please to see the migration effort in full swing.  However I'm not trying to change an actual branch name, just references in the guide.  I've personally been contributing to the docs, and since the default branch is 'main' there then it makes these workflow commands incorrect.  I fear that this inconsistency could scare off a new contributor who is intimidated by git.

**Review by mrbobbytables — CHANGES_REQUESTED** [review]
We are still mostly on `master` right now =/  I'd avoid updating those notes till we at least get above 50% migration.

What could be done is a note at the top or a comment in each section stating to use the default branch for that repo (e.g. main)

**Comment by wiggitywhitney** [comment]
Love your idea, @mrbobbytables !  What do you think of my changes?

**Review by mrbobbytables — COMMENTED** [review]
One small request, instead of putting it at the bottom of each codeblock, can you put at the top? that way people will see it before potentially executing the commands.

**Comment by wiggitywhitney** [comment]
(☞ﾟ∀ﾟ)☞  It is done.

**Comment by mrbobbytables** [comment]
Thanks!

/label tide/merge-method-squash
/lgtm
/approve

**Comment by mrbobbytables** [comment]
oh, derp

/ok-to-test

**Pull request merged**
