### PR TITLE
updating SIG-Scalability Readme.md

### PR DESCRIPTION
**Pull request by alejandroEsc**
The intention here is to lead by example about what information the readme file for each sig should more or less contain and perhaps be organized.

### CODE REVIEW

**Comment by spiffxp** [comment]
lgtm but I'd like one of the organizers to approve

**Comment by jbeda** [comment]
Sorry I missed this!  Looks great!

**Comment by MHBauer** [comment]
Out of scope of your changes, the images on the linked blog post are dead.

**Pull request merged**
