### PR TITLE
Extending resource quota to support node labels

### PR DESCRIPTION
**Pull request by vishh**

### CODE REVIEW

**Comment by vishh** [comment]
cc @kubernetes/api-approvers @derekwaynecarr @bsalamat

**Comment by jbeda** [comment]
/approve

Based on form, not content.  Assuming that others from sig-scheduling are on board, feel free to merge early and iterate on the checked in version. I'd add sig-architecture as an involved SIG so that they are consulted wrt API review as this moves along and before it moves to `implementable`.

**Comment by vishh** [comment]
@davidopp

**Comment by derekwaynecarr** [comment]
per our prior discussion on the earlier draft form, i prefer solution A.

/approve
/lgtm

**Comment by vishh** [comment]
@jdumars can you get this KEP queued up for API review?

**Comment by hex108** [comment]
@vishh Thanks for the great feature! Is there any plan to implement it? We need this feature to manage quota for different GPU cards, I could do some work if it's OK.

**Pull request merged**
