### PR TITLE
Stepping down from sig service catalog, add Konstantin as a co-chair

### PR DESCRIPTION
**Pull request by mszostok**
I'm leaving the project and Konstantin was selected as the new co-chair 🎉 

It was awesome to be part of the SIG Service Catalog, wish you all the best! Special thanks to @jberkhahn!

Here's to new adventures! 🚀

@jberkhahn 
@jhvhs

### CODE REVIEW

**Comment by nikhita** [comment]
@mszostok Thanks for all your efforts with running sig service catalog! :)

@jhvs Congratulations!! :tada: 


We've been discussing how to improve communicating changes in SIG leadership in the steering committee - https://github.com/kubernetes/steering/issues/179. We haven't documented any process changes yet but could you also send an email to the SIG Service Catalog mailing list with a heads up and maybe a 2 day lazy consensus period? An example - https://groups.google.com/g/kubernetes-sig-contribex/c/fHJe36rjOdI/m/20v_vrqBBwAJ :)

/hold
Adding a hold for the mailing list heads up

**Comment by mszostok** [comment]
Hi @nikhita! 

Thanks for the information, I will send email today about those changes :)

**Comment by dims** [comment]
@nikhita looks like notifications were sent a few days ago. Can we merge this now?

**Comment by nikhita** [comment]
> @nikhita looks like notifications were sent a few days ago. Can we merge this now?

Yes. For the record, here are the notifications to the mailing lists:

- https://groups.google.com/g/kubernetes-dev/c/LMuqq1BgOmk
- https://groups.google.com/g/kubernetes-sig-service-catalog/c/qtNVXvK7b0s

Welcome, @jhvhs and thanks for everything, @mszostok!

/hold cancel
/approve

**Pull request merged**
