### PR TITLE
sig-scheduling: add monthly meeting for APAC timezone

### PR DESCRIPTION
**Pull request by Huang-Wei**
Add monthly meeting for APAC timezone.

cc @ahg-g

### CODE REVIEW

**Review by mrbobbytables — CHANGES_REQUESTED** [review]
@Huang-Wei the changes need to be made in sigs.yaml, after that you run `make` and it'll update it in all the places its needed 👍

**Comment by Huang-Wei** [comment]
Thanks Bob. That's way fancy lol...

**Comment by Huang-Wei** [comment]
@mrbobbytables could you please approve this? (just realized it's not merged yet)

**Comment by alculquicondor** [comment]
/assign @liggitt 
our liaison

**Comment by Huang-Wei** [comment]
Kindly ping @liggitt for approval.

**Comment by liggitt** [comment]
sorry, missed this

/approve

**Review by mrbobbytables — COMMENTED** [review]
oof yeah, sorry this slipped through the cracks :(

/lgtm

**Pull request merged**
