### PR TITLE
stop suggesting depth=1, suggest filter=blob:none instead

### PR DESCRIPTION
**Pull request by BenTheElder**
depth=1 will break git version info and break the build

**Which issue(s) this PR fixes**:

Fixes #

https://github.com/kubernetes/kubernetes/issues/116716 may be related, see also https://github.com/kubernetes/test-infra/issues/26590

### CODE REVIEW

**Comment by BenTheElder** [comment]
/approve-cancel
not intending to over-wield steering root approval

**Comment by BenTheElder** [comment]
Hmm, that's a fun edge case in prow
/hold
Holding for approvals instead

**Comment by thockin** [comment]
I need to learn about this filter, but initial reading says it is OK.

/lgtm

**Comment by BenTheElder** [comment]
> I need to learn about this filter, but initial reading says it is OK.

Good reading:
https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/

Basically this means you still pull down the history tree and current blobs but not past blobs.

All the filter options and depth basically defer what is available. Depth also _breaks_ some things, filter only adds the latency of deferred on-demand fetches for certain comments.

If you need to run something like `git blame` on a clone with `filter=blob:none` it will have to fetch the required missing blobs then, adding some latency to that class of command.

For a typical build we just need `git describe --tags` to work and don't need to blame/diff/...
Describing a version based on the most recent tag doesn't work with `--depth=1` but it does work with filter.

_Some_ of our CI runs with this now https://github.com/kubernetes/test-infra/pull/28954

**Comment by thockin** [comment]
Interesting:

Cloning k/k default: 1m6.651s
Cloning k/k with `--filter=blob:none`: 0m27.236s
Cloning k/k with `--filter=tree:0`: 0m17.843s
Cloning k/k with `--depth=1`: 0m13.215s

**Comment by thockin** [comment]
Fetching a single k/k SHA:
* default: 0m54.218s
* --filter=blob:none: 0m8.949s
* --filter=tree:0: 0m3.536s
* --depth=1: 0m11.262s

I am surprised!  If I add in time to checkout FETCH_HEAD I get:

* --filter=blob:none: 0m21.754s
* --filter=tree:0: 0m22.544s
* --depth=1: 0m12.816s

I think I hit some rate-limits, becuase re-running shows slower.

**Pull request merged**
