### PR TITLE
Add client-python to supported clients

### PR DESCRIPTION
**Pull request by mbohlool**
Client is in development and soon to be released out of alpha, but it is supported. I would like to add it to this list so it gets more attraction.
I also want this to be updated at main kubernetes repo, how does that work from this repo to main repo? ref: kubernetes/kubernetes#37719

### CODE REVIEW

**Comment by philips** [comment]
What does supported even mean? I mean I bet some of those community repos are supported as well. Can we call them Kubernetes Community Supported vs Wider Community Supported?

**Comment by mbohlool** [comment]
By supported here I mean we as kubernetes community (and specifically here @kubernetes/sig-api-machinery ) make sure it will be maintained and keep in sync with latest kubernetes changes (newly added API/Groups, changes in API definitions, etc.). We may not sync the release of the client with release of the kubernetes, but it would be close. If there is a formal definition of supported and list of requirements to be in this list, please elaborate on that.

**Comment by philips** [comment]
@mbohlool How about we say "Supported by Kubernetes SIG API Machinery"?

**Comment by mbohlool** [comment]
@philips Look good to me, will do the change.

**Comment by mbohlool** [comment]
Done. Also updated sig-api-machinary page in the community page with links and infos to the team channels #139

**Comment by philips** [comment]
LGTM

**Comment by mbohlool** [comment]
@philips Thanks. I also did not see last part of your message. The reply should have been simply yes, we should call it Kubernetes Community supported :)

**Pull request merged**
