### PR TITLE
Fix sig-ui updates

### PR DESCRIPTION
**Pull request by cblecker**
Sig UI updates from https://github.com/kubernetes/community/pull/931 weren't done in the right place, so autogeneration reverted them.

### CODE REVIEW

**Comment by grodrigues3** [comment]
I can confirm that the updates to sigs.yaml is fine and you ran make correctly.

Someone from sig-ui (which doesn't appear to have gh teams set up) should confirm leadership change and lgtm

**Comment by grodrigues3** [comment]
@danielromlein

**Comment by cblecker** [comment]
The leadership change was in #391, but it got reverted because it was done in the wrong place

**Comment by grodrigues3** [comment]
Think you meant #931.

/lgtm

**Comment by cblecker** [comment]
yes, sorry :) thanks @grodrigues3 !

**Pull request merged**
