### PR TITLE
slack: add loft channel

### PR DESCRIPTION
**Pull request by LukasGentele**
I would like to open a #loft slack channel for users of [Loft](https://loft.sh/): Virtual clusters and multi-tenancy extension for Kubernetes

The channel would also be used to discuss the open-source projects around Loft located in the [loft-sh](https://github.com/loft-sh) organization on GitHub. So far, discussions have mostly been 1:1 between users and Loft maintainers or users have used other slack channels to ask questions about Loft and surrounding projects, so I think it would make sense to have a separate channel for everyone to ask questions, share thoughts and discuss the roadmap.

### CODE REVIEW

**Comment by coderanger** [comment]
Given that Loft itself is a commercial product, and it looks like all your open source projects are in support of that product, I'm not sure this would be appropriate. We do sometimes allow for channels about proprietary tools for organic user-to-user support, but given that you are requesting this on the behalf of the vendor I think you should pursue building your own community spaces first.

What say the other Slack admins?

**Comment by LukasGentele** [comment]
I didn't know that this was a requirement for opening a channel. There is the #k8spin channel for example which [was opened last year](#4643) for users of a commercial k8s-focused SaaS platform. I think from an end-user perspective, it's more convenient to be able to chat in a larger workspace than having to join all slack groups of each vendor individually but that's just my personal opinion.

**Comment by coderanger** [comment]
As I said, we do allow it from it time to time, but usually we try and encourage vendors to build their own spaces. Additionally they have quite a few FOSS projects that as not specifically related to their products (as in, they are useful to people that do not use their product) while I don't see any of that for Loft so far.

**Comment by LukasGentele** [comment]
I beg to differ: My team and I created two fairly popular open-source projects: [DevSpace](https://github.com/devspace-cloud/devspace) and [kiosk](https://github.com/kiosk-sh/kiosk). Both projects can be used entirely without Loft and plenty of people are doing exactly that. However, in the case of kiosk, for example, we have the project in a separate kiosk-sh org on github because we intend to eventually contribute it to CNCF once it is more mature and more popular.

Because of the separate github orgs, it may not be obvious to you that this is the same group of maintainers and we can change that and move kiosk back to the loft-sh org, for example, if that is the recommended approach going forward. We also have 2 further open-source projects in the pipeline which are currently part of Loft and therefore would be adequate to discuss in a #loft channel before they reach a number of users that makes sense to spin out in a separate channel. One of these projects in the making is virtual-cluster which you can see as a separate project in the loft-sh namespace. It is currently part of Loft and therefore as of today closed-source but the project is intentionally already placed in a separate repo because we will open-source this part of Loft in a few weeks.

**Comment by mrbobbytables** [comment]
We do generally only allow OSS projects. There are a few fuzzy areas such as with the cloud providers, but there is history there and they have associated upstream projects e.g. the cluster-api implementations.

>  I beg to differ: My team and I created two fairly popular open-source projects: DevSpace and kiosk. Both projects can be used entirely without Loft and plenty of people are doing exactly that. However, in the case of kiosk, for example, we have the project in a separate kiosk-sh org on github because we intend to eventually contribute it to CNCF once it is more mature and more popular.

To be frank, none of that was clear in your original request, and not obvious from the website. Viewing it from our perspective, it appears like a commercial project with a helm chart.

From the [slack guidelines on requesting a channel](https://www.kubernetes.dev/docs/comms/slack/#requesting-a-channel):
```
Channels are NOT:
- Company specific; cloud providers are ok with product names as the channel.
  Discourse will be about Kubernetes-related topics and not proprietary information of the provider.
 ```

> It is currently part of Loft and therefore as of today closed-source but the project is intentionally already placed in a separate repo because we will open-source this part of Loft in a few weeks.

We have historically blocked on this until the project is open sourced to prevent potential squatting or misuse.

In this instance, I would opt for a kiosk channel or wait till a bit after the OSS project is released before requesting a channel.

**Comment by LukasGentele** [comment]
@mrbobbytables I mean you're right. Loft is a commercial product with a helm chart and we are spinning open source projects out of it which all happen to be then maintained by the same folks. I just thought it made sense to point users to one place for discussion rather than separate slack workspaces/channels for each project.

**Comment by coderanger** [comment]
As I said, we encourage you to set up your own community resources. Most of the cases of vendor-specific channels we have are due to upstream vendors having insufficient community support spaces and so users come to us and ask for it so they can support each other, rather than the vendor asking us for it.

**Comment by LukasGentele** [comment]
That makes sense. I understand that. I'll close this for now and will open a new PR once we have the virtual cluster project out and once the kiosk project has been moved back to the loft-sh org because I do think it makes sense to have a central place for discussion about projects spinning out of Loft and since they are all related, it may not make sense to have separate fragmented slack channels for everything. But I get your point that right now, loft org on github hosts only a commercial project and the relationship is not clear from the name, so we'll change that in the future. Thanks

**Pull request closed without merging**
