### PR TITLE
Fix Cloud Provider Azure Subproject meeting times

### PR DESCRIPTION
**Pull request by craiglpeters**

### CODE REVIEW

**Comment by craiglpeters** [comment]
make WHAT=sig-cloud-provider generate

**Comment by craiglpeters** [comment]
/assign @timothysc
I can't figure out why the pull-community-verify job failed

**Comment by craiglpeters** [comment]
NOTE: The one hour shift of the second meeting is intentional

**Comment by nikhita** [comment]
@craiglpeters you'll need to run `make generate`

**Comment by craiglpeters** [comment]
@nikhita did I do it wrong here? https://github.com/kubernetes/community/pull/4322#issuecomment-566649629

**Comment by nikhita** [comment]
@craiglpeters sorry, I should have been clearer -- I meant that you'll need to run `make generate` on your machine (not as a prow command). That will generate the README file. :)

**Comment by nikhita** [comment]
tiny nit: Can you also squash the commits to a single commit? Thanks!

**Comment by craiglpeters** [comment]
I'm going to abandon this mess, and create a new clean PR

**Pull request closed without merging**
