### PR TITLE
Corrected URL destination

### PR DESCRIPTION
**Pull request by kojikaz**
**Which issue(s) this PR fixes**:

Fixes #
https://github.com/kubernetes/community/blob/master/contributors/guide/contributor-cheatsheet/README-ja.md

### CODE REVIEW

**Comment by Okabe-Junya** [comment]
Hello @kojikaz!! Thank you for your contribution!! 

I'm one of the SIG-Docs Japanese l10n reviewer, so let me move forward to this PR!!

/ok-to-test
/assign @mrbobbytables

**Comment by Okabe-Junya** [comment]
/assign nikhita
for approval

**Comment by mrbobbytables** [comment]
Sorry, this fell through the cracks >_<
/lgtm
/approve

**Pull request merged**
