### PR TITLE
Update sig-architecture for enhancments subproject

### LINKED ISSUE #4890: Update enhancements subproject meeting info under sig-architecture
The enhancements subproject (under sig-arch) has scheduled a reoccuring subproject meeting. This info should be updated into the `sigs.yaml` and sig-architecture's README.

### PR DESCRIPTION
**Pull request by jeremyrickard**
This PR updates sigs.yaml and the sig-architecture/README.md file to add meeting
info for the enhancements subproject. Does a small extra cleanup to remove a reference
to SIG-PM owning the enhancements process and updates the scope of sig-architecture to again
include the KEP process.

**Which issue(s) this PR fixes**:
Fixes #4890 

Signed-off-by: Jeremy Rickard <rickardj@vmware.com>

### CODE REVIEW

**Comment by jdumars** [comment]
didn't mean to steal @johnbelamaric thunder here :)

**Comment by justaugustus** [comment]
/lgtm
/approve
I leave the hold-lifting to SIG Arch Chairs

**Comment by dims** [comment]
/approve
/lgtm

will leave /hold cancel to @johnbelamaric

**Pull request merged**
