### PR TITLE
add Slack channel for the vcluster project

### PR DESCRIPTION
**Pull request by richburroughs**
**Which issue(s) this PR fixes**:

Hi,

We'd like to add a channel to the Slack for the open source vcluster project. vcluster is a tool for creating and managing virtual Kubernetes clusters.

The GitHub page for the project is: [https://github.com/loft-sh/vcluster](https://github.com/loft-sh/vcluster)

Thank you.

### CODE REVIEW

**Comment by richburroughs** [comment]
@parispittman Hi thanks :) I just signed it.

**Review by markyjackson-taulia — APPROVED** [review]
/lgtm
Holding for a one more moderator to approve
/hold

**Comment by thebsdbox** [comment]
Hey @markyjackson-taulia, is there anything we can do to move this forward as it's been stuck for quite a while 😀

**Comment by markyjackson-taulia** [comment]
@thebsdbox yeah, let me cc @coderanger / @castrojo

**Comment by FillZpp** [comment]
I'm sorry, is it a little weird to create a channel in K8s workspace for a 3rd party project from an independent company.

**Comment by markyjackson-taulia** [comment]
@FillZpp not at all, most projects have donated their project to the CNCF. 
As stated here https://github.com/kubernetes/community/blob/master/communication/slack-guidelines.md

Very normal

**Pull request merged**
