### PR TITLE
Update CAPV meeting notes links

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**Which issue(s) this PR fixes**:

This PR updates the links to the CAPV meeting notes (we recently moved them to the community gdrive)

### CODE REVIEW

**Review by chrischdi — COMMENTED** [review]
/lgtm

**Review by neolit123 — COMMENTED** [review]
pro tip is to just keep the same meeting link on a private google acc and archive old docs by copy + paste.

**Comment by neolit123** [comment]
ok, understood. +1 for using the community drive. i think the SIG CL meeting is still on `@roberthbailey` 's account.

**Review by pacoxu — APPROVED** [review]

**Pull request merged**
