### PR TITLE
Private Triage Process and Vulnerability Scanning for Build Time Dependencies

### PR DESCRIPTION
**Pull request by PushkarJ**
Related https://github.com/kubernetes/kubernetes/issues/101528

### CODE REVIEW

**Comment by PushkarJ** [comment]
@navidshaikh PTAL

**Comment by PushkarJ** [comment]
This PR: https://github.com/kubernetes/test-infra/pull/22833, enables notification and private triage after which the category and its corresponding resolution is identified.

**Comment by MadhavJivrajani** [comment]
/remove-lifecycle stale
/lifecycle frozen
@PushkarJ anything else that needs to be done here?

**Comment by PushkarJ** [comment]
@MadhavJivrajani I will be closing this shortly and create a new one (or two) on https://github.com/kubernetes/sig-security as most of the content on deliverables has moved there for SIG Security. 11

**Comment by PushkarJ** [comment]
New PR: https://github.com/kubernetes/sig-security/pull/16 replaces the need for this PR. Hence, closing!

**Pull request closed without merging**
