### PR TITLE
Add the meeting notes for etcdadm Office Hours

### PR DESCRIPTION
**Pull request by championshuttler**
Signed-off-by: championshuttler <shivams2799@gmail.com>

/assign @mrbobbytables

### CODE REVIEW

**Comment by nikhita** [comment]
You'll also need to run `make` to autogenerate some files.

**Comment by championshuttler** [comment]
> You'll also need to run `make` to autogenerate some files.

@nikhita Done

**Comment by mrbobbytables** [comment]
Thanks @championshuttler :)
/lgtm
/approve

**Pull request merged**
