### PR TITLE
sig-api-machinery: Add C Kubernetes Client Library repo

### PR DESCRIPTION
**Pull request by mrbobbytables**
ref: https://github.com/kubernetes/org/issues/1700
/cc @brendandburns @ityuhui
/assign  @fedebongio @deads2k @lavalamp

/hold 
For sign-off from leads

### CODE REVIEW

**Comment by nikhita** [comment]
>  /assign @fedebongio @deads2k @lavalamp

Weird that this didn't assign folks. Take 2.

/assign @fedebongio @deads2k @lavalamp

**Comment by mrbobbytables** [comment]
gentle nudge: @fedebongio @deads2k @lavalamp

**Comment by lavalamp** [comment]
/lgtm
/approve

sorry, thought I already approved this...

**Comment by mrbobbytables** [comment]
No worries :)
/hold cancel

**Pull request merged**
