### PR TITLE
Remove myself from SIG-CLI chairs

### PR DESCRIPTION
**Pull request by soltysh**
Per the announcement from Sep 22, 2021, see here: https://groups.google.com/g/kubernetes-sig-cli/c/Hxqb7h-fZGI/m/wRiT-2Z1CwAJ I'm removing myself from sig-cli chairs.

/assign @eddiezane @KnVerey @seans3

### CODE REVIEW

**Review by mrbobbytables — COMMENTED** [review]
Not a blocker, but how about moving yourself over to emeritus?^^;;;

**Comment by pwittrock** [comment]
@soltysh hold is for if you want to move to emeritus

**Comment by mrbobbytables** [comment]
@soltysh just a bump reminder, it needs a rebase :x

**Comment by soltysh** [comment]
/hold cancel
@mrbobbytables should be good to merge

**Pull request merged**
