### PR TITLE
Organizing community events into folders by year

### PR DESCRIPTION
**Pull request by czahedi**
Created a 2016-events directory, and moved the 2016 event announcements into said directory. I will soon make a 2017-events directory to announce 2017-events.

We could make an "Events" directory and then organize by year, if that makes more sense. I was just trying to start organizing this stuff instead of filling up the folder with individual event announcements. 

Also the web interface won't let me move the whole "developer-summit-2016" folder into the "2016-events" folder. I'll try to learn how to do it through the terminal, but if someone wants to go ahead and move it thanks in advance :)

### CODE REVIEW

**Comment by philips** [comment]
LGTM but CLA problems

**Comment by czahedi** [comment]
I signed the CLA

"I signed it!" in case there's a text filter lookup or something


Cameron Zahedi |  Developer Relations Program Manager | Google Cloud
Platform |  czahedi@google.com |  +1 770-658-4595

**Comment by sarahnovotny** [comment]
cncf-cla: yes \o/

**Comment by idvoretskyi** [comment]
@czahedi great initiative, thank you!

**Pull request merged**
