### PR TITLE
Updated chairs, recordings link and security audit subproject owners …

### PR DESCRIPTION
**Pull request by JayBeale**
Updated chairs, recordings link and security audit subproject owners.

@IanColdwater @tabbysable @aasmall @cji

### CODE REVIEW

**Review by mrbobbytables — COMMENTED** [review]
Once other small request, can you remove the ` \n` from the community discussion subproject? That probably shouldn't have made it in there the first time 😬

**Comment by tabbysable** [comment]
/lgtm

So excited to help build a shelter for hackers, policy wonks, horrible geese, and everybody else (even information security professionals) that wants to make k8s better and safer!

/honk

**Comment by JayBeale** [comment]
> Once other small request, can you remove the ` \n` from the community discussion subproject? That probably shouldn't have made it in there the first time 😬

Can do!

/honk

**Comment by JayBeale** [comment]
@mrbobbytables - newline removed.

**Comment by aasmall** [comment]
> 
> 
> New changes are detected. LGTM label has been removed.

/lgtm

**Pull request merged**
