### PR TITLE
Update design doc based on code

### PR DESCRIPTION
**Pull request by orainxiong**
update design pattern doc with :
* Integrating binding with scheduling
* Scheduler Changes
* Update volume-topology-scheduling.png

@kubernetes/sig-storage
cc @msau42

### CODE REVIEW

**Comment by orainxiong** [comment]
update volume-topology-scheduling.png

**Comment by orainxiong** [comment]
cc @lichuqiang

**Comment by msau42** [comment]
Thanks for taking a close look at this design doc.  I also made some similar updates in https://github.com/kubernetes/community/pull/1857.  I think we can just include it all in change to make it easier to merge.  Could you compare the two and see if anything is missing?

**Comment by orainxiong** [comment]
OK.

**Pull request closed without merging**
