### PR TITLE
Update info in svc-cat chairs section

### PR DESCRIPTION
**Pull request by mszostok**
**Description**
I left the SAP at the end of last month and now I'm self-employed.

### CODE REVIEW

**Comment by mrbobbytables** [comment]
@mszostok you should update your affiliation in sigs.yaml then run `make`. That will auto-update all the sources.

**Comment by mszostok** [comment]
@mrbobbytables thanks, now I updated that properly 👍 also the error message in pipeline was meaningful, so +1 for the validator author

**Pull request merged**
