### PR TITLE
Fixed sig-contribex youtube link

### LINKED ISSUE #6442: Incorrect link for sig-contribex video meetings
### Describe the issue

On this page https://github.com/kubernetes/community/blob/master/sig-contributor-experience/README.md#meetings  there is a link for video meetings that is incorrect.

It should be updated
from:
```
https://www.youtube.com/watch?v=EMGUdOKwSns&list=PL69nYSiGNLP2x_48wbOPO0vXQgNTm_xxr
```
to:
```
https://www.youtube.com/playlist?list=PL69nYSiGNLP2x_48wbOPO0vXQgNTm_xxr
```

### PR DESCRIPTION
**Pull request by csantanapr**
**Which issue(s) this PR fixes**:
Fixes #6442

### CODE REVIEW

**Comment by csantanapr** [comment]
>@csantanapr - if you update sigs.yaml and run make that will update it in all the places that are needed :)

Already took care of it. the build error told me what to do

**Comment by csantanapr** [comment]
@mrbobbytables PTAL when you have a chance

**Review by Debanitrkl — APPROVED** [review]
Thanks for the changes
/lgtm

**Pull request merged**
