### PR TITLE
Cluster API: update office hours agenda document link

### PR DESCRIPTION
**Pull request by jackfrancis**
This doc updates the link to the CAPI office hours agenda doc to use the new alias (the old one no longer works).

**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Comment by fabriziopandini** [comment]
Thanks for taking care of this!
/lgtm
/approve

**Comment by sbueringer** [comment]
Thx. Looks like verify is not happy

**Comment by cblecker** [comment]
@jackfrancis you'll need to update sigs.yaml and then run a `make`

**Comment by jackfrancis** [comment]
@sbueringer @cblecker did this the right way, finally!

thx

**Comment by sbueringer** [comment]
Thx!

/lgtm

**Review by cblecker — APPROVED** [review]

**Pull request merged**
