### PR TITLE
hpa: fix invalid links

### PR DESCRIPTION
**Pull request by sak0**
hpa-v2.md:  fix invalid links

Signed-off-by: CuiHaozhi <cuihaozhi@chinacloud.com.cn>

### CODE REVIEW

**Comment by stp-ip** [comment]
@feiskyer The link is not absolute and breaks, when this document is moved. Don't we usually use links like: `/contributors/design-proposals/instrumentation/resource-metrics-api.md`

**Comment by feiskyer** [comment]
@stp-ip It's true for kubernetes websites, but we should make markdown link work here.

**Comment by stp-ip** [comment]
Absolute paths (not absolute links) would work here too and remove the breaking, when a document is moved.

**Pull request merged**
