### PR TITLE
Automatically update OWNERS_ALIASES for UGs

### PR DESCRIPTION
**Pull request by nikhita**
Got missed in https://github.com/kubernetes/community/pull/3298 :(

/cc @spiffxp @idealhack @erikerlandson

### CODE REVIEW

**Comment by nikhita** [comment]
I checked https://github.com/kubernetes/community/pull/3304 out locally and can confirm this works now fwiw.

**Comment by nikhita** [comment]
/assign @spiffxp 
for approval

**Comment by erikerlandson** [comment]
bump

**Comment by nikhita** [comment]
/assign @grodrigues3 
can you approve?

**Pull request merged**
