### PR TITLE
Deleting stub file - Issue 3064

### PR DESCRIPTION
**Pull request by eduartua**
Just removing a stub file. There are no files in k/community pointing it.
issue #3064 
/sig contributor-experience
/kind feature

/assign @spiffxp 
/assign @cblecker 
/assign @guineveresaenger

### CODE REVIEW

**Comment by guineveresaenger** [comment]
Some of this is duplicated in https://github.com/kubernetes/community/pull/3086 I think?

**Comment by guineveresaenger** [comment]
ah, I see what happened, you'll want a new git branch for this PR. it's late in the week, but happy to help unpick some Git. 😄

**Comment by eduartua** [comment]
> ah, I see what happened, you'll want a new git branch for this PR. it's late in the week, but happy to help unpick some Git.

Now there is no duplicated content. Could you review this again?

**Comment by guineveresaenger** [comment]
Awesome!
/lgtm

**Pull request merged**
