### PR TITLE
Proto is our default storage serialization; we can't break it

### PR DESCRIPTION
**Pull request by lavalamp**

### CODE REVIEW

**Comment by lavalamp** [comment]
/assign @smarterclayton 
/assign @liggitt 
cc @bgrant0607

**Comment by lavalamp** [comment]
/assign @grodrigues3 

Can you rubber stamp this please?

Should we move this file into an api machinery specific location?

**Comment by cblecker** [comment]
/approve

Up to you. Yes we can totally move this to a more specific folder with an OWNERS file.

**Pull request merged**
