### PR TITLE
Remove the APAC meeting from SIG-Scheduling

### LINKED ISSUE #7254: [SIG Scheduling] Negotiating the community meeting time
### Describe the issue

Refer to https://github.com/kubernetes/community/pull/7215/files#r1153628357

Some context:

We have quite a bit of contributors from APAC, but the scheduled biweekly meeting time is usually too late, so we reached an agreement of another APAC meeting monthly. We have attenders in APAC meeting, but usually very little, and gradually we host the meeting less and less. It acts like the broken windows effect, however, we can not just ignore the meeting in case we do have members attend.

@alculquicondor provides a suggestion here:

> Maybe we should go back to alternated times, preserving meetings every 2 weeks.

> We have 3 TLs, two in PDT and one in EDT. Ideally each meeting should fall within business hours of at least two TLs. The > current one falls within business hours of all of us. I think we can keep this one and move the other one, but I think it will still > have to be slightly out of business hours.

So in this thread, we'll discuss about:
- Whether we should cancel the APAC meeting
- Whether we agree to turn the primary meeting to alternated times, also the exact meeting time.
- Or we have other advices

/sig scheduling
cc @kubernetes/sig-scheduling-misc

### PR DESCRIPTION
**Pull request by sanposhiho**
**Which issue(s) this PR fixes**:

Fixes #7254

### CODE REVIEW

**Comment by sanposhiho** [comment]
/cc @kerthcet @Huang-Wei 
Can you check if you agree

**Review by kerthcet — COMMENTED** [review]
/lgtm
/approve
Thanks!

**Comment by Huang-Wei** [comment]
Thanks @sanposhiho . I've also removed the AP meeting from Google calendar.

**Pull request merged**
