### PR TITLE
sig-release: Assume ownership of k/repo-infra

### PR DESCRIPTION
**Pull request by justaugustus**
Continuing the conversation from https://github.com/kubernetes/community/pull/4981.

/assign @tpepper @saschagrunert @alejandrox1 
SIG Release leads

/assign @spiffxp @BenTheElder @stevekuznetsov
SIG Testing leads

/hold for discussion

### CODE REVIEW

**Comment by saschagrunert** [comment]
I'm not very opinionated on that topic.
/lgm

**Comment by BenTheElder** [comment]
/lgtm
:+)

**Comment by justaugustus** [comment]
@BenTheElder -- We have a winner! :stuck_out_tongue_winking_eye: 
/hold cancel

**Pull request merged**
