### PR TITLE
Update release.md

### PR DESCRIPTION
**Pull request by maxsxu**
**Which issue(s) this PR fixes**:

Fix broken link of the release versioning document.

**Motivation**

The current link https://github.com/kubernetes/community/blob/master/contributors/design-proposals/release/versioning.md is broken as the design proposals have been archived.

We should use the latest link https://github.com/kubernetes/sig-release/blob/master/release-engineering/versioning.md

### CODE REVIEW

**Comment by puerco** [comment]
Thanks @maxsxu , can you please squash your commits?
Make sure the PR has a single non-merge commit.

Thanks!

**Comment by maxsxu** [comment]
> Thanks @maxsxu , can you please squash your commits? Make sure the PR has a single non-merge commit.
> 
> Thanks!

@puerco Commits squashed. PTAL, thanks

**Review by cpanato — APPROVED** [review]
thanks!
/lgtm

**Pull request merged**
