### PR TITLE
wg-cluster-api: add meeting details

### PR DESCRIPTION
**Pull request by nikhita**
`sig-list.md` currently shows `* Regular WG Meeting: s at ()` in the Meetings column for wg-cluster-api.

This PR adds meeting details. The details have been taken from the ones mentioned in sig-cluster-lifecycle column. They can also be verified from here: https://docs.google.com/document/d/16ils69KImmE94RlmzjWDrkmFZysgB2J4lGnYMRN89WM/edit#heading=h.oc87g6fd6waj.

Since the meetings go explicitly into the column for wg-cluster-api, I removed the details from sig-cluster-lifecycle. But there are two PRs which seem to be changing this to "office hours": https://github.com/kubernetes/community/pull/2528 and https://github.com/kubernetes/community/pull/2592. Adding an explicit hold because of them.
/hold

/wg cluster-api
/sig cluster-lifecycle
/assign luxas timothysc roberthbailey kris-nova

### CODE REVIEW

**Comment by detiber** [comment]
/lgtm

@timothysc might be good to rebase your update to include this change.

**Comment by roberthbailey** [comment]
I wonder if it would make more sense to just remove the cluster-api working group directory and make it officially a sub project of sig cluster lifecycle. Our recently merged charter includes the cluster api project.

**Comment by timothysc** [comment]
NAK on this, it's a sub-project and I actually made that change in the other PR.  

I will make it more explicit, closing this one.

**Comment by timothysc** [comment]
Working groups don't own code and are ephemeral according to the definition.

**Pull request closed without merging**
