### PR TITLE
Fixes some link in sig-cli

### PR DESCRIPTION
**Pull request by ahmadnurus**
Fixes some link in sig-cli

* On a smartphone, link with the anchor directly to [/sig-cli](https://github.com/kubernetes/community/tree/master/sig-cli)  it doesn't work, so I add README.md before the anchor
* Link to header instead of line number on `SIG Technical Leads` link

### CODE REVIEW

**Comment by prksu** [comment]
cc @seans3 @pwittrock

**Comment by pwittrock** [comment]
woot

**Pull request merged**
