### PR TITLE
add slack channel for k8s-image-swapper

### LINKED ISSUE #7007: REQUEST: New Slack channel #k8s-image-swapper
### GitHub Username

@estahn

### Slack Username

@estahn

### What Type of Request is it (Channel, User Group, Bot, Token, or Webhook)?

channel

### Name of Requested Resource

#k8s-image-swapper

### Description of Request

Similar to other tools to help and support the community using https://github.com/estahn/k8s-image-swapper

### PR DESCRIPTION
**Pull request by estahn**
**Which issue(s) this PR fixes**:

Fixes #7007

### CODE REVIEW

**Comment by coderanger** [comment]
@estahn The tests are all run (it's just some formatting checks for the file)

/lgtm

**Comment by jberkus** [comment]
ooops!  didn't realize this hadn't merged.

/approve

**Pull request merged**
