### PR TITLE
docs(contributor guide): fix broken link

### PR DESCRIPTION
**Pull request by lloydchang**

### CODE REVIEW

**Comment by lloydchang** [comment]
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.

Replying.

**Review by markyjackson-taulia — APPROVED** [review]
/lgtm

**Review by markyjackson-taulia — APPROVED** [review]
/approve

**Comment by markyjackson-taulia** [comment]
@lloydchang someone will grab it; thanks for the pr.

**Comment by lloydchang** [comment]
Thank you for your time @markyjackson-taulia @mrbobbytables @alisondy @nikhita @cblecker

**Suggestion:**
• To improve the user experience for new contributors, perhaps Kubernetes Prow Robot can simply say, "someone will grab it."

**User experience as a new contributor:**
• I was following prescriptive instructions from 🤖 our new robot overlords 🤖.
• 🤷‍♂️ I don't understand why Kubernetes Prow Robot repeatedly _(three times)_ asked me to assign this to @cblecker.
• After receiving three emails, I interpreted that I needed to follow prescriptive instructions — **before** Kubernetes Prow Robot emails me a fourth time.

-----

**Email 1 of 3:**

**Pull request merged**
