### PR TITLE
Kubernetes Blog Subproject: Proposed README and Role Handbooks 

### PR DESCRIPTION
**Pull request by kbarnard10**
This PR includes proposed documentation, processes, and roles for the Kubernetes blog.

### CODE REVIEW

**Comment by kbarnard10** [comment]
/hold
cc // @zacharysarah @parispittman @mrbobbytables @vonguard @cody-clark @castrojo

**Comment by parispittman** [comment]
yay so happy for this!! thank you for all of your hard work to date and future :)

**Comment by vonguard** [comment]
Done!

Should read much better now.

**Comment by nikhita** [comment]
:wave: Is there anything blocking this? Looks like it is ready to be merged?

**Comment by parispittman** [comment]
I see Zach and Kaitlyn both approved it so I'll give the final lgtm to merge

/lgtm

**Pull request merged**
