### PR TITLE
create e2e-framework slack channels

### PR DESCRIPTION
**Pull request by cpanato**
create slack channels for the e2e-framework project

one for the development and the other for users support and general requests/topics

/assign @jberkus @mrbobbytables @harshanarayana @vladimirvivien

### CODE REVIEW

**Comment by vladimirvivien** [comment]
@cpanato @jeefy @mrbobbytables 
Let us know if there anything else this PR needs to be approved?
It would be great to be able to set this up prior to KubeCon NA if possible.

**Comment by cpanato** [comment]
thanks @jberkus

**Comment by jberkus** [comment]
sorry for delay, but you know *exactly* what I've been doing.

**Pull request merged**
