### PR TITLE
Initial Draft VMware User Group

### PR DESCRIPTION
**Pull request by cantbewong**

### CODE REVIEW

**Comment by cantbewong** [comment]
committee/steering

**Comment by jdumars** [comment]
@cantbewong is this blocked?  Is the steering committee working on it? Not sure what the status is.

**Comment by cantbewong** [comment]
Yes @jdumars , this is temporarily blocked while proposed co-chair Myles Gray attempts to get membership status. He is having difficulty because nearly all his Kubernetes activity has been VMware focussed so getting a second membership sponsor, from a second org other than VMware has been an issue

**Comment by jdumars** [comment]
Send me some links so I can take a look.

**Comment by cantbewong** [comment]
@jdumars > Send me some links so I can take a look.

Work on upstream docs, bug logging and reviewing PRs logged for CAPV, vSphere Cloud Provider, vSphere CPI and vSphere CSI drivers. Example"
https://github.com/kubernetes-sigs/vsphere-csi-driver/commit/63447770bf1990bf01baaf8e9e88439da49e3b8f

https://github.com/kubernetes/cloud-provider-vsphere/pull/181 (work done through Andrew’s fork and squashed into his commit).
https://github.com/kubernetes/cloud-provider-vsphere/pull/236 (worked offline with Cormac and pushed commits through his fork)
https://github.com/kubernetes/cloud-provider-vsphere/issues?utf8=✓&q=mylesagray

https://github.com/vmware/vsphere-storage-for-kubernetes/pulls?utf8=✓&q=mylesagray

https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues?utf8=✓&q=author%3Amylesagray+
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pulls?utf8=✓&q=mylesagray


Contributions to external-dns incubator project: https://github.com/kubernetes-incubator/external-dns/pull/1116

Contributions (indirectly) to Velero (kubernetes backup) project, refactored and build Velero images for multi-architectures, amd64, arm32v7 and arm64v8 (https://github.com/mylesagray/velero-multiarch) which became the basis of IBM’s multi-arch PR for Velero: https://github.com/heptio/velero/pull/1768

Active member on K8s Slack help troubleshooting VMware users installing and running K8s.

Active member on SIG-VMware community meetings

Co-authored RedHat reference architecture for 3.11 running on VMware: https://access.redhat.com/documentation/en-us/reference_architectures/2019/html-single/deploying_and_managing_openshift_3.11_on_a_vmware_software-defined_data_center/index

Extensive blogs on using K8s on vSphere via upstream plugins: http://blah.cloud/course/k8s-on-vmw/

**Comment by jdumars** [comment]
@cantbewong I couldn't find the org membership issue in https://github.com/kubernetes/org/issues  could you direct me to it?  Thanks!

**Comment by cantbewong** [comment]
> @cantbewong I couldn't find the org membership issue in https://github.com/kubernetes/org/issues could you direct me to it? Thanks!

@mylesagray didn't open a issue yet because he didn't have a non VMware (second org) sponsor lined up yet.

If you are willing to sponsor he can submit this

**Comment by jdumars** [comment]
Based on the activity, and commutative trust, I am willing to sponsor. Ping me a link when it is up.

**Comment by mylesagray** [comment]
Request in @jdumars - much appreciated, https://github.com/kubernetes/org/issues/1244

**Comment by jdumars** [comment]
cc: @idvoretskyi @mrbobbytables

**Pull request merged**
