### PR TITLE
add new KEP aws-lb-prefix-annotation

### PR DESCRIPTION
**Pull request by minherz**
New KEP for sig-aws group.

@justinsb, @kris-nova or @d-nishi, can you assign someone to review the KEP?

@justaugustus, please review that the content of KEP answers the current template.

### CODE REVIEW

**Comment by d-nishi** [comment]
@minherz can you link to the specific issue or PR this KEP is related to?

**Comment by minherz** [comment]
@d-nishi I had created #2891

**Comment by d-nishi** [comment]
@minherz can you link to the specific issue or PR this KEP is related to?

**Comment by d-nishi** [comment]
@minherz -- I am not talking about this PR that opens the KEP. 
Is there an existing bug or issue that has been discussed for this issue so I can create the problem?

**Comment by minherz** [comment]
@d-nishi, sorry for misunderstanding. I had opened feature request #62640 and submitted PR #64358 which was then closed due massive change in design of the cloud providers and an advise to open KEP first.

**Comment by justaugustus** [comment]
REMINDER: KEPs are moving to [k/enhancements](https://github.com/kubernetes/enhancements) on November 30. Please attempt to merge this KEP before then to signal consensus.
For more details on this change, review [this thread](https://groups.google.com/d/msg/kubernetes-dev/LIkZoIqCT20/t515CV2mAgAJ).

Any questions regarding this move should be directed to that thread and not asked on GitHub.

**Comment by minherz** [comment]
@d-nishi, due the move of KEPs to k/enhancements by Nov. 30, can I have this KEP merged?

**Comment by M00nF1sh** [comment]
The kep motivation looks good to me.

However, currently the name of ELB is used to discover existing ELBs. If the prefix on the ELB is configurable, should the implementation handle cases like change the name prefix?

Also, have you considering limiting IAM policies using resourceTags?  Which seems can solve same problem as described in this kep.
https://aws.amazon.com/about-aws/whats-new/2018/05/alb-and-nlb-now-support-resource--and-tag-based-permissions/

**Comment by d-nishi** [comment]
@M00nF1sh - lets address these questions post merge as separate PRs. Thanks for your inputs.

**Comment by justaugustus** [comment]
@d-nishi -- can you also `/approve` to trigger the merge?

**Pull request merged**
