### PR TITLE
Add submariner to slack channels.yaml file

### PR DESCRIPTION
**Pull request by mangelajo**
From the submariner[1][2] community we are looking for a neutral discussion place. We participate on the sig-multicluster and sig-networking SIG discussions to align API design with upstream.
We have lots of internal design threads which would pollute #sig-multicluster or #sig-networking channels.

Submariner is a project for connecting the IP address spaces of separate k8s clusters via IPSEC (and eventually WireGuard) plus routing. Today it mainly works with kube-proxy / iptables based implementations, but we plan to make proposals to the CNI interface for routing enhancements.

[1] https://submariner-io.github.io
[2] https://submariner.io

### CODE REVIEW

**Comment by gyliu513** [comment]
/lgtm

Glad to see we have a channel for submariner

**Comment by roytman** [comment]
Hi ,I'd like to request a new Submariner specific Slack channel. The #sig-multicluster and #sig-networking  channels are too wide for Submariner specific topics.

**Comment by Oats87** [comment]
+1 from me, having a dedicated space to discuss Submariner would be great, and less of a disturbance to other members of `#sig-networking` and `#sig-multicluster`

**Comment by castrojo** [comment]
/approve

Welcome!

**Comment by mangelajo** [comment]
Thank you!!! :-)

**Pull request merged**
