### PR TITLE
Rename seccomp-operator to security-profiles-operator

### PR DESCRIPTION
**Pull request by saschagrunert**
Renaming the operator to it's new proposed name.

Refers to https://github.com/kubernetes/org/issues/2177

### CODE REVIEW

**Comment by coderanger** [comment]
PR #5098 also needs an update to match this new name :) Can happen after this is merged though, as long as it's not too long.

**Comment by coderanger** [comment]
Heh, after posting that comment I see you superseded that PR, you'll want to include the existing channel ID so it's a rename rather than a new channel creation. (unless you want a new blank channel, up to you)

**Comment by saschagrunert** [comment]
> Heh, after posting that comment I see you superseded that PR, you'll want to include the existing channel ID so it's a rename rather than a new channel creation. (unless you want a new blank channel, up to you)

Yes, let's keep it in one PR. I updated the PR to now include the ID as well.

**Comment by nikhita** [comment]
/approve

Will let a slack admin lgtm

**Comment by coderanger** [comment]
Looks good on the slack side, Tempelis will rename the channel.

/lgtm

**Pull request merged**
