### PR TITLE
sig-multicluster: transition from @csbell to @pmorie

### PR DESCRIPTION
**Pull request by csbell**
Also, remove obsolete oncall rotation from Federation v1.

### CODE REVIEW

**Comment by spiffxp** [comment]
/approve
/hold
for SIG chairs

also please address the commit message error

**Comment by quinton-hoole** [comment]
/lgtm

This has also been discussed and agreed upon by the other active members of the SIG.

cc @irfanurrehman @shashidharatd @marun

**Comment by spiffxp** [comment]
Is there a linkable decision for this? Mailing list thread, meeting minutes, etc?

**Comment by csbell** [comment]
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/kubernetes-sig-multicluster/qc_QLqo1hGQ

**Comment by spiffxp** [comment]
>This group either doesn't exist, or you don't have permission to access it. If you're sure this group exists, contact the Owner of the group and ask them to give you access.

I can't seem to access your google group.  I can't even seem to get to a UI to ask to join the group.  Can you check to see if the permissions match what is described here? https://github.com/kubernetes/community/blob/master/communication/mailing-list-guidelines.md#mailing-list-creation

**Comment by csbell** [comment]
@spiffxp Should be readable now, Google groups changed their permissions model. Had to update Settings->Information->Directory

**Comment by spiffxp** [comment]
/hold cancel
Thanks for the audit trail

**Pull request merged**
