### PR TITLE
Update SIG Testing info

### PR DESCRIPTION
**Pull request by spiffxp**
- new meeting time, 9:30am PDT -> 1:00pm PDT
- new organizers: @fejta, @timothysc
- dropped old github team, added new github teams (hi @kubernetes/sig-testing-pr-reviews)
- added `sig/testing` label queries

### CODE REVIEW

**Comment by fejta** [comment]
Should we also update sig-list.md?

**Comment by spiffxp** [comment]
yes we should, good catch

**Comment by fejta** [comment]
LGTM!

**Pull request merged**
