### PR TITLE
Cluster API Provider vSphere Updated hours

### PR DESCRIPTION
**Pull request by randomvariable**
Update hours for Cluster API Provider vSphere (again, sorry).

**Which issue(s) this PR fixes**:

N/A

### CODE REVIEW

**Comment by randomvariable** [comment]
ping @ncdc  @timothysc

**Comment by nikhita** [comment]
/approve

leaving lgtm to @ncdc and @timothysc

**Comment by markyjackson-taulia** [comment]
Oops. Sorry @nikhita i gave an lgtm

**Comment by nikhita** [comment]
@markyjackson-taulia np, this looked good to be merged anyway :)

**Comment by randomvariable** [comment]
This is all good, folks, thanks.

Was pinging Tim mainly to update the google calendar.

**Pull request merged**
