### PR TITLE
Update meeting time for a cloud provider subproject

### PR DESCRIPTION
**Pull request by spzala**
Reflect updated meeting time for the Provider IBM Cloud subproject.

### CODE REVIEW

**Review by rtheis — APPROVED** [review]
/lgtm

**Comment by spzala** [comment]
cc @mrbobbytables @nikhita @andrewsykim

**Comment by mrbobbytables** [comment]
/approve
/hold
for sign off from a SIG-Cloud Provider leads

**Comment by spzala** [comment]
cc @nckturner @cheftako @andrewsykim - review request :), thanks!!

**Comment by mrbobbytables** [comment]
can you run make again? after that can merge

**Comment by spzala** [comment]
> can you run make again? after that can merge

Thanks @mrbobbytables Done.

**Review by mrbobbytables — COMMENTED** [review]
/lgtm
/hold cancel

**Comment by spzala** [comment]
Thank you @mrbobbytables !!

**Pull request merged**
