### PR TITLE
Archive SIG Service Catalog

### PR DESCRIPTION
**Pull request by mrbobbytables**
Archives SIG Serice Catalog, repos will be archived and follow-ups taken care after this PR is merged.

/hold

For steering review.

Context:
- [April 4th, 2022 Steering Meeting](https://docs.google.com/document/d/1qazwMIHGeF3iUh5xMJIJ6PDr-S3bNkT8tNLRkSiOkOU/edit?pli=1#heading=h.xcqoj5ucf1on) ([Recording](https://youtu.be/ctiECKpqHXE?list=PL69nYSiGNLP1yP1B_nd9-drjoxp0Q14qM))
- [[RFC] Retiring SIG Service Catalog (k-dev mailing list)](https://groups.google.com/a/kubernetes.io/g/dev/c/QRcg6XacYRw/m/4ghGcUk3EwAJ)
- [Spinning down of SIG Service Catalog / Repos (service catalog mailing list)](https://groups.google.com/g/kubernetes-sig-service-catalog/c/i4MqKYWhYx0/m/MO_7sNRqAgAJ)
- [minibroker - Is this project in use by anyone?](https://github.com/kubernetes-sigs/minibroker/issues/256)
- [service-catalog - Is this project in use by anyone?](https://github.com/kubernetes-sigs/service-catalog/issues/2913)
- [go-open-service-broker-client - Is this project in use by anyone?](https://github.com/kubernetes-sigs/go-open-service-broker-client/issues/172)

### CODE REVIEW

**Review by justaugustus — APPROVED** [review]
+1 (Steering)

**Comment by parispittman** [comment]
+1

**Comment by mrbobbytables** [comment]
+1 (steering)

**Comment by tpepper** [comment]
+1 (steering)

**Comment by cblecker** [comment]
+1 (steering)

**Comment by liggitt** [comment]
+1 (steering)

**Comment by dims** [comment]
+1 (steering)

**Comment by duanhongyi** [comment]
[Drycc service-catalog](https://github.com/drycc/service-catalog) is a fork of service-catalog that is actively developed and accepts code contributions.

Can you help me add this link(https://github.com/drycc/service-catalog) to the Archive Project?

**Comment by duanhongyi** [comment]
@mrbobbytables

**Comment by mohamedhani** [comment]
Hi, can any one provide me with helm chart of latest version of minibroker. when i try to add its repo i got this error
helm repo add minibroker "https://minibroker.blob.core.windows.net/charts"
Error: looks like "https://minibroker.blob.core.windows.net/charts" is not a valid chart repository or cannot be reached: failed to fetch https://minibroker.blob.core.windows.net/charts/index.yaml : 403 This request is not authorized to perform this operation.

**Comment by duanhongyi** [comment]
@mohamedhani

**Pull request merged**
