### PR TITLE
Update channels.yaml

### PR DESCRIPTION
**Pull request by pnbrown**
Add channel for Tanzu Community Edition

This PR adds a channel for the open source Kubernetes Distribution Tanzu Community Edition:

https://github.com/vmware-tanzu/community-edition
https://tanzucommunityedition.io

### CODE REVIEW

**Comment by pnbrown** [comment]
CLA signed

**Comment by nikhita** [comment]
This needs approval from slack admins

/assign @mrbobbytables

**Comment by jdumars** [comment]
/hold
/approve 

I did the hold because I would like another admin to +1 since I work at VMware

**Review by idvoretskyi — APPROVED** [review]
/approve
/hold cancel

**Pull request merged**
