### PR TITLE
updating with sig-windows two technical leads

### PR DESCRIPTION
**Pull request by michmike**
adding the two new sig-windows tech leads as reviewers and approvers

### CODE REVIEW

**Comment by michmike** [comment]
i guess my CLA expired and i had to resign it

**Comment by michmike** [comment]
trying a comment to see if my CLA is picked up

**Comment by nikhita** [comment]
@michmike looks like the email of the commit needs to be updated so that the CLA bot recognizes your GitHub ID.

Ref: https://github.com/kubernetes/community/commit/9b69a1adcaf952af17cd30b6a956bbaeed440533.patch

**Comment by michmike** [comment]
i have to close this PR. i did not want to rewrite the entire history of commits and i could not find an easy way to fix the root committer.
updated with https://github.com/kubernetes/community/pull/4080
/close

**Pull request closed without merging**
