### PR TITLE
Add vendor selection process writeup for security audit

### PR DESCRIPTION
**Pull request by cji**
In the interest of transparency, the Security Audit Working Group would like to document the decision process we used for evaluating the vendor proposals for the security audit. 

cc the rest of the WG: @aasmall @joelsmith

### CODE REVIEW

**Comment by joelsmith** [comment]
/assign @aasmall 
If you're happy with it and you give a /approve I think it should merge since the changes are all under our wg.

**Comment by cji** [comment]
cc @jaybeale

**Pull request merged**
