### PR TITLE
Ms4720 issue 1317

### PR DESCRIPTION
**Pull request by ms4720**

### CODE REVIEW

**Comment by bgrant0607** [comment]
The PR title and description were very reviewer-hostile, and will be incomprehensible in commit history. Please use descriptive titles and PR descriptions.

**Comment by ms4720** [comment]
Fair point sorry

On Nov 3, 2017 7:22 AM, "Brian Grant" <notifications@github.com> wrote:

The PR title and description were very reviewer-hostile, and will be
incomprehensible in commit history. Please use descriptive titles and PR
descriptions.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/community/pull/1319#issuecomment-341586800>,
or mute the thread

**Comment by jdumars** [comment]
@bgrant0607 @ms4720 had created a detailed issue here: https://github.com/kubernetes/community/issues/1317 so the takeaway is to have that documentation in the PR as well, as Brian suggested.  Thanks for fixing this, Marc.

**Comment by bgrant0607** [comment]
This didn't even link to the issue

**Comment by ms4720** [comment]
@bgrant0607 you are right and now here is a better way of doing it:

Marc,

Thanks for the submission, there were a couple of things that could be improved though.  Here are two things that would make it easier for other people help you get your future pulls committed:

- linking the ticket to the pull request, here is github's help page for that: link here
- the subject line of the ticket was not that clear, this page may help you name things better: link here

We can always use more help, even more so if you are cleaning up documentation.  

Brian

Marc

**Pull request merged**
