### PR TITLE
Big Data SIG changed meeting frequency to biweekly

### PR DESCRIPTION
**Pull request by lfrancke**
This is my first contribution (CLA is signed). Please be gentle.

### CODE REVIEW

**Comment by lfrancke** [comment]
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.

I think I was missing a step in the CLA process.

**Comment by jdumars** [comment]
/lgtm
Welcome to the community @lfrancke!

**Comment by jdumars** [comment]
/approve
proxy for @liyinan926 approve

**Pull request merged**
