### PR TITLE
Rename k/community/sig-security links to k/sig-security

### PR DESCRIPTION
**Pull request by Evalle**
**Which issue(s) this PR fixes**:
Fixes https://github.com/kubernetes/sig-security/issues/10

### CODE REVIEW

**Review by mrbobbytables — COMMENTED** [review]
@Evalle did you make the changes in sigs.yaml and then run make?
It's failing the generated docs check

**Comment by Evalle** [comment]
@mrbobbytables I did not, thx for the tip, let me do it.

**Comment by PushkarJ** [comment]
/lgtm

Thank you for working on this @Evalle

**Comment by PushkarJ** [comment]
/lgtm

(Thank you for working on this @Evalle )

**Pull request merged**
