### PR TITLE
Add existing spotlights in a list

### LINKED ISSUE #6981: List of existing Spotlights does not exist
### Describe the issue

Right now there are no easy ways to see what sig spotlights exists. 

This makes finding sig spotlights to work on or figuring out which spotlights needs updating difficult.

Plan is to create a `communication/marketing-team/storytelling-resources/sig-spotlights.md` file that would list out all the existing spotlights with links and dates. And all the subsequent spotlight blogs will be added here.

### PR DESCRIPTION
**Pull request by moficodes**
**Which issue(s) this PR fixes**: 

Fixes #6981

### CODE REVIEW

**Comment by chris-short** [comment]
Thank you for this, @moficodes! One requested change: For the date, could you use an internationally recognized date (ex. 2022-11-22).

Also, if you could update https://github.com/kubernetes/community/blob/master/communication/contributor-comms/storytelling-resources/sig-spotlight-blog-process.md with a link to this, it'd be very helpful. You can replace the existing list with a link, or put this table in there instead of a new file. Whatever you feel is best is probably the right way to go.

**Comment by moficodes** [comment]
@chris-short Updated.

**Comment by chris-short** [comment]
Thank you!

/lgtm

/approve

**Comment by imnmo** [comment]
Thanks, @moficodes for this list! This will be useful for both experienced and new contributors.

**Comment by moficodes** [comment]
@chris-short I think its need another label for the bot to test / add approval label?

**Comment by kaslin** [comment]
Oops! Sorry I lost this over the holidays.
/lgtm
/approve

**Pull request merged**
