### PR TITLE
add mayanks bio for 2020 steering election

### PR DESCRIPTION
**Pull request by krmayankk**
**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Comment by tpepper** [comment]
Should this PR also append the individual in events/elections/2020/README.md ?

**Comment by jdumars** [comment]
Tim is correct, please update to include events/elections/2020/README.md addition.

**Comment by krmayankk** [comment]
@jdumars @tpepper  done

**Comment by jdumars** [comment]
/approve
/hold

unhold once election officers have reviewed

**Review by idvoretskyi — APPROVED** [review]
/lgtm

**Review by tpepper — COMMENTED** [review]
/lgtm

**Comment by tpepper** [comment]
On closer review I'm realizing this bio is dramatically over the 300 word limit, even if markdown/template/urls are excluded from the count.

@krmayankk can you reduce the content?

**Comment by jdumars** [comment]
The election officers really appreciate your help with all of this @tpepper

**Comment by krmayankk** [comment]
> On closer review I'm realizing this bio is dramatically over the 300 word limit, even if markdown/template/urls are excluded from the count.
> 
> @krmayankk can you reduce the content?

 cat mayankkumar.md  |wc 
      37     295    2185

**Comment by tpepper** [comment]
/lgtm
/unhold
Thanks for fixing up!

**Pull request merged**
