### PR TITLE
Update support resources in github issue template

### LINKED ISSUE #5261: Consider linking to support resources from our github templates
Ek9pr8jU0AEJ6YR

You can add links to external support resources in github templates, we should consider doing this so users end up in the right place.

### PR DESCRIPTION
**Pull request by championshuttler**
Ref #5261

cc @mrbobbytables

### CODE REVIEW

**Review by mrbobbytables — CHANGES_REQUESTED** [review]
The current support issue request template will also need to be removed^^;;;
https://github.com/kubernetes/community/blob/master/.github/ISSUE_TEMPLATE/support.md

**Comment by mrbobbytables** [comment]
/lgtm
/assign @nikhita @cblecker 
For a 2nd set of eyes :)

**Review by nikhita — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
