### PR TITLE
Simplify Container Status for Ephemeral Containers proposal

### PR DESCRIPTION
**Pull request by verb**
This leaves reporting command & args of Ephemeral Containers for a future proposal.

### CODE REVIEW

**Comment by castrojo** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/community/1136)

**Comment by lavalamp** [comment]
/lgtm
/approve

Debate is still going on in the other PR but this is a minor fix to the existing doc that I think is an improvement.

**Pull request merged**
