### PR TITLE
Add a channel for Persian docs

### LINKED ISSUE #4979: REQUEST: New Slack channel kubernetes-docs-fa
Create a Slack channel for فارسی (Persian) docs localization. 

For reference, the SIG Docs issue is https://github.com/kubernetes/website/pull/22565.

/sig docs
/language fa

### PR DESCRIPTION
**Pull request by zacharysarah**
Fixes #4979 

/assign @sftim @jimangel @kbarnard10 

Holding for 👍 from @sattarfeizollahibarough
/hold

/sig docs
/language fa

### CODE REVIEW

**Comment by zacharysarah** [comment]
@spiffxp 👋 Do we need to do anything to propagate https://github.com/kubernetes/test-infra/pull/18369/ to other repos?

Screen Shot 2020-07-20 at 6 00 09 PM

**Comment by sattarfeizollahibarough** [comment]
> 
> 
> Fixes #4979
> 
> /assign @sftim @jimangel @kbarnard10
> 
> Holding for +1 from @sattarfeizollahibarough
> /hold
> 
> /sig docs
> /language fa

+1   Thanks @zacharysarah

**Pull request merged**
