### PR TITLE
[wip] draft sig-testing annual-report 2021

### PR DESCRIPTION
**Pull request by spiffxp**
ref: https://github.com/kubernetes/community/issues/5515

/assign @BenTheElder @stevekuznetsov @spiffxp

### CODE REVIEW

**Comment by spiffxp** [comment]
Per today's SIG Testing meeting, I've moved this to https://hackmd.io/Jp4K7p6nQPG6ihMe226mLw for iteration.  Signed-in users can comment, leads can edit.

Will refresh this PR once we've fleshed things out more.

**Comment by parispittman** [comment]
we are on to a new cycle and will work with sig testing leads to get 2022 in 
/close

**Pull request closed without merging**
