### PR TITLE
Fix the broken links in design-proposals of Vertical Pod Autoscaler.

### LINKED ISSUE #5954: Broken Links in design-proposals of Vertical Pod Autoscaler
**This is a Bug Report**

**Problem:**
The following links under the design proposal of [vertical-pod-autoscaler](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/autoscaling/vertical-pod-autoscaler.md#combining-vertical-and-horizontal-scaling) are not working:
**1)** https://github.com/kubernetes/community/blob/master/contributors/design-proposals/autoscaling/vertical-pod-autoscaler.md#complete_vpa_api_object_definition  for **below** under [VPA API object overview](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/autoscaling/vertical-pod-autoscaler.md#vpa-api-object-overview)

**2)** https://kubernetes.io/docs/api-reference/v1/definitions/#_v1_localobjectreference for **reference** under  [Pods point at VPA](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/autoscaling/vertical-pod-autoscaler.md#pods-point-at-vpa)

**Proposed Solution:**
The **1st** link should be linked to https://github.com/kubernetes/community/blob/master/contributors/design-proposals/autoscaling/vertical-pod-autoscaler.md#complete-vpa-api-object-definition

The **2nd** link should be linked to  https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/local-object-reference/

**Page to Update:**
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/autoscaling/vertical-pod-autoscaler.md

### PR DESCRIPTION
**Pull request by Shubham82**
Correct the links in [vertical-pod-autoscaler.md](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/autoscaling/vertical-pod-autoscaler.md)

**Which issue(s) this PR fixes**:

Fixes #5954

### CODE REVIEW

**Comment by Shubham82** [comment]
Hi @gjtempleton, @mwielgus
Could please take a look.

**Comment by coderanger** [comment]
Hi there, while we appreciate the frustration of broken links, we've decided to globally lock the design proposals. They are still present for archival purposes only. As such, we're not updating stuff like this anymore.

**Comment by Shubham82** [comment]
Hi @coderanger, Thanks for the information. I don't know that
I am new to sig-autoscaling so I am understanding things.

**Comment by Shubham82** [comment]
@coderanger, Should I close this PR? if nothing will change in it.

**Comment by Shubham82** [comment]
Just a suggestion: It would be better if we add this information as a note somewhere in the docs so the newbie to the community has an idea about it.
What do you suggest?

**Comment by coderanger** [comment]
This is mentioned in https://github.com/kubernetes/community/blob/master/contributors/design-proposals/README.md already. And yes going to close this out now. Thanks for taking a look though!

/close

**Pull request closed without merging**
