### PR TITLE
Adding markyjackson to moderators list for zoom & youtube

### LINKED ISSUE #4370: REQUEST: New moderator for New moderator for markyjackson-taulia of Zoom and YouTube
### GitHub Username
@markyjackson-taulia 

### Property you'd like to Moderate
Zoom, YouTube

### Username on Property Requested
@markyjackson-taulia 

### Requirements

- [x] I am a Kubernetes Org member already
- [x] I have enabled 2FA on my account for the property I would like to moderate (if applicable).
- [x] I have read and will abide by the policies mentioned in the [Moderation Guidelines](https://git.k8s.io/community/communication/moderation.md)
- [x] I have two sponsors that meet the sponsor requirements listed in the moderator guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @castrojo 
- @parispittman 

### List of qualifications for this position

- Prior moderation experience
- A host of community meeting several times
- Summit staff lead

### PR DESCRIPTION
**Pull request by markyjackson-taulia**
Signed-off-by: markyjackson-taulia <marky.r.jackson@gmail.com>

**Which issue(s) this PR fixes**:

Fixes #4370

### CODE REVIEW

**Comment by mrbobbytables** [comment]
@markyjackson-taulia The commit message can't have a github handle in it prefixed with the `@` symbol. 😬

**Comment by markyjackson-taulia** [comment]
@mrbobbytables I removed that but the label didn't go away 😢

**Comment by mrbobbytables** [comment]
The commit message that shows up still has it in it :x
> Adding @markyjackson-taulia to mod list for zoom & youtube

**Comment by mrbobbytables** [comment]
Thanks @markyjackson-taulia :)
/lgtm
/approve

**Pull request merged**
