### PR TITLE
Archive past years of SIG-node agenda

### PR DESCRIPTION
**Pull request by tallclair**
Archiving meeting agenda for historical availability, and to clean up the agenda doc for performance. I'll delete the old entries from https://docs.google.com/document/d/1Ne57gvidMEWXR70OxxnRkYquAoMpt56o75oZtg-OeBg/edit once this merges.

Generated using the [Docs to Markdown extension](https://workspace.google.com/marketplace/app/docs_to_markdown/700168918607)

/assign @SergeyKanzhelev @mrunalp

### CODE REVIEW

**Comment by cblecker** [comment]
Looks like there are 3 spelling mistakes:
```
sig-node/archive/meeting-notes-2022.md:485:523: "regsitry" is a misspelling of "registry"
sig-node/archive/meeting-notes-2021.md:2461:220: "prefered" is a misspelling of "preferred"
sig-node/archive/meeting-notes-2021.md:3234:131: "prefered" is a misspelling of "preferred"
```

You can either fix those in the markdown, or add these files to `/hack/.spelling_failures`

**Comment by bart0sh** [comment]
@tallclair 
> I'll delete the old entries from https://docs.google.com/document/d/1Ne57gvidMEWXR70OxxnRkYquAoMpt56o75oZtg-OeBg/edit once this merges.

Please, don't delete 2023 or at least leave half of it as people may still be interesting to have it in agenda.

/lgtm

**Comment by tallclair** [comment]
> Please, don't delete 2023 or at least leave half of it as people may still be interesting to have it in agenda.

Yes, I'll leave the second half of the year in place.

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
