### PR TITLE
Add slack #jp-users-novice channel

### PR DESCRIPTION
**Pull request by bells17**
I want to append a channel for study and q&a by novice users of Kubernetes in Japan(for Japanese speakers).
ref: https://kubernetes.slack.com/archives/C0QKVN230/p1577342193032500

### CODE REVIEW

**Comment by bells17** [comment]
duplicated: https://github.com/kubernetes/community/pull/4351

**Comment by bells17** [comment]
Hi @jeefy! https://github.com/kubernetes/community/pull/4351 is moved to this PR.
(Because @ryojsb dont't sign the CLA yet...)
https://github.com/kubernetes/community/pull/4351#issuecomment-569283154

> Does it serve a separate purpose from #jp-users?

Yes, #jp-users have many Kubernetes in Japan.
But Many users working on this channel are already familiar with Kubernetes.
So I think that it is a bit difficult for Kubernetes novice users to hear very simple questions.
We think #jp-users-novice channel is for study and q&a by novice users of Kubernetes in Japan.

**Comment by idealhack** [comment]
This looks reasonable to me, thanks for being considering. I’m a bit concerned if this will cause any fragmentation though. We can try this approach and see how it goes.

/approve

**Comment by bells17** [comment]
Thank you @idealhack !

> I’m a bit concerned if this will cause any fragmentation though.

Year, I'm also concerned about this point.
But I would like to try this approach to increase the number of Kubernetes users in Japan.

**Comment by vishakhanihore** [comment]
Looks good to me.
/lgtm

**Pull request merged**
