### PR TITLE
sig-pm: Update SIG PM Chairs

### PR DESCRIPTION
**Pull request by justaugustus**
- Promote Ihor Dvoretskyi to Emeritus Chair
- Add Lachie Evenson

Mailing list announcement to follow shortly.

Signed-off-by: Stephen Augustus <saugustus@vmware.com>

/assign @idvoretskyi @calebamiles @jdumars 
/cc @lachie83 

Lazy consensus period - until Friday, June 7 EOD PST:
/hold

### CODE REVIEW

**Comment by justaugustus** [comment]
Mailing list post: https://groups.google.com/d/msg/kubernetes-sig-pm/NGnJcNjkWuI/hezVpyMcBAAJ

**Comment by lachie83** [comment]
Thanks @justaugustus. I accept this nomination.

**Comment by calebamiles** [comment]
/hold-cancel
/lgtm
👍

**Comment by calebamiles** [comment]
👍

**Comment by justaugustus** [comment]
Lazy consensus has been achieved for this leadership change:
/hold cancel

**Pull request merged**
