### PR TITLE
Makes SIGs responsible for implementations of `CloudProvider`

### PR DESCRIPTION
**Pull request by calebamiles**
Make the existing SIGs
- SIG AWS
- SIG Azure
- SIG GCP
- SIG OpenStack

the "owners" for the repositories which will be created to host provider
specific code. Other SIGs will be charted as needed/desired for other
providers at a later time.

### CODE REVIEW

**Comment by jbeda** [comment]
Awesome! Thanks for doing this @calebamiles. It looks good to me but I don't want to say so as it might merge before others have a chance to see/weigh in.

**Comment by derekwaynecarr** [comment]
@jbeda @calebamiles - for a future pr, we should figure out who owns the implementations of the other "cloud provider" interfaces in kubernetes/autoscaler 

see: https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider)

**Comment by jdumars** [comment]
/lgtm
Speaking for Azure

**Comment by hogepodge** [comment]
/lgtm

We're working on externalizing our provider as an OpenStack hosted project, so this will likely have little impact on us. It's worth our sig discussing our plans for provider source hosting.

**Comment by hogepodge** [comment]
For clarification, is one of the outcomes of this patch to create the repositories listed in the owners files? When an org takes ownership, what exactly does that entail?

**Comment by calebamiles** [comment]
@hogepodge one of the intended outcomes of this PR was to create the repositories listed, at the very least to provide the justification for doing so. If I'm recalling correctly we're currently working to map all the areas of the project to SIGs. What SIG "ownership" means beyond the initial mapping will probably be listed in a) an individual SIGs charter and/or b) in the [top level governance docs][]. If your question relates to moving code _out_ of a CNCF GitHub organization is a topic that far exceeds my understanding of the project mechanics, however, the `OWNERS` mechanism should provide sufficient "control" over who can approve changes to a subproject or component. 


[top level governance docs]: https://github.com/kubernetes/community/blob/master/governance.md#subprojects

**Comment by calebamiles** [comment]
@wlan0 or @justinsb could one of you `lgtm` again?

**Pull request merged**
