### PR TITLE
add azure cloud provider to sig-cloud-provider doc

### PR DESCRIPTION
**Pull request by tariq1890**
Signed-off-by: tariqibrahim <tariq181290@gmail.com>

Adding the link to the Azure Cloud Provider OWNERS file

### CODE REVIEW

**Comment by andrewsykim** [comment]
/lgtm

Thanks @tariq1890!!

**Comment by tariq1890** [comment]
Can this be approved?

**Comment by feiskyer** [comment]
Need approval from OWNERS

@jdumars Could you help to approve the change?

**Comment by justaugustus** [comment]
We [discussed](https://groups.google.com/d/topic/kubernetes-sig-azure/49KS7hKn16I/discussion) that cloud-provider-azure will continue to be owned by SIG Azure until we decide to fold under SIG Cloud Provider. Here's the PR that removed it: https://github.com/kubernetes/community/pull/2526

Closing this out.
/close

**Pull request closed without merging**
