### PR TITLE
Adding sig-security-docs slack channel

### PR DESCRIPTION
**Pull request by savitharaghunathan**
New slack channel for discussions for the security docs sub-project in sig-security 🎉 

cc: @IanColdwater @tabbysable

### CODE REVIEW

**Comment by coderanger** [comment]
Looks good on the Slack config side. Will give it a day or two in case any SIG-Security folks want to weigh in.

/approve
/hold

**Comment by mrbobbytables** [comment]
/assign @IanColdwater @tabbysable 
For sign off 👍

**Comment by tabbysable** [comment]
/lgtm

This is great, thanks so much Savitha!

**Pull request merged**
