### PR TITLE
Fix SIG scalability's slack channel link.

### PR DESCRIPTION
**Pull request by porridge**
Channel #sig-scalability does not exist. There is #sig-scale though.

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
Good catch!
But I prefer to rename the slack channel to keep consistency. @sarahnovotny can slack channel be renamed?
/cc @wojtek-t

**Comment by castrojo** [comment]
I can rename a channel, would prefer a confirmation from the SIG leads though.

**Comment by porridge** [comment]
@wojtek-t @countspongebob @jbeda WDYT?

**Comment by countspongebob** [comment]
I'm fine with renaming the channel for consistency. I'll add it to the list for our Thursday meeting just to give people a heads up.

**Comment by porridge** [comment]
Closing this one in favour of #1223 then.

**Pull request closed without merging**
