### PR TITLE
Adding second round of questions to security RFP

### PR DESCRIPTION
**Pull request by cji**
Adding the second round of questions from the security audit RFP process

cc @aasmall @joelsmith

### CODE REVIEW

**Comment by jdumars** [comment]
Is there any external reference for this change?

**Comment by cji** [comment]
@jdumars  sure! similar to #2903, the security audit working group has been collecting questions during the RFP process from vendors via a Google form and then adding our responses here. 

The spreadsheet that contains the questions and responses is available [here](https://docs.google.com/spreadsheets/d/1XHDLIlnfBPkq9YsH0Get398oQuKot1GUNVnF8vAocE4/edit#gid=163152809) (@aasmall 	may need to provide you with access)

**Comment by aasmall** [comment]
/lgtm
/approve

But we'll probably need a member to actually approve :)

**Comment by aasmall** [comment]
@jdumars Can you approve as well?

**Pull request merged**
