### PR TITLE
Add kubectl plugin mechanism KEP

### PR DESCRIPTION
**Pull request by juanvallejo**
cc @soltysh @seans3 

Adds proposal describing an updated, git-style plugin mechanism.

### CODE REVIEW

**Comment by mikedanese** [comment]
Can we add kubectl to the title? Kubernetes has a lot of different types of plugins.

**Comment by juanvallejo** [comment]
@philips 
> Can you add some color on why plugins are useful? I get the technical details but I don't know what the goal is. Thanks!

Sure, will update KEP to expand more on this

**Comment by juanvallejo** [comment]
Updated _Motivation_ section to expand on the reasoning for having plugins.

**Comment by philips** [comment]
@juanvallejo thanks, looks good.

**Comment by soltysh** [comment]
This topic was discussed for almost past 6 months during various SIG-CLI meetings. The KEP itself was posted few weeks ago and was broadcast to kubernetes-dev and sig-cli ML. During today's SIG-CLI there were no objections so I'm approving this PR as is.

**Comment by philips** [comment]
makes sense. Thanks for the work.

**Comment by soltysh** [comment]
@cblecker mind approving the KEP number bump for this one?

**Comment by carolynvs** [comment]
I haven't been following the dev list closely enough lately, but I just resurfaced and saw this 🎁. Exciting to see us moving forward with plugins!

**Pull request merged**
