### PR TITLE
Reformat Technical Lead expectations

### PR DESCRIPTION
**Pull request by saschagrunert**
We now split up the huge sentence into a list of bullet points under the
headline of the expectations of technical leads.

**Which issue(s) this PR fixes**:

Follow up of https://github.com/kubernetes/community/pull/5179#discussion_r507764919

### CODE REVIEW

**Review by idvoretskyi — APPROVED** [review]
/lgtm

/hold for @nikhita's review.

**Review by nikhita — APPROVED** [review]
/lgtm
/approve
/meow

**Pull request merged**
