### PR TITLE
Update wg-security-audit leads; include RFP link in readme.md

### PR DESCRIPTION
**Pull request by aasmall**
I don't think [PR 2872](https://github.com/kubernetes/community/pull/2872) used the generator to update wg leads. Including that in this PR.

We are ready to publish the RFP for the third party security audit. Added link to RFP in wg-security-audit README.md.

CC: @cblecker @joelsmith @cji

### CODE REVIEW

**Comment by cblecker** [comment]
@aasmall it did use the generator, or it wouldn't have passed CI. If you rebase, you should be able to pick up the changes.

**Comment by aasmall** [comment]
@cblecker Not sure how I got so confused. I've rebased this PR. Now it is just the readme update.

**Comment by cblecker** [comment]
/approve
LGTM to one of the other wg-security-audit organizers

**Comment by cblecker** [comment]
/lgtm

Oops. Yeah, if you're not a part of the org, you can't LGTM. I'll do that too :)

**Pull request merged**
