### PR TITLE
Add slack channel for csi-snapshot working group

### PR DESCRIPTION
**Pull request by jingxu97**
The purpose of this channel is to set up a shared communication place for the working group on supporting CSI snapshot.

The proposal for enhancement to support CSI snapshots is here https://github.com/kubernetes/enhancements/blob/master/keps/sig-storage/20190709-csi-snapshot.md

### CODE REVIEW

**Comment by saad-ali** [comment]
There is an on going discussion about the creation of a new "Data Protection" workgroup. I have questions between the overlap between snapshot workgroup and that. I think it may make sense to combine both, in which case we may want to rename the snapshot workgroup to data protection and make it co-owned by sig storage and sig apps. So, let's hold off on this PR until we have a conclusion on that discussion.

**Comment by mrbobbytables** [comment]
@saad-ali @xing-yang do you think this is still needed with the formation of the data protection wg?

**Comment by xing-yang** [comment]
I think discussions on CSI snapshot can happen on the data protection wg slack channel.

**Pull request closed without merging**
