### PR TITLE
Remove references to outside collaborators

### LINKED ISSUE #1565: Remove "outside collaborator" role in favor of lowering requirements for "member" role
ref: https://github.com/kubernetes/community/pull/1330#issuecomment-355467738

The additional role makes the contributor ladder more complicated.  It's also just as much if not more effort to administer the role, and more difficult to audit across repos and orgs.

The only real benefit the additional role adds is constraining people's ability to use certain commands to specific repos instead of all repos in the org they're a member of (eg: /lgtm, /close, /assign).  

When discussed during a sig-contribex meeting, there was agreement on simplifying and cutting the role.  Unfortunately, this agreement didn't land in meeting notes, and I haven't seen the video recording hit youtube yet.

I think we could benefit from a survey of where and how extensively the role is used today across kubernetes/* and kubernetes-incubator/* repos.  This is something only people with... write? admin? access to said repos can do.  But IMO anyone is free to tackle modifying community-membership.md and I'm happy to review PR's to that effect.

FYI @kubernetes/sig-contributor-experience-proposals

### PR DESCRIPTION
**Pull request by cblecker**
fixes #1565

### CODE REVIEW

**Comment by cblecker** [comment]
@idvoretskyi Any issues cancelling the hold? :)

**Comment by idvoretskyi** [comment]
@cblecker just waiting for other voices. Since there are no extra voices,

/hold cancel

**Pull request merged**
