### PR TITLE
stepping down as sig-service-catalog chair

### PR DESCRIPTION
**Pull request by jberkhahn**
Hello,

I don't really have the time anymore to devote to this project, so I'm moving on. It's been fun. 

I'm not really sure what the process is for this, but I've sent out an email to the SIG mailing list, and will be opening PRs here and in kubernetes/org

### CODE REVIEW

**Comment by mrbobbytables** [comment]
Thanks @jberkhahn <3 for everything.
/lgtm
/approve

**Comment by mrbobbytables** [comment]
/hold
Just noticed the job failure - did you make the changes to sigs.yaml and run make?

**Comment by jberkhahn** [comment]
should be fixed now?

**Review by mrbobbytables — COMMENTED** [review]
/lgtm
/hold cancel

**Comment by jberkhahn** [comment]
Did how the CLA works get rejiggered? My profile lists my IBM org membership as public, which is how I thought that was handled? If I click through with the EasyCLA thing, I don't see a generic IBM or IBM America listed in the corporate contributor drop down.

**Comment by jberkhahn** [comment]
Wait, what? The PR got merged with the CLA check failing?

**Pull request merged**
