### PR TITLE
Remove an unexpected colon

### PR DESCRIPTION
**Pull request by whs-dot-hk**
For Hugo

### CODE REVIEW

**Comment by cblecker** [comment]
@whs-dot-hk Why is this change necessary? Need a bit more background than "For Hugo"

**Comment by castrojo** [comment]
This is to allow hugo to build the community repo markdown pages, [KEP-005](https://github.com/kubernetes/community/blob/master/keps/sig-contributor-experience/0005-contributor-site.md).

**Comment by cblecker** [comment]
But what is the issue with it? Are colons aren't allowed as a part of the mission statement? This is valid YAML, and Go Templates consume it properly.

**Comment by whs-dot-hk** [comment]
Colons are allowed the html generated fine, but when looking at the result, you will spot the colon immediately, it looks unnatural to me in html

**Comment by cblecker** [comment]
@whs-dot-hk Okay, so this is purely cosmetic?

If so, then I'm okay with this change. You'll need to rebase, make the change, and then regenerate the docs (directions here: https://git.k8s.io/community/generator/README.md)

**Pull request merged**
