### PR TITLE
Add some audio/visual recommendations

### PR DESCRIPTION
**Pull request by castrojo**
I had these as a blog post, which I've adapted for general use and might be useful to folks.

/sig contributor-experience

### CODE REVIEW

**Comment by spiffxp** [comment]
```
W0809 14:54:36.549] communication/zoom-guidelines.md:69:313: "occurence" is a misspelling of "occurrence"
W0809 14:54:36.549] communication/zoom-guidelines.md:72:185: "concensus" is a misspelling of "consensus"
```

**Comment by castrojo** [comment]
I filed this for a followup: https://github.com/kubernetes/community/issues/2599

**Comment by idvoretskyi** [comment]
@castrojo great!

**Pull request merged**
