### PR TITLE
Create a slack channel where we can discuss K8s Binding patterns.

### PR DESCRIPTION
**Pull request by mattmoor**
cc @sspeiche @vaikas @n3wscott @pmorie @bbrowning 
(That's all the github handles I know.  I'll also reply to the mail thread)

Some more context: https://twitter.com/mattomata/status/1247691450961121280

### CODE REVIEW

**Comment by resouer** [comment]
Thanks for brought this up, strongly +1.

**Comment by sbose78** [comment]
Thanks, looking forward to collaborating more on this! 
Let's name the channel "servicebinding"

( Note, I represent https://github.com/redhat-developer/service-binding-operator )

**Comment by arthurdm** [comment]
+1!  looking forward to this.

**Comment by n3wscott** [comment]
Servicebinding is one example, let's keep it generic, for k8s binding name.

**Comment by hasheddan** [comment]
+1 from me!

**Pull request merged**
