### PR TITLE
added kcp-edge-dev community

### PR DESCRIPTION
**Pull request by clubanderson**
adding kcp-edge-dev to the channels list to support the community at https://github.com/kcp-dev/edge-mc

**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Comment by mrbobbytables** [comment]
/hold
Please don't prefix it with SIG, SIG/WG/UG are reserved for the kubernetes project.
We also generally only do user/dev channels for other projects.

**Comment by mrbobbytables** [comment]
Yup - looking at the channel list there is already a kcp-dev channel. I don't think we'd okay one for a sig/wg.
If you want to do that sort of thing, please consider your own slack/discord

**Comment by clubanderson** [comment]
I have updated the name of the channel to conform with guidance in this issue.  It is now kcp-edge-dev

**Comment by mrbobbytables** [comment]
kcp-edge is just kcp though? its a wg and not really a thing we do in the k8s slack for other projects.

I don't think we'd move forward with this, but will wait for other slack admins to weigh in.

**Comment by jberkus** [comment]
Howdy, the slack admins discussed this.  Usually we only offer external projects two slack channels, *-user and *-dev.  We can approve this channel, but it would then be one of kcp's two slack channels, and if kcp wanted another later on it wouldn't be available.  Can you chat with the kcp leads and make sure that's the way you want to go?

**Comment by clubanderson** [comment]
Thank you. I will check in with KCP at the beginning of the week and get back to you here. Thank you very much for your consideration.

**Comment by clubanderson** [comment]
Per kcp, we are going to try to share the kcp-dev channel.  closing this issue for now.

**Pull request closed without merging**
