### PR TITLE
Removing the referer link files and Depreciated Directories

### LINKED ISSUE #4324: Remove the unwanted refereres file present.
Currently, there are many references files present to redirect to another page, might be due to changes in repo directory.
 
Remove such files as they were supposed to be deleted earlier.

/sig contributor-experience

### PR DESCRIPTION
**Pull request by vishakhanihore**
Fixes #4324

### CODE REVIEW

**Comment by vishakhanihore** [comment]
assign @markyjackson-taulia

**Comment by vishakhanihore** [comment]
cc: @nikhita

**Comment by mrbobbytables** [comment]
/hold 
For a bit more review
e.g. The style-guide shouldn't be removed.

**Comment by vishakhanihore** [comment]
> /hold
> For a bit more review
> e.g. The style-guide shouldn't be removed.

@mrbobbytables The style guide is already moved to `ReadME` of the following section. I compared both and both were the same.

**Comment by mrbobbytables** [comment]
> @mrbobbytables The style guide is already moved to `ReadME` of the following section. I compared both and both were the same.

That's the only location that I can find with it 😬 
```
[bob@muninn community] (master $)$ grep -R --exclude-dir=".git" 'slug: "style-guide"'
contributors/guide/style-guide.md:slug: "style-guide"
[bob@muninn community] (master $)$
```
The location for it should be`contributors/guide/style-guide.md`.

**Comment by vishakhanihore** [comment]
@mrbobbytables You were right, I removed other `style-guide` file. I restored and fixed up my mistake.

**Comment by vishakhanihore** [comment]
@mrbobbytables Please have a look.
Thanks

**Comment by mrbobbytables** [comment]
It looks good to me :) but would you mind squashing the commits down?

/hold cancel
/ok-to-test

**Comment by vishakhanihore** [comment]
Sur

**Comment by vishakhanihore** [comment]
@mrbobbytables Done the squashing!

**Comment by castrojo** [comment]
/approve

Thanks!

**Comment by mrbobbytables** [comment]
/lgtm
Thanks!

**Pull request merged**
