### PR TITLE
add capi provider gcp office hours

### PR DESCRIPTION
**Pull request by salasberryfin**
This PR updates `sig-cluster-lifecycle` information adding [CAPI Provider GCP](https://github.com/kubernetes-sigs/cluster-api-provider-gcp) office hours to the list.

### CODE REVIEW

**Comment by furkatgofurov7** [comment]
cc @cblecker

**Comment by salasberryfin** [comment]
This is now rebased. @justaugustus, could you please take a look at this?

**Comment by justaugustus** [comment]
Sorry for missing this!
One more rebase please and I'll approve.

**Comment by salasberryfin** [comment]
It is now rebased, @justaugustus

**Review by justaugustus — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
