### PR TITLE
Add a French translation of contributor-cheatsheet

### PR DESCRIPTION
**Pull request by remyleone**

### CODE REVIEW

**Comment by guineveresaenger** [comment]
/approve

Merci beaucoup pour votre contribution!

/assign @ameukam

Mon français, c‘est ne pas tres bien - Arnaud, votre assistance, s‘il vous plant?

**Comment by cblecker** [comment]
/remove-lifecycle stale
ping @kubernetes/sig-docs-fr-reviews

**Comment by remyleone** [comment]
I got a some spelling detector that are all warned up because of some French words 🇫🇷

**Comment by mrbobbytables** [comment]
> I got a some spelling detector that are all warned up because of some French words 🇫🇷

Can you add it to the spelling ignore list here? - https://github.com/kubernetes/community/blob/master/hack/.spelling_failures

After that it shouldn't be flagged again 👍

**Comment by remyleone** [comment]
@AWKIF I didn't alter the content, could you add a LGTM again please. Just added the ignore rule

**Comment by AWKIF** [comment]
@idvoretskyi is too fast for me <3

**Pull request merged**
