### PR TITLE
remove non-active SIG Service Catalog chairs

### PR DESCRIPTION
**Pull request by jboyd01**
I am stepping aside from Service Catalog work and am therefore removing myself from sig co-chair role.  I also removed Michael Kibbe who resigned chair position on January 14 as documented in [email to sig service catalog leads](https://groups.google.com/forum/#!topic/kubernetes-sig-service-catalog-leads/q1ZRCsI_jFw)
cc @jberkhahn, @kibbles-n-bytes

### CODE REVIEW

**Comment by cblecker** [comment]
/cc @kubernetes/steering-committee 

This leaves the sig with only a single active chair.

**Comment by derekwaynecarr** [comment]
Are there other members in the existing community willing to take on the
role?  We may want to reach out to members from the kyma project which I
thought uses the component to see if they would be interested?

https://kyma-project.io
https://github.com/kyma-project

**Comment by jberkhahn** [comment]
We're already in touch with the Kyma team. They're actively contributing to the team and we're trying to fasttrack them into moving up the maintainer track. I've also reached out to a couple other users of Service Catalog to see if they're interested in contributing.

/lgtm

**Pull request closed without merging**
