### PR TITLE
various documentation fixes

### PR DESCRIPTION
**Pull request by thecrudge**
Fixed the link in setting up dev... this has been an open issue for quite some time.

### CODE REVIEW

**Comment by thecrudge** [comment]
Fixes #1632

**Comment by thecrudge** [comment]
also addresses #2696

**Comment by cblecker** [comment]
you'll need to fix the author on your first commit.

**Comment by thecrudge** [comment]
I've rebased my commits, please confirm 

> you'll need to fix the author on your first commit.

**Pull request merged**
