### PR TITLE
Updating the Agenda documentation for SIG Docs

### PR DESCRIPTION
**Pull request by divya-mohan0209**
Updating the SIG Docs agenda documentation to make it community-owned.

/sig docs

### CODE REVIEW

**Review by sftim — COMMENTED** [review]
/lgtm
for SIG Docs

/hold
@divya-mohan0209 you can use this hold to synchronize changes if you wish. Feel free to unhold any time you want to!

**Comment by divya-mohan0209** [comment]
/unhold 
since changes have been synchronized to reflect in the archive doc

**Pull request merged**
