### PR TITLE
update notes about SIG multicluster meeting

### PR DESCRIPTION
**Pull request by makkes**
**Which issue(s) this PR fixes**:

no issue

### CODE REVIEW

**Comment by mrbobbytables** [comment]
@makkes just an FYI - you should update that in [sigs.yaml](https://github.com/kubernetes/community/blob/master/sigs.yaml) and then run `make`. That will auto-update the docs in all the required locations 👍 

https://github.com/kubernetes/community/blob/54c62fddc6d2785f99c9f53fe514522fb13f1992/sigs.yaml#L1454-L1470

/ok-to-test

**Comment by makkes** [comment]
> @makkes just an FYI - you should update that in [sigs.yaml](https://github.com/kubernetes/community/blob/master/sigs.yaml) and then run `make`. That will auto-update the docs in all the required locations 👍

Thanks, @mrbobbytables for the heads-up. I updated the PR, should be good to go now.

**Comment by makkes** [comment]
Hey @mrbobbytables, would you mind giving this a 2nd look, please?

**Comment by mrbobbytables** [comment]
Thanks @makkes, things look good :) once @pmorie signs off can merge it 👍

**Comment by mrbobbytables** [comment]
Going back on my comment yesterday :P The link is valid and meeting frequency verified. Going to go ahead and get this in.

/lgtm
/approve

**Pull request merged**
