### PR TITLE
code of conduct: expand the list of people whose privacy will be respected

### PR DESCRIPTION
**Pull request by eparis**
While we later said that any leak of personal information is inappropriate, this
sentence only specifically mentioned the right of privacy of the reporter. We believe
the reporter, anyone named in the report, anyone we talk to about the report, and
everyone involved should have their privacy respected. So this language is more
broad to make our intent more clear.

### CODE REVIEW

**Comment by eparis** [comment]
@parispittman @carolynvs @jdumars @Bradamant3

**Comment by eparis** [comment]
/hold
until all of committee reviews

**Comment by jdumars** [comment]
/lgtm

All incidents should be treated with the highest possible level of discretion.

**Pull request merged**
