### PR TITLE
Add mbbroberg to usergroup

### PR DESCRIPTION
**Pull request by mbbroberg**
- Adding myself to the Upstream Marketing group because I enjoy contributing there 🚀

### CODE REVIEW

**Comment by mbbroberg** [comment]
I signed it

☝️ posting per the recommendation in the [CLA docs](https://identity.linuxfoundation.org/projects/cncf)

**Comment by mrbobbytables** [comment]
/ok-to-test
/lgtm
/assign @parispittman 

will leave approve to @parispittman :)

**Comment by mrbobbytables** [comment]
I swear I checked this >_< -- you need to add the mapping for your user here:
https://github.com/kubernetes/community/blob/master/communication/slack-config/users.yaml
since slack ID's can change.

You will also need to alpha sort the handles. So your handle should be below jonas.

**Comment by mbbroberg** [comment]
Thanks @mrbobbytables, done and pushed and amended. I assume we want everything squashed in these cases?

**Comment by mrbobbytables** [comment]
Yup, all good now :) Thanks!
/lgtm

**Pull request merged**
