### PR TITLE
remove keps directory

### PR DESCRIPTION
**Pull request by tddorgtfo**
For #3220 
Ref: #3833
Addresses comment https://github.com/kubernetes/community/pull/3833#issuecomment-504771192

### CODE REVIEW

**Comment by tddorgtfo** [comment]
cc @nikhita  @eduartua

**Comment by nikhita** [comment]
Created https://github.com/kubernetes/test-infra/pull/13174 to update blocked paths.

**Comment by cblecker** [comment]
/lgtm
/approve

Manually overriding blocked-paths

**Pull request merged**
