### PR TITLE
Update CAPI, CAPA notes doc URLs

### PR DESCRIPTION
**Pull request by ncdc**
Update CAPI, CAPA notes doc URLs due to VMware G Suite data migration.

**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Comment by ncdc** [comment]
/hold
Need to fix 1 more thing

**Comment by nikhita** [comment]
@ncdc are these docs under the corporate account? we usually ask community docs to be hosted on a personal account because we've had cases where we've lost complete access to the docs when folks moved between companies...

**Comment by vincepri** [comment]
Actually let's hold on one second, I'm trying to see if we can re-allow access to these

/hold

**Comment by ncdc** [comment]
They are in the VMware corporate account in a team drive that allows outside access. I have confirmed that they are world-viewable. @CecileRobertMichon and @detiber confirmed they have edit access.

@vincepri can we cancel the hold?

**Comment by ncdc** [comment]
When we start new docs for meetings in 2021, they should probably be in personal accounts for the reason you mentioned (or in a corporate team drive with external sharing enabled)

**Comment by nikhita** [comment]
> They are in the VMware corporate account in a team drive that allows outside access. I have confirmed that they are world-viewable. @CecileRobertMichon and @detiber confirmed they have edit access.

I'll leave this to @castrojo to approve since he's been the one wrangling google docs upstream :)

**Comment by nikhita** [comment]
Looks like @castrojo is out of office...

/assign @mrbobbytables

**Comment by mrbobbytables** [comment]
please please please don't use corp accounts for owning docs :( We've been bitten sooo many times by this. If you need a shared space, we can create one to house your docs under the contributors@kubernetes.io account.

**Comment by vincepri** [comment]
@mrbobbytables Might be worthwhile to do that instead, would that be a shared drive? Can we add some of the emails from `gitdm` maybe?

**Comment by ncdc** [comment]
👍 to not use a corp account. How long would it take to create a shared space as you mentioned above?

**Comment by mrbobbytables** [comment]
I'll follow up in pm

**Comment by vincepri** [comment]
Let's merge this?

**Comment by mrbobbytables** [comment]
If all docs are moved over under teh shared dir, we should be good to go to merge 👍

**Pull request merged**
