### PR TITLE
update policy workgroup information

### PR DESCRIPTION
**Pull request by rficcaglia**
the sigs.yaml, and therefore the README generated is very stale and incorrect. correcting it.

~~I did read the note here and the "SIG Doc builder" readme but I am confused if I am supposed to make generate and commit those generated files here in this PR? or the pipeline will do this automagically? Please clarify and I will add the commit if required.~~

EDIT: ok I see the failed check: pull-community-verify #1387755120137080832 and the logs tell me all I needed! so I will add these files to the commit!

**Which issue(s) this PR fixes**:

There is no active GHI for this - if this is the required process I am happy to create one. Please advise.

### CODE REVIEW

**Comment by mrbobbytables** [comment]
Once you make the changes to sigs.yaml, you run `make` and that will automatically update your readme and any associated files 👍

**Comment by rficcaglia** [comment]
this is now a fascinating deep dive into the governance :) 

 I am a co-chair currently, per https://github.com/kubernetes/community/issues/4185#issuecomment-566807296 but it seems the yaml was never updated as requested here:

https://github.com/kubernetes/community/pull/4485#issue-371157197

The original chair approved here:

https://github.com/kubernetes/community/pull/4485#issuecomment-582634707

after but maybe didn't understand that ANOTHER pr was required to add me.  (I certainly didn't understand.) So while in spirit I am a "human approved" 3rd chair, and @JimBugwadia is a 4th (but not technically "approved") - NEITHER of us is a chair per the git process, and the current sigs.yaml chairs are both unavailable. (We have both tried several times to contact them via all channels.)

So it seems to me that the principle of lazy consensus applies per:

https://github.com/kubernetes/community/blob/master/contributors/chairs-and-techleads/leadership-changes.md

- [X] Discuss the proposed changes with the current leadership.

@JimBugwadia and I are the current leadership - although *technically* by git neither are! We have reached out to the sigs.yaml defined chairs with no response.

- [x] Send an email to the SIG/WG/UG mailing list and cc the [kubernetes-dev]
mailing list. At a minimum, the email should contain:
  - [ ] intent to step down as the current lead -- NOT APPLICABLE
  - [x] if nominating another lead  -- TECHNICALLY THIS IS WHAT WE ARE DOING
    - [] 1-2 lines about why they are being nominated  -- Jim is awesome and kyverno maintainer!
    - [x] contacts to privately reach out to for questions (current leads)
          or concerns (current leads + [steering-private]) about the nomination
  - [x] if this was discussed in a meeting, link to meeting notes --- WAS IN ZOOM CALL AND POSTED ON SLACK
  - [ ] lazy consensus deadline of at least one week --- PENDING

- [x ] If nominating another lead, ensure that they
  - [x ] are a Kubernetes GitHub org [member]
  - [x] have completed the [Inclusive Leadership Training] --- YES. @JimBugwadia ?

- [ ] Once lazy consensus has been achieved, update the following
      files in the respective repos:
  - [ ] [kubernetes/community]: [`sigs.yaml`] and use the [generator doc]
        to update `README.md` and `OWNERS_ALIASES` files
  - [ ] [kubernetes/org]: `OWNERS_ALIASES`, [milestone-maintainers team],
        kubernetes and kubernetes-sigs [team configs]
  - [ ] [kubernetes/enhancements]: `OWNERS_ALIASES`

- [ ] Update all communication properties used by the community group.
      See [sig-wg-lifecycle.md] for details.

Phew! So there we are folks!!  I love that it's all laid out in code :)  But feel free to correct me if I have erred in any of these steps!

**Comment by rficcaglia** [comment]
> @rficcaglia - we cannot directly update the WG lead information. I believe we will need to go through an election / voting process. We can discuss at the next meeting.

Jim - see the governance links noted.  If you still feel it needs discussion on 5/12 - then by the process and by all that is good and right for the community, we can indeed discuss on 5/12. Otherwise, following the defined process, let's allow the community to comment here and then the PR reviewers can adjudicate. Sound good?

**Comment by JimBugwadia** [comment]
@rficcaglia - thanks for sharing the details. Yes, I believe that this is certainly worth a quick discussion at the next meeting and as per the referenced guidelines sending an email to the wg-policy and kubernetes-dev mailing lists.

**Comment by rficcaglia** [comment]
Will add to agenda! Point of order, there was an email sent to WG-policy
but not kubernetes-dev. Will fix that! Good catch!

**Comment by cblecker** [comment]
I would add a line:

```
If you wish to raise any concerns privately, you can contact the Kubernetes Steering Committee at steering-private@kubernetes.io.
```

Otherwise looks great!

**Comment by rficcaglia** [comment]
@cblecker for the Zoom account we need control of the google groups - per the checklist guidance.  Can you either add Jim and myself to that as admins, and/or advise the reviewers to LGTM this PR to allow that to happen?  we're ready otherwise!  we have achieved lazy (and explicit meeting attendee) consensus, so unless there are any objections sent to the Steering Committee we don't know of, would be good to get this merged so we can archive Zoom talks. We have a series of presentations coming up in June we'd LOVE to share with the whole community! thanks!

**Comment by rficcaglia** [comment]
@JimBugwadia related to #4959 above, can you post your cert (I guess here since that issue is now closed).  

Here's mine:
https://ti-user-certificates.s3.amazonaws.com/e0df7fbf-a057-42af-8a1f-590912be5460/7c18479a-d5be-43d9-82b7-d49e26ae560f-robert-ficcaglia-the-inclusive-speaker-orientation-lfc101-certificate.pdf

**Comment by JimBugwadia** [comment]
@rficcaglia - I just completed the course. Here is the certificate:

https://ti-user-certificates.s3.amazonaws.com/e0df7fbf-a057-42af-8a1f-590912be5460/6b815036-10b5-56b9-8550-65b3b1eeb80f-jim-bugwadia-inclusive-open-source-community-orientation-lfc102-certificate.pdf

**Comment by rficcaglia** [comment]
@cblecker @jdumars @spiffxp everything we can do is complete! I did reach out on slack about Youtube and Zoom but i think this PR needs to be merged to make progress on those fronts.  hopefully this can be merged in as-is. please advise if I've got that wrong

**Comment by cblecker** [comment]
/lgtm
/approve

https://groups.google.com/g/kubernetes-dev/c/rsYcJQfGHV4

**Pull request merged**
