### PR TITLE
Create README file for new SIGs

### LINKED ISSUE #697: sig-generator fails on new sig creation
/cc @jamiehannaford  @jbeda 
If a new sig is being created through addition to sigs-list.yaml, make will fail because there is not an existing README.md.  

workaround was touch sig-newsig/README.md, then re-run make

### PR DESCRIPTION
**Pull request by jamiehannaford**
Fixes #697

### CODE REVIEW

**Comment by jdumars** [comment]
/lgtm

As a UX note, you need to make all again once you upgrade app.go 

Thanks for this PR!


# Jazz SIG

Covering the intersection of jazz and Kubernetes, bop-api

## Meetings
* [Wednesdays at 18:00 UTC](https://staging.talkgadget.google.com/hangouts/_/google.com/kubernetes-sig) (biweekly). [Convert to your timezone](http://www.thetimezoneconverter.com/?t=18:00&tz=UTC).

Meeting notes and Agenda can be found [here](https://goo.gl/x5nWrF).

## Leads
* [John Coltrane](https://github.com/trane), Prestige Records
* [Charlie Parker](https://github.com/yardbird), Blue Note

## Contact
* [Slack](https://kubernetes.slack.com/messages/sig-api-jazz)
* [Mailing list](https://groups.google.com/forum/#!forum/kubernetes-sig-jazz)

**Comment by cblecker** [comment]
@kubernetes/sig-testing-misc : Should we get some CI going on k/community if we have code checked in here?

**Comment by jamiehannaford** [comment]
@cblecker I think so. I created a [CI script](https://github.com/kubernetes/community/tree/master/scripts) already, so we'd just need to add a hook

**Comment by cblecker** [comment]
I opened an issue on test-infra to see if we can get some help on this (ref: https://github.com/kubernetes/test-infra/issues/3034)

**Comment by cblecker** [comment]
/lgtm
The code looks good to me, but I'll leave it for a bit before merging if anyone else wants to review. (please do)

**Comment by cblecker** [comment]
Three reviews and local testing is good enough for me (just being cautious with no CI).

Merging!

**Pull request merged**
