### PR TITLE
fix path to dockerfile, update icons, update visio file

### PR DESCRIPTION
**Pull request by istickz**
**What this PR does / why we need it**:
This PR fixes the path to the Dockerfile in the icons README.md file and updates the base Ubuntu version used in the Dockerfile. Additionally, the icons have been regenerated according to the instructions provided.

**Changes made**:
- Updated the Dockerfile path in `README.md` from `hack/svgconvertor/Dockefile` to `./tools/Dockefile`.
- Updated the base Ubuntu version in the Dockerfile from `ubuntu:18.04` to `ubuntu:24.04`.
- Regenerated icons using `./tools/rasterize.sh` and `./tools/update-visio.sh`.

### CODE REVIEW

**Comment by pacoxu** [comment]
After regenerating, there are some minor changes to the PNG format icons. 

/assign @thockin @JohnTitor

**Comment by thockin** [comment]
I checked out this PR and ran the update to confirm.  It looks like the Visio update changes on every run. Yay.

Thanks!

/lgtm
/approve

**Pull request merged**
