### PR TITLE
contributors/devel/sig-release: use dl.k8s.io where possible

### PR DESCRIPTION
**Pull request by spiffxp**
Update the kubernetes-versions guide to avoid referencing `gsutil` and
URI's that have GCS bucket names hardcoded in them where possible.

We don't have a CLI accessible way to list the contents of a given build
through dl.k8s.io, so it was necessary to keep it there.

Anything else that uses http or https to download kubernetes artifacts
should always use dl.k8s.io. It greatly reduces the amount of code that
will need to change whenever a different location is used (GCS bucket
rename, some other backing store, etc.)

There are a few other `kubernetes-release` references in this repo that
could be changed, but they're all historical or blockaded, so the
version markers doc was the only file that needed changes

This is part of https://github.com/kubernetes/k8s.io/issues/2318

### CODE REVIEW

**Comment by ameukam** [comment]
/hold
if anyone want to review.

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
