### PR TITLE
chore: add karpenter-dev channel for karpenter contributors

### PR DESCRIPTION
**Pull request by ellistarn**
**Which issue(s) this PR fixes**:

Fixes #
Looking to foster collaboration for https://karpenter.sh/v0.20.0/contributing/working-group/

### CODE REVIEW

**Review by markyjackson-taulia — CHANGES_REQUESTED** [review]
@ellistarn kindly sign the cla

**Comment by ellistarn** [comment]
@markyjackson-taulia, :done

**Review by markyjackson-taulia — APPROVED** [review]
This label will add the lgtm. I will also place a hold so other slack admins can take a look. With the holidays, it may take a week or more.

/lgtm
/hold

**Review by mrbobbytables — COMMENTED** [review]
/approve
/hold cancel

**Pull request merged**
