### PR TITLE
Adding Elasticsearch channel

### PR DESCRIPTION
**Pull request by aravindputrevu**
Request Reason: Elasticsearch is a popular search engine project. There are many use cases in this ecosystem that people use k8s. 
- Running Elasticsearch, Kibana, APM on Kubernetes via k8s operator
- Using Elasticsearch for Kubernetes monitoring.

I could see a channel as `#elk-charts` but they are helm charts specific. They are k8s community members who want to talk about other (Search, Observability) aspects around the k8s & ES. 

Please let me know if you need any details further.

### CODE REVIEW

**Comment by aravindputrevu** [comment]
I've signed the CLA long back and part of the k8s org too. Please let me know if something else needs to be done.

**Comment by mrbobbytables** [comment]
We generally only do channels for kubernetes centric external projects and specific charts don't really warrant their own channel. I could potentially see a generic observability channel, but I'd reach out to `sig-observability` in CNCF slack about it first.

**Comment by aravindputrevu** [comment]
@mrbobbytables As I mentioned in the issue, it is not about observability or a chart. Elasticsearch is more generic as a technology and also a popular OSS project. Many run it on k8s as a stateful workload.  

The reason to ask for a channel is because of community members reaching out for help. 
And hence having a channel with `elasticsearch`, it would be easy for folks to discuss topics around it. 

`elk-charts` is already a channel in the slack workspace but it caters to only helm charts which are not useful for discussing other use cases or people searching for `elasticsearch`.

**Comment by mrbobbytables** [comment]
Oh derp, I read it wrong - I thought we didn't have an elk-chart channel 🤦 . Going back through the history in the slack-admins channel it looks like it was a temporary thing and was supposed to be folded back into the main charts channel early last year. I'll announce and follow up with a PR to take care of that - but in general I'm still not a fan of an ES specific channel. I'll let other slack admins weigh in on it though.

**Comment by jeefy** [comment]
Unfortunately I'm also -1 on it. Elasticsearch is only tangentially related to Kubernetes. One doesn't rely on the other.

**Comment by aravindputrevu** [comment]
Thank you, closing this PR.

**Pull request closed without merging**
