### PR TITLE
Update channels.yaml

### PR DESCRIPTION
**Pull request by swinges**
New channel request for kalm (https://kalm.dev/), an open source Kubernetes management project

### CODE REVIEW

**Comment by swinges** [comment]
Signed the CLA!

**Comment by jdumars** [comment]
/approve
The contributor activity level in this project and relation to the Kubernetes community are consistent with precedents.

**Comment by rlenferink** [comment]
/lgtm
/approve

As @jdumars mentioned, the relation of the project is conform existing channels.

**Pull request merged**
