### PR TITLE
Update release managers group in documentation

### PR DESCRIPTION
**Pull request by jtslear**
The existing group was not valid.  This may have been updated at some point.  This ensures the documentation is pointed to the correct group.

### CODE REVIEW

**Comment by markyjackson-taulia** [comment]
@jtslear can you run a 'make generate'

**Comment by justaugustus** [comment]
All of the go is rubbing off on me! I dropped the `kubernetes-` in https://github.com/kubernetes/org/pull/828 to remove the stutter when mentioning the team.

Thanks for updating the reference! I'll approve this once the yaml is regenerated, as @markyjackson-taulia mentioned.

**Comment by justaugustus** [comment]
@jtslear -- Can you check in on this? The PR doesn't have any content right now.
Also, the commits need to be squashed once you recover the content.

/hold

**Comment by jtslear** [comment]
@justaugustus it would appear that the `make generate` wiped out my desired changes.  Now that I've learned how to contribute to this particular repo, we should be good to go with the latest changes.  My apologies :grimacing:

**Comment by justaugustus** [comment]
Hehe, no worries, John. Thanks again for the fix!
/lgtm
/approve
/hold cancel

**Pull request merged**
