### PR TITLE
Add kuberneto channel

### PR DESCRIPTION
**Pull request by Goodsmileduck**
This requests a new channel for kuberneto, which is a desktop client for Kubernetes clusters
Github: https://github.com/kuberneto/kuberneto
website: https://kuberneto.com

### CODE REVIEW

**Comment by mrbobbytables** [comment]
/hold

The repo is empty -- are you planning on publishing the code soon?
The reason being -- we usually forgo brand new projects for channels until they're a little established. 😬

**Comment by Goodsmileduck** [comment]
@mrbobbytables Hi. I see. Repo kuberneto/kuberneto created for issues and bugs. We want to make it open source later. Meanwhile, the application already available for download. I was thinking channel in kubernetes slack, could be a good place for community and support. If that not possible in the current time, not a problem, I will wait.

**Comment by mrbobbytables** [comment]
Yeah, I'd hold off for a little bit.

**Comment by mrbobbytables** [comment]
Going to go ahead and close this for now, please reopen in the future or cut a new PR once things have been opened up 👍 

/close

**Pull request closed without merging**
