### PR TITLE
Update SIG-Docs Leads info

### PR DESCRIPTION
**Pull request by chenopis**

### CODE REVIEW

**Comment by cblecker** [comment]
@chenopis Is there a reference to where this change in leads was decided? I skimmed the sig-docs mailing list and didn't see it (but I could have missed it for sure)

**Comment by chenopis** [comment]
@cblecker devin-donnelly recently transferred to a different project, so I was named TL in his place, and @zacharysarah should have been added a while ago. He's the kubernetes.io editor from the Linux Foundation that runs SIG Docs now. @jaredbhatti can verify these changes.

**Comment by cblecker** [comment]
Thanks @chenopis ! Yeah, just want that paper trail of where this was decided.

@jaredbhatti if you could confirm when you have a moment, that would be fantastic! Thanks!

**Comment by jaredbhatti** [comment]
Confirmed! I also added Zach as the primary contact for the docs from the community.

**Pull request merged**
