### PR TITLE
Added kubernetes-docs-tr channel

### PR DESCRIPTION
**Pull request by mkaramuk**
Hello there :wave: I am Muhammed Karamuk, from Turkey. I currently learning computer science concepts and interested in system administration. I want to translate Kubernetes website and documentation along my learning way.  I begin to localization by opening a Slack channel. Currently [Samim Özcan](https://github.com/Saozcan) and me are core localization team and we are eagerly waiting for new team members.

### CODE REVIEW

**Comment by mkaramuk** [comment]
I am new at here. Can anyone help me and show what should I do?

**Comment by sftim** [comment]
Hi there @mkaramuk 

Did you and the prototype Turkish localization team already introduce yourselves in #sig-docs-localizations on Slack?

The description for this PR is a bit brief and I'm not sure about the context. Would be great to learn more.

**Comment by jberkus** [comment]
@mkaramuk you need to sign a Contributor Licensing Agreement in order to submit PRs to the project.  Click on the "details" next to the failed check, and it should walk you through the process.

Note that this channel needs to be approved by SIG-Docs in any case.  Holding for Docs approval.

/hold

**Comment by mkaramuk** [comment]
I don't have the requirements those specified [here](https://github.com/kubernetes/org/issues/new/choose) (Organization Member Request). So I think I can't go further :/ If the Turkish localization starts, I will contribute.

**Pull request closed without merging**
