### PR TITLE
sig-testing: add k/sig-testing repo

### PR DESCRIPTION
**Pull request by nikhita**
Fixes https://github.com/kubernetes/org/issues/2490

/assign @BenTheElder 

/hold
for lgtm from sig-testing leads

### CODE REVIEW

**Review by spiffxp — APPROVED** [review]
/lgtm

**Comment by nikhita** [comment]
Thanks, @spiffxp!

/hold cancel

**Comment by BenTheElder** [comment]
Thank you!

**Comment by spiffxp** [comment]
First discussion! https://github.com/kubernetes/sig-testing/discussions/1

**Pull request merged**
