### PR TITLE
Make bio files follow name convention

### PR DESCRIPTION
**Pull request by xiangpengzhao**
In community/elections/2017/README.md, wrote `If you don't see a link, try here under first+lastname.` However, some bio files don't follow this convention. This PR fixes this.

/cc @castrojo

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
TBH, I'm not sure if this name convention is necessary :)

**Comment by justinsb** [comment]
I think we should remove the suggestion; people can update the links.

Setting rules on people's names does not end well :-)

**Comment by justinsb** [comment]
Sent https://github.com/kubernetes/community/pull/1064 to avoid the naming policy

**Comment by xiangpengzhao** [comment]
@justinsb agreed. makes a lot sense to me. Thanks!

/close

**Pull request closed without merging**
