### PR TITLE
Update Office Hours times and sessions for 2020

### PR DESCRIPTION
**Pull request by castrojo**
Updating this to reflect reality, also added host instructions. 

/hold
/sig contributor-experience
/area community-management

### CODE REVIEW

**Comment by parispittman** [comment]
/lgtm
/approve

🚀

**Comment by tpepper** [comment]
Looks good to me, except the commit / PR message.  "Initial update" is opaque.  Something like "office hours: freshening docs for the new year" would be notably more descriptive.

**Comment by tpepper** [comment]
The commit message update didn't change the PR message (GitHub populates this on first creation), but I guess that's ok at this point...

**Pull request merged**
