### PR TITLE
fixed the marketing council links in charter.md

### LINKED ISSUE #6268: Marketing Council links are not working
[In this](https://github.com/kubernetes/community/blob/master/communication/marketing-team/CHARTER.md) marketing council links are broken and need to be fixed for Kubernetes upstream marketing contributor communications team.

### PR DESCRIPTION
**Pull request by oshi36**
**Which issue(s) this PR fixes**:

Fixes #6268

### CODE REVIEW

**Review by Debanitrkl — APPROVED** [review]
LGTM

**Comment by chris-short** [comment]
Markdown linking is fun. You don't necessarily need the (URL) in the doc, only at the bottom I believe.

**Comment by oshi36** [comment]
@chris-short, I made the required changes

**Comment by Debanitrkl** [comment]
@oshi36 could you please make the changes I suggested above so that we can merge it

**Comment by chris-short** [comment]
WISH: markdown linter

**Comment by parispittman** [comment]
/lgtm
/approve

ty!

**Pull request merged**
