### PR TITLE
Added contact info for sig-scheduling.

### PR DESCRIPTION
**Pull request by ConnorDoyle**
attn @philips

### CODE REVIEW

**Comment by ConnorDoyle** [comment]
Covered by Intel corporate CLA.

**Comment by philips** [comment]
@sarahnovotny I know Connor works at Intel. Can I just merge?

**Comment by Hui-Zhi** [comment]
@davidopp Is that ok to add your info here? 

```
## Organizers

- [David Oppenheimer](https://github.com/davidopp) / Google
- [Tim St. Clair](https://github.com/timothysc) / RedHat

```

**Comment by sarahnovotny** [comment]
hey @ConnorDoyle the CLA bot needs to check a public email address from your github profile against a whitelist google group for your Intel CCLA.  Please make the address listed in the white list public on your profile and the bot should unstick.

**Comment by sarahnovotny** [comment]
@davidopp see @Hui-Zhi 's check above?  https://github.com/kubernetes/community/pull/44#issuecomment-239738251

**Comment by davidopp** [comment]
yes fine to list me

**Comment by ConnorDoyle** [comment]
@sarahnovotny thanks, updated public profile. If it is still unhappy I'll check around to make sure I'm a member of the group.

**Pull request merged**
