### PR TITLE
remove grodrigues3 from OWNERS files

### PR DESCRIPTION
**Pull request by grodrigues3**
Removing myself from reviewers/approvers

### CODE REVIEW

**Comment by grodrigues3** [comment]
@idvoretskyi still super on top of the PR reviews!  Thank you.

**Comment by idvoretskyi** [comment]
¯\_(ツ)_/¯

**Comment by idvoretskyi** [comment]
I don't like being on top of the sad PR reviews, but thank you @grodrigues3 for all your hard work since the early days of the Kubernetes community!

**Comment by parispittman** [comment]
@grodrigues3 helped kick start the early days and forever grateful! 🚀 🙏 🙇‍♀ 

thank you!!

**Pull request merged**
