### PR TITLE
Updating sig-aws leaders

### PR DESCRIPTION
**Pull request by kris-nova**
Hey @justinsb @countspongebob @jbeda I think this is what we talked about on the call today?

### CODE REVIEW

**Comment by countspongebob** [comment]
Looks good. 
Not sure if it is appropriate for me to lgtm in this case. Thanks Kris!

**Comment by chrislovecnm** [comment]
/hold 

We should probably discuss this next sig meeting. I am not really looking to step down.

**Comment by chrislovecnm** [comment]
@kris-nova I think it is appropriate that we contact @mfburnett via email to determine if she is ok to step down. I have not communicated with her in about a year so I assume that her stepping down is ok, but I would like to ensure that she is ok with the transition. Would you like to send the email?

Please rebase leaving my name as a lead.

**Comment by kris-nova** [comment]
Im out. 

Please accept this pull request as my resignation from the sig. You boys have fun, and good luck with the community.

**Comment by justinsb** [comment]
/hold

I think we all need some time to figure this out.

**Comment by quinton-hoole** [comment]
Agreed.  Please make sure that the SIG and it's leadership are aligned on the chosen way forward, and that this is appropriately communicated.

Here is an example of recent successful SIG leadership change that you might want to emulate:

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/kubernetes-sig-auth/SqOJsdaG7CA/qPz0e1R4AQAJ

**Comment by jbeda** [comment]
If the SIG leaders/members cannot come to agreement here, anyone in the community can bring concerns to the steering committee and we can make a call.  However, we would much rather not have to do that.

**Comment by chrislovecnm** [comment]
It would be good to get all parties on a call to communicate the concerns and choices around the transition. There also was confusion about my stepping down in April '17, as it was meant to be temporary.   I can add an item to the next meeting in two weeks or organize a call sooner if that is more appropriate. I support a solution that is best for the SIG. If part of that is me stepping down, I am happy to help the community in other ways.

**Comment by mfburnett** [comment]
Sorry delayed response but I'm okay stepping down! I sent in a PR but feel free to override and just fully remove me from all of the relevant files. cc @philips

**Pull request closed without merging**
