### PR TITLE
sig-cli: add Eddie Zaneski as a co-chair

### PR DESCRIPTION
**Pull request by soltysh**
/assign @seans3 @pwittrock @nikhita 
@eddiezane fyi

### CODE REVIEW

**Comment by soltysh** [comment]
/hold 
for visibility

**Comment by nikhita** [comment]
@eddiezane congratulations!! :tada: :clap: 

Whenever you get a chance, please complete the Inclusive Leadership Training - https://training.linuxfoundation.org/training/inclusive-speaker-orientation/ :pray:

**Comment by sallyom** [comment]
thanks, @eddiezane for all that you do! :partying_face: :+1: :tada:

**Comment by eddiezane** [comment]
Thanks team! It's been incredible to learn from y'all and be a part of this community. Looking forward to continuing along and helping others grow as well.

@nikhita I have completed the training

**Comment by cblecker** [comment]
/approve
/hold

Holding until lazy consensus achieved.

**Comment by soltysh** [comment]
The lazy consensus date has passed.
/hold cancel

**Comment by nikhita** [comment]
Re-adding lgtm. Congrats, Eddie!! :partying_face: 

/lgtm

**Pull request merged**
