### PR TITLE
Add batch-condor-hpc channel

### PR DESCRIPTION
**Pull request by jimbobby5**
New channel batch-condor-hpc. G-Research and CERN to use initially to discuss batch workloads and migration from HTCondor to Kubernetes

### CODE REVIEW

**Comment by mrbobbytables** [comment]
What are your thoughts on making a more generic channel for broader HPC/batch discussion? We have the `kubernetes-batch-jobs` channel, but that has historically been on kubernetes jobs specifically. 

My thought is based on the batch community being pretty small in Kubernetes, but there is definitely some efforts going on: [kube-batch](https://github.com/kubernetes-sigs/kube-batch), [Volcano](https://volcano.sh), [Sylabs SLURM operator](https://github.com/sylabs/slurm-operator), and the [IBM LSF Operator](https://github.com/IBMSpectrumComputing/lsf-kubernetes). It may be worth sharing a channel just to get all members with a vested interest in batch computing in the same place.

/assign @jeefy @mrbobbytables

**Comment by jimbobby5** [comment]
@mrbobbytables can do. What would you suggest, kubernetes-batch? Or just get everyone to pile into kubernetes-batch-jobs?

**Comment by mrbobbytables** [comment]
I'd lean towards `batch-computing`
@jeefy what are your thoughts?

**Comment by jeefy** [comment]
I would still lean towards using `#kubernetes-batch-jobs` until there is a specific need to spin out a separate channel for a separate project. While the main focus of that channel has been Kubernetes-specific jobs, this project would (presumably) still be doing batch-style jobs on Kubernetes, which that channel is meant for.

If a project is spun out of this collaboration, that would be a more appropriate time to create a new channel for project-specific communication. 

Thoughts?

**Comment by mrbobbytables** [comment]
> The reason for this specific channel is for a project we were hoping to spin up with CERN, so it might not be ready for the primetime of a central batch channel.

I'd still opt to general shared channel even if not ready for primetime 👍 It's great to just get the conversations going 😄 

> I would still lean towards using #kubernetes-batch-jobs until there is a specific need to spin out a separate channel for a separate project.

We can change the topic of `#kubernetes-batch-jobs` to be focused on batch computing over just the batch api.

**Comment by jimbobby5** [comment]
Happy to use `#kubernetes-batch-jobs` if this is the right place. Although there's not much going on there are ~500 people in there so I didn't necessarily want to broadcast everything we were thinking about immediately.

**Comment by mrbobbytables** [comment]
It's okay to blast 😄 can also create a thread when things are very specific.

**Comment by jimbobby5** [comment]
Ok will do that then, thanks. Closing this.

**Pull request closed without merging**
