### PR TITLE
Incorrect serial number

### PR DESCRIPTION
**Pull request by wxb0521**
Signed-off-by: Xinbo Weng <xihuanbo_0521@zju.edu.cn>

### CODE REVIEW

**Comment by jonboulle** [comment]
Good example of why https://github.com/kubernetes/community/pull/210#issuecomment-268471990 is preferable

**Comment by wxb0521** [comment]
this change is not same as #210.  it is not markdown idiom. 
in website, the number is error too.

**Comment by jonboulle** [comment]
I'm not saying this should be closed, I'm saying it's an example of why it's useful to use the same-number idiom (because then this issue wouldn't arise)

**Comment by wxb0521** [comment]
Thanks! At the first time, I misunderstand your suggestion.
And I agree with that auto-enumeration is more efficient.
But in this file, the number starts from '0', and the number in title can not be auto-enumerated good.
So is this PR can be merged? Or I should close it?

**Comment by jonboulle** [comment]
This can be merged, lgtm

**Pull request merged**
