### PR TITLE
Update sigs.yaml with aws-ebs-csi-driver subproject details

### PR DESCRIPTION
**Pull request by d-nishi**

### CODE REVIEW

**Comment by d-nishi** [comment]
@cblecker please check.

**Comment by spiffxp** [comment]
@d-nishi 
```
I1010 22:16:31.785] ====================================================================
I1010 22:16:31.785] 1 mismatches were detected.
I1010 22:16:31.785] Do not manually edit sig-list.md or README.md files inside the sig folders.
I1010 22:16:31.785] Instead make your changes to sigs.yaml, then run `make`, and then
I1010 22:16:31.785] commit your changes to sigs.yaml and any generated docs.
I1010 22:16:31.785] ====================================================================
```

**Comment by cblecker** [comment]
ping @d-nishi

**Comment by leakingtapan** [comment]
Ref kubernetes-sigs/aws-ebs-csi-driver#2

**Comment by d-nishi** [comment]
@spiffxp @cblecker - Thanks, forgot to `make generate`.

**Pull request merged**
