### PR TITLE
Correct spelling mistake

### LINKED ISSUE #1538: incorrect wording
you have it listed as on premise.  a premise is a thought or idea, what is meant is premises.  not exactly the same thing, and this mistake is very common.

https://github.com/kubernetes/community/blob/master/sig-list.md#master-sig-list

### PR DESCRIPTION
**Pull request by vbmade2000**
What this PR does / why we need it:
This PR corrects word `premise` to `premises`.

Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):
Fixes #1538

Special notes for your reviewer:

Release note:
Word `premise` to `premises` for correction.

### CODE REVIEW

**Comment by marcoceppi** [comment]
I suppose this makes sense, so long as we can keep the onprem short name :+1:

**Comment by vbmade2000** [comment]
@calebamiles @sarahnovotny Can someone please review ?

**Comment by vbmade2000** [comment]
@marcoceppi  sig-on-premise is archived. Do We still need this PR ?

**Comment by cblecker** [comment]
no, we don't anymore. thanks anyways, @vbmade2000 !

**Pull request closed without merging**
