### PR TITLE
correct spell error

### PR DESCRIPTION
**Pull request by likeXXxx**

### CODE REVIEW

**Comment by nikhita** [comment]
/hold

@likeXXxx Looks good, but please squash the commits into a single commit.

**Comment by cblecker** [comment]
Squashing..
/hold cancel
/approve

**Comment by nikhita** [comment]
> Squashing..

Woah, didn't know about the `tide/squash` label! :heart_eyes: 

@cblecker can it be invoked with a command? I think it would be helpful to have a command for it.

**Comment by jdumars** [comment]
I am convinced @cblecker is actually a wizard.

**Pull request merged**
