### PR TITLE
slack: Fix channel auto-joins for release-managers usergroup

### PR DESCRIPTION
**Pull request by justaugustus**
Signed-off-by: Stephen Augustus <saugustus@vmware.com>

Okay, one more time...
/assign @Katharine @jdumars @jeefy 
ref: #3829 #3828 #3827

### CODE REVIEW

**Comment by justaugustus** [comment]
Weird...
```
Verifying verify-generated-docs.sh
SUCCESS  verify-generated-docs.sh	8s
Verifying verify-spelling.sh
Can't find misspell - is your GOPATH 'bin' in your PATH?
  GOPATH: /home/prow/go
  PATH:   /google-cloud-sdk/bin:/workspace:/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
FAILED   verify-spelling.sh	5s
========================
FAILED TESTS
========================
hack/../hack/verify-spelling.sh
Makefile:16: recipe for target 'verify' failed
make: *** [verify] Error 1
```

**Comment by spiffxp** [comment]
That's my bad, going to revert https://github.com/kubernetes/test-infra/pull/13126

**Comment by spiffxp** [comment]
Opened revert https://github.com/kubernetes/test-infra/pull/13130

**Pull request merged**
