### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jayunit100**
kube proxy hangout info

### CODE REVIEW

**Review by mrbobbytables — CHANGES_REQUESTED** [review]
The meeting needs to be added via sigs.yaml and re-running `make` :x

**Comment by caseydavenport** [comment]
@jayunit100 if we're making this an ongoing thing, I think we should update the zoom meeting information to be owned by sig-network. I can help with that.

**Comment by jayunit100** [comment]
yeah definetly ! thanks casey, we can just reuse the netpol link right?

**Comment by jayunit100** [comment]
@caseydavenport @mrbobbytables  ok, removed the `meeting recording` for now, all set ?

**Comment by jayunit100** [comment]
@caseydavenport one last lgtm needed ! :)

**Comment by nikhita** [comment]
/approve

Leaving lgtm to @caseydavenport

**Pull request merged**
