### PR TITLE
Archive wg-iot-edge

### PR DESCRIPTION
**Pull request by mrbobbytables**
IOT / Edge is now a CNCF group. Cleaning up the K8s side of things.

/hold

/cc @cantbewong @CindyXing @dejanb

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm

**Comment by pohly** [comment]
:+1:

**Review by justaugustus — APPROVED** [review]
/lgtm
/approve

**Review by pacoxu — APPROVED** [review]

**Pull request merged**
