### PR TITLE
Going emeritus, remove zacharysarah from WG Naming

### PR DESCRIPTION
**Pull request by zacharysarah**
This PR removes me as a lead from WG-Naming.

In the regularly scheduled WG Naming meeting on Monday, April 19, 2021 I announced my intent to step down as a lead from WG Naming and other Kubernetes projects. This PR acts on the announcement.

Thanks, and so long!

/wg naming
/assign @celestehorgan @justaugustus @jdumars

### CODE REVIEW

**Comment by cblecker** [comment]
@zacharysarah Do you want to be listed as emeritus? There's a `emeritus_leads:` stanza that can be used.

**Comment by zacharysarah** [comment]
@cblecker Sure!

**Comment by justaugustus** [comment]
We'll miss you, @zacharysarah!! 🥺
/lgtm
/approve

**Comment by justaugustus** [comment]
For root approve:
/assign @cblecker

**Comment by nikhita** [comment]
/approve

@zacharysarah :two_hearts: :two_hearts: :two_hearts:

**Pull request merged**
