### PR TITLE
Cleanup cluster federation references in sig-multicluster docs

### PR DESCRIPTION
**Pull request by marun**
cc: @pmorie

### CODE REVIEW

**Comment by mrbobbytables** [comment]
Hey there @marun. Just as a heads up, when making changes to a meeting time, adding a project etc those should be done in [sigs.yaml](https://github.com/kubernetes/community/blob/master/sigs.yaml). After that you run `make` and it will regenerate that portion of the README along with updating the root [sig-list.md](https://github.com/kubernetes/community/blob/master/sig-list.md) 👍 

https://github.com/kubernetes/community/blob/633434afcbb0706707bc9f85034668ae7f04f527/sigs.yaml#L1312-L1319

**Comment by jdumars** [comment]
@marun any update here?

**Comment by marun** [comment]
@jdumars Updated!

**Comment by jdumars** [comment]
/approve
(per @quinton-hoole earlier LGTM+mine)

**Pull request merged**
