### PR TITLE
Fixes broken link for WG-IOT-EDGE meeting timezone conversion.

### PR DESCRIPTION
**Pull request by clcollins**
This PR Fixes a broken link to the timezone conversion site for the
regular working group meeting in the WG-IOT-EDGE README.md.

Signed-off-by: Christopher Collins <collins.christopher@gmail.com>

### CODE REVIEW

**Comment by clcollins** [comment]
As prompted by @k8s-ci-robot:

/assign @cantbewong

**Comment by cantbewong** [comment]
LGTM

**Pull request merged**
