### PR TITLE
Mark minikube as graduated from incubator

### PR DESCRIPTION
**Pull request by r2d4**
The corresponding post is here https://groups.google.com/forum/#!topic/kubernetes-dev/Ek8xVGuGNRA

### CODE REVIEW

**Comment by stp-ip** [comment]
LGTM

**Comment by MHBauer** [comment]
Also, is `github.com/kubernetes/charts` in there twice or am I hallucinating?

**Comment by r2d4** [comment]
Yeah, I just added the date to follow the convention set by helm.

And yes, it looks like charts is there twice at HEAD

**Comment by bgrant0607** [comment]
Someone else took care of this, thanks

**Pull request closed without merging**
