### PR TITLE
Updated to show Tasha as the co-organizer

### PR DESCRIPTION
**Pull request by craiglpeters**

### CODE REVIEW

**Comment by mrbobbytables** [comment]
@craiglpeters The sig and wg readme's are generated from [sigs.yaml](https://github.com/kubernetes/community/blob/master/sigs.yaml#L2253-L2255). To update it, you should update the [appropriate information there](https://github.com/kubernetes/community/blob/master/sigs.yaml#L2253-L2255) and run `make generate` or `make generate-dockerized` to update all the references. 

Thanks!

**Comment by egernst** [comment]
@craiglpeters - while you are touching the readme, updating the meeting schedule would be good too, as this is also wrong.

**Comment by craiglpeters** [comment]
Closing as this is not the right way to edit

**Pull request closed without merging**
