### PR TITLE
Update SIG Scalability zoom link

### PR DESCRIPTION
**Pull request by wojtek-t**
/assign @mm4tt @shyamjvs

### CODE REVIEW

**Review by mm4tt — COMMENTED** [review]
/lgtm

**Comment by wojtek-t** [comment]
@cblecker @mrbobbytables  - for approval

@kubernetes/sig-scalability - FYI

**Comment by mrbobbytables** [comment]
Linking to tracking issue: https://github.com/kubernetes/community/issues/5146

**Pull request merged**
