### PR TITLE
fix dead link

### PR DESCRIPTION
**Pull request by huxiaoliang**

### CODE REVIEW

**Comment by huxiaoliang** [comment]
I finished HelloSign steps just now, I am waiting for cncf-cla: no change to  cncf-cla: yes

**Comment by cblecker** [comment]
@huxiaoliang The commit looks good, and it's connecting to your user. Hopefully the CLA should register in the system shortly. If there is still a problem after 24h, you can contact the Linux Foundation Helpdesk at the e-mail in the above comment: https://github.com/kubernetes/community/pull/1499#issuecomment-351320661

**Comment by huxiaoliang** [comment]
@cblecker thanks for your comments, I am waiting for that.

**Comment by huxiaoliang** [comment]
check cla again

**Pull request merged**
