### PR TITLE
sig-pm: Update SIG PM Chairs

### PR DESCRIPTION
**Pull request by justaugustus**
Signed-off-by: Stephen Augustus <saugustus@vmware.com>

/hold
/assign @calebamiles @idvoretskyi @jdumars

### CODE REVIEW

**Comment by justaugustus** [comment]
Mailing list notification: https://groups.google.com/d/topic/kubernetes-pm/NGnJcNjkWuI/discussion
Lazy consensus hold to expire Wednesday, April 24th, 6pm PT.

**Comment by jdumars** [comment]
/lgtm

Also spoke to Aparna about the change and she did not have any reservations.

**Comment by justaugustus** [comment]
Much appreciated, Aparna!

**Comment by cblecker** [comment]
/approve
pending consensus being achieved

**Comment by justaugustus** [comment]
Lazy consensus achieved:
/hold cancel

**Pull request merged**
