### PR TITLE
Add devops-stack channel

### PR DESCRIPTION
**Pull request by raphink**
Add a Slack channel for the DevOps Stack

The DevOps Stack is an Open Source project that aims to ease the deployment of
Kubernetes and its ecosystem in a GitOps fashion, using Terraform & ArgoCD.

https://devops-stack.io/

**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Comment by jeefy** [comment]
/ok-to-test
Please sign the CLA :)

**Comment by raphink** [comment]
Will do @jeefy, just need to find the right person in our org to sign it 😁

**Comment by raphink** [comment]
@jeefy I think the CCLA should be fine now

**Comment by coderanger** [comment]
@raphink Any chance you can make this a less generic channel name? I'm concerned this will be taken by new users as a more generic meaning rather than a specific project named "devops-stack". Perhaps `#camptocamp-devops-stack`?

**Comment by raphink** [comment]
If you prefer, I'm fine with `#camptocamp-devops-stack`, if it's ok with the rules, considering there's not supposed to be company specific channels.

**Comment by raphink** [comment]
The channel description will obviously make it clear that it's related to the project, and not a generic channel. We could also add a disclaimer in the description of necessary.

**Comment by coderanger** [comment]
Unfortunately channel topics and descriptions are rarely looked at, especially by new users, so I don't think that would help much. If you have non-company-named suggestions I'm all ears :) That was just an off-the-cuff idea, anything that makes it clear this is a specific project rather than "let's talk about devops in general" works for me.

**Comment by raphink** [comment]
Not really. If adding `camptocamp` to the channel name works for you, I'm fine with that.

**Comment by coderanger** [comment]
/lgtm

I think this is reasonable, leaving approve for a second set of eyes since I'm mildly potato-brained today.

**Review by markyjackson-taulia — APPROVED** [review]
/lgtm

**Pull request merged**
