### PR TITLE
sig-cluster-lifecycle: update time of CAPZ office hours meeting

### PR DESCRIPTION
**Pull request by mboersma**
**Which issue(s) this PR fixes**:

N/A

See also kubernetes-sigs/cluster-api-provider-azure#2592 and [discussion in Slack](https://kubernetes.slack.com/archives/CEX9HENG7/p1660946780127319).

cc: @CecileRobertMichon, @jackfrancis

### CODE REVIEW

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/approve

**Review by neolit123 — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
