### PR TITLE
Remove User Groups as an official K8s group

### PR DESCRIPTION
**Pull request by mrbobbytables**
Related k/steering discussion on spinning down / migrating UGs - https://github.com/kubernetes/steering/issues/241

- Remove all governance docs and references to UGs as official K8s entities - cc8437d5d0c455b2031e546026bd444624eefa8f

/cc @cantbewong 
/cc @kubernetes/steering-committee 

/hold

EDIT: Dropped commit removing vmware ug, @cantbewong will handle that as part of #7405

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
/lgtm

**Review by palnabarun — APPROVED** [review]
/lgtm
/approve

**Review by BenTheElder — COMMENTED** [review]
/lgtm
/approve

**Comment by cblecker** [comment]
@mrbobbytables looks like you have a possible bad rebase?

**Comment by mrbobbytables** [comment]
@cblecker I will rebase once ug-vmware has been archived 👍

**Comment by mrbobbytables** [comment]
Closing in favor of #7407 

/close

**Pull request closed without merging**
