### PR TITLE
Add sig-etcd lead emails to sigs.yaml

### PR DESCRIPTION
**Pull request by jmhbnz**
xref https://groups.google.com/a/kubernetes.io/g/leads/c/3A2d1_onI3o

cc @serathius, @wenjiaswe, @ahrtr

### CODE REVIEW

**Comment by jmhbnz** [comment]
/hold
Hold for ack from @serathius, @ahrtr and @wenjiaswe that emails proposed are correct/preferred (I've taken them from our existing `OWNERS` file).

**Review by BenTheElder — APPROVED** [review]
/lgtm
/approve
/hold
Thank you!

**Comment by ahrtr** [comment]
/lgtm
/approve

Thanks  @jmhbnz

**Pull request merged**
