### PR TITLE
add minutes for 06-08-16

### PR DESCRIPTION
**Pull request by michelleN**
* + update agenda

### CODE REVIEW

**Comment by michelleN** [comment]
cc/ @mattfarina

**Comment by mattfarina** [comment]
@michelleN I agree on the July 6th meeting. It's very US centric thinking but we have many attendees from the US. Are there holidays in other countries we should pay attention to?

**Comment by mattfarina** [comment]
also, nice job on the notes and scheduling.

**Comment by michelleN** [comment]
@mattfarina awesome, thanks. 
On the note of holidays in other countries, I can ask around!

**Pull request merged**
