### PR TITLE
SIG Docs chair transition

### PR DESCRIPTION
**Pull request by zacharysarah**
ref: https://github.com/kubernetes/website/issues/23797

## 🟢 OK TO MERGE 🟢 

Don't merge this PR until all conditions are true:
- [x] all governance pieces of #23797 are approved
- [x] Date equal to or later than September 15th, 2020

## Description

This PR updates repo permissions and contacts for @irvifa becoming a chair and @zacharysarah transitioning to chair emeritus.

/assign @irvifa @jimangel @kbarnard10

### CODE REVIEW

**Comment by kbhawkey** [comment]
LGTM

**Comment by jimangel** [comment]
Appears ready to merge after rebase. Feel free to DM me on slack once rebased - I know this document changes often w/ the Zoom changes happening.

**Comment by zacharysarah** [comment]
/assign @mrbobbytables 

👋

**Comment by mrbobbytables** [comment]
Sorry, I missed this >_<
If you don't mind (and it wouldn't have to be in this PR), but would love to see you listed under emeritus <3 Docs would never have gotten to where they were with you, and the least that can be done is give you the nod in the readme :) 
/approve
/hold

**Comment by irvifa** [comment]
@zacharysarah Hi Zach 👋 we need you in the emeritus list, since you're back now could you please update it >_<

**Comment by zacharysarah** [comment]
Closing in favor of #5287. 
@irvifa ☝️ 

/close

**Pull request closed without merging**
