### PR TITLE
Adding link to San Diego CS testgrid presentation

### LINKED ISSUE #2441: document some testgrid analysis workflows
Testgrid is a bit mysterious to folks when they first approach it.  It could use better documentation.

For the release team this week we did a couple walk throughs of test grid:
https://youtu.be/K997_QKYKc8?t=1598
https://youtu.be/0tIFzATBCfM?t=1278
showing how we navigate it and tunnel into assessing status and triaging to a specific SIG for next level help.

In our discussion around that we've come up with a number of things that might be more broadly useful to the community:
* section in developer and/or contributor guide minimally describing navigating test grid
* a more proper scripted and recorded video posted to youtube covering some basics of test grid usage and triage workflows
* a screen shotted and annotated version of same posted to the website
* a blog post announcing any or all of that

### PR DESCRIPTION
**Pull request by markyjackson-taulia**
Signed-off-by: markyjackson-taulia <marky.r.jackson@gmail.com>

**Which issue(s) this PR fixes**:

Fixes #2441

### CODE REVIEW

**Comment by markyjackson-taulia** [comment]
cc @mrbobbytables per the last triage meeting

**Comment by jdumars** [comment]
nit - do you intend to also include the playlist in the link? My preference is to link to the specific video only.

**Comment by markyjackson-taulia** [comment]
Good call @jdumars I will fix that now

**Comment by markyjackson-taulia** [comment]
@jdumars Made that change and thank you again friend 😺

**Pull request merged**
