### PR TITLE
Append to ML WG organizers.

### PR DESCRIPTION
**Pull request by ConnorDoyle**
- [X] Ran `make WHAT=wg-machine-learning`

cc @vishh @kow3ns

### CODE REVIEW

**Comment by cblecker** [comment]
@ConnorDoyle Is there a public record of this organizer change? I can't see anything on the mailing list or meeting minutes.

**Comment by ConnorDoyle** [comment]
@cblecker apologies, we did this in the wrong order. I sent something to the list just now: https://groups.google.com/forum/#!topic/kubernetes-wg-machine-learning/kQqz5t2tL7c

**Comment by cblecker** [comment]
All good! Let me know when you have lazy consensus and I can approve this in :)

/assign

**Comment by kow3ns** [comment]
@cblecker do we need lazy consensus for adding organizers to a WG? I thought Vish and I could add other organizers based on quorum of existing organizers (which we have).

**Comment by cblecker** [comment]
@kow3ns it's not super well defined at the moment (there are active governance discussions going on at the steering committee level). historically, changes to leadership of sigs/working groups is done in a public forum, by some fair and open method of the group's choosing (consensus being the the most common).

I mentioned lazy consensus specifically based on the email that @ConnorDoyle linked on the mailing list.

**Comment by vishh** [comment]
/lgtm

On Thu, Apr 5, 2018 at 12:01 PM, Christoph Blecker <notifications@github.com

**Comment by balajismaniam** [comment]
@cblecker I think we have lazy consensus now. Can you please approve this PR?

**Pull request merged**
