### PR TITLE
added contributor course to getting started section

### LINKED ISSUE #7191: adding new contributor course to contributor cheat sheet
### Describe the issue

would love to add the new contributor course (k8s.dev/course) to the cheat sheet under the getting started section to cross-reference and overall be helpful to new and existing contirubtors

Here:
https://github.com/kubernetes/community/tree/master/contributors/guide/contributor-cheatsheet

### PR DESCRIPTION
**Pull request by chadmcrowell**
**Which issue(s) this PR fixes**:
Fixes #7191 

added new contributor course (k8s.dev/course) to the contributor cheat-sheet

### CODE REVIEW

**Comment by tokt** [comment]
Chad, did you sign CLA? (We've had some issues with EasyCLA, hopefully it'll work this time?)

**Comment by kubeskills-chad** [comment]
I did, twice! :)

-Chad

**Comment by chadmcrowell** [comment]
@tokt yes I signed the CLA twice 😃

**Pull request closed without merging**
