### PR TITLE
Archive the 2020 meeting notes.

### PR DESCRIPTION
**Pull request by jberkus**
/sig contributor-experience

/assign @mrbobbytables @alisondy

### CODE REVIEW

**Comment by mrbobbytables** [comment]
/hold
its an empty file

**Comment by jberkus** [comment]
Fixed, sorry.

**Comment by jberkus** [comment]
Hey, so I am NOT going to copy-edit a full year of notes just to pass the spellcheck.  In general, this directory should be exempt from spellcheck.

**Comment by mrbobbytables** [comment]
Added it to the exception list here:
https://github.com/kubernetes/community/pull/6287

**Pull request merged**
