### PR TITLE
Make sig-scalability meetings on-demand

### PR DESCRIPTION
**Pull request by shyamjvs**
As discussed on the slack channel.

/cc @wojtek-t

### CODE REVIEW

**Comment by mrbobbytables** [comment]
@shyamjvs The sig README's are generated from the entries in [sigs.yaml](https://github.com/kubernetes/community/blob/master/sigs.yaml#L1723-L1727). Once you update it there you then run `make generate` or `make generate-dockerized` to update it in the main sig-list and sig specific README.

The message might be a bit too big, but you could do something similar to [wg-resource-management](https://github.com/kubernetes/community/blob/master/sigs.yaml#L2269) where it lists it as  _"biweekly (on demand)"_ or add a note like _"biweekly (see agenda)"_.

**Comment by shyamjvs** [comment]
That's nice, thanks @mrbobbytables. Updated it.

**Comment by parispittman** [comment]
does on demand mean you may not meet for 3+ weeks?

according to [sig governance](https://github.com/kubernetes/community/blob/master/committee-steering/governance/sig-governance.md), it's been laid out that sigs need to have an update meeting at least every three weeks for 30 mins.

**Comment by spiffxp** [comment]
Ping for an answer on this.  If you're unable to meet regularly for N months in a row, it may be time to consider retiring this SIG.

I feel like I regularly hear about cloud providers other than GCP interested in doing scalability testing (Azure was just mentioned today), so it seems like there should be stuff to talk about here.

**Comment by parispittman** [comment]
@spiffxp i talked to shyam and wojtek about bi weekly with one true meeting a month and another bug triage/live code reviews session (which could be turned into another update meeting if needed). not sure what their decision is on this yet.

**Comment by wojtek-t** [comment]
> @spiffxp i talked to shyam and wojtek about bi weekly with one true meeting a month and another bug triage/live code reviews session (which could be turned into another update meeting if needed). not sure what their decision is on this yet.

I definitely support that (also, if there is enough content to discuss, we should do triage/reviews etc offline - this is more like to fill the time if there aren't enough agenda items).

@shyamjvs - can you please update this PR to reflect this?

**Comment by shyamjvs** [comment]
@wojtek-t Not sure if there's anything to be updated in this PR then. Guess we should just close it (i.e keep the meetings at bi-weekly, as it is currently). The only difference IIUC is we'll be doing triaging/reviews as gap-filler if there's nothing else.

**Comment by parispittman** [comment]
@shyamjvs do you mind if i share this news with kubernetes-dev@ mailing list and some other sources? many folks will be interested in a live triage session and want to make sure everyone is in the loop. i can help with getting the word out if you'd like.

**Comment by shyamjvs** [comment]
SGTM @parispittman, thanks!

**Comment by shyamjvs** [comment]
Closing this. We've decided to stick with bi-weekly for now. We'll change to weekly if needed in future.

**Pull request closed without merging**
