### PR TITLE
Add stealthybox as wg-component-standard co-chair

### PR DESCRIPTION
**Pull request by mtaufen**
Lucas announced that he is stepping down from co-chairing
wg-component-standard due to time constraints. He nominated Leigh Capili
(stealthybox@) to take his place:
https://groups.google.com/forum/#!topic/kubernetes-wg-component-standard/eBKx2LY9AMk

Leigh has the general support of contributors in the working group, and
my approval as co-chair. There have been no other nominations or
objections in the past two days.

/assign @sttts 
for co-chair approval.

### CODE REVIEW

**Comment by stealthybox** [comment]
ack :+1:

**Comment by nikhita** [comment]
/assign @cblecker 
for approval

**Pull request merged**
