### PR TITLE
Update docs: recommend setting DBG instead of GOGCFLAGS to make in debug mode

### LINKED ISSUE #6888: Development for Building Kubernetes is inaccurate
### Describe the issue

The [documentation suggests](https://github.com/kubernetes/community/blob/002ec4b213ba3b00bc456dc8e2eaa1643de4bff0/contributors/devel/development.md?plain=1#L360-L364) using `GOGCFLAGS="-N -l"`.

In the Makefile we have [another way to set debug mode](https://github.com/kubernetes/kubernetes/blob/299e65cdc5799b982b6af69858c14bfe41463540/build/root/Makefile#L78-L79), which is using `DBG=1`.

If we check the code for `hack/lib/golang.sh`([link](https://github.com/kubernetes/kubernetes/blob/299e65cdc5799b982b6af69858c14bfe41463540/hack/lib/golang.sh#L840-L845)), it sets `-N -l` for us when `DBG=1`. Otherwise, it sets `goldflags="${goldflags} -s -w"`.

Having `goldflags="${goldflags} -s -w"` and `gogcflags="${GOGCFLAGS:-} all=-N -l"` is going to make a succesful build, but when trying to use [Delve](https://github.com/go-delve/delve) for debugging we get this error: `could not launch process: could not open debug info - debuggee must not be built with 'go run' or -ldflags='-s -w', which strip debug info`.

We should change this documentation to suggest using `DBG` instead.

### PR DESCRIPTION
**Pull request by sreekaransrinath**
**Which issue(s) this PR fixes**: 
Fixes #6888

### CODE REVIEW

**Comment by brianpursley** [comment]
I don't think i can approve this, but the change is good... it matches what is commented in the Makefile:
https://github.com/kubernetes/kubernetes/blob/a2a2d5c13b8524102896299ec8aec0372debcdf7/build/root/Makefile#L81-L84

**Comment by cblecker** [comment]
/lgtm
/approve
/remove-lifecycle stale

Thanks! 🚀

**Pull request merged**
