### PR TITLE
Reformat SIGs List

### PR DESCRIPTION
**Pull request by whs-dot-hk**
Reformat SIGs list so it now support unordered list
screen shot 2018-07-22 at 23 41 10

### CODE REVIEW

**Comment by castrojo** [comment]
I assume moving the table to html is to avoid rendering differences between the markdown generator in hugo vs. the one github uses? 

/cc @cblecker to see if this affects any tooling.

**Comment by whs-dot-hk** [comment]
@castrojo I turned it to html so unordered list could be display in table cells

**Pull request closed without merging**
