### PR TITLE
Update scheduler code locations.

### PR DESCRIPTION
**Pull request by misterikkit**
The scheduler code was moved in [kubernetes #57852](https://github.com/kubernetes/kubernetes/pull/57852), and we should update docs do reflect the new location.
 
/sig scheduling
/sig docs

### CODE REVIEW

**Comment by misterikkit** [comment]
/hold
until [kubernetes #57852](https://github.com/kubernetes/kubernetes/pull/57852) merges

**Comment by liggitt** [comment]
Hold until it's released, so 1.10, right?

**Comment by misterikkit** [comment]
@liggitt Hmm, the state of master will be out of sync with community docs for some time, unless I misunderstand the release process.

**Comment by liggitt** [comment]
ah, these are referencing code paths in master... you are right, it doesn't need to wait for release

**Comment by cblecker** [comment]
/ok-to-test
Yeah, this should be fine once https://github.com/kubernetes/kubernetes/pull/57852 is merged.

**Comment by misterikkit** [comment]
I think someone with write access needs to explicitly merge this?

**Pull request merged**
