### PR TITLE
Outdated file and it refers to a non-existent concepts

### PR DESCRIPTION
**Pull request by eduartua**
This file can be deleted. It was written long ago and it refers to a non-existent concept ("API server plugin").

/sig contributor-experience

/kind cleanup

/assign @cblecker @nikhita 

/cc @parispittman

### CODE REVIEW

**Comment by eduartua** [comment]
Related to #3064

**Comment by davidopp** [comment]
Just for posterity, here's what I wrote about this deletion on the sig-architecture mailing list:

I wrote this doc, very early in the project's history. (Unfortunately I put neither my name nor a date on it; sigh.)

It is unrelated to, and pre-dated, the work to integrate Mesos with Kubernetes. It was describing how you could use a combination of a custom controller, (optionally) a custom scheduler, and what I called an "API server plugin" (which appears to be very roughly equivalent to today's aggregated/extension API server) to build the functional equivalent of a Mesos framework in Kubernetes. In a sense it foreshadowed the "operator model," though much more heavyweight, more about running the application than managing the application, and much less practical since it pre-dated TPRs/CRDs.

I'm fine with deleting it. It was interesting in an era when people were writing tons of blog posts about why the decentralized Mesos scheduling/application orchestration approach was better than Kubernetes; the point was that actually you can use Kubernetes to build the Mesos model. But it will be confusing today because there is nothing called "API server plugin" today. If I ever were to get some free time, I would just write an updated version as a blog post or something like that.

**Comment by cblecker** [comment]
Thanks @davidopp!

/lgtm
/approve

**Comment by bgrant0607** [comment]
ref #3097

**Pull request merged**
