### PR TITLE
Added link to SIG-docs youtube channel

### LINKED ISSUE #1052: SIG docs link to meeting recordings should point to the recorded meeting videos
https://github.com/kubernetes/community/blob/master/sig-docs/README.md

Has a self-referential link back to the same page. 

@kubernetes/sig-docs-maintainers

### PR DESCRIPTION
**Pull request by zacharysarah**
Closes #1052 

This PR:
- Updates the link to sig-docs meeting videos with an actual link to videos

### CODE REVIEW

**Comment by cblecker** [comment]
Can you please add to sigs.yaml and run `make`?
https://github.com/kubernetes/community/blob/052e5e9603599fb9d9ca88a9dcbcf52d60918808/sigs.yaml#L303-L323

**Comment by zacharysarah** [comment]
@cblecker :wave:

> Can you please add to `sigs.yaml`

👍 https://github.com/kubernetes/community/pull/1071/commits/d441507d83ced8728f12c24392430ac3eb74d19e

> and run `make`?

Can you be more specific about the context in which `make` needs to run? This is what I get locally:
```shell
$ make
docker build -q -t kube-communitydocs -f generator/Dockerfile generator
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
make: *** [build-image] Error 1
```

**Comment by cblecker** [comment]
It's a docker image/go application that ensures all the sig documents are updated in the right places based on the source of truth (sigs.yaml). Do you have docker installed on your machine?

**Comment by zacharysarah** [comment]
@cblecker It wasn't running. Whoops! 😳 
<details><summary>Anyway, here's the finished output:</summary><pre><code>
$ make
docker build -q -t kube-communitydocs -f generator/Dockerfile generator
sha256:3f7b5fb10e84254342cf132f759287eaac871dadd3256d6c70f672bddb3d0c0a
docker run --rm -e WG -e SIG -v /Users/zacharysarah/git/repositories/kubernetes/community:/go/src/app/generated:Z kube-communitydocs app
Generating sig-api-machinery/README.md
Generating sig-aws/README.md
Generating sig-apps/README.md
Generating sig-architecture/README.md
Generating sig-auth/README.md
Generating sig-autoscaling/README.md
Generating sig-azure/README.md
Generating sig-big-data/README.md
Generating sig-cli/README.md
Generating sig-cluster-lifecycle/README.md
Generating sig-cluster-ops/README.md
Generating sig-contributor-experience/README.md
Generating sig-docs/README.md
Generating sig-federation/README.md
Generating sig-instrumentation/README.md
Generating sig-network/README.md
Generating sig-node/README.md
Generating sig-on-premise/README.md
Generating sig-openstack/README.md
Generating sig-product-management/README.md
Generating sig-release/README.md
Generating sig-scalability/README.md
Generating sig-scheduling/README.md
Generating sig-service-catalog/README.md
Generating sig-storage/README.md
Generating sig-testing/README.md
Generating sig-ui/README.md
Generating sig-windows/README.md
Generating wg-container-identity/README.md
Generating wg-resource-management/README.md
Generating wg-cluster-api/README.md
Generating wg-kubeadm-adoption/README.md
Generating sig-list.md
Finished generation!</code></pre></details>
<br>
Should I commit the generated results?

```
modified:   sig-docs/README.md
modified:   sig-list.md
```

**Comment by cblecker** [comment]
yes please :)

**Comment by zacharysarah** [comment]
@cblecker Done!

**Pull request merged**
