### PR TITLE
Add notes for LTS and End Users sessions at the Contributor Summit.

### PR DESCRIPTION
**Pull request by jberkus**
Adds a notes directory for KCSNA2019, adds notes for the LTS and End User discussion sessions.

/sig contributor-experience

### CODE REVIEW

**Comment by jberkus** [comment]
I am *not* editing these notes for spelling.

**Comment by cblecker** [comment]
```
events/2019/11-contributor-summit/session-notes/LTS-notes.md:17:223: "wierd" is a misspelling of "weird"
events/2019/11-contributor-summit/session-notes/LTS-notes.md:25:36: "teh" is a misspelling of "the"
events/2019/11-contributor-summit/session-notes/LTS-notes.md:33:214: "becuase" is a misspelling of "because"
events/2019/11-contributor-summit/session-notes/LTS-notes.md:34:265: "mutliple" is a misspelling of "multiple"
events/2019/11-contributor-summit/session-notes/end-user-panel.md:54:41: "dependancies" is a misspelling of "dependencies"
```

**Comment by cblecker** [comment]
@jberkus CI will not allow this to merge without the above spelling fixes being applied.

**Comment by jberkus** [comment]
@cblecker the maybe this repository is not a good place for meeting notes.

**Comment by parispittman** [comment]
@jberkus can you add the folder to this file https://github.com/kubernetes/community/blob/master/hack/.spelling_failures

**Comment by tpepper** [comment]
I have WG LTS notes to merge into Josh's.  If this PR's going to be stalled, should I PR an alternate stack of commits that are Josh's, spelling fix, and added notes on top?

**Comment by jberkus** [comment]
superceded by @tpepper's PR.  Closing.

/close

**Pull request closed without merging**
