### PR TITLE
Adding CC-BY-4.0 as a documentation license

### LINKED ISSUE #5734: Missing documentation license
The community repo has only an Apache 2.0 License in the LICENSE file and there is no indication that all documentation is licensed under [CC BY 4.0](https://git.k8s.io/website/LICENSE) what should be the case according to the [CNCF charter](https://github.com/cncf/foundation/blob/master/charter.md).

### PR DESCRIPTION
**Pull request by CsatariGergely**
**Which issue(s) this PR fixes**:
Fixes #5734

### CODE REVIEW

**Comment by coderanger** [comment]
/ok-to-test
/hold

This will require some legal confirmation that we are allowed this relicensing.

**Comment by CsatariGergely** [comment]
> 
> 
> /ok-to-test
> /hold
> 
> This will require some legal confirmation that we are allowed this relicensing.

@coderanger, @caniszczyk is LF legal looking into this or how can we proceed with this?

**Comment by caniszczyk** [comment]
@coderanger we are fine here as essentially this states what is the actual IP Policy for CNCF and contributors agree too

**Comment by parispittman** [comment]
For context to folks reading this, I asked @CsatariGergely to come and talk to us at a Steering Committee meeting, unfortunately it can't happen in December due to Nokia schedules. I offered a contribex meeting but the Steering Committee has decided that is not an appropriate venue for this conversation. 

Speed up to now/the latest :)
@CsatariGergely, we'd like to welcome you and any other Nokia reps to our January 3, 2022 meeting. If you'd like to continue the discussion in the meantime, we are happy to here on this issue or at one of our mailing list options: steering@kubernetes.io or steering-private@kubernetes.io. thanks!

**Comment by justaugustus** [comment]
/close
(see https://github.com/kubernetes/community/issues/5734)

**Pull request closed without merging**
