### PR TITLE
Metrics server design proposal

### PR DESCRIPTION
**Pull request by piosz**
This was reviewed and approved in https://docs.google.com/document/d/1w6-ZfnA18aKYLJ8DCLBFKlv_1umm74x0I2X4V188kvU/edit#

### CODE REVIEW

**Comment by piosz** [comment]
As I wrote this was discussed, reviewed and approved in the mentioned doc, so I'm merging it right now, but feel free to comment. Since this is an alpha feature I'm open to revisit the design in a follow up PR.

**Comment by pigmej** [comment]
@piosz FYI this document has restricted access.

**Comment by zen** [comment]
I just wanted to note here that there is a very good practice not to merge own PRs. Also this merge is very, very fast, I don't think anyone was able to even read the document, not to mention any discussion, since document is restricted.

**Comment by piosz** [comment]
@pigmej this is shared with `kubernetes-sig-instrumentation@` and `kubernetes-sig-api-machinery@`. I'm also happy to share it upon request. Unfortunatelly there is not an option to make it public. I'll share this also with `kubernetes-dev@`.

@zen apologies for that. I find it much, much, much easier to review the proposal in a doc rather than on github and as I mentioned we went through the review process with approvers in the doc, but you are totally right and I've just realized that I haven't reached everyone who might be interested.

Anyway all feedback is welcome. Feel free to comment and I'm happy to apply them in a follow up PR.

**Pull request merged**
