### PR TITLE
Move testing-commons subproject to best-effort

### PR DESCRIPTION
**Pull request by spiffxp**
After discussion with current testing-commons subproject owners
@alejandrox1 and @andrewsykim we have decided to move the
testing-commons subproject to best-effort.

It is important that we have oversight of kubernetes/kubernetes tests,
but folks now lack the bandwidth to consistently set and drive an agenda
in this area.

Best-effort means we are stopping the testing-commons meeting and
archiving the testing-commons slack channel, and ask those contributors
interested in this topic to bring discussion to the sig-testing meeting
and sig-testing slack channel.

While I was here, I went ahead and moved sig-testing related slack
config into its own directory.

/hold
for lazy consensus, deadline 3pm PT Friday ([kubernetes-sig-testing@ thread](https://groups.google.com/g/kubernetes-sig-testing/c/3TeENNJrilo/m/M7XhgGbRAAAJ))
/cc @BenTheElder @stevekuznetsov
for sig-testing approval
/cc @alejandrox1 @andrewsykim
for current subproject owner approval

FYI @kubernetes/steering

### CODE REVIEW

**Comment by spiffxp** [comment]
/cc @mrbobbytables @coderanger 
for any opinions on the slack config changes

**Comment by spiffxp** [comment]
post-merge TODO:
- remove testing-commons meeting from zoom
- remove testing-commons meeting from sig-testing calendar

**Comment by spiffxp** [comment]
/hold cancel
lazy consensus deadline has passed

I've removed the testing-commons meeting from zoom and sig-testing's calendar

**Review by alejandrox1 — COMMENTED** [review]
/lgtm

**Comment by spiffxp** [comment]
/assign @cblecker @nikhita @mrbobbytables @alisondy 
for /approve

**Review by nikhita — APPROVED** [review]
/approve

/hold
for explicit review by slack admins. @mrbobbytables @coderanger can you take a look?

**Comment by spiffxp** [comment]
Also closed the testing-commons project board: https://github.com/orgs/kubernetes/projects/44

**Pull request merged**
