### PR TITLE
Assigning weights to contributor documents for proper surfacing

### PR DESCRIPTION
**Pull request by vishakhanihore**
**Which issue(s) this PR fixes**:

Refers #4444

### CODE REVIEW

**Comment by vishakhanihore** [comment]
I would still put owners file below the good first issues. As owners file
is more related to Kubernetes reviewing workflow not the contributing
workflow. Except that I agree with the flow of the docs you suggested.

**Comment by parispittman** [comment]
biggest questions from new contributors:
- how do i get started
- what sig do i join
- where can i get help
so i think if the workflow above addresses those three things we are good to go :)

i wonder if the cheatsheet should be higher in bobs suggestion. also curious if we should have a page or section dedicated to 'getting help' explicitly.

**Comment by vishakhanihore** [comment]
Regarding the getting help section, I think it will be coveryef when we get
a new role board for our Contributor Website. Coming to cheatsheet part it
should be below as it is more of a concise sum up of our contributor
guide.I will make the changes according to Bob opinion and the above
question asap.

**Comment by mrbobbytables** [comment]
> Regarding the getting help section, I think it will be coveryef when we get
a new role board for our Contributor Website

For now we're going to continue to link to the role board on discuss. We have a few other ideas on how to push more engagement over there.

**Comment by mrbobbytables** [comment]
> I would still put owners file below the good first issues. As owners file
is more related to Kubernetes reviewing workflow not the contributing
workflow. Except that I agree with the flow of the docs you suggested.

I think that'd be fine. Once the weights are adjusted we can start on some of the other stuff 👍

**Comment by vishakhanihore** [comment]
Great on it then.

**Comment by vishakhanihore** [comment]
@mrbobbytables @parispittman Have a look now, Made the changes according to the contributor's priority.

**Comment by mrbobbytables** [comment]
Thanks @vishakhanihore 
/approve
/hold
Once squashed should be good to go :)

**Comment by vishakhanihore** [comment]
> Thanks @vishakhanihore
> /approve
> /hold
> Once squashed should be good to go :)

@mrbobbytables done

**Pull request merged**
