### PR TITLE
Fixes contributors guide pull request doc #3087

### LINKED ISSUE #3087: The Contributor Guide pull request doc conflates developer and non-developer personas
/area contributor-guide
/kind documentation

Summarizing a [thread in #sig-contribex](https://kubernetes.slack.com/archives/C1TU9EB9S/p1547230614247500)

We view the contributor guide as a place where all contributors - developers, writers, etc can get the same information and if anything speaks to solely the developers persona, it should go in a dev guide.

We need to edit the contributor guide PR doc:
- A lot of folks who only want to contribute to our contributing docs and end up getting stuck on the dev environment pieces that they don't need.
- Need to add disclosures / separate code/non-code concerns
- There are also significant "setting up your dev environment" steps in there that should just live elsewhere, not really in a "how to pull request" doc!

(ref: https://github.com/kubernetes/community/issues/1413 for the origin story of the contrib guide)

https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md is the doc in question, some content probably belongs in:
- https://github.com/kubernetes/community/blob/master/contributors/devel/development.md
- https://github.com/kubernetes/community/blob/master/contributors/devel/testing.md
- [etiquette](https://github.com/kubernetes/community/issues/3032)

/help
/assign @guineveresaenger @parispittman 
Please /unassign and delegate as needed

### PR DESCRIPTION
**Pull request by Sai-Adarsh**
Squashed Commits, Closed previous [pull request](https://github.com/kubernetes/community/pull/3436) due to improper squashing.

* Fixes #3087 
* Build contents from [/contributors/guide/github-worflow.md](https://github.com/kubernetes/community/blob/master/contributors/guide/github-workflow.md#build)  belongs to [/community/contributors/devel/development.md](https://github.com/kubernetes/community/blob/master/contributors/devel/development.md)

/assign @guineveresaenger @spiffxp

### CODE REVIEW

**Comment by guineveresaenger** [comment]
/approve

(not sure I have approver powers)

**Comment by guineveresaenger** [comment]
cc @nikhita or @parispittman for approval

**Comment by nikhita** [comment]
Could you update the commit message to describe what is being changed? It's helpful to understand while doing a git blame :)

**Comment by Sai-Adarsh** [comment]
> Could you update the commit message to describe what is being changed? It's helpful to understand while doing a git blame :)

@nikhita  done!

**Comment by nikhita** [comment]
/assign @castrojo 
for approval

**Comment by castrojo** [comment]
/approve

Thanks for your revisions, and welcome to Kubernetes!

**Comment by Sai-Adarsh** [comment]
Thanks, @guineveresaenger @nikhita @castrojo

**Pull request merged**
