### PR TITLE
feat: Introduce channel for docs on KEDA

### PR DESCRIPTION
**Pull request by tomkerkhove**
**Which issue(s) this PR fixes**:
N/A

### CODE REVIEW

**Comment by tomkerkhove** [comment]
Any thoughts on this @markyjackson-taulia?

**Comment by markyjackson-taulia** [comment]
@tomkerkhove can you provide a link to the project so slack admins can review?

**Comment by tomkerkhove** [comment]
To keda.sh or what are you looking for exactly?

**Review by markyjackson-taulia — APPROVED** [review]
/lgtm
Holding for other Slack admins to review.
/hold

**Pull request merged**
