### PR TITLE
Remove all references to cluster-api-provider-docker

### PR DESCRIPTION
**Pull request by fabriziopandini**
This repository has been inactive for a long time, and it's due for archival.

**Which issue(s) this PR fixes**:
Rif https://github.com/kubernetes-sigs/cluster-api/issues/5087

/cc @vincepri @neolit123

### CODE REVIEW

**Comment by fabriziopandini** [comment]
@neolit123 @vincepri PTAL

**Review by neolit123 — COMMENTED** [review]
/lgtm

**Review by vincepri — APPROVED** [review]
/approve

**Comment by fabriziopandini** [comment]
@vincepri @neolit123 @justinsb looking for an approve here
(it seems the bot missed Vince's one above)

**Comment by neolit123** [comment]
@fabriziopandini our SIG cannot approve sigs.yaml changes.

/assign @mrbobbytables 
PTAL if you have a minute.

**Comment by mrbobbytables** [comment]
/approve
ref: https://github.com/kubernetes/org/issues/2888

**Pull request merged**
