### PR TITLE
Updated link to meeting notes

### PR DESCRIPTION
**Pull request by gaby-moreno**
SIG Usability README has a link to an empty meeting notes google doc. Updated the link with our first meeting notes document.

### CODE REVIEW

**Comment by nikhita** [comment]
@gaby-moreno looks like the link still allows anyone to edit the doc...

**Comment by gaby-moreno** [comment]
hi @nikhita, thanks for the heads up!

I don't own the doc so i'll defer to @vllry or @tashimi to make any changes accordingly.

**Comment by tashimi** [comment]
Yeah, permissions were intentionally left public

**Pull request merged**
