### PR TITLE
Update sigs.yml for new localization subproject

### PR DESCRIPTION
**Pull request by a-mccarthy**
Updating sig docs information to include new localization subproject

- If you are editing SIG information, please follow these instructions: https://git.k8s.io/community/generator
  You will need to follow these steps:
  1. Edit sigs.yaml with your change 
  2. Generate docs with `make generate`. To build docs for one sig, run `make WHAT=sig-apps generate`

### CODE REVIEW

**Comment by a-mccarthy** [comment]
I assume that i need to complete step 2 above once the PR merges, but please let me know if i should do it before. thanks!

**Comment by a-mccarthy** [comment]
@palnabarun Thanks for the feedback! i've updated the files. 

@natalisucks can you review this? Can you recommend what we should do about the OWNERS file for the localization subproject?

**Comment by natalisucks** [comment]
@a-mccarthy Thanks for these changes! Linking to the same OWNERS file for the website is the right way to go here, where we then update the OWNERS_ALIASES file to reflect the Localization changes we need to make. Once I update the file I can confirm with you 💛

**Comment by a-mccarthy** [comment]
This should be updated with all the correct info. One of the checks is failing, and i believe it happened when i resolved som merge conflict. 

If i need to address the failing check, can someone advise on me the best way to do this? thanks!

**Comment by mrbobbytables** [comment]
Right now its detecting a mismatch of whats in sigs.yaml and the other generated docs. - If you update sigs.yaml and then run `make` that should fix everything. It's expecting to update the docs in very specific ways that aren't obvious.

**Comment by a-mccarthy** [comment]
@mrbobbytables thanks for the help! I think i've fixed the issue 🚀

**Comment by natalisucks** [comment]
🥳 🙌 
/lgtm

**Review by mrbobbytables — COMMENTED** [review]
/approve

**Pull request merged**
