### PR TITLE
slack-config: add apko channel

### PR DESCRIPTION
**Pull request by kaniini**
apko is a free and open source software tool for building container images
using apk, the package manager most typically used in Alpine Linux.

Signed-off-by: Ariadne Conill <ariadne@chainguard.dev>

### CODE REVIEW

**Comment by coderanger** [comment]
Hi there, it looks like this is a very new project and not really specifically Kubernetes related? We are happy to support our broader community but you might want to look at building your own Slack as ours comes with some heavy restrictions due to the size and community makeup.

**Comment by markyjackson-taulia** [comment]
Is there any links you can provide regarding the project I can review?

**Review by markyjackson-taulia — APPROVED** [review]
Thank you @puerco I will give the lgtm and put a hold on it for one more slack admin to review but you should be good to go.
/lgtm
/hold

Cc: @coderanger

**Comment by puerco** [comment]
Thanks @markyjackson-taulia! You are the best :two_hearts:

**Comment by markyjackson-taulia** [comment]
@puerco 

https://media.giphy.com/media/OBuyIUMHO6yVq/giphy.gif

**Comment by puerco** [comment]
Thanks @coderanger and @markyjackson-taulia :pray:

**Pull request merged**
