### PR TITLE
fix broken links

### PR DESCRIPTION
**Pull request by LambertZhaglog**
**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Comment by alculquicondor** [comment]
I remember we were discussing this somewhere, but can't find any related open issue or PR.

**Comment by LambertZhaglog** [comment]
> This entire file is actually outdated and should be removed. cc @Huang-Wei

Sure, I know the file is outdated, the latest release has remove file pkg/scheduler/framework/plugins/legacy_registry.go. I am newer to Github PR workflow, the community contribute [guide](https://github.com/kubernetes/community/blob/master/contributors/guide/first-contribution.md#find-a-good-first-topic) tell me 
> Another way to get started is to find a documentation improvement, such as a missing/broken link, which will give you exposure to the code submission/review process without the added complication of technical depth.

so I have a try. 

Thanks a lot

**Comment by ingvagabund** [comment]
There's currently no new documentation describing filters/scores in more detail. So this document has still some value. Nevertheless, it is out of date and needs to be updated. E.g. removing mention of the legacy policy, changing names of the plugins, scores scales (0 to 100 now instead of 0 to 10), etc.

**Comment by alculquicondor** [comment]
> There's currently no new documentation describing filters/scores in more detail.

The public documentation covers it https://kubernetes.io/docs/reference/scheduling/config/

**Comment by ingvagabund** [comment]
Nice. https://kubernetes.io/docs/reference/scheduling/config/#scheduling-plugins looks good.

**Comment by Huang-Wei** [comment]
> I remember we were discussing this somewhere, but can't find any related open issue or PR.

In #6198, we discussed how to refer to the scheduler docs in the top-leveled [devel/README.md](https://github.com/kubernetes/community/blob/master/contributors/devel/README.md#sig-scheduling).

> This entire file is actually outdated and should be removed.

- Let's remove this file as it's really out-of-dated and we don't want to maintain it to confuse readers.
- Replaced the link entry in devel/README.md to "Scheduler Configuration" (with link "https://kubernetes.io/docs/reference/scheduling/config/")
image

**Pull request closed without merging**
