### PR TITLE
Use better reference links for lazy consensus

### PR DESCRIPTION
**Pull request by idealhack**
As it’s been used elsewhere in this repo already

### CODE REVIEW

**Comment by cblecker** [comment]
/lgtm
/hold

/cc @kubernetes/steering-committee 

This looks fine to me, but as it modifies sig-governance docs, I'd like to get a thumbs up from steering.

**Comment by philips** [comment]
sort of annoying the https site is broken...

/lgtm
/approve

**Comment by cblecker** [comment]
/hold cancel
Thanks @philips !

**Pull request merged**
