### PR TITLE
Slack channel for TGIK community

### PR DESCRIPTION
**Pull request by FL3SH**
Channel purpose:
Channel will be a dedicated community gathered around [TGIK](https://github.com/vmware-tanzu/tgik). The main purpose of the channel will be discussing topics related to Kubernetes and extend knowledge on the subject mentioned in TGIK streams.

### CODE REVIEW

**Comment by mrbobbytables** [comment]
I'm a -1 on this one. TGIK is an effort from vmware directly. If it was a meetup or general community run thing I'd be on board.

**Comment by FL3SH** [comment]
I didn't think about that this way, for me it was just a nice community.
If this PR violates rules I will close it.

**Comment by markyjackson-taulia** [comment]
I am also a -1 for the same reasons

**Comment by pbnj** [comment]
I am sorry I don't quite fully understand the reasoning.

- Many vendor-led projects have dedicated channels in K8s slack (ref: azure, aws, vmware, redhat, jenkins channels and more).
- TGIK dives into open source community projects, more often than vmware projects.
- TGIK also recently had non-vmware co-hosts, like [Ian Coldwater](https://youtu.be/ibrDDaLD6Ks) and [Steve Wade](https://youtu.be/F70wRexHIwg).
- TGIK invites community input on their [GH repo](https://github.com/vmware-tanzu/tgik/issues).

Just trying to understand what a general community run event should look like.

**Comment by coderanger** [comment]
@pbnj Those vendor-specific channels are for user-to-user support and do not represent the projects in an official capacity. And if we were starting from scratch we probably wouldn't allow them now so not a very helpful argument :)

In general I agree with the other admins in here that this feels overly like VMWare marketing which is out of scope for a dedicated channel. We would encourage you post your streams to `#events` though if you would like more community participation :D

**Comment by markyjackson-taulia** [comment]
#kubernetes-streaming and a another good channel

**Comment by coderanger** [comment]
It sounds like we have team consensus so going to close this out.

/close

**Pull request closed without merging**
