### PR TITLE
Add sig-cluster-lifecycle/kubespray meeting details

### PR DESCRIPTION
**Pull request by chadswen**
/cc @roberthbailey

### CODE REVIEW

**Comment by roberthbailey** [comment]
/lgtm

FYI I've also added an event to the sig cluster lifecycle calendar and it should show up on the universal calendar as well.

**Comment by chadswen** [comment]
@jdumars looks like this one is ready, but let me know if there's anything else we need to do before removing the hold.

**Comment by chadswen** [comment]
@jdumars had to rebase, so this will need /lgtm again once the hold is removed.

**Comment by chadswen** [comment]
Had to rebase again.

**Pull request merged**
