### PR TITLE
Update leadership for sig-on-premise

### PR DESCRIPTION
**Pull request by dghubble**
cc @marcoceppi @zen

### CODE REVIEW

**Comment by cblecker** [comment]
Please run `make` to generate the docs :)

**Comment by cblecker** [comment]
@dghubble should this still be merged? if so, can you run `make` on your branch to regenerate the docs?

**Comment by dghubble** [comment]
Oh, yes, its updated now.

note: Had to temporarily prefix docker cmds with sudo and disable SELinux to get this to run properly. I guess a lot of folks are using macOS, docker in a VM, and sudoless docker...

**Comment by cblecker** [comment]
@dghubble That's probably true (it is for sure in my case). Definitely open to any improvements :) (cc: @jamiehannaford)

/lgtm

**Comment by jamiehannaford** [comment]
@cblecker @dghubble Yeah, I don't think we're tested on selinux. Any suggested fixes for better support is definitely welcome :)

**Pull request merged**
