### PR TITLE
Adding meeting details for cluster-api-provider-kubevirt project

### PR DESCRIPTION
**Pull request by cchengleo**
Adding meeting details

### CODE REVIEW

**Comment by fabriziopandini** [comment]
/ok-to-test
/lgtm
@vincepri @justinsb @neolit123

**Review by vincepri — APPROVED** [review]
/approve

**Comment by neolit123** [comment]
LGTM
Needs approval from the top owners.

**Review by mrbobbytables — APPROVED** [review]
/label tide/merge-method-squash
/approve

**Pull request merged**
