### PR TITLE
remove URLS which can not accessed and were removed

### PR DESCRIPTION
**Pull request by bruceauyeung**
Signed-off-by: bruceauyeung <ouyang.qinhua@zte.com.cn>

### CODE REVIEW

**Comment by cblecker** [comment]
@bruceauyeung This is an autogenerated file. Please edit sigs.yaml and run make. More details in the comment at the top of this file.

**Comment by nikhita** [comment]
Changes look good!

@bruceauyeung can you squash the commits to a single commit?

Also, could you add "Fixes https://github.com/kubernetes/community/issues/2613" in the PR body? That way https://github.com/kubernetes/community/issues/2613 can close automatically when this PR is merged.

**Comment by bruceauyeung** [comment]
Fixes #2613

**Pull request merged**
