### PR TITLE
Add channel for Atmosphere

### PR DESCRIPTION
**Pull request by mnaser**
This is a request for the [Atmosphere](https://github.com/vexxhost/atmosphere) project to get a channel in the Kubernetes Slack.

The project allows you to deploy a full Kubernetes control plane (using `kubeadm`), deploy an OpenStack cloud on top of it (using `openstack-helm`, which the community exists on the Kubernetes slack), leverage Rook to provide object storage and use the Cluster API for OpenStack to deploy Kubernetes clusters on top of that infrastructure.

The project is fully open sourced, there are several contributors from different organizations and with the increased volume of PRs, we wanted to have a space that new users can talk and ask about it, but also a space for existing developers to discuss the project.

### CODE REVIEW

**Comment by coderanger** [comment]
@mnaser You seem to have added it twice? :)

**Comment by mnaser** [comment]
> @mnaser You seem to have added it twice? :)

oops.  sorry, I put it in there first and then ran the abc's in my head to put it in the right place.

**Comment by mnaser** [comment]
hi there, is it possible to have a look at this? :)

**Comment by mrbobbytables** [comment]
Sorry^^;; thought this merged already 
/approve

**Pull request merged**
