### PR TITLE
add eksctl channel in k8s slack

### PR DESCRIPTION
**Pull request by azpaulp**
This is a request for the [eksctl](https://eksctl.io/) project to have a channel in the Kubernetes Slack.

eksctl is a simple CLI tool for creating and managing clusters on EKS - AWS's managed Kubernetes service. The project is open source, and we want to move our Slack channel to Kubernetes Slack.

### CODE REVIEW

**Comment by coderanger** [comment]
@azpaulp Hi there, are you part of the eksctl project? Given that it already has its own community resources (https://eksctl.io/community/) I would like some confirmation from the project that they actually want this.

/hold

**Comment by yuxiang-zhang** [comment]
Hi @coderanger, I've recently [become a core contributor](https://github.com/weaveworks/eksctl/commit/fa85b14f53f5ff336031847c3a4c8409a9cd6930). Yes I can confirm that this is something we are pushing towards.

**Comment by dims** [comment]
@coderanger i can confirm @azpaulp is from our [AWS/EKS team](https://www.linkedin.com/in/paul-pollack-b8b9751/) helping with eksctl as well.

**Comment by coderanger** [comment]
Got it! Sounds good then :) If you need things like this in the future, it streamlines the process if you make a ticket in your own project with visible approvals so we know this is an official request, every now and then we'll get community members trying to make unofficial channels and we usually don't prefer then when there's clear community resources from the project itself.

/hold cancel
/lgtm
/approve

**Pull request merged**
