### PR TITLE
Update channels.yaml to add ACK

### PR DESCRIPTION
**Pull request by mikestef9**
Proposal for new channel dedicated to discussion of AWS Controllers for Kubernetes 

https://aws-controllers-k8s.github.io/community/

### CODE REVIEW

**Review by markyjackson-taulia — CHANGES_REQUESTED** [review]
The CLA will need to be fixed before we can review this.

**Comment by markyjackson-taulia** [comment]
@mikestef9 Please tag me once that is done and I will start the first part of the review. Thanks kindly.

**Comment by mikestef9** [comment]
@markyjackson-taulia Just signed the CLA

**Review by markyjackson-taulia — APPROVED** [review]
This lgtm and I will add that label, I also place a hold until another moderator can review and approve, as well as remove the hold label.
This process can take a few days (maybe more) due to availability. Please do not think it is forgotten.
Lastly, thank you for this PR.

/lgtm
/hold

**Comment by mikestef9** [comment]
assign @alejandrox1

**Comment by mrbobbytables** [comment]
woops, thought I released the hold - will do that now
/hold cancel

**Pull request merged**
