### PR TITLE
Update some test-infra related doc for federation oncall page

### PR DESCRIPTION
**Pull request by krzyzacy**
Killed Jenkins section, updated a few links and rerun section.

/assign @madhusudancs

### CODE REVIEW

**Comment by krzyzacy** [comment]
I think this PR is fine and made the doc up-to-date

**Comment by spiffxp** [comment]
FYI @kubernetes/sig-multicluster-pr-reviews

**Comment by krzyzacy** [comment]
/cc @shashidharatd 
I think this doc update is still useful

**Comment by shashidharatd** [comment]
This looks good to me. The on-call-federation-build-cop.md needs to be updated after our recent move-out-of-core and updates in CI jobs. I will follow up this PR and raise a pr for updates.
/lgtm

**Pull request merged**
