### PR TITLE
Removing extra words (use)

### PR DESCRIPTION
**Pull request by shavidissa**
The word 'use' was used twice. Removed the extra word.

### CODE REVIEW

**Comment by duglin** [comment]
@shavidissa can you please sign the CLA?
/lgtm  once signed

**Comment by shavidissa** [comment]
@duglin Just signed it :)

**Comment by duglin** [comment]
thanks
/LGTM

**Comment by castrojo** [comment]
/approve

Thanks and welcome to Kubernetes!

**Pull request merged**
