### PR TITLE
Add africa-dev channel for dedicated k8s mentorship

### PR DESCRIPTION
**Pull request by prondubuisi**
Addresses issue #6729

This is a request for a public slack channel for African contributorsof Kubernetes for easy communication and mentoring of new African devs to the Kubernetes community.

Cc @somtochiama

### CODE REVIEW

**Review by Debanitrkl — APPROVED** [review]
Thanks for the PR
/ok-to-test

**Review by mrbobbytables — COMMENTED** [review]
/lgtm

**Pull request merged**
