### PR TITLE
Adding Past Designs

### PR DESCRIPTION
**Pull request by kaslin**
Adding low res watermarked versions of past KCS designs along with a README recognizing the designers.

Hold this PR until all designers (@mfahlandt, @thockin, @jberkus) have given explicit approval. We have discussed this in Slack, but I still want explicit approval on this PR.

### CODE REVIEW

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by mfahlandt** [comment]
Thank you!

/Lgtm
/Approve

**Review by mfahlandt — APPROVED** [review]

**Pull request merged**
