### PR TITLE
Add another reference on level-based concepts to architecture.md

### PR DESCRIPTION
**Pull request by jbowes**

### CODE REVIEW

**Comment by jbeda** [comment]
Thanks for the PR @jbowes.  While I like your article (and you quote me!), I'm a little hesitant to merge this.  I don't want to start the pattern of folks submitting links to their own work in our documentation.  This is doubly true as these docs migrate from being a pile of markdown in a github repo to something that is hosted on a web page.  This just invites SEO abuse.

I'd love to get a read from @bgrant0607 on this too.  But my gut is that this is something we want to avoid.

**Comment by jbowes** [comment]
Thanks for looking so quickly, @jbeda!

Usually I wouldn't put my own stuff in PRs like this, but @bgrant0607 suggested it [on twitter](https://twitter.com/bgrant0607/status/956554934798901248). I'm happy to retract the PR though.

**Comment by jbeda** [comment]
Ha!  I'll defer to Brian.

/approve no-issue
/lgtm
/ok-to-test

**Comment by bgrant0607** [comment]
Thanks!

**Pull request merged**
