### PR TITLE
wg-multitenancy: add meeting info

### PR DESCRIPTION
**Pull request by ericchiang**
/assign @jessfraz

### CODE REVIEW

**Comment by jessfraz** [comment]
Ah I did this in https://github.com/kubernetes/community/pull/1526

we can merge which ever

/lgtm

**Comment by jessfraz** [comment]
you are going to have to teach me your ways since my other PR was open for months hahaha :P

**Comment by ericchiang** [comment]
Looks like you had `/approve` but not `/lgtm` in #1526? Oh well, one day this will all make sense.

**Pull request merged**
