### PR TITLE
update go version to 1.13.4 for Kubernetes 1.17+

### PR DESCRIPTION
**Pull request by jiahuif**
see kubernetes/kubernetes#82809
see kubernetes/kubernetes#85019

### CODE REVIEW

**Comment by cblecker** [comment]
Thanks for fixing this! It's actually 1.17+ for go1.13. Can you please make this change?

**Comment by jiahuif** [comment]
Sure! Looks like we are about to update this document again once kubernetes/kubernetes#85019 is merged.

**Comment by jiahuif** [comment]
changed accordingly.

**Comment by cblecker** [comment]
/ok-to-test
/lgtm
/approve

Thank you! 🚀

**Pull request merged**
