### PR TITLE
Add slack channel for sig-contribex issue triage team

### PR DESCRIPTION
**Pull request by ameukam**
Purpose of this channel is to set a place where leads and shadows for the new sig-conttribex issue triage team can connect and talk but also for folks who want to be involved.

/assign @parispittman

### CODE REVIEW

**Comment by idealhack** [comment]
This seems nice to have, like other team effort channels, the discussions may happen in private chats anyway, and it's better if it's public.

Do you have an estimate of the volume? I'd support this if it would be too noisy to have these conversations happen in `#sig-contribex`.

/lgtm

leave approval to sig leads

**Comment by nikhita** [comment]
> Do you have an estimate of the volume? I'd support this if it would be too noisy to have these conversations happen in #sig-contribex.

I agree, can we use #sig-contribex for triage related discussions for now? If we find that it's noisy and a separate channel would help, we can create one then.

/hold
for discussion

**Comment by ameukam** [comment]
I expect to not have a lot of conversations about tihs topic but i would prefer to have a separate place for new shadows or people interested to participate so they are not overwhelmed by everything happening in sig-contribex.
> Do you have an estimate of the volume? I'd support this if it would be too noisy to have these conversations happen in `#sig-contribex`.

@nikhita I'm fine with everything decided by the sig leads.

**Pull request merged**
