### PR TITLE
Add Bob Killen  bio for 2020 Steering Committee election

### PR DESCRIPTION
**Pull request by mrbobbytables**
/assign @jdumars @jberkus @idvoretskyi

### CODE REVIEW

**Comment by jdumars** [comment]
/lgtm 

unhold after election officers review

**Review by idvoretskyi — APPROVED** [review]
/lgtm

**Review by tpepper — COMMENTED** [review]
/lgtm

**Comment by mrbobbytables** [comment]
rebased 👍

**Comment by tpepper** [comment]
/lgtm
will add to README.md index after the set of folks' bios are merged.

**Comment by mrbobbytables** [comment]
I removed myself from the readme so it can be merged without lots of rebasing, can add to README later 👍

**Pull request merged**
