### PR TITLE
sig-cl: remove nested CAPI provider subproject

### PR DESCRIPTION
**Pull request by neolit123**
xref 
- https://github.com/kubernetes/org/issues/5194

### CODE REVIEW

**Comment by neolit123** [comment]
rebased @fabriziopandini @Priyankasaggu11929  please reapply LGTM.

**Comment by neolit123** [comment]
@Priyankasaggu11929 please help with the approval.
also we need assistance with the archival:
- https://github.com/kubernetes/org/issues/5194
thanks!

**Comment by Priyankasaggu11929** [comment]
>also we need assistance with the archival https://github.com/kubernetes/org/issues/5194

@neolit123, assigned ^ issue to myself. I'll address it.

**Pull request merged**
