### PR TITLE
Update SIG-CLI meeting time

### PR DESCRIPTION
**Pull request by ymqytw**
@fabianofranz

### CODE REVIEW

**Comment by fabianofranz** [comment]
@ymqytw when did the time change?

**Comment by ymqytw** [comment]
@fabianofranz You sent email to update the meeting time, did you?

**Comment by AdoHe** [comment]
@ymqytw @fabianofranz @kubernetes/sig-cli-misc I got quite confused about the meeting time, I even thought the Google calendar played a joke :(

**Comment by pwittrock** [comment]
Did we decide to change the time to be more Asia friendly?

**Comment by fabianofranz** [comment]
It looks like someone inadvertently changed the date/time to everyone when trying to make it adjust to his timezone. I'll close this and correct it in the calendar, apologies folks!

**Pull request closed without merging**
