### PR TITLE
Add myself to the CoCC

### PR DESCRIPTION
**Pull request by AevaOnline**
I was elected to the Code of Conduct Committee recently. This commit adds my name to the official listing.

### CODE REVIEW

**Comment by cblecker** [comment]
/ok-to-test
cc: @kubernetes/code-of-conduct-committee

**Comment by mrbobbytables** [comment]
Hey there @AevaOnline. One quick piece of administrivia if you don't mind. 😬  Could you [create an org membership request](https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-membership&template=membership.md&title=REQUEST%3A+New+membership+for+%3Cyour-GH-handle%3E)?

**Comment by AevaOnline** [comment]
@mrbobbytables done!

**Comment by mrbobbytables** [comment]
/approve

Thanks!

**Pull request merged**
