### PR TITLE
Update SIG Cluster Lifecycle chairs

### LINKED ISSUE #2471: kubernetes-sigs/kubeadm-dind-cluster subproject needs to be added to sigs.yaml
ref: #2464

Ownership of this code must fall on a single sig. I assume it's sig-cluster-lifecycle based on https://groups.google.com/a/kubernetes.io/d/msg/steering/XguRKvkEFQg/gVqGsir9AgAJ

/sig cluster-lifecycle
@kubernetes/sig-cluster-lifecycle-misc

/assign @timothysc @roberthbailey @lukemarsden @luxas 
sig-cluster-lifecycle chairs

### PR DESCRIPTION
**Pull request by timothysc**
Update sig-cluster-lifecycle chairs.

### CODE REVIEW

**Comment by roberthbailey** [comment]
I fixed #2471 in https://github.com/kubernetes/community/pull/2485. Can you remove the kubeadm-dind-cluster bits from this PR and just use it to update the chairs?

**Comment by cblecker** [comment]
@timothysc Is there a record of this chair change? I glanced through the mailing list and meeting notes and didn't see anything, obvious discussing it.

**Comment by roberthbailey** [comment]
@lukemarsden mentioned in the sig-clstr-life-leads slack channel (which is open to anyone but has a small membership - 11 members) in late July that he'd be stepping down. We've been slow at making the change official in the docs.

**Comment by timothysc** [comment]
@roberthbailey - updated.

**Comment by timothysc** [comment]
@cblecker  here is the conversation  - 

```
lukemarsden [2:26 PM]
Hey @luxas @timothysc & other leads - sorry for having been so absent recently. Work wise, we are pivoting to data science/machine learning & AI tools, and I'm not getting much spare time. So I'm thinking it might make sense to step down as SIG lead. In future it might be easier for me to get involved again and actually help with coding :-)


timothysc [2:26 PM]
Ack.
Best of luck, I can update the owners ref if you would like.

lukemarsden [2:32 PM]
Thanks! It's been a pleasure and a privilege to work with all of you :bow::relaxed:
I'll still be around the community, and kubecons - looking forward to seeing you there :+1:
```

**Comment by cblecker** [comment]
Sounds good to me. Thanks for posting the record!

/approve
LGTM to @roberthbailey

**Pull request merged**
