### PR TITLE
Updated federation meeting time to 7:30 PT.

### PR DESCRIPTION
**Pull request by gyliu513**
Based on comments at https://groups.google.com/forum/#!topic/kubernetes-sig-multicluster/4rzsWzDRXfs

### CODE REVIEW

**Comment by cblecker** [comment]
@gyliu513 This is a generated document. Please update sigs.yaml and run make, per the directions at the top of the document.

**Comment by gyliu513** [comment]
Thanks @cblecker , done.

**Comment by waynr** [comment]
@csbell @quinton-hoole I'm new to kubernetes community and almost mistakenly set up my calendar for the old time, any chance this could get merged soon? I know at least one other person that will be reading the sig/multicluster README to get started soon.

**Comment by quinton-hoole** [comment]
Thanks @waynr @gyliu513 .  Apologies for the delay in reviewing.

**Pull request merged**
