### PR TITLE
 Remove expired placeholder files 

### PR DESCRIPTION
**Pull request by praseodym**

### CODE REVIEW

**Comment by idvoretskyi** [comment]
cc @parispittman @Phillels @cblecker @nikhita @kubernetes/sig-contributor-experience-pr-reviews to discuss.

**Comment by cblecker** [comment]
@idvoretskyi Why wouldn't we want to remove them? Having tombstones all over the repo gets messy and confusing.

**Comment by idvoretskyi** [comment]
@cblecker if the original link was publicized somewhere (eg. in a blog post, presentation etc.), removing the tombstone file will cause 404.

Keeping the tombstone files is a safe way to let people to interact with the original content (even if the content is migrated), rather than skipping it entirely.

I understand and agree that it's messy, but it's a lesser issue than content unavailability.

**Comment by cblecker** [comment]
The idea of the tombstone is for folks to go update their links.

**Comment by idvoretskyi** [comment]
@cblecker yes, but we can't enforce that globally (especially in the sources outside of the Kubernetes community control as Kubernetes blog).

Also, not all resources allow to modify historical links. While it could be possible to update the link in a blog post or an article (if someone still has an editable control), but it's impossible to update the links in the printed books, YouTube videos (especially recorded from the conferences/other events), and even in the non-trivial sources as Twitter posts.

**Comment by cblecker** [comment]
/ok-to-test
/lgtm
/approve

We spoke a couple weeks ago at ContribEx about this. If we find specific tombstones that have problematic inbound links, we can keep them around for longer, but we need to be able to clean out tombstones or the repo will get unwieldy.

**Pull request merged**
