### PR TITLE
Fix "upcoming meeting" link to 2020

### PR DESCRIPTION
**Pull request by michaelrp**
**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Comment by wojtek-t** [comment]
/ok-to-test

@michaelrp - you need to sign CLA before we will be able to update it.

@mm4tt - FYI

**Comment by mrbobbytables** [comment]
Just a heads up this actually needs to be updated in [sigs.yaml](https://github.com/kubernetes/community/blob/master/sigs.yaml)

https://github.com/kubernetes/community/blob/9f02ff15ff9f8c75c0e2ebb960d907a5ea0f7a68/sigs.yaml#L1821

Once updated there, you can run `make` which will regenerate the readme 👍

**Comment by michaelrp** [comment]
@wojtek-t Done (I think).

**Comment by wojtek-t** [comment]
@michaelrp - you should also address what Bob wrote above: https://github.com/kubernetes/community/pull/4645#issuecomment-602581259

**Comment by michaelrp** [comment]
@wojtek-t - Maybe would be better to abandon this PR, and make a new one based on Bob's comment? Or I could update with a second commit.

I didn't clone to my computer for this (just edited right in GitHub), but I could and then run `make`. I'm using Windows, but that shouldn't matter I don't think.

Suggestions?

**Comment by wojtek-t** [comment]
I'm fine with closing this one and opening another one too - whatever is more convenient for you.

**Comment by michaelrp** [comment]
I cloned, made the change to sigs.yaml, and am trying to run the Makefile. I'm getting the following error:

`yaml: line 2: block sequence entries are not allowed in this context`

I've tried running `make generate`, `make generate-dockerized`, and `make WHAT=sig-scalability`. Not sure if this is a Windows problem (even in the Docker image?), or something else.

Sorry that you're spending more time on this than you would to make the change yourself, but it's good learning for me. Cheers.

**Pull request closed without merging**
