### PR TITLE
Update node perf testing doc

### PR DESCRIPTION
**Pull request by adisky**
/cc @SergeyKanzhelev 
/sig node

**Which issue(s) this PR fixes**:
Updates node performance testing doc with the current status. Add information about k8s performance dashboard.
Fixes the doc for the error encountered while running the tests.

Fixes #

### CODE REVIEW

**Comment by MadhavJivrajani** [comment]
@adisky is there anything to-do here?

**Comment by endocrimes** [comment]
change is a lgtm with Madhav's nit about https

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

it is fine even with http. Maybe fix it later

**Pull request merged**
