### PR TITLE
Fix url4

### PR DESCRIPTION
**Pull request by LinshanYu**

### CODE REVIEW

**Comment by idealhack** [comment]
thanks for addressing the comment https://github.com/kubernetes/community/pull/4318#discussion_r358099759, could you squash the commits? or this will need a squash label that can only added by repo admins.

**Comment by LinshanYu** [comment]
> thanks for addressing the comment [#4318 (comment)](https://github.com/kubernetes/community/pull/4318#discussion_r358099759), could you squash the commits? or this will need a squash label that can only added by repo admins.

ths , no problem

**Comment by LinshanYu** [comment]
> hanks for addressing the comme



> thanks for addressing the comment [#4318 (comment)](https://github.com/kubernetes/community/pull/4318#discussion_r358099759), could you squash the commits? or this will need a squash label that can only added by repo admins.



> thanks for addressing the comment [#4318 (comment)](https://github.com/kubernetes/community/pull/4318#discussion_r358099759), could you squash the commits? or this will need a squash label that can only added by repo admins.

Sry , I can't squash the commits, because I closed #4318 (comment), how to deal with this situation？

**Comment by idealhack** [comment]
I don't think the closed PR will block you from squashing the commits? even both PRs are from the same branch.

Maybe you can try it after reading https://github.com/kubernetes/community/tree/master/contributors/guide/contributor-cheatsheet. Feel free to reach out to me on k8s slack (idealhack) if you have more questions :)

**Comment by LinshanYu** [comment]
> I don't think the closed PR will block you from squashing the commits? even both PRs are from the same branch.
> 
> Maybe you can try it after reading https://github.com/kubernetes/community/tree/master/contributors/guide/contributor-cheatsheet. Feel free to reach out to me on k8s slack (idealhack) if you have more questions :)

ths , I'll close this pr and open a new pr, which links is https://github.com/kubernetes/community/pull/4321

**Comment by idealhack** [comment]
thanks! I will approve that one. For future contributions, you can just force push to the same branch instead of open new PRs in this case :)

**Pull request closed without merging**
