### PR TITLE
Cody's Unconference Team Updates

### PR DESCRIPTION
**Pull request by thecrudge**
Team updates for Unconference EU 2020 Amsterdam

### CODE REVIEW

**Comment by thecrudge** [comment]
@jeefy - Marky has committed to other aspects of the CS. I have removed @markyjackson-taulia as note taker and added @VineethReddy02 as a stand in, if until a full time note taker can be found. Thanks everyone for your help!

**Comment by jeefy** [comment]
@thecrudge Could you update the formatting so that Vineeth is in the same column as Peeyush? :) 

Otherwise lgtm!

**Comment by thecrudge** [comment]
Sorry for the delay @jeefy

**Comment by tpepper** [comment]
I think this is ready for squash and merge?  @thecrudge can you squash?

**Pull request merged**
