### PR TITLE
Slack Channel Addition

### LINKED ISSUE #5750: REQUEST: New Slack channel autoscaling-api
**GitHub Username:**

Supriya Premkumar
**Slack Username:**

@supriya premkumar 

**What Type of Request is it (Channel, User Group, Bot, Token, or Webhook)?**

Channel

**Name of Requested Resource:**
autoscaling-api

**Description of Request:**
This is for autoscaling working group to work on graduation of v2beta2 autoscaling APIs to GA  for 1.22 release.

### PR DESCRIPTION
**Pull request by supriya-premkumar**
- Creates autoscaling-api slack channel
- This is for the autoscaling working group for coordinating the graduation of v2beta2 autoscaling APIs to GA for the 1.22 release.

**Which issue(s) this PR fixes**:

Fixes #5750

### CODE REVIEW

**Comment by coderanger** [comment]
Hi there, is this an actual formal working group? If so it should be `#wg-autoscaling-api` or whatever the WG name is. Otherwise I would suggest `#sig-autoscaling-api` to keep things under the `#sig-autoscaling` prefix :)

**Comment by gjtempleton** [comment]
Hey, it's not at the level of a formal working group as we're not crossing SIG boundaries beyond coordinating with SIG Release, we're just looking for a dedicated space to discuss the work required to graduate the HPA v2 API to GA without the discussion getting lost in general SIG queries.

Agreed with the suggested channel naming to `#sig-autoscaling-api`

**Comment by supriya-premkumar** [comment]
Hi folks, if everything looks good, can I get an LGTM on this one?

**Comment by coderanger** [comment]
The list needs to be sorted.

**Pull request merged**
