### PR TITLE
Update capi v1.7 release team members

### PR DESCRIPTION
**Pull request by cahillsf**
**Which issue(s) this PR fixes**:

This PR updates the slack user groups for the new Cluster API release v1.7 team.

### CODE REVIEW

**Comment by cahillsf** [comment]
/assign @jdumars @jeefy

PTAL when you have a chance 🙇

**Comment by cahillsf** [comment]
bumping this @jdumars @jeefy -- if you don't have a chance to review would you be able to tag in someone who can?  this change really helps us to streamline communication for the release cycle

**Comment by elmiko** [comment]
we talked about this at the capi community meeting today, think we are all set from our end.

**Pull request merged**
