### PR TITLE
Add active chairs to catalog's OWNERS

### PR DESCRIPTION
**Pull request by carolynvs**
Adding the current active chairs per @fejta's suggestion. Until our leads team is created in GH, this will help us collaborate on our SIG work in this repo.

### CODE REVIEW

**Comment by MHBauer** [comment]
How did it pick dug and paul, but it won't allow aaron?

/cc @arschles 
/assign @duglin @pmorie

**Comment by carolynvs** [comment]
Aaron is not a member in the GitHub kuberentes org (just kuberentes incubator). Once he's added, assigning him will work going forward.

**Comment by MHBauer** [comment]
Yup, yup. I see the messages now. I feel like they should reverse the order of those two lines.

**Comment by MHBauer** [comment]
for helping solve problems in https://github.com/kubernetes/community/pull/2233

**Comment by cblecker** [comment]
This alias already exists:
https://github.com/kubernetes/community/blob/98d87ab432f296a1d30cb1f136f9164273732884/OWNERS_ALIASES#L93-L97

/close

**Pull request closed without merging**
