### PR TITLE
Create resource-dependent-pod-preset.md

### PR DESCRIPTION
**Pull request by therc**
A policy to automatically inject changes into a pod when specific resources are requested.

cc @jessfraz @derekwaynecarr

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
cc @pmorie

**Comment by bgrant0607** [comment]
cc @pwittrock

**Comment by bgrant0607** [comment]
cc @vishh @davidopp

**Comment by bgrant0607** [comment]
ref https://github.com/kubernetes/kubernetes/issues/17097

and

https://github.com/kubernetes/community/blob/master/contributors/design-proposals/metadata-policy.md

**Comment by derekwaynecarr** [comment]
is this something we can experiment doing with custom resource types and initializers?

the service catalog community that initiated development of pod preset has been challenged to think along similar lines rather than do this in the core.

**Comment by bgrant0607** [comment]
I agree with @derekwaynecarr. I cannot foresee adding this in the next few releases.

**Comment by jessfraz** [comment]
I agree with initializers :)

**Pull request closed without merging**
