### PR TITLE
Cleanup tombstone files in community/devel

### PR DESCRIPTION
**Pull request by tddorgtfo**
For #3220

### CODE REVIEW

**Comment by eduartua** [comment]
Good job!
/lgtm

**Comment by nikhita** [comment]
Thanks for cleaning that up @tddorgtfo!  

I just realized all kep praceholders can be removed as well i.e. the whole keps directory here: https://github.com/kubernetes/community/tree/master/keps
Ref: https://github.com/kubernetes/community/tree/master/keps

Can you remove these in a separate commit as well? :)

/unassign @grodrigues3 
/assign @justaugustus 
for kep part

**Comment by nikhita** [comment]
/pony nuke

cc @Katharine @mrbobbytables @jeefy

**Comment by Katharine** [comment]
> /pony nuke

sorry, been busy :(

**Comment by mrbobbytables** [comment]
> sorry, been busy :(

No need to be sorry :) 🤗 It was a random request and things have been busy :P

For now, manual random pony nuke~

**Comment by cblecker** [comment]
> just realized all kep praceholders can be removed as well
Mind if we do that in a follow up?

/lgtm
/approve
/hold

**Comment by justaugustus** [comment]
We can definitely just do the KEP removals in a separate PR! :)

**Comment by nikhita** [comment]
Sgtm :)

/hold cancel

**Comment by tddorgtfo** [comment]
Added #3846 to address the keps folder

**Pull request merged**
