### PR TITLE
removed personal emails on communication mailing list

### LINKED ISSUE #4426: personal emails in docs
there are some personal emails in https://github.com/kubernetes/community/blob/master/communication/mailing-list-guidelines.md#mailing-list-owners

they should be processes and/or group emails at this point and should be removed.

### PR DESCRIPTION
**Pull request by samudralavamshi54**
**Which issue(s) this PR fixes**:

Fixes #4426

### CODE REVIEW

**Comment by castrojo** [comment]
The address should be contributors@kubernetes.io.

**Comment by samudralavamshi54** [comment]
@castrojo corrected the address as per suggestion, please verify

**Comment by idealhack** [comment]
/ok-to-test
/lgtm

thanks! could you please rebase?

**Comment by samudralavamshi54** [comment]
@idealhack  rebase done ..let me know if any issues

**Comment by mrbobbytables** [comment]
I think he meant squash the commits together :x

**Comment by idealhack** [comment]
/lgtm

thanks!

**Comment by castrojo** [comment]
/approve

Thanks!

**Pull request merged**
