### PR TITLE
sig/azure: Update sig-azure info and regen docs

### PR DESCRIPTION
**Pull request by justaugustus**
Update:
* remove ACS from mission statement (to signify SIG is about supporting all k8s deployments on Azure)
* update Zoom link
* set meeting to weekly
* @colemickens affiliation

/sig azure
/cc @jdumars

### CODE REVIEW

**Comment by cblecker** [comment]
There was an issue with sig-multicluster's description. Fixed in https://github.com/kubernetes/community/pull/1825. You should be able to rebase and pick it up.

**Comment by justaugustus** [comment]
@cblecker hehe, I was fixing when I saw your comment :)
mind hitting this w/ an `/approve`?

**Comment by jdumars** [comment]
Thank you @justaugustus !

**Pull request merged**
