### PR TITLE
added users from kubestellar-devs

### PR DESCRIPTION
**Pull request by clubanderson**
**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Review by markyjackson-taulia — APPROVED** [review]
Thank you for the PR. I will add the lgtm label and another review will review and add the approve label. It may take a couple more days.
/lgtm

**Comment by clubanderson** [comment]
Thank you @markyjackson-taulia

**Comment by clubanderson** [comment]
@markyjackson-taulia can I get an update on this?

**Comment by markyjackson-taulia** [comment]
We are running behind @clubanderson shouldnt be much longer.

**Comment by clubanderson** [comment]
fyi - we have updated our name today to reinforce the separation from kcp.  I have updated all related PRs accordingly to reflect our new name "KubeStellar"

**Comment by clubanderson** [comment]
@markyjackson-taulia can I get an update on this?

**Comment by clubanderson** [comment]
@MadhavJivrajani

**Review by markyjackson-taulia — APPROVED** [review]
/approve

**Comment by clubanderson** [comment]
@markyjackson-taulia I updated the names to match the names in kube slack org for our team members.  The IDs were correct.  These names match the names in #7275

**Comment by markyjackson-taulia** [comment]
@clubanderson yep.

**Comment by clubanderson** [comment]
good, we should be all set now - sorry for the mistake on my part.

**Comment by MadhavJivrajani** [comment]
/approve
/hold
Holding in case @markyjackson-taulia would like to take a final look. Feel free to remove hold whenever ready!

**Comment by markyjackson-taulia** [comment]
Thank you @MadhavJivrajani 
/hold cancel

**Review by markyjackson-taulia — APPROVED** [review]
/lgtm

**Pull request merged**
