### PR TITLE
Fixing zoom meeting for new passcode requirements.

### PR DESCRIPTION
**Pull request by cheftako**
Fixing zoom links to reflect passcode requirements.
**Which issue(s) this PR fixes**:
Fixes # [ACTION REQUIRED] Zoom meeting changes

### CODE REVIEW

**Review by andrewsykim — COMMENTED** [review]
/approve
/lgtm

Thanks @cheftako!

**Comment by mrbobbytables** [comment]
Linking to tracking issue: https://github.com/kubernetes/community/issues/5146

**Pull request merged**
