### PR TITLE
Add co-chair Gaby to doc

### PR DESCRIPTION
**Pull request by tashimi**
Gaby Moreno Cesar is a co-chair of SIG Usability. Adding her to this doc. 

Signed-off-by: Tasha Drew <tasha.drew@gmail.com>

**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Review by mrbobbytables — CHANGES_REQUESTED** [review]
These updates can't be done through the web-ui^^;;
Once you update sigs.yaml you then run `make` and it will auto-generate all the other files that need updating 👍

**Comment by dims** [comment]
cc @kubernetes/steering-committee 

/approve
/lgtm

/hold for more steering folks to chime in

**Comment by nikhita** [comment]
Needs some more things before this can be merged (like sending an email to k-dev). Details here - https://github.com/kubernetes/community/blob/master/contributors/chairs-and-techleads/leadership-changes.md

**Comment by tashimi** [comment]
@nikhita : I sent all the emails back in September 2020, I just didn't cc k-dev. I will forward an email to k-dev so the documentation exists. Can you please merge?

**Comment by tashimi** [comment]
@nikhita : paper trail here: https://groups.google.com/g/kubernetes-sig-usability/

**Comment by tashimi** [comment]
@kubernetes/steering-committee : can you please approve this now, the checklist has been adhered to and we should be good to go.

**Comment by dims** [comment]
@tashimi ack, will round up approvals early next week

**Comment by nikhita** [comment]
> @nikhita : I sent all the emails back in September 2020, I just didn't cc k-dev. I will forward an email to k-dev so the documentation exists. Can you please merge?

@tashimi sorry for the late response, was out of office. I'm good with this to be merged since an email was forwarded to k-dev :+1: 

The steering committee was also cc'd 6 days ago and there are no major comments - https://github.com/kubernetes/community/pull/5754#issuecomment-831526763

Cancelling the hold!
/hold cancel

**Pull request merged**
