### PR TITLE
SIG Release promotions

### PR DESCRIPTION
**Pull request by justaugustus**
As discussed on November 15th SIG Release [meeting](https://docs.google.com/document/d/1Fu6HxXQu8wl6TwloGUEOXVzZ1rwZ72IAhglnaAMCPqA/edit#bookmark=id.ophpb4cnbfkv) and previously, with @kubernetes/sig-release-leads, we would like to propose the following promotions in our @kubernetes/sig-release leadership roster:

- Add @jeremyrickard as SIG Chair
- Add @Verolop as SIG Technical Lead

Both Verónica and Jeremy continue to deliver tremendous value to the SIG through their contributions!
(We have also discussed with each of them and confirmed interest in taking on these additional responsibilities.)

/hold setting a consensus date for Wednesday, November 23rd, 3pm US Eastern

### CODE REVIEW

**Comment by salaxander** [comment]
🥳

**Review by saschagrunert — APPROVED** [review]
Awesome, welcome onboard! 🥳

**Comment by jrsapi** [comment]
+100

**Comment by jimangel** [comment]
+1 🎉 Congrats!

**Comment by cpanato** [comment]
yayy super cool

/lgtm

**Comment by JamesLaverack** [comment]
+1
🎉

**Comment by leonardpahlke** [comment]
+1 🥳

**Comment by palnabarun** [comment]
Huge +1 🎉

**Comment by reylejano** [comment]
+1  🎉

**Comment by tpepper** [comment]
+1

**Comment by divya-mohan0209** [comment]
+1 🥳🍾

**Comment by justaugustus** [comment]
Hearing no objections (and with the consensus period elapsed), I'd like to welcome @Verolop and @jeremyrickard to their new roles!

We'll proceed with their onboarding in https://github.com/kubernetes/sig-release/issues/2099.
/hold cancel

**Pull request merged**
