### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by nataliesea**
I hope it's okay, I just updated the frequency of the meetings. Per the meeting notes I reviewed, it appears the meetings are every two weeks, but I wasn't sure if there was still meetings in APAC

### CODE REVIEW

**Review by markyjackson-taulia — CHANGES_REQUESTED** [review]
@nataliesea Did you run the `make generate` after making the file changes? If not, please do so locally in this repo.. See https://github.com/kubernetes/community/blob/75e8013d560a8bc204c122a42c95326a2273b700/generator/README.md#how-to-use

**Comment by joerober** [comment]
@nataliesea per the pull-community-verify and the link from @markyjackson-taulia on Aug 12, looks like the update should be within the sigs.yaml file (vs the readme itself) around this line: https://github.com/nataliesea/community/blob/patch-1/sigs.yaml#L3052

**Comment by fujitatomoya** [comment]
@nataliesea friendly ping, are you still working on this?

CC: @cantbewong

**Pull request closed without merging**
