### PR TITLE
update cloud provider KEPs to implementable status

### PR DESCRIPTION
**Pull request by andrewsykim**
These two KEPs have been in progress for quite a bit but we forgot to update them.

### CODE REVIEW

**Comment by justaugustus** [comment]
Could we bump the `Implementation History` sections as well?

**Comment by andrewsykim** [comment]
Done, PTAL! :)

**Comment by justaugustus** [comment]
REMINDER: KEPs are moving to [k/enhancements](https://github.com/kubernetes/enhancements) on November 30. Please attempt to merge this KEP before then to signal consensus.
For more details on this change, review [this thread](https://groups.google.com/d/msg/kubernetes-dev/LIkZoIqCT20/t515CV2mAgAJ).

Any questions regarding this move should be directed to that thread and not asked on GitHub.

**Comment by justaugustus** [comment]
This looks like it's ready for approval. Could we get this in before 11/30?
/assign @jagosan @hogepodge

**Pull request merged**
