### PR TITLE
Add etcd-operator subproject to etcd-io

### PR DESCRIPTION
**Pull request by kvaps**
Hey everyone,

We've established a community to develop a unified etcd-operator. This project is entirely community-driven and currently comprises mainly members of the Russian-speaking Kubernetes community. Although we've just begun, there's already significant activity, with approximately 10 active developers onboard.

We want two things:<s>
1. To donate this project to CNCF:
   - https://github.com/cncf/sandbox/issues/91</s>
1. Get a place under kubernetes-sigs:
    - https://github.com/kubernetes/community/pull/7796
    - https://github.com/kubernetes/org/pull/4839

### CODE REVIEW

**Comment by cblecker** [comment]
Hello @kvaps !

This item needs some further discussion. Becoming a CNCF Sandbox project, or a subproject of a SIG (either Cluster Lifecycle or etcd) are mutually exclusive goals. CNCF Sandbox projects are independently governed projects, while subprojects of SIGs are housed under the auspices of the Kubernetes project itself and are subject to the governance processes of the Kubernetes project itself.

I see there is a link to a thread where you are discussing this with sig-etcd, which I think is a great start. Have you discussed this at all with SIG Cluster Lifecycle? I think you should pull folks from these groups together in order to discuss where you want to house this.

The process for donating repos to the Kubernetes project is outlined here: https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#rules-for-donated-repositories

That said, if you want this to be an independently governed project in the CNCF sandbox, that is a completely separate process.

Until those conversations happen and some decisions have been made around where the best place to host this are, I'm putting these requests on hold. I would also note that as KubeCon EU just wrapped up, some folks might be slow to respond as they may be travelling and catching up.

/sig etcd cluster-lifecycle
/committee steering
/hold

**Comment by kvaps** [comment]
Hi @cblecker thanks for explanation, I’ll take a look into the documentation and update the PR accroding to it.

> Have you discussed this at all with SIG Cluster Lifecycle?

Not yet, I’ve just copied the configuration for etcdadm that’s included in `#sig-cluster-lifecycle`, `#sig-etcd` has [expressed a potential interest](https://kubernetes.slack.com/archives/C3HD8ARJ5/p1711145190605849?thread_ts=1711138820.558879&cid=C3HD8ARJ5) in sponsoring the project, but now I’m thinking that `#sig-cloud-provider` would be more suitable for this project.

/sig sig-cloud-provider

**Comment by kvaps** [comment]
Okay, I withdrew my application to join the CNCF sandbox and [informed](https://kubernetes.slack.com/archives/C718BPBQ8/p1711212742321249) the sig-cloud-provider about our proposal.

@cblecker just fyi

**Comment by serathius** [comment]
Maybe let me share in more detail on what happened during KubeCon. We have agreed that the etcd community needs an official operator and we will create a document that specifies requirements and options we have on either adopting something existing or bootstrapping a new one.

I share some of @ahrtr concerns (from slack discussion on #sig-etcd) about this etcd-operator being pretty new. However I don't have any strong opinions on which etcd-operator we should pick.
My goal is to ensure that we don't miss anyone's voice when making the decision and provide necessary etcd expertise from etcd maintainers.

I understand that there are already existing etcd management projects in sig-cluster-lifecycle, however I can't speak to their production readiness as those communities never really reached out to the etcd community. My first thought would be to put the operator in etcd project to make sure it can take advantage of our expertise.

**Comment by neolit123** [comment]
> I share some of @ahrtr concerns (from slack discussion on #sig-etcd) about this etcd-operator being pretty new. However I don't have any strong opinions on which etcd-operator we should pick.
My goal is to ensure that we don't miss anyone's voice when making the decision and provide necessary etcd expertise from etcd maintainers.

oh, so https://github.com/aenix-io/etcd-operator is a new operator.
i was thinking https://github.com/coreos/etcd-operator which is a mature project.

with such a conflict of interest it feels like this topic really should be under the sig etcd expertise.

> I understand that there are already existing etcd management projects in sig-cluster-lifecycle, however I can't speak to their production readiness as those communities never really reached out to the etcd community. My first thought would be to put the operator in etcd project to make sure it can take advantage of our expertise.

that would be https://github.com/kubernetes-sigs/etcdadm
and if sig etcd adapts its charter to include etcd lifecycle management tools such as operators, sig cl could propose to sig etcd to migrate the etcdadm project to sig etcd.

i think now that we have the specialized SIG, etcdadm is better suited for a new home. but that's a separate discussion.
@justinsb @hakman @srikiz CC for etcdadm

**Comment by fabriziopandini** [comment]
> in SIG cluster lifecycle we have etcdadm, but now that we have SIG etcd IMO all etcd* related bits should be under them.
SIG Cloud provider seems unrelated to an etcd operator.

This seems the best way forward also for me, but happy to chat about it if necessary

**Comment by elmiko** [comment]
agreed with @neolit123 about sig cloud-provider, i'm not convinced that cloud-provider is the proper sig for this effort. that said, i'm happy to have a discussion about it during a sig meeting. my gut feeling is that cluster-lifecycle is the most appropriate.

**Comment by justinsb** [comment]
etcdadm is the merge of the two production-ready etcd tools, etcdadm and etcd-manager.  etcd-manager is used in kOps and is certainly very production ready.  etcdadm I think got less traction.

etcd-manager is very old; it was forced on us by the etcd 2 -> etcd 3 migration.  It certainly predates sig-etcd, but it would be great to figure out what the right way to manage etcd should be.

Note that etcd-manager and etcdadm are not what I would call _operators_ - they have to work without etcd and thus without a kube cluster.  Is the plan that the new etcd-operator will support this mode of operation?  Or is it strictly for running when we already have a kube cluster?

We haven't built a great community around etcdadm / etcd-manager, it might be interesting to see if we can reboot it by combining etcd-operator under sig-etcd

**Comment by serathius** [comment]
https://github.com/aenix-io/etcd-operator is very new, just 50 commits with oldest one from 3 weeks ago.

**Comment by kvaps** [comment]
> https://github.com/aenix-io/etcd-operator is very new, just 50 commits with oldest one from 3 weeks ago.

Correct. And that's why we are here at such an early phase of development. We aim to create a universal tool that meets the needs of every adopter.
Now is the right time to collect your wishes and make influence on the project development. We would highly appreciate any mentorship from etcd and Kubernetes organizations.


> Note that etcd-manager and etcdadm are not what I would call operators - they have to work without etcd and thus without a kube cluster. Is the plan that the new etcd-operator will support this mode of operation? Or is it strictly for running when we already have a kube cluster?

Right now it is intended to run etcd in ready Kubernetes cluster to bootstrup other tenant Kubernetes control-planes.
This is useful for providing Kubernetes-as-a-service, eg. projects like Kamaji, Cozystack and HyperShift and some other porjects which use etcd for storing their metadata, eg. cilium, mayastor, vitastor and so on.

Currently we don't have plans for managing etcd outside of kubernetes cluster, there is a project [openshift/cluster-etcd-operator](https://github.com/openshift/cluster-etcd-operator) that aims to do just that.

**Comment by dlipovetsky** [comment]
@justinsb, thanks for nicely summarizing the state of etcdadm and etcd-manager.

> Currently we don't have plans for managing etcd outside of kubernetes cluster, there is a project [openshift/cluster-etcd-operator](https://github.com/openshift/cluster-etcd-operator) that aims to do just that.

Managing etcd outside of a kubernetes cluster is what etcdadm and etcd-manager do.

**Comment by serathius** [comment]
@justinsb @neolit123 @vincepri, I see we are forming consensus that at least for etcd-operator, better place for it would be in SIG-etcd rather than SIG-cluster-lifecycle? 

Making sure before I move the discussion to SIG-etcd for efficiency, instead of being spread between multiple groups.

**Comment by neolit123** [comment]
> @justinsb @neolit123 @vincepri, I see we are forming consensus that at least for etcd-operator, better place for it would be in SIG-etcd rather than SIG-cluster-lifecycle?
> 
> Making sure before I move the discussion to SIG-etcd for efficiency, instead of being spread between multiple groups.

yes, let's close existing PRs for SIG CL or adapt them for SIG etcd.

@kvaps ideally subproject proposals happen during a Zoom call or on a mailing list
https://github.com/kubernetes/community/blob/master/sig-etcd/README.md

**Comment by kvaps** [comment]
> yes, let's close existing PRs for SIG CL or adapt them for SIG etcd.

I rebased this PR to refer sig-etcd instead.

> @kvaps ideally subproject proposals happen during a Zoom call or on a mailing list
> https://github.com/kubernetes/community/blob/master/sig-etcd/README.md

Sure, I informed the team, we will come tomorrow at sig-etcd meeting

**Comment by serathius** [comment]
> Sure, I informed the team, we will come tomorrow at sig-etcd meeting

The tomorrows sig-etcd meeting is not a normal meeting, it's a triage meeting. Meaning it's not for discussion, it's for reading through issues and assigning them to contributors. The both meetings run bi-weekly sharing the same spot. Please consider joining the following week.

Please start from opening an umbrella issue in https://github.com/etcd-io/etcd to merge all the discussion. The etcd community wants to introduce a etcd-operator, but we haven't decided on which one. We are discussion with Datadog on open sourcing their operator. We need single forum for everyone to gather and be heard.

**Comment by kvaps** [comment]
@serathius ok thanks, I created this issue https://github.com/etcd-io/etcd/issues/17668

**Comment by bsctl** [comment]
@kvaps thanks for the great work. An etcd-operator is the missing piece as this landscape looks fragmented. Your work looks promising and we can consider to adopt it once it becomes stable.

**Comment by Bo0km4n** [comment]
@kvaps 
This is so good proposal for me. 
Especially, I strongly agree this your statement.

>Right now it is intended to run etcd in ready Kubernetes cluster to bootstrap other tenant Kubernetes control-planes.
This is useful for providing Kubernetes-as-a-service, eg. projects like Kamaji, Cozystack and HyperShift and some other projects which use etcd for storing their metadata, eg. cilium, mayastor, vitastor and so on.

openshift/etcd-operator is already exists, but I think we can't use this operator on the plane Kubernetes cluster.

**Comment by ahrtr** [comment]
> Etcd maintainers will continue the effort to introduce a official etcd-operator, with the one proposed here as one of the candidates.

Yes, I am evaluating some of the existing etcd operators, and will share it with the community in the following 1~2 weeks. etcd maintainers will discuss & coordinate & drive the effort.

**Comment by cblecker** [comment]
@serathius Where would be the right place for interested folks to coordinate with the SIG on those efforts? I'm concerned this open PR is probably not the right place. Would it be https://github.com/etcd-io/etcd/issues/17668 perhaps?

**Comment by ahrtr** [comment]
> Would it be [etcd-io/etcd#17668](https://github.com/etcd-io/etcd/issues/17668) perhaps?

I think so. We should have only one place for all discussion, let's continue all the following discussion in [etcd-io/etcd#17668](https://github.com/etcd-io/etcd/issues/17668). 

We may send email to etcd-dev or draft google doc to collect feedback later, also raise meetings to collect all interested folks.

**Comment by cblecker** [comment]
@ahrtr Sounds great!

@kvaps Thanks for engaging with us! I'm going to close this PR for now so that the discussion focuses in https://github.com/etcd-io/etcd/issues/17668 . Once a decision is made, this or a subsequent PR can be opened.

**Pull request closed without merging**
