### PR TITLE
update the link of cri api proto

### PR DESCRIPTION
**Pull request by jeffchanjunwei**

### CODE REVIEW

**Comment by cblecker** [comment]
/hold
Please use the git.k8s.io link format (what it was previously)

**Comment by jeffchanjunwei** [comment]
@cblecker, the previous link is "https://git.k8s.io/kubernetes/pkg/kubelet/apis/cri/v1alpha1/runtime/api.proto".  Now I have replace it with 
"https://git.k8s.io/kubernetes/pkg/kubelet/apis/cri/runtime/v1alpha2/api.proto". Please check.

**Pull request merged**
