### PR TITLE
Updated reference to admission_control.md

### PR DESCRIPTION
**Pull request by vaibhav2107**
The [Design Proposals](https://github.com/kubernetes/community/tree/master/contributors/design-proposals) under community/contributors have been archived. 
This PR updates the broken link of [admission_control.md](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/api-machinery/admission_control.md) to the archived [admission_control.md](https://github.com/kubernetes/design-proposals-archive/blob/main/api-machinery/admission_control.md)

### CODE REVIEW

**Comment by vaibhav2107** [comment]
Hi @guineveresaenger @lavalamp 
Please have a look

**Comment by lavalamp** [comment]
/approve

Needs a rebase

**Comment by jberkus** [comment]
@vaibhav2107 this update is fine but you need to rebase it, please.

**Pull request closed without merging**
