### PR TITLE
update sig-auth mission statement for vernacular readers

### PR DESCRIPTION
**Pull request by deads2k**
sig-auth's existing mission statement indicates how we achieve our objectives and this quote really sums up what our objective is to end users.

@kubernetes/sig-auth-api-reviews

### CODE REVIEW

**Comment by liggitt** [comment]
Heh, I'd take this. 

/cc @tallclair @mikedanese

**Comment by enj** [comment]
Haha, LGTM!

**Comment by deads2k** [comment]
> Unrelated: @deads2k, was there some other path you modified at some point? I'm curious as to why this is labelled as an api-change

@cblecker I suspect it's because I tagged @kubernetes/sig-auth-api-reviews rather than the leads individually.

**Comment by cblecker** [comment]
Yeah, that'll be it. Thanks for pointing that out :D

**Comment by mikedanese** [comment]
If a tree falls in the woods, does it make a sound? If a feature provides security without usability, are users any more secure?

**Comment by tallclair** [comment]
/lgtm
:clap:

**Pull request merged**
