### PR TITLE
Copying Brian Grant's article on declarative application management from Drive

### PR DESCRIPTION
**Pull request by marpaia**
There was an ask in the [Google Doc](https://docs.google.com/a/arpaia.co/document/d/1cLPGweVEYrVqQvBLJg6sxV-TrE5Rm2MNOBA_cxZP2WU/edit?disco=AAAABWmp15I) to add this document to this repo, so I ran a gdoc to markdown conversion script and went through and fixed up a few formatting errors. I didn't make any changes to content, although I did make some edits to formatting so that GitHub markdown rendering worked well.

I noticed that the [WG Apply README](https://github.com/kubernetes/community/tree/master/wg-apply) links to the Google Drive folder which contains the original, so I'm not sure if we want to just leave that as the canonical place for resources. Happy to close this out if that's the case.

### CODE REVIEW

**Comment by bgrant0607** [comment]
@marpaia Thanks much. Could you please move this to contributors/design-proposals/architecture? 

And remove the last section, "Application Definition Format Sketch"? That's a partial design proposal rather than background.

And if you have time, could you also translate my resource-model doc?
https://docs.google.com/document/d/1RmHXdLhNbyOWPW_AtnnowaRfGejw-qlKQIuLKQWlwzs/edit#

@monopole Could you please take a look at this, and check whether there were any important discussions in comments that should be incorporated?

**Comment by bgrant0607** [comment]
I did a quick skim. Thanks for removing the bottom section. We can fix any issues in subsequent PRs.

/lgtm
/approve

**Comment by kargakis** [comment]
:+1:

**Pull request merged**
