### PR TITLE
slack config: add Flatcar channel

### PR DESCRIPTION
**Pull request by t-lo**
Flatcar Container Linux is a fully open source, minimal-footprint, secure by default and always up-to-date Linux distribution for running containers at scale.

https://www.flatcar.org/

Flatcar has many users in the cloud native community, using Flatcar as their OS of choice to run Kubernetes. Our maintainers actively participate in multiple cloud native projects (e.g. image-builder, CAPI, and several CAPI providers).

Flatcar CC: @ahrkrak @jepio @vbatts @pothos @tormath1 @miao0miao
Kubernetes / cloud native CC: @dims @codenrhoden

### CODE REVIEW

**Comment by codenrhoden** [comment]
yeah, +1 from me as well.
/lgtm

**Review by markyjackson-taulia — APPROVED** [review]
This looks good. Adding a slack admin lgtm and holding for other slack admin reviews.
/lgtm

**Comment by castrojo** [comment]
/approve

@markyjackson-taulia this doesn't seem controversial, unhold at your convenience. 🖖🏾

**Comment by t-lo** [comment]
> /unholy cancel

Ummmm... @markyjackson-taulia is this a typo or should we pull in an exorcist?

**Pull request merged**
