### PR TITLE
cluster capacity proposal

### PR DESCRIPTION
**Pull request by ingvagabund**
Feature issue: https://github.com/kubernetes/features/issues/123

cc @aveshagarwal  @hodovska @derekwaynecarr

### CODE REVIEW

**Comment by aveshagarwal** [comment]
@kubernetes/sig-scheduling-misc

**Comment by derekwaynecarr** [comment]
@davidopp -- any objection to merging this since its the basis of the new repo?  or we can manage this document in that new repo itself.

**Comment by philips** [comment]
Ping @davidopp

**Comment by davidopp** [comment]
Oh sorry for not seeing this. I'm fine either way.

Has this doc been reviewed? Since this has already be mostly implemented, it's probably not that important, but at least one person should presumably review it.

**Pull request closed without merging**
