### PR TITLE
feat(slack): Adding homelab slack channel

### PR DESCRIPTION
**Pull request by kris-nova**
Can we please have a channel for homelab Kubernetes rigs?

The topic: Home hardware running Kubernetes community

I can update the topic and volunteer to triage any issues
 that come up.

Signed-off-by: Kris Nova <kris@nivenly.com>

**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Comment by kris-nova** [comment]
Hi @parispittman @castrojo!

**Comment by munnerz** [comment]
A big +1 to this 🙂 I'm also happy to help moderate as part of my slack admin duties too.

We have a similar channel on our work slack and it's home to a lot of great conversation. I'll leave it to other admins to decide if this is an appropriate channel for the kubernetes slack 😄

/cc @mrbobbytables @jeefy

**Comment by kris-nova** [comment]
I love our community so much.

**Comment by munnerz** [comment]
excessive homelab setups -> twitter -> github -> community slack channels 🎉

**Comment by castrojo** [comment]
/approve

This will be fun!

**Pull request merged**
