### PR TITLE
wg-serving: add link to K8s WG Serving playlist

### PR DESCRIPTION
**Pull request by terrytangyuan**
/cc @SergeyKanzhelev @ArangoGutierrez

### CODE REVIEW

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Comment by SergeyKanzhelev** [comment]
dup of https://github.com/kubernetes/community/pull/7862

Reviews are not fast here =)

**Comment by terrytangyuan** [comment]
Oh oops. I even lgtm-ed that one.

**Pull request merged**
