### PR TITLE
SIG Release cleanups

### PR DESCRIPTION
**Pull request by justaugustus**
- @hasheddan is now Emeritus (https://github.com/kubernetes/sig-release/issues/1667)
- Minor link/comment cleanups

Signed-off-by: Stephen Augustus <foo@auggie.dev>

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
/lgtm

**Review by saschagrunert — APPROVED** [review]

**Comment by justaugustus** [comment]
> /assign @BenTheElder @spiffxp

Wrong PR --> https://github.com/kubernetes/test-infra/pull/23332#issuecomment-903930027
/unassign @BenTheElder @spiffxp

**Review by cblecker — APPROVED** [review]

**Pull request merged**
