### PR TITLE
Improvements to Docs in (Communication)

### PR DESCRIPTION
**Pull request by Krishnamohan-Yerrabilli**
### Why:

Incorrect form of noun, pronoun, and unwanted article usage

### What's being changed:

Changed "all of communication" to "all of the communication" -> article usage fixed
Changed "community groups" to "community group's" -> noun form fixed 
Replaced "listed in the" to "listed on the" -> preposition fixed
Changed "groups and" to "groups and," -> added (,) to separate the elements
Changed "each community groups" to "each community group" -> mentioned "each" as individual group so removing (s) would be appropriate
Changed "weekly" to "a weekly" -> missing a determiner before it, adding "a" could be essential.
Changed "held every" to "is held every" -> missing verb fixed.

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the self-review checklist.

### CODE REVIEW

**Comment by Krishnamohan-Yerrabilli** [comment]
@jberkus Opened this PR with new branch(Krishnamohan-Yerrabilli:new-branch-for-commu.-rm), I hope now this changes make things run smoothly now, please review it ty.

**Comment by jdumars** [comment]
/approve
Thanks for the edits!

**Comment by Krishnamohan-Yerrabilli** [comment]
> /approve Thanks for the edits!

Pleasure is mine!

**Comment by jberkus** [comment]
Looks good.  Thanks for your persistence!

/lgtm
/approve

**Comment by Krishnamohan-Yerrabilli** [comment]
> Looks good. Thanks for your persistence!
> 
> /lgtm /approve

Pleasure is mine :)

**Pull request merged**
