### PR TITLE
Add OWNERS for sig-storage design proposals

### PR DESCRIPTION
**Pull request by msau42**
/cc @kubernetes/sig-storage-pr-reviews

### CODE REVIEW

**Comment by cblecker** [comment]
Is this coordinated with @grodrigues3 https://github.com/kubernetes/community/pull/1010 ?

**Comment by msau42** [comment]
Whoops nope

**Comment by msau42** [comment]
Just spoke to @grodrigues3, he'll handle moving the files.  I'll change my pr to just add an owners file.

**Comment by msau42** [comment]
Updated

**Comment by saad-ali** [comment]
We can merge this once @grodrigues3's changes go in.

**Pull request merged**
