### PR TITLE
Update sig-service-catalog chairs

### PR DESCRIPTION
**Pull request by jberkhahn**
with Jay stepping aside and Kibbles having been gone for a while now, Mateusz is stepping in

as per the discussion in the steering committee meeting last month

### CODE REVIEW

**Comment by cblecker** [comment]
@jberkhahn Do you have a link to where the public record of this change is? Thanks!

**Comment by jberkhahn** [comment]
we discussed it in the weekly meeting on 6/17, as evidenced by the recording [here](https://www.youtube.com/playlist?list=PL69nYSiGNLP2k9ZXx9E1MvRSotFDoHUWs) and the agenda [here](https://docs.google.com/document/d/17xlpkoEbPR5M6P5VDzNx17q6-IPFxKyebEekCGYiIKM/edit?usp=sharing)

**Comment by cblecker** [comment]
@jberkhahn Thank you!
/approve

**Comment by MHBauer** [comment]
I can lgtm it tho!
/lgtm
@jberkhahn

**Pull request merged**
