### PR TITLE
Fix owner aliases for provider-aws

### LINKED ISSUE #5671: provider-aws OWNERS_ALIAS is mostly stale
This alias is copy-pasted in a bunch of different repos (kubernetes/org, kubernetes/test-infra).  Two of its members have moved on from the project and have at most 5 contributions for the year (kris-nova, d-nishi) vs ~1K for justinsb (according to devstats).  PRs that touch paths it owns go unaddressed if justinsb happens to be unavailable.

This is the alias definition in this repo, but as I said, it's copy-pasted around:
https://github.com/kubernetes/community/blob/099566260faa4674fc98b3789e2d36b42bcd1978/OWNERS_ALIASES#L166-L169

https://cs.k8s.io/?q=provider-aws&i=nope&files=OWNERS%24&excludeFiles=&repos= are the paths in question, basically:
- KEPs related to aws
- GitHub team changes related to aws

/kind bug
/priority important-soon
/sig cloud-provider
/provider aws
/assign @justinsb @cheftako @andrewsykim 
FYI @AndyXiangLi @wongma7

### PR DESCRIPTION
**Pull request by nckturner**
Replace inactive owners with active provider-aws contributors. 

**Which issue(s) this PR fixes**:

Fixes #5671

### CODE REVIEW

**Review by spiffxp — APPROVED** [review]
/approve
/hold
For lgtm from assignees

**Review by andrewsykim — COMMENTED** [review]
/approve
/lgtm

**Pull request merged**
