### PR TITLE
Update sigs.yaml for wg-policy chair changes

### PR DESCRIPTION
**Pull request by rficcaglia**
wg-policy would like to add 2 new co-chairs

### CODE REVIEW

**Comment by mrbobbytables** [comment]
@rficcaglia they cannot go from non org member to lead. They have to demonstrate ongoing contributions to be added as an org member in the first place. I've reached out in slack to discuss, but closing this for now

/close

**Comment by JimBugwadia** [comment]
@rficcaglia - looks like you need to remove the company name?

`ERROR: wg-policy: emeritus leads should not have company specified; company specified for: Robert Ficcaglia`

**Comment by rficcaglia** [comment]
@JimBugwadia updated per guidance from @mrbobbytables to include generated files

**Review by JimBugwadia — APPROVED** [review]

**Comment by JimBugwadia** [comment]
Hi @mrbobbytables - no problems, yes this is good to merge!

**Pull request merged**
