### PR TITLE
remove initial-resources proposal

### PR DESCRIPTION
**Pull request by wackxu**
initial-resource plugin has been removed in https://github.com/kubernetes/kubernetes/pull/58784.

### CODE REVIEW

**Comment by DirectXMan12** [comment]
Hmm... I not sure what the appropriate process is here?  Do we keep the proposal around and mark as removed, or do we remove the proposal entirely?

**Comment by nikhita** [comment]
> Hmm... I not sure what the appropriate process is here? Do we keep the proposal around and mark as removed, or do we remove the proposal entirely?

@cblecker probably knows?

**Comment by cblecker** [comment]
I'd suggest marking as historical/deprecated as opposed to removing. Makes it easier for those looking it up to know what happened to it (rather than look through git history)

**Pull request closed without merging**
