### PR TITLE
Update sigs.yaml with new sig-aws-leads

### PR DESCRIPTION
**Pull request by d-nishi**
* Delete Bob Wise.
 * Add Nishi Davidson.
 * Update with `make generate`.

### CODE REVIEW

**Comment by cblecker** [comment]
/hold

Hi Nishi! Do you have a public record of how and where this decision was made? I skimmed through the sig-aws mailing list and the recent meeting minutes, and didn't see mention of this transition anywhere there. Thanks!

/cc @justinsb @kris-nova @countspongebob @kubernetes/steering-committee

**Comment by d-nishi** [comment]
@cblecker there was a voting done on SIG-AWS meeting on 8/10/2018 - The evidence is in the zoom recording for that meeting which I do not have access to. I was asked to raise this PR. 
@kris-nova @countspongebob -- can you comment on ways in which this can be confirmed?

**Comment by countspongebob** [comment]
I nominated Nishi verbally and we had a vote conducted by Kris Nova. Kris had host/recording duties, I'll ask her to post it.

**Comment by kris-nova** [comment]
Hey all - at the office today but yes we have a video, with some chat dialogue showing support from the rest of the sig. Also I chatted with @justinsb and he also thinks this is a great move for the sig.

As soon as I get back home to my linux desktop at the house I can grab the video and upload it.

**Comment by cblecker** [comment]
Thanks! Please post it when it's available.

While the governance and transition of leadership of a sig is up to the sig itself, I would encourage sig aws (as I would all sigs) to make major decisions in a transparent, and asynchronous way (typically mailing list, but github issues or otherwise are good to). This is important to keep in mind looking forward as the project is a global project, and we need to ensure we incorporate inputs from those who might not be able to make a specific meeting due to time zones.

So what I see as the path forward:
- The video of the meeting is posted (@kris-nova)
- The minutes of the meeting is updated to reflect that this happened in the meeting (someone from sig-aws)
- As sig-aws doesn't have an approved charter, I'm going to defer to steering for the final sign off that the process sig-aws followed is acceptable, or if they would like more done (like sending out notice to an e-mail list)

That work for everyone?

**Comment by countspongebob** [comment]
The purpose of the PR was to have a public record and generate comment.  As it was my agenda item  I updated the notes.

**Comment by cblecker** [comment]
@countspongebob Should we leave this PR open then for <time frame> in order to give sig-aws a chance to comment?

Also: I'd encourage @d-nishi to look at applying to become a [member](https://git.k8s.io/community/community-membership.md#member). It would make being a sig lead a lot easier :)

**Comment by kris-nova** [comment]
Just wondering what we are gaining as a community by pushing back on this? Seems like overwhelming support from the sig. 

Recording: https://www.youtube.com/watch?v=JTxaMXlZoHg&feature=youtu.be
Chat dialogue with +1's from the sig:

```
09:21:43  From Kraig Amador : +1
09:21:44  From Seth Pollack : +1
09:21:48  From PeterR : +1
09:21:50  From Micah Hausler (AWS) : +1
09:21:51  From Spike Curtis : +1
09:21:52  From Ilya Dmitrichenko : +1
09:21:52  From Nick Turner (EKS) : +1
09:21:57  From Bryce Carman (Amazon EKS) : +1
09:23:06  From Kendall Miller : We enjoy your keyboard
09:23:12  From Kendall Miller : I don’t care what anyone says.
```

Also I kicked off an email to the sig here: https://groups.google.com/forum/#!topic/kubernetes-sig-aws/ZanncL7_h6E

As a side note, I am going to be spending time over the coming months helping get the sig up to speed with the direction that kubernetes governance is expecting. This is a good first step in that direction. So any help here would be appreciated.

**Comment by cblecker** [comment]
@kris-nova To be explicitly clear, there I am not pushing back on the actual change.

The health of the community relies heavily on having fair, open, and transparent governance.. in particular surrounding leadership. That's why there is a strong push for sig charters and the like -- that way procedures and policies around how the project is run are clear.

As sig-aws currently doesn't have a ratified charter that explicitly lays out what the process for selecting a new chair would be, I want to err on the side of being as transparent and explicit as possible.

For example, listening to the recording where this is discussed [[16m10s](https://youtu.be/JTxaMXlZoHg?t=16m10s)] it's noted clearly that @justinsb isn't in attendance. It's been noted here he's in support, but if there was objections, he wouldn't have the opportunity to raise them if the only discussion is whoever happened to be in attendance for the meeting. This also doesn't appear to have been on the agenda in advance of the meeting, so nobody would have known that it was up for discussion.

So again, thank you for uploading and providing that recording. At this point, I will step back and defer to the steering committee to review this and provide guidance.

cc: @kubernetes/steering-committee

**Comment by jbeda** [comment]
Giving this a LGTM and approve from a form point of view.  I'll let @cblecker remove his hold as appropriate.

/lgtm
/approve

**Comment by quinton-hoole** [comment]
LGTM.  Thanks for helping to make this process transparent @cblecker, @kris-nova , @countspongebob , @d-nishi and others.

**Comment by spiffxp** [comment]
I really appreciate @cblecker's input here.  I say this as someone who talked face-to-face for weeks about a SIG Testing Lead addition, but didn't have a written vote, and didn't have any mailing list traffic about it.

>I skimmed through the sig-aws mailing list and the recent meeting minutes, and didn't see mention of this transition anywhere there

>This also doesn't appear to have been on the agenda in advance of the meeting, so nobody would have known that it was up for discussion.

These are bad habits that can look an awful lot like back-channeling even if the best of intentions are behind them.  Let's ensure our charters hold us to a higher standard and avoid legitimizing this behavior.

**Comment by countspongebob** [comment]
The SIG decided to use the PR as the public method for getting feedback, which it clearly accomplished. What back-channeling concern do you have here?

**Comment by derekwaynecarr** [comment]
LGTM

**Comment by quinton-hoole** [comment]
+1 @justinsb .  Any objections to leaving this open until a week has passed since first submission to allow adequate time for people to see it and comment if they want to?

**Comment by countspongebob** [comment]
As I'm having to step back one of the obligations I have as a SIG lead is to nominate a replacement to ensure project continuity.  Trying to take my project obligations seriously here. If the steering committee wants to provide guidance for a time box on PRs for this kind of change that would be welcome, but in defense of our transparency here: Major project changes of all kinds are based on reviewing PRs, with no obligation that I'm aware of to ensure that those PRs are listed in advance in meeting notes.

**Comment by countspongebob** [comment]
@quinton-hoole I'm totally support of leaving this open for a week or even until the next SIG AWS meeting.

**Comment by cblecker** [comment]
/lgtm
/approve

Thanks everyone! All my concerns here are completely addressed. Appreciate the timely review from steering.

@kris-nova @justinsb @countspongebob: Please feel free to `/hold cancel` this when the week comment period is up 👍

@d-nishi: I mentioned this earlier, but I'd also look into applying to become a [member](https://git.k8s.io/community/community-membership.md#member). This will give you the ability to be assigned things (which is important for a sig chair).

**Comment by d-nishi** [comment]
@cblecker -- will follow up this week and close.

**Comment by justinsb** [comment]
We re-ratified this in sig-aws as well on Friday, just to ensure everyone had time to contemplate.  A big outpouring of +1s again.

We've also had a week I reckon, so...

/hold cancel

Welcome @d-nishi 🎉

**Comment by d-nishi** [comment]
Thanks @justinsb @kris-nova @countspongebob and everyone else who helped this through!

**Pull request merged**
