### PR TITLE
Translation to Bengali [bn]

### PR DESCRIPTION
**Pull request by aindrila2412**
**Which issue(s) this PR fixes**:

Fixes #<28426>
Fixes (https://github.com/kubernetes/website/issues/28426)

### CODE REVIEW

**Comment by aindrila2412** [comment]
So what do I have to do now? Can you please guide me in brief @mrbobbytables

**Comment by nikhita** [comment]
@aindrila2412 I'd recommend localizing https://github.com/kubernetes/community/tree/master/contributors/guide/contributor-cheatsheet to Bengali instead.

For this, you will need to create a new file `README-bn.md` in [this](https://github.com/kubernetes/community/tree/master/contributors/guide/contributor-cheatsheet) directory. You can refer to the existing localized docs as examples.

cc @palnabarun -- for Bengali review

**Comment by nikhita** [comment]
@aindrila2412 Closing this PR. Please create a new PR if you want to localize https://github.com/kubernetes/community/tree/master/contributors/guide/contributor-cheatsheet to Bengali. Thanks for the current efforts though :)

**Pull request closed without merging**
