### PR TITLE
New PR for an already assigned issues

### PR DESCRIPTION
**Pull request by spzala**
Clarify when to create a PR to address an issue when the issue is already assigned to someone else.

### CODE REVIEW

**Comment by spzala** [comment]
@mrbobbytables @idvoretskyi created this PR per our discussion in the last contrib-ex sig meeting. Thanks!

**Review by idvoretskyi — APPROVED** [review]
/lgtm 

/hold

**Comment by idvoretskyi** [comment]
+1, this makes sense @spzala 

I'll let @mrbobbytables or other folks to comment and cancel hold.

**Comment by spzala** [comment]
> +1, this makes sense @spzala
> 
> I'll let @mrbobbytables or other folks to comment and cancel hold.

@idvoretskyi thanks, sounds great!

**Review by guineveresaenger — APPROVED** [review]
Thank you for this change!

/approve

**Comment by guineveresaenger** [comment]
It's been a week.

/hold cancel

**Comment by spzala** [comment]
Thanks @guineveresaenger

**Pull request merged**
