### PR TITLE
Update channels.yaml

### PR DESCRIPTION
**Pull request by stephenatwell**
Added ‘Armory k8s’ slack channel for our users to discuss issues around advanced deployments to Kubernetes. Armory is a commercial Open Source company originally built around OSS Spinnaker. Our newest deployment offering is a Kubernetes-specific deployment service, which is why we would like to get a slack channel on the Kubernetes.io slack server as well.

Purpose:
For discussion about advanced deployments to all forms of Kubernetes using Armory Continuous Deployment

Links to Armory's products for Kubernetes:
https://www.armory.io/products/scale-agent-for-spinnaker-kubernetes/ (Based on OSS Spinnaker, extends it's ability to scale to large numbers of Kubernetes clusters)
https://www.armory.io/products/continuous-deployment-self-hosted/ (Based on OSS Spinnaker, supports Kubernetes + additional targets))
https://www.armory.io/products/continuous-deployment-as-a-service/ (not based on Spinnaker, only deploys to Kubernetes)

### CODE REVIEW

**Comment by markyjackson-taulia** [comment]
Going to need to fix the cla @stephenatwell

Also I am not sure the Kubernetes slack is the most appropriate place for this type of a channel but let's let some of the other slack admins add their comments.

/hold
/ok-to-test

**Comment by markyjackson-taulia** [comment]
I also feel this is more appropriate for the spinnaker slack under the # Kubernetes channel rather than this slack

**Comment by markyjackson-taulia** [comment]
You can also use the CDF slack server as well

**Comment by mrbobbytables** [comment]
I generally agree with @markyjackson-taulia that the CDF slack is likely a better home if they support that sort of channel. If it is to stay here, the ug prefix should be removed, those are used to indicate K8s user groups.

**Comment by markyjackson-taulia** [comment]
I verified there is a Kubernetes channel within the CDF slack. @stephenatwell would just need to reach out to the CDF moderators if you wanted to create another channel

**Pull request closed without merging**
