### PR TITLE
sig-cluster-lifecycle: move kubeadm office hours to biweekly

### PR DESCRIPTION
**Pull request by neolit123**
The change was announced in:
https://groups.google.com/forum/#!topic/kubernetes-sig-cluster-lifecycle/M84pthzo5tA

the community calendar was already updated.

/sig cluster-lifecycle
/kind cleanup
/priority important-longterm

### CODE REVIEW

**Comment by mrbobbytables** [comment]
oh derp, I missed it didn't touch the docs.
can you run make and push again?

**Comment by neolit123** [comment]
forgot to run "make", updated.

**Pull request merged**
