### PR TITLE
Add slack-infra subproject to sig-contribex

### PR DESCRIPTION
**Pull request by nikhita**
Ref: https://github.com/kubernetes/org/issues/663

/cc @Katharine @jeefy

### CODE REVIEW

**Comment by parispittman** [comment]
should it live in the communications subproject because the guidelines are there?

**Comment by mrbobbytables** [comment]
As it's going to be code and tool development It'd probably be best as a separate repo.

**Comment by BenTheElder** [comment]
Gentle ping.

**Comment by jeefy** [comment]
The tooling should exist in a separate repo, while the configuration that the tooling runs should live within k/community.

How said configs are housed can be discussed, but it feels right to separate the code-repo from the config. 

/lgtm

**Comment by nikhita** [comment]
> How said configs are housed can be discussed, but it feels right to separate the code-repo from the config.

IMO having a new subproject also allows us to "bundle" the config under it with the code, so a new subproject sgtm.

**Comment by cblecker** [comment]
+1 from me to new subproject too. This will allow it to be more easily handed off to a separate sig/group at a later date if need be.

/cc @parispittman @Phillels 
Per our charter, we should have sign off from all chairs + TLs.

**Pull request merged**
