### PR TITLE
Update the vendor selection date in the 2021 External Audit RFP 

### PR DESCRIPTION
**Pull request by reylejano**
This PR updates the vendor selection date in the 2021 external audit RFP to <strike>7/23/2021</strike> 8/10/2021 for sufficient time to review

/sig security

### CODE REVIEW

**Comment by dims** [comment]
ooh exciting :)

**Comment by raesene** [comment]
LGTM :)

**Comment by reylejano** [comment]
After an ad hoc discussion with members of the Kubernetes SIG Security External Audit subproject, updated PR to extend the vendor selection date to 8/10/2021

**Comment by tabbysable** [comment]
Given that we've already said that project timelines would be determined by mutual consent between the subproject and the vendor, take your time and do a good job.
/lgtm
/approve

**Pull request merged**
