### PR TITLE
Update CLA.md

### PR DESCRIPTION
**Pull request by mack1024**
**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Comment by jberkus** [comment]
@mack1024 

Can you explain what you're trying to accomplish with this PR, please?  It appears that you added one line of whitespace.  Was that your intention?  

/hold

**Comment by kalyan-vurugonda** [comment]
Hi @jberkus, I want to make a PR regarding CLA. How do i do it

**Comment by mrbobbytables** [comment]
/close
Please reopen or open a new PR with the intended change.

**Comment by jberkus** [comment]
@kalyan-vurugonda I don't understand; is @mack1024 your account as well?

**Pull request closed without merging**
