### PR TITLE
Add cluster api cloud director slack channel

### PR DESCRIPTION
**Pull request by Anirudh9794**
Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

The purpose of the PR is to create a slack channel for the project https://github.com/vmware/cluster-api-provider-cloud-director
 - The project implements cluster-api (https://github.com/kubernetes-sigs/cluster-api) for VMWare cloud director platform.

**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Comment by markyjackson-taulia** [comment]
@Anirudh9794 thank you for you pr. A question:
* where has community conversation been taking place?

**Comment by markyjackson-taulia** [comment]
Holding for now
/hold

**Comment by arunmk** [comment]
I can answer this question @markyjackson-taulia since I am also a contributor to https://github.com/vmware/cluster-api-provider-cloud-director

We are engaging with the community using the following modes:
1. Direct github tickets
2. The cluster-api channel itself (much lesser)
3. 1:1 conversations with the people who asked the questions in the cluster-api channel. Once the question-askers discovered that we were the ones behind the code, they pinged us directly on slack.

We also have a biweekly 1:1 with a partner who is also contributing to the project.

**Comment by Anirudh9794** [comment]
@markyjackson-taulia Please let us know if there is any other information that is needed from us.

**Comment by markyjackson-taulia** [comment]
@Anirudh9794 Thank you. Please allow up to two weeks for review.

**Comment by Anirudh9794** [comment]
Hello @markyjackson-taulia,
I wanted to follow up on the review for the PR.

**Review by markyjackson-taulia — APPROVED** [review]
Adding LGTM label and holding for one more slack administrator to review.
/lgtm
/hold

**Pull request merged**
