### PR TITLE
Update Cluster API Provider AWS meeting notes for 2021

### PR DESCRIPTION
**Pull request by randomvariable**
New document moved to non-corporate Google account

Signed-off-by: Naadir Jeewa <jeewan@vmware.com>

**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Comment by randomvariable** [comment]
/assign @fabriziopandini 

Could someone update the calendar invite's doc URL to https://docs.google.com/document/d/1iW-kqcX-IhzVGFrRKTSPGBPOc-0aUvygOVoJ5ETfEZU/edit#heading=h.3447ulwu7j9j  ?

**Comment by neolit123** [comment]
/lgtm
/approve

> Could someone update the calendar invite's doc URL to https://docs.google.com/document/d/1iW-kqcX-IhzVGFrRKTSPGBPOc-0aUvygOVoJ5ETfEZU/edit#heading=h.3447ulwu7j9j ?

done

**Review by nikhita — APPROVED** [review]
Thanks @randomvariable!

/approve

**Comment by tantsteven** [comment]
Go Module sigs.k8s.io/cluster-api-[provider](https://petdogsworld.com/)-aws Latest version v0.6.4. February 4th 2021 Note: These AMIs are not updated for security fixes and it is recommended to always use the latest patch version for  13:00 (Eastern) / 18:00 (Europe/London), and are published on the Kubernetes community meetings calendar.

**Pull request merged**
