### PR TITLE
Move NCW under Mentoring subproject

### PR DESCRIPTION
**Pull request by jeefy**
Hey y'all, 

tl;dr: This moves the NCW handbook / info under the Mentoring subproject folder. 

I did an initial scrub of the docs looking for any Kubecon/Summit-specific references and updated accordingly. Also I've reached out to previous NCW event-runners and populated the OWNERS file with authorities on it. :) 

/assign @markyjackson-taulia @parispittman @nikhita 
/cc @alisondy @guineveresaenger @jberkhahn @tpepper

### CODE REVIEW

**Comment by jberkhahn** [comment]
I think you meant to tag @jberkus instead of me?

**Comment by jeefy** [comment]
Blasted auto-complete, yes. Sorry about that @jberkhahn 

/uncc @jberkhahn 
/cc @jberkus

**Comment by parispittman** [comment]
lgtm from a subproject owner; want @nikhita to weigh in with final approval from a subproject owner and tech lead perspective.

**Comment by jberkus** [comment]
wait, are we waiting for @nikhita to approve this, or for more NCW folks?  I'm confused.

**Comment by parispittman** [comment]
@jberkus i thought this has been shopped around the ncw folks already? re: jeffs comment about owners

**Comment by jberkus** [comment]
AFAIK, yes.  I just wanted to make sure I didn't need to approve anything.

**Comment by nikhita** [comment]
Sorry for the delay! Lgtm from my side.
/approve

/hold
Not sure if you wanted more eyes on the PR, but feel free to cancel the hold otherwise. :+1:

**Comment by tpepper** [comment]
A minor nit, but:  In the old location if somebody came upon the directory browsing GitHub or a markdown file with an url in it and they saw the string "new-contributor-workshop" they'd probably be able to intuit what they're looking at.  In the new location named "ncw" that wont be the case.  Is that worth the savings in typing for those of us who occasionally type one of these urls?  I'd personally go with less jargon.

**Comment by jeefy** [comment]
@tpepper Good catch, strongly agree, and pushed an update. :)

**Comment by markyjackson-taulia** [comment]
@mrbobbytables Is it okay to remove the hold on this

cc @jeefy @parispittman

**Comment by mrbobbytables** [comment]
I believe so, all feedback has been addressed \o/
/lgtm
/hold cancel

**Pull request merged**
