### PR TITLE
communication: add mrbobbytables and jeefy as reviewers

### PR DESCRIPTION
**Pull request by nikhita**
Both @mrbobbytables and @jeefy have been involved in moderation and authoring/reviewing guidelines for our communication mediums.

/cc @mrbobbytables @jeefy 
can you leave lgtms here just to confirm that you are ok with this? :)

/assign @parispittman

### CODE REVIEW

**Comment by mrbobbytables** [comment]
/lgtm

Thanks @nikhita :D

**Comment by jeefy** [comment]
/lgtm

Happy to help anywhere I can. Thanks @nikhita!!

**Comment by parispittman** [comment]
of course!!! 🎊  I'm so happy to have you both here

/hold cancel 
/lgtm
/approve

**Pull request merged**
