### PR TITLE
sig-release: Fix biweekly meeting times

### LINKED ISSUE #6436: Update meeting schedule in sig-release/README.md
### Describe the issue

The biweekly meeting time referred to in https://github.com/kubernetes/community/tree/master/sig-release#readme is incorrect.
The meetings are scheduled at 15:30 UTC, not at 14:30 UTC.

/assign me

### PR DESCRIPTION
**Pull request by dishantsethi**
Change sig-release biweekly meeting time from 14:30 UTC to 15:30 UTC in sig-release/README.md

**Which issue(s) this PR fixes**:

Fixes #6436

### CODE REVIEW

**Comment by saschagrunert** [comment]
@dishantsethi thank you for this PR! May I ask you to sign the CLA?

**Review by mrbobbytables — CHANGES_REQUESTED** [review]
Thanks for updating, but meeting changes need to made in sigs.yaml and then you run `make` which will populate it in every location that's needed^^;;;

**Comment by dishantsethi** [comment]
Hi, @mrbobbytables I have updated the changes in sigs.yaml as well.

**Comment by dishantsethi** [comment]
@saschagrunert Needs approved and lgtm labels

**Review by justaugustus — APPROVED** [review]
Thanks @dishantsethi (and congrats on your first PR)! 🎉 
/retitle sig-release: Fix biweekly meeting times

**Pull request merged**
