### PR TITLE
Add spell checking script to the community verify job

### PR DESCRIPTION
**Pull request by cblecker**
Adds a spell checking script that will run in the pull-community-verify presubmit job.

Shoutout to @dixudx who did the heavy lifting on this for k/k

### CODE REVIEW

**Comment by cblecker** [comment]
Note that https://github.com/kubernetes/community/pull/1888 with spelling fixes needs to merge first :)

**Comment by liggitt** [comment]
> hack/verify-generateded-docs.sh

oh, the irony

**Comment by cblecker** [comment]
*facepalm*

**Comment by spzala** [comment]
+100 Super @cblecker @dixudx

**Pull request merged**
