### PR TITLE
#3469: Removing arbitrarily mention of GKE versioning

### PR DESCRIPTION
**Pull request by kaushikchaubal**
Fixes https://github.com/kubernetes/community/issues/3469

### CODE REVIEW

**Comment by kaushikchaubal** [comment]
I signed it

**Comment by justaugustus** [comment]
If I'm pedantic, we shouldn't reference this outdated design proposal at all, but yes, thank you for removing the GKE reference.
I'll take an action item to move our release policy out of the design proposal and blockade this directory for future.

/lgtm
/approve

**Comment by justaugustus** [comment]
And thank you for your first PR to Kubernetes, @kaushikchaubal! :)

**Pull request merged**
