### PR TITLE
Add Jordan Liggitt bio

### PR DESCRIPTION
**Pull request by liggitt**

### CODE REVIEW

**Comment by jdumars** [comment]
lest more rebases, we can add to index after all the other candidate PRs are merged
/approve
/hold
unhold after election officer review

**Review by idvoretskyi — APPROVED** [review]
/lgtm

**Review by tpepper — COMMENTED** [review]
/lgtm

**Comment by tpepper** [comment]
/unhold
after discussion with Jaice/Josh/Ihor.  Will merge and fixup index after.

**Comment by jdumars** [comment]
thanks for your help Tim!

**Pull request merged**
