### PR TITLE
Add Event style guide for Events v2

### PR DESCRIPTION
**Pull request by gmarek**
I got reminded by @bgrant0607 that I forgot to put this into markdown. I'm fixing this omission now.

cc @timothysc @smarterclayton @bgrant0607 @kubernetes/sig-instrumentation-misc

### CODE REVIEW

**Comment by bgrant0607** [comment]
Thanks, @gmarek.

I assume this matches the doc: https://docs.google.com/document/d/1e7RJ9kdxZfaUSuepO-idmuEY8Ee6uOojGHk4YhbfzRc/edit

/lgtm
/approve

**Comment by bgrant0607** [comment]
@cblecker Could you please approve?

**Comment by cblecker** [comment]
/approve
How did we miss you in the top level approvers file? I'm very confused.

**Comment by gmarek** [comment]
@bgrant0607 - yup. It's a copy-paste from it, modulo markdown comments.

**Pull request merged**
