### PR TITLE
Add sig-network-policy-api slack channel

### PR DESCRIPTION
**Pull request by rikatz**
Signed-off-by: Ricardo Pchevuzinske Katz <ricardo.katz@gmail.com>

Adds the sig-network-policy-api slack channel for the sig-network network policy evolution subproject.

### CODE REVIEW

**Comment by coderanger** [comment]
Leaving this for the sig-network-leads to confirm.

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Pull request merged**
