### PR TITLE
Add new Slack channel for Koordinator

### LINKED ISSUE #6954: REQUEST: New Slack channel #koordinator
### GitHub Username

@FillZpp

### Slack Username

@FillZpp

### What Type of Request is it (Channel, User Group, Bot, Token, or Webhook)?

Channel

### Name of Requested Resource

#koordinator

### Description of Request

Koordinator is a QoS based scheduling system for hybrid orchestration workloads on Kubernetes.
Website: https://koordinator.sh/

This channel would be a place for the community discussion, release announcements and so on. Thanks!

### PR DESCRIPTION
**Pull request by FillZpp**
Add new Slack channel for Koordinator, which is a QoS based scheduling system for hybrid orchestration workloads on Kubernetes.

- Website: https://koordinator.sh/
- Github: https://github.com/koordinator-sh/koordinator

This channel would be a place for the community discussion, release announcements and so on. Thanks!

Fixes #6954

### CODE REVIEW

**Comment by FillZpp** [comment]
friendly ping @castrojo @coderanger , anyone could help on this?

**Comment by castrojo** [comment]
/lgtm

(Apologies for my late review, I was on the road)

**Pull request merged**
