### PR TITLE
Update Outreachy program deadline and link

### PR DESCRIPTION
**Pull request by xiangpengzhao**
Ref: #1227

cc @sarahsharp @sarahnovotny @castrojo @cblecker

### CODE REVIEW

**Comment by nikhita** [comment]
cc @parispittman

**Comment by nikhita** [comment]
@xiangpengzhao I had created https://github.com/kubernetes/community/pull/1231 but closed it since it's almost a dupe of this.

There are a few other changes I made there, could you update it here in this PR? Thanks!

**Comment by xiangpengzhao** [comment]
@nikhita updated with your changes. PTAL. Thanks!

**Comment by nikhita** [comment]
@xiangpengzhao LGTM but I'll let someone else give the final `/lgtm`.

**Comment by pwittrock** [comment]
Thanks!

**Pull request merged**
