### PR TITLE
idvoretskyi company affiliation updated

### PR DESCRIPTION
**Pull request by idvoretskyi**
Having joined CNCF as a [Developer Advocate](https://www.cncf.io/blog/2017/09/18/meet-cncfs-newest-developer-advocate/), updating the affiliation mentions.

### CODE REVIEW

**Comment by stp-ip** [comment]
LGTM

**Comment by xiangpengzhao** [comment]
Congratulations, Ihor!

Kindly reminder: you need to modify https://github.com/kubernetes/community/blob/master/sigs.yaml and then run `make` to update other sig related docs :)

**Comment by xiangpengzhao** [comment]
sigs.yaml was fixed by @cblecker in #1096 :)

**Pull request merged**
