### PR TITLE
Added steps for Windows users for the setup.

### PR DESCRIPTION
**Pull request by NikhilSharmaWe**
**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/community/issues/6026

### CODE REVIEW

**Comment by Debanitrkl** [comment]
@NikhilSharmaWe could you please mention the issue this PR is fixing or if there is no issue to which this PR is related then please mention N/A against ` Fixes`

> **Which issue(s) this PR fixes**:
> 
> Fixes #6028

**Comment by NikhilSharmaWe** [comment]
It is mentioned that this PR is for issue #6028 "It should be mentioned for Windows Users to build tools inside WSL environment to run make test", I opened this issue.

**Comment by Debanitrkl** [comment]
I guess you didn't get what I was talking about, see this #6028 is a PR it's not an [issue](https://github.com/kubernetes/community/blob/master/contributors/guide/first-contribution.md#file-an-issue). Since it's your first contribution it's better to go through [this](https://github.com/kubernetes/community/blob/master/contributors/guide/contributor-cheatsheet/README.md#opening-and-responding-to-issues) to have a clear understanding.

**Comment by NikhilSharmaWe** [comment]
Sorry, deleted the branch by mistake, made a new PR.

**Pull request closed without merging**
