### PR TITLE
Update archive_url (google doc) and mailing list for wg-etcd-operator

### PR DESCRIPTION
**Pull request by ahrtr**
Since the https://github.com/kubernetes/community/issues/7937 hasn't been resolved for a long time, so we decided to create a temporary (we can use it as permanent doc if there is no objection) google doc. 

@hakman @jberkus @jmhbnz @justinsb @neolit123

### CODE REVIEW

**Comment by Priyankasaggu11929** [comment]
@ahrtr, I've just lgtm/approved PR https://github.com/kubernetes/k8s.io/pull/7125#issuecomment-2271339854

Once merged, that should unblock https://github.com/kubernetes/community/issues/7937

**Comment by ahrtr** [comment]
> @ahrtr, I've just lgtm/approved PR [kubernetes/k8s.io#7125 (comment)](https://github.com/kubernetes/k8s.io/pull/7125#issuecomment-2271339854)
> 
> Once merged, that should unblock #7937

OK, thanks. Once https://github.com/kubernetes/community/issues/7937 is resolved, I will update this PR.

**Comment by Priyankasaggu11929** [comment]
`wg-etcd-operator` DLs are created.

I'm able to access - https://groups.google.com/a/kubernetes.io/g/wg-etcd-operator

**Comment by ahrtr** [comment]
> https://groups.google.com/a/kubernetes.io/g/wg-etcd-operator

YES, thanks. How can we create a google doc for wg etcd-operator?

**Comment by Priyankasaggu11929** [comment]
I've pinged Bob offline to help with google doc/directory access. Will update.

**Comment by ahrtr** [comment]
The new google doc has been created under the "wg etcd operator", and also updated this PR.

This PR should be ready to be merged now. PTAL @hakman @jberkus @jmhbnz @justinsb @neolit123 @Priyankasaggu11929

**Comment by Priyankasaggu11929** [comment]
/lgtm
/approve

/hold
for any further reviews.

**Review by jmhbnz — APPROVED** [review]
/lgtm
/approve
/unhold

**Pull request merged**
