### PR TITLE
Update NCW Resources, Files

### PR DESCRIPTION
**Pull request by alisondy**
- Added the Content Proposal and Runbook
- Reorganizing of files

### CODE REVIEW

**Comment by tpepper** [comment]
I want to honor the work that has happened across the team's member, but wonder if it might make more sense to PR just a small note that the contrib summit and NCW did not happen in April 2020 due to COVID, and then shift to more updating the detailed content toward merge for the next planned event?  I can also see merging the current stuff as a record of decisions made.

/shrug

What do others think?

**Comment by jeefy** [comment]
@tpepper Strongly agree.

I like the idea of updating the EU2020 event folder with the fact that we've canceled, why, and the state of NCW (linking to this material) That shouldn't block this going in I don't think? This does look lgtm and I think proper attribution to the former EU team should go in that folder. Feel free to keep the hold or lgtm-cancel if I'm off my rocker. :) 

/lgtm
/hold

**Comment by tpepper** [comment]
I'm fine with these being separately handled.

/lgtm

**Pull request merged**
