### PR TITLE
Add Stefan as tech lead for sig-api-machinery

### PR DESCRIPTION
**Pull request by deads2k**
Stefan has spent eight years working in kubernetes, the majority of those in the apimachinery area developing key infrastructure like CRDs and the less glamorous code like code generators.  His knowledge of the apiserver internals, type system, schemes, generators, clients, controller libraries, binary helper libraries, and all aspects of the apimachinery stack are very deep.

/assign @jpbetz @fedebongio @sttts

### CODE REVIEW

**Comment by fedebongio** [comment]
/lgtm
(add a lot of happiness to this approval)

**Comment by jpbetz** [comment]
/lgtm
/approve
Congrats and thanks @sttts !

**Comment by aojea** [comment]
+100

**Comment by mrbobbytables** [comment]
> > @deads2k The specific change you're making needs to happen in sigs.yaml, and then a `make` will regenerate the docs. Additionally, here's the checklist of things that need to happen for a leads change (including consensus period): https://git.k8s.io/community/contributors/chairs-and-techleads/leadership-changes.md
> 
> Thanks. We'll work our way through the list.

We actually made it into a issue template that has a bit more of the enumerated details 👍 
https://github.com/kubernetes/community/issues/new?assignees=&labels=&projects=&template=leadership-change.yml&title=%3CSIG%2FWG+FOO%3E%3A+Leadership+Change

**Comment by deads2k** [comment]
> We actually made it into a issue template that has a bit more of the enumerated details 👍
> https://github.com/kubernetes/community/issues/new?assignees=&labels=&projects=&template=leadership-change.yml&title=%3CSIG%2FWG+FOO%3E%3A+Leadership+Change

That checklist is extremely helpful.  The discussion has met its lazy consensus and our other PRs have started merging.  Can we get this approved?

**Pull request merged**
