### PR TITLE
added vector grapics icons from the Learn Kubernetes Basics tutorial.…

### PR DESCRIPTION
**Pull request by muemich**
The vector graphics from the Learn Kubernetes Basic Tutorial are missing and I saw people on Twitter looking for it. I thought this is the most appropriate place to put them, let me know if this is the wrong place.

### CODE REVIEW

**Comment by spiffxp** [comment]
Need context: which tutorial is this (link)? Is it something the project owns? Do we have the copyright to these assets?

**Comment by muemich** [comment]
It is from [https://kubernetes.io/docs/tutorials/kubernetes-basics/](url) I do believe the project owns the tutorial and we created it back then. It was either coming from Google or the CNCF, so the copyrights are part of this.

**Comment by spiffxp** [comment]
Thanks, that helped clarify things

/assign @kbhawkey @onlydole @sftim 

I think this is your call as sig-docs TLs. Do these belong here or someplace in k/website?

**Comment by sftim** [comment]
SIG Docs tech lead here.
I'd expect to see these SVG documents having a home inside [k/website](https://github.com/kubernetes/website).

@muemich we'd be happy to have those documents there. If you've got time please feel free to open a pull request there to update the tutorials or add them as static content. If not please comment and we can look for another approach.

**Comment by sftim** [comment]
I've taken advantage of the copyright grant to the CNCF and have already made a copy of the images in this pull request. That means @muemich that in a strong sense, your work is done. We have (well, I have) a copy.

**Comment by spiffxp** [comment]
@sftim can you link the PR and /close this issue?

**Comment by muemich** [comment]
Good that this is sorted

**Pull request closed without merging**
