### PR TITLE
sig-release: Caleb moves to Emeritus

### PR DESCRIPTION
**Pull request by justaugustus**
Discussed w/ Caleb and Tim earlier.
Caleb -- Thank you immensely for all of your work in SIG Release across the years!

Signed-off-by: Stephen Augustus <saugustus@vmware.com>

/assign @calebamiles @tpepper @alejandrox1 @saschagrunert 
/hold for SIG Release leadership approval
cc: @kubernetes/sig-release

### CODE REVIEW

**Comment by dims** [comment]
Thanks a ton @calebamiles !!!

**Comment by BenTheElder** [comment]
thanks for everything caleb :-)

**Comment by tpepper** [comment]
/lgtm
/approve
Thanks for all you've done over many years @calebamiles !

**Comment by justaugustus** [comment]
Tim, Sascha, and Jorge have approved, so I'm lifting the hold.
/hold cancel

**Pull request merged**
