### PR TITLE
Promote those who are chopping wood and carrying water.

### PR DESCRIPTION
**Pull request by timothysc**
Within SCL, we want to recognize those who have been doing a lot of good work in the community.  

- @neolit123 has already been doing a lot of the work of a chair.  release notes, organization, and leading by example.  

- @fabriziopandini has helped out across a number of different efforts and has proven his depth of understanding and impact across SCL's sub-projects (kubeadm, cluster API, component config). 

These changes are a recognition of their efforts, and are still pending on confirmation from the community. 

/assign @justinsb 
/cc @kubernetes/sig-cluster-lifecycle-pr-reviews 
/hold
/lgtm

### CODE REVIEW

**Comment by timothysc** [comment]
xref - #4289

**Comment by neolit123** [comment]
thanks @timothysc , i will try to help with the new responsibilities.

**Comment by fabriziopandini** [comment]
thanks @timothysc! 
it is a pleasure to serve in this sig, and I'm more than happy to step up on new responsibilities

**Comment by justinsb** [comment]
Thank you @neolit123 and @fabriziopandini for all your hard work!  I'm sorry that we reward you with more work ;-)

/lgtm

**Comment by guineveresaenger** [comment]
thank you everyone, for your past and future service!

❤️

**Comment by timothysc** [comment]
Per SCL meeting on 20191217 we will merge by EOW based on lazy consensus.

**Comment by yagonobre** [comment]
Thanks for all the hard work! 🎉

**Comment by timothysc** [comment]
I have had only positive affirmations, so unholding.  
/hold cancel

**Pull request merged**
