### PR TITLE
Add self to sig-instrumentation maintainers

### PR DESCRIPTION
**Pull request by richabanker**
Issue: https://github.com/kubernetes/community/issues/8149

### CODE REVIEW

**Review by logicalhan — APPROVED** [review]
/lgtm
/approve

**Comment by cblecker** [comment]
Hello @richabanker!

Is there a link to the email to the dev@ list where consensus on this was achieved? I also don't see a leadership change issue related to this. I'd suggest opening one up (https://github.com/kubernetes/community/issues/new/choose) as it has a whole checklist of things you need, and can help you step through the process of changing a SIG leadership position.

/hold

**Comment by richabanker** [comment]
@cblecker [here's](https://groups.google.com/g/kubernetes-sig-instrumentation/c/r8d3UyHGszU) the link to the email thread. We opened https://github.com/kubernetes/community/issues/8149, I'll start going through the list now.

**Comment by cblecker** [comment]
@richabanker It looks like that thread went out to the sig instrumentation list, but not the main dev@ list (which is one of the requirements). 

Thank you opening that issue! If you have questions as you run through the list, please feel free to reach out to either SIG ContribEx or the Steering Committee for assistance.

**Comment by richabanker** [comment]
@cblecker The email was now forwarded to the dev@ list, [link](https://groups.google.com/a/kubernetes.io/g/dev/c/UMZ6c_gBtzc/m/LD0TEqsmBgAJ), does that suffice for this PR to be merged?

**Comment by BenTheElder** [comment]
I think the intention is to have at least a week for any comments after sending it out to everyone? Probably best to give it a few days to clearly achieve that.

While we're waiting for that decision, can you set the new email field on your entry? Thanks!

**Comment by richabanker** [comment]
> I think the intention is to have at least a week for any comments after sending it out to everyone? Probably best to give it a few days to clearly achieve that.


Ah that makes sense, thanks!
Also, added my email now.

**Comment by richabanker** [comment]
@cblecker are we ok to merge this now?

**Comment by BenTheElder** [comment]
https://groups.google.com/a/kubernetes.io/g/dev/c/UMZ6c_gBtzc/m/LD0TEqsmBgAJ was forwarded to dev@kubernetes.io november 18th, 2.5 weeks ago.


/lgtm
/approve
/hold

**Comment by richabanker** [comment]
@BenTheElder are we good to unhold this now?

**Pull request merged**
