### PR TITLE
Make resource management working group discoverable

### PR DESCRIPTION
**Pull request by vishh**
cc @derekwaynecarr @bgrant0607

### CODE REVIEW

**Comment by vishh** [comment]
@sarahnovotny we need a mailing list and possibly a slack channel for the RM workgroup.

**Comment by derekwaynecarr** [comment]
Should you list sig-node as slack channel for now?

**Comment by derekwaynecarr** [comment]
Looks like we may need to make other changes.

https://github.com/kubernetes/community/tree/master/generator

**Comment by vishh** [comment]
@derekwaynecarr PTAL

**Comment by sarahnovotny** [comment]
LGTM.

**Pull request merged**
