### PR TITLE
sig-cl: resolve some warnings with the maintainers tool + governance updates

### PR DESCRIPTION
**Pull request by neolit123**
list of commits:
```
sig-cl: update CONTRIBUTING.md

- Fix malformed link
- Include link to VODs
```

```
sig-cl: remove the kubespray Zoom meeting

As discussed with the kubespray maintainers:
https://kubernetes.slack.com/archives/C2V9WJSJD/p1643716538243509[](https://github.com/neolit123)

Their Zoom meeting is no longer active.
The maintainers expressed that Slack is sufficient for them
and we should remove the meeting from the calendar for the time being.

Remove the meeting from sigs.yaml
It was also removed from the SIG CL calendar.
```

```
sig-cl: resolve some warnings with the maintainers tool

- Remove kube-up as a subproject. The tool correctly discovers that
we do not have OWNERS under k/k/cluster.
- Add mailing list / slack / description to projects that did not
have it.
- Rename kops -> kOps to match the project rename that happened
some time ago.
- Add more OWNERS URLs in the kubeadm subproject section. These are
not kubeadm specific repositories, but kubeadm is the best
fit given the top level SIG struct does not have OWNERS.
```

-------

list of ERRORS from the [maintainers tool](https://github.com/dims/maintainers):
- first two will be resolved with fixes in the repositories:
https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3104
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1122
- third one is unknown

```
~/go/bin/maintainers --kubernetes-directory=/home/lubo/go/src/k8s.io/kubernetes audit sig-cluster-lifecycle | grep ERROR
ERROR: unable to parse owners file at https://raw.githubusercontent.com/kubernetes-sigs/cluster-api-provider-aws/master/OWNERS url - error unmarshaling JSON: while decoding JSON: json: unknown field "emeritus_maintainers"
ERROR: unable to parse owners file at https://raw.githubusercontent.com/kubernetes-sigs/cluster-api-provider-openstack/master/OWNERS url - error unmarshaling JSON: while decoding JSON: json: unknown field "emeritus_maintainers"
ERROR: unable to read file /home/lubo/go/src/k8s.io/kubernetes/_output/local/go/pkg/mod/k8s.io/kube-openapi@v0.0.0-20210421082810-95288971da7e/OWNERS - error unmarshaling JSON: while decoding JSON: json: unknown field "emritus_approvers"
```

list of warnings BEFORE this change:

<details>
```
WARNING: missing 'description' key
WARNING: missing 'mailing_list' in contact
WARNING: missing 'description' key
WARNING: missing 'mailing_list' in contact
WARNING: missing 'description' key
WARNING: missing 'contact' key
WARNING: missing 'description' key
WARNING: missing 'contact' key
WARNING: missing 'description' key
WARNING: missing 'contact' key
WARNING: missing 'description' key
WARNING: missing 'contact' key
WARNING: missing 'meetings' key
WARNING: missing 'description' key
WARNING: missing 'contact' key
WARNING: missing 'meetings' key
WARNING: missing 'description' key
WARNING: missing 'contact' key
WARNING: missing 'meetings' key
WARNING: missing 'description' key
WARNING: missing 'contact' key
WARNING: missing 'description' key
WARNING: missing 'contact' key
WARNING: missing 'description' key
WARNING: missing 'contact' key
WARNING: missing 'meetings' key
WARNING: missing 'description' key
WARNING: missing 'contact' key
WARNING: missing 'meetings' key
WARNING: missing 'description' key
WARNING: missing 'mailing_list' in contact
WARNING: missing 'description' key
WARNING: missing 'mailing_list' in contact
WARNING: missing 'description' key
WARNING: missing 'mailing_list' in contact
WARNING: missing 'description' key
WARNING: missing 'contact' key
WARNING: missing 'description' key
WARNING: missing 'contact' key
WARNING: needs labels reflecting sig-cluster-lifecycle - https://raw.githubusercontent.com/kubernetes/kubernetes/master/cluster/OWNERS
WARNING: needs an alias as approver/reviewer reflecting sig-cluster-lifecycle - https://raw.githubusercontent.com/kubernetes/kubernetes/master/cluster/OWNERS
WARNING: missing 'meetings' key
WARNING: missing 'description' key
WARNING: missing 'mailing_list' in contact
WARNING: needs an alias as approver/reviewer reflecting sig-cluster-lifecycle - https://raw.githubusercontent.com/kubernetes/kubernetes/master/cmd/kubeadm/OWNERS
WARNING: missing 'description' key
WARNING: missing 'mailing_list' in contact
WARNING: missing 'description' key
WARNING: missing 'mailing_list' in contact
WARNING: file staging/src/k8s.io/cluster-bootstrap/OWNERS should be in one of ["sig-cluster-lifecycle"] based on labels/aliases
WARNING: file staging/src/k8s.io/component-base/configz/OWNERS should be in one of ["sig-cluster-lifecycle"] based on labels/aliases
WARNING: file staging/src/k8s.io/component-base/featuregate/OWNERS should be in one of ["sig-api-machinery" "sig-cluster-lifecycle"] based on labels/aliases
WARNING: file test/e2e/lifecycle/OWNERS should be in one of ["sig-cluster-lifecycle"] based on labels/aliases
WARNING: file test/e2e_kubeadm/OWNERS should be in one of ["sig-cluster-lifecycle"] based on labels/aliases
```

</details>

list of WARNINGS after this change:

```
WARNING: needs an alias as approver/reviewer reflecting sig-cluster-lifecycle - https://raw.githubusercontent.com/kubernetes/kubernetes/master/cmd/kubeadm/OWNERS
WARNING: needs an alias as approver/reviewer reflecting sig-cluster-lifecycle - https://raw.githubusercontent.com/kubernetes/kubernetes/master/test/e2e/lifecycle/OWNERS
WARNING: needs an alias as approver/reviewer reflecting sig-cluster-lifecycle - https://raw.githubusercontent.com/kubernetes/kubernetes/master/test/e2e_kubeadm/OWNERS
WARNING: needs an alias as approver/reviewer reflecting sig-cluster-lifecycle - https://raw.githubusercontent.com/kubernetes/kubernetes/master/staging/src/k8s.io/component-base/configz/OWNERS
WARNING: needs an alias as approver/reviewer reflecting sig-cluster-lifecycle - https://raw.githubusercontent.com/kubernetes/kubernetes/master/staging/src/k8s.io/component-base/featuregate/OWNERS
```
these seem to be due to missing SIG-CL in OWNER_ALIAS files (?) and maybe should be optional.

### CODE REVIEW

**Comment by neolit123** [comment]
/kind cleanup
/sig cluster-lifecycle
/priority backlog
/triage accepted
/hold
for comments

**Comment by neolit123** [comment]
>Q: would it make sense to have omitempty in the YAML spec for meetings?

with the following patch:
```
diff --git a/generator/app.go b/generator/app.go
index bae4903e..fbd8ee8b 100644
--- a/generator/app.go
+++ b/generator/app.go
@@ -84,10 +84,10 @@ type Person struct {
 // Meeting represents a regular meeting for a group.
 type Meeting struct {
        Description   string
-       Day           string
-       Time          string
-       TZ            string
-       Frequency     string
+       Day           string `yaml:",omitempty"`
+       Time          string `yaml:",omitempty"`
+       TZ            string `yaml:",omitempty"`
+       Frequency     string `yaml:",omitempty"`

```

it allows us to do things like:
```
     meetings:
     - description: Use the main Cluster API meeting
-      day: ""
-      time: ""
-      tz: ""
-      frequency: ""
```

this would tell the user, "yes, there is a meeting, but not a specific one for this subproject and you can go other meeting".

WDYT?

**Comment by fabriziopandini** [comment]
/lgtm
for the changes to sigs.yaml
also, I notice that cluster-api-operator is missing; might be worth to cross-check is also someone else is missing and then open issues in their reporsitories

**Comment by neolit123** [comment]
> also, I notice that cluster-api-operator is missing; might be worth cross-checking is also if someone else is missing and then open issues in their repositories

yep, some could be missing. they can be added in a follow up.
as part of the repository / subproject creations we should tell the elected maintainers to PR the new subproject into sigs.yaml and we can LGTM the PR.

**Comment by alexander-demichev** [comment]
I requested slack channel for CAPI operator https://github.com/kubernetes/community/pull/6304, I'll update the PR when it's ready.

**Review by vincepri — APPROVED** [review]

**Comment by fabriziopandini** [comment]
@neolit123  I have checked all the CAP* providers and all of them are listed except Cluster API operator which will be fixed by the PR linked above. Nevertheless, I have asked the various team to update sub-project info, given that in some cases they are incomplete (e.g lack of slack channel, etc.)

**Comment by fabriziopandini** [comment]
/lgtm
for the changes to sigs.yaml

**Comment by neolit123** [comment]
/hold cancel
/assign @dims 
PTAL as part of the annual report cleanup.

i can omit the kube-up change and the first commit about the generator if these seem too bikesheddy to you.

**Comment by dims** [comment]
/assign @mrbobbytables 
/unassign

@neolit123 looks good in general, want to let sig-contribex folks look at the changes proposed in the tools

**Comment by mrbobbytables** [comment]
looping in TLs 👍 
/assign @cblecker @nikhita

**Comment by neolit123** [comment]
i'm considering dropping the first commit here - `generator: allow only description under subproject meetings`..
the `maintainers` tool currently complains if a subproject does not have a `meetings` struct, but AFAIK there is no clear requirement for subprojects to have zoom calls.

e.g. kubespray expressed that they don't want to have a zoom call and slack / github is enough for them.

**Comment by neolit123** [comment]
/cc @dims
PTAL for LGTM

to unblock the SIG yearly report.

**Pull request merged**
