### PR TITLE
Create new github issue template for security assessments

### PR DESCRIPTION
**Pull request by PushkarJ**
Creates a new security assessment Github issue template for making this a self-service request for any sub-projects

/cc @kubernetes/sig-security-leads @rficcaglia @savitharaghunathan @reylejano 
/sig security 

X-Ref: https://github.com/kubernetes/community/issues/5921

### CODE REVIEW

**Comment by PushkarJ** [comment]
New label `area/security-assessment` is being requested here: https://github.com/kubernetes/test-infra/pull/23070

**Comment by nikhita** [comment]
Where would the security assessments live? Would it be helpful to create a new repo for this or potentially create a directory under https://github.com/kubernetes/security?

k/community mostly houses meta info about the community (info about SIGs, etc) and community-wide developer docs. I'm a little concerned that we might be trying to fit in too much info in this repo if we include security assessments here.

**Comment by savitharaghunathan** [comment]
> Where would the security assessments live? Would it be helpful to create a new repo for this or potentially create a directory under https://github.com/kubernetes/security?

+1 to this suggestion. I am not sure what the repository would be or where, but a dedicated one for sig-security will definitely help in tracking all assessments/audits/issues in one place.

**Comment by PushkarJ** [comment]
Thank you Nikhita, for bringing this up. I really like this idea and have started a conversation with SIG Security chairs (@IanColdwater and @tabbysable ) on this topic [in this slack thread](https://kubernetes.slack.com/archives/C019LFTGNQ3/p1627669243003400) to create a `kubernetes-sigs/security` repo. 

Until there is a decision made regarding the right place for not just security assessments but for all of the deliverables of SIG Security, I will put a /hold on this PR. cc @reylejano

**Comment by PushkarJ** [comment]
Thank you Nikhita, for bringing this up. I really like this idea and have started a conversation with SIG Security chairs (@IanColdwater and @tabbysable ) on this topic [in this slack thread](https://kubernetes.slack.com/archives/C019LFTGNQ3/p1627669243003400) to create a `kubernetes-sigs/security` repo. 

Until there is a decision made regarding the right place for not just security assessments but for all of the deliverables of SIG Security, I will put a hold on this PR. 

cc @reylejano 

/hold

**Comment by PushkarJ** [comment]
Waiting on this https://github.com/kubernetes/org/issues/2923 to be completed

**Comment by PushkarJ** [comment]
`kubernetes/sig-security` now exists!! 🎉  Closing this PR in favor of: https://github.com/kubernetes/sig-security/pull/5

**Pull request closed without merging**
