### PR TITLE
Add automatic labelling for annual reports and charter changes

### PR DESCRIPTION
**Pull request by cblecker**
Automatically adds labels for annual reports and charter changes

### CODE REVIEW

**Comment by cblecker** [comment]
/hold
depends on https://github.com/kubernetes/test-infra/pull/28479

**Comment by cblecker** [comment]
/hold cancel
label has been created: https://github.com/kubernetes/community/labels/area%2Fannual-reports

**Review by nikhita — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
