### PR TITLE
Add ppc64le channel

### PR DESCRIPTION
**Pull request by mkumatag**
**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/community/issues/6959

### CODE REVIEW

**Review by markyjackson-taulia — CHANGES_REQUESTED** [review]
i am a -1, simply based our guidelines stated [here](https://github.com/kubernetes/community/blob/master/communication/slack-guidelines.md#should-you-have-a-channel-on-the-kubernetes-slack).
Now that isn't end all. I see hope here. Can you @mkumatag point us to where the current community shares things openly?

/hold

**Comment by mkumatag** [comment]
> i am a -1, simply based our guidelines stated [here](https://github.com/kubernetes/community/blob/master/communication/slack-guidelines.md#should-you-have-a-channel-on-the-kubernetes-slack). Now that isn't end all. I see hope here. Can you @mkumatag point us to where the current community shares things openly?
> 
> /hold

Currently I see folks reaching out directly to individuals in the IBM or the [IBM's communities](https://community.ibm.com/community/user/home) but I always felt these channels aren't good enough, need some space where people can talk to some of the folks who are working on this platform to have a better adoption. wdys?

**Comment by mkumatag** [comment]
> > i am a -1, simply based our guidelines stated [here](https://github.com/kubernetes/community/blob/master/communication/slack-guidelines.md#should-you-have-a-channel-on-the-kubernetes-slack). Now that isn't end all. I see hope here. Can you @mkumatag point us to where the current community shares things openly?
> > /hold
> 
> Currently I see folks reaching out directly to individuals in the IBM or the [IBM's communities](https://community.ibm.com/community/user/home) but I always felt these channels aren't good enough, need some space where people can talk to some of the folks who are working on this platform to have a better adoption. wdys?

We are aiming only for the Kubernetes content for the ppc64le platform(may be that is missing in the request)

**Comment by markyjackson-taulia** [comment]
@mkumatag can you share some info on ppc64le arch/platform ?
Assume I know nothing … the goal is to demonstrate some community traction, somewhere, other than here. Because we have our hands full and can use help to manage the amazing things Kubernetes brought us. 
We just have to make sure we water it and tend to it. Not to sound like a patronizing ass, I apologize.

**Comment by mkumatag** [comment]
> @mkumatag can you share some info on ppc64le arch/platform ?
> Assume I know nothing … the goal is to demonstrate some community traction, somewhere, other than here. Because we have our hands full and can use help to manage the amazing things Kubernetes brought us.
> We just have to make sure we water it and tend to it. Not to sound like a patronizing ass, I apologize.

ppc64le is like another cpu architecture like amd64, arm etc.. and is a pure [little-endian](https://en.wikipedia.org/wiki/Little-endian) mode that has been introduced with the [POWER8](https://en.wikipedia.org/wiki/POWER8) belongs to [IBM Power Processor](https://en.wikipedia.org/wiki/IBM_Power_microprocessors) family.

And also it is one of the [supported alternative architecture](https://github.com/kubernetes/sig-release/blob/master/release-engineering/platforms/guide.md) of Kubernetes project.

**Comment by markyjackson-taulia** [comment]
@mkumatag thank you for that additional info.. perhaps there is an ibm slack with a #kubernetes channel. I still feel like the Kubernetes slack is not the right place so I am still a -1 but let's have some of the other slack admins add their thoughts.

**Comment by coderanger** [comment]
@mkumatag Does anyone other than IBM handle this CPU architecture? If no, I would probably reject this too, it should be handled by IBM's community team.

**Comment by mkumatag** [comment]
> @mkumatag Does anyone other than IBM handle this CPU architecture? If no, I would probably reject this too, it should be handled by IBM's community team.

There is a [openpower](https://openpowerfoundation.org/members/) consortium with quite a few members involved, having that said.. I don't see any point taking this request forward, will use any preexisting channels for related topics. -Thanks.

**Pull request closed without merging**
