### PR TITLE
Trivial: code highlight for Event fields in style guide

### PR DESCRIPTION
**Pull request by joadavis**
A simple suggestion to highlight the Event fields in the event-style-guide.md to improve readability.

### CODE REVIEW

**Comment by joadavis** [comment]
Thank you k8s-ci-bot for pointing out I submitted this from my github account which hadn't signed the agreement yet. :facepalm:

**Review by ehashman — APPROVED** [review]
/lgtm

**Comment by joadavis** [comment]
A humble Thank You. :)

**Pull request merged**
