### PR TITLE
community/icons: Graphics out of sync

### PR DESCRIPTION
**Pull request by joshti**
Hi Team,

I'm using the in-tree Visio stencils to help create some diagrams for some of the training that we're doing (thank you so much for having these!). I'm hoping to align the naming with the current documentation in the project to help reduce the friction for introducing people who are brand new to k8s. In particular, the friction I'm experiencing is between these two commits:
https://github.com/kubernetes/website/pull/18438 
https://github.com/kubernetes/community/blob/0b167c8b8a11586116ffc4befc84d7b0a519ecbe/icons/png/infrastructure_components/labeled/master-256.png

Please don't squash on merge as there's two very different changes present in my tree. Additionally, please let me know how I can help improve this if changes are requested.

### CODE REVIEW

**Comment by joshti** [comment]
I signed it

on this account 😉

**Comment by thockin** [comment]
Why does this remove 2 PNGs but not add replacements?

**Comment by joshti** [comment]
Hi @thockin , thanks for taking a look at this one.

> Why does this remove 2 PNGs but not add replacements?

What do you mean by this? Two of the PNG labels are modified / regenerated and are drop in a for existing consumers with CI/CD. I'm not seeing any removals in the cset.

**Comment by castrojo** [comment]
I see the icons but the text is red, so now that's confusing me too.

**Comment by joshti** [comment]
@thockin no worries - I agree the red UX could be improved upon to make it clearer.

@castrojo can you please take another look?

**Pull request merged**
