### PR TITLE
Fix formatting of OOM score configuration section in resource-qos.md

### PR DESCRIPTION
**Pull request by Jonnymcc**
Two things were confusing to me in this section.
1. "The base OOM score is between 0 and 1000, so if process A's OOM_SCORE_ADJ - process B's OOM_SCORE_ADJ is over a 1000, then process A will always be OOM killed before B."
This implies that both A and B have the same base score? And could it be simplified to say if A's OOM_SCORE_ADJ > B, then A will be killed. And this would also apply to the final OOM score, if this is saying they both have the same base OOM score.
2. Pods, containers, and processes are mixed into a bunch of these rules and it's not super clear in each rule which one the OOM score applies to.

Examples:
- The final OOM score of a process is also between 0 and 1000. (process)
- If a burstable pod uses less memory than requested, then its OOM_SCORE < 1000 (pod)
- Pod infra containers or Special Pod init process (containers?)

### CODE REVIEW

**Comment by gkarthiks** [comment]
hi @Jonnymcc Since we have a KEP process, can we please merge this soon or close this and create a KEP?

**Comment by mrbobbytables** [comment]
@Jonnymcc I know this is a formatting fix -- but for the most part design proposals are there for historic/archival purposes and not updated. 

They're going to be migrated in the near future to exist alongside their replacement ([Kubernetes Enhancement Proposals](https://github.com/kubernetes/enhancements)). We can leave this open for a bit longer, but we'll be closing out all PRs later this month that touch the design proposals in preparation for their migration.

**Comment by mrbobbytables** [comment]
@Jonnymcc thanks for your PR, but at this time we're no longer going to be accepting updates to design-proposals as they're flagged for archival and will soon be moved out of the repo.

With that I'm going to go ahead and close this PR. If you have questions, please feel free to ping me here or in slack.

Thanks!

/close

**Pull request closed without merging**
