### PR TITLE
Added slack channel for cert-manager/aws-privateca-issuer

### PR DESCRIPTION
**Pull request by solonish**
**Which issue(s) this PR fixes**:
Adding a slack Channel

Fixes #
* Slack Channel Name: cert-manager-aws-privateca-issuer

* Purpose of the Channel: To communicate with the users of the cert-manager/aws-privateca-issuer plugin for Kubernetes and keep the users informed about on potential issues and Plugin updates.

* GitHub Link: https://github.com/cert-manager/aws-privateca-issuer

### CODE REVIEW

**Comment by coderanger** [comment]
Confirmed with the cert-manager team that they are okay with this, they are.

/ok-to-test
/lgtm
/approve

@solonish You'll need to sign the CLA before we can merge this.

**Comment by solonish** [comment]
I signed it

**Comment by solonish** [comment]
I have joined CNCF (Kubernetes) - Amazon group.
The PR check is not successful.
Can anyone check and approve the same?

**Pull request merged**
