### PR TITLE
Update Code of Conduct Committee membership

### PR DESCRIPTION
**Pull request by cblecker**
/cc @jdumars @carolynvs @Bradamant3 @AevaOnline @tashimi 
/cc @kubernetes/steering-committee

### CODE REVIEW

**Comment by parispittman** [comment]
lgtm - thank you for doing this!! 🙏

**Comment by jdumars** [comment]
/approve 

@parispittman you will be missed!

**Comment by jdumars** [comment]
Oh, we need an LGTM... 
/lgtm

**Pull request merged**
