### PR TITLE
update SIG scheduling meeting times and info

### PR DESCRIPTION
**Pull request by bsalamat**

### CODE REVIEW

**Comment by cblecker** [comment]
Per the notice at the top of these files, they are auto generated, and the source of truth is the sigs.yaml file. Instructions for using the generator are here: https://github.com/kubernetes/community/blob/master/generator/README.md

**Comment by bsalamat** [comment]
@cblecker I followed the same instructions. Is there anything that I did incorrectly?

**Comment by cblecker** [comment]
This works!
/approve

**Pull request merged**
