### PR TITLE
Add a moderator template

### PR DESCRIPTION
**Pull request by castrojo**
This adds a moderator template so that moderators can apply via the community repo.

### CODE REVIEW

**Comment by nikhita** [comment]
@castrojo Can we add an OWNERS file for `.github` so that we can automatically apply the `sig/contributor-experience` for all PRs that target that directory?

**Comment by castrojo** [comment]
Sure, is it possible to do a team ownership or should I just clone the owners file from the root of this repo?

**Comment by nikhita** [comment]
> Sure, is it possible to do a team ownership or should I just clone the owners file from the root of this repo?

If by team ownership, you mean GitHub team ownership - no, that's not possible today.

Cloning the OWNERS file from the root sgtm...but if that's the case, we don't really need to add it because without it, the approval needs to come from root OWNERS anyway. ¯\\\_(ツ)\_/¯

I'm fine with not adding an explicit OWNERS file too in that case. :)

**Comment by castrojo** [comment]
Yeah I think I'll skip the OWNERS file if it's just us again. Thanks!

**Comment by cblecker** [comment]
/hold

Thanks for this Jorge! I'm going to copy over some generic templates first, and then we can merge this in.

**Comment by nikhita** [comment]
Looks like this is good to go since https://github.com/kubernetes/community/pull/3285 merged.

**Comment by jdumars** [comment]
We need moderators yesterday, so someone please unhold this besides me :)

**Pull request merged**
