### PR TITLE
explicit and clear about what majority means

### PR DESCRIPTION
**Pull request by MHBauer**
@carolynvs @duglin @kibbles-n-bytes @pmorie

### CODE REVIEW

**Comment by duglin** [comment]
I like line 87 needs to be changed too

**Comment by MHBauer** [comment]
The chairs are enumerated specifically, and lazy consensus is a find a negative response situation. 2/3rds of those lazily responding implies they have to respond when laziness implies the opposite. It just doesn't make sense.

**Comment by duglin** [comment]
fair enough. Personally, I wish we didn't have lazy consensus - to assume a default position of 'yes' is just weird to me and can be easily gamed by wording but that's a different issue I guess.
/approve

**Pull request merged**
