### PR TITLE
Adding markyjackson-taulia to mods list

### LINKED ISSUE #6241: REQUEST: New moderator for markyjackson-taulia of Slack, YouTube, Zoom, Discuss
### GitHub Username
markyjackson-taulia

### Property you'd like to Moderate
Youtube, Slack, discuss.k8s.io, kubernetes-dev, and zoom

### Username on Property Requested
@markyjackson-taulia 

### Requirements

- [x] I am a Kubernetes Org member already
- [x] I have enabled 2FA on my account for the property I would like to moderate (if applicable).
- [x] I have read and will abide by the policies mentioned in the [Moderation Guidelines](https://git.k8s.io/community/communication/moderation.md)
- [x] I have two sponsors that meet the sponsor requirements listed in the moderator guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @parispittman 
- @coderanger 

### List of qualifications for this position

- Was previous moderator for slack, Youtube, zoom, discuss etc..

### PR DESCRIPTION
**Pull request by markyjackson-taulia**
Fixes #6241

### CODE REVIEW

**Comment by markyjackson-taulia** [comment]
Happy Friday all!
I wanted to circle back on this.
Cc. @coderanger

**Comment by coderanger** [comment]
/lgtm

I think we need a contribex lead to approve though :)

**Comment by nimbinatus** [comment]
/lgtm
+10000

**Review by idvoretskyi — APPROVED** [review]
/approve

**Pull request merged**
