### PR TITLE
first-contribution: add sig-node link

### PR DESCRIPTION
**Pull request by esotsal**
This PR add SIG Node link in first-contribution.md

### CODE REVIEW

**Comment by stmcginnis** [comment]
/lgtm

But would be great if you could move it up in the list to keep alphabetization. ;)

**Comment by esotsal** [comment]
> /lgtm
> 
> But would be great if you could move it up in the list to keep alphabetization. ;)

Thanks, good point. Done

**Comment by stmcginnis** [comment]
/lgtm

Thanks!

**Review by MadhavJivrajani — APPROVED** [review]
/lgtm
/approve
Thank you!

**Pull request merged**
