### PR TITLE
Node E2E test suite documentation

### PR DESCRIPTION
**Pull request by knabben**
Add Node E2e code walkthrough on local documentation.

**Which issue(s) this PR fixes**:

Rel https://github.com/kubernetes/kubernetes/issues/92673

### CODE REVIEW

**Comment by alejandrox1** [comment]
reviewing :nerd_face: 
Thank you @knabben !
/ok-to-test

**Comment by alejandrox1** [comment]
/assign @derekwaynecarr @dchen1107 
ptal

**Review by alejandrox1 — COMMENTED** [review]
Ping'd Dawn and Derek for approval but this looks good!
Thank you @knabben !
/lgtm

**Comment by derekwaynecarr** [comment]
@knabben this is an excellent write-up!

/lgtm
/approve

**Pull request merged**
