### PR TITLE
Topology aware dynamic provisioning design

### PR DESCRIPTION
**Pull request by msau42**
Update volume topology design doc with:
* Defining terms used to describe topology
* Dynamic provisioning new APIs
* In-tree and external provisioning interface changes
* Scheduler implementation details
* Examples for local, zonal, and multi-zonal volumes

@kubernetes/sig-storage-pr-reviews

### CODE REVIEW

**Comment by thockin** [comment]
Nice doc!  Thanks for updating

/lgtm
/approve

**Comment by msau42** [comment]
Ah hold on, this is design discussion for 1.11 :-)

**Comment by thockin** [comment]
LOL.  You send me a PR on code-freeze day, expect it to get looked at.  :)

**Comment by msau42** [comment]
Whoops :-D

Reverted, and opened new PR to continue discussion: #1857

**Comment by m1093782566** [comment]
@thockin 

Please don't forget our service topology proposal, #1551  :)

**Pull request merged**
