### PR TITLE
Add RESULTS, BALLOT files

### PR DESCRIPTION
**Pull request by jberkus**
This adds the final files for the 2020 election.

Also includes a little after-the-fact cleanup of voter IDs.

### CODE REVIEW

**Comment by jberkus** [comment]
/sig contributor-experience
/kind documentation
/committee steering

attn:
@jdumars @idvoretskyi

**Comment by cblecker** [comment]
/hold
for election officer review

**Review by idvoretskyi — APPROVED** [review]
/lgtm

**Comment by nikhita** [comment]
Going to cancel the hold since this has a lgtm from an election officer

/hold cancel

**Pull request merged**
