### PR TITLE
Add wg-iot-edge.

### PR DESCRIPTION
**Pull request by dejanb**
Signed-off-by: Benjamin Cabé <benjamin.cabe@eclipse-foundation.org>

Add wg-iot-edge - fixup

### CODE REVIEW

**Comment by idvoretskyi** [comment]
/hold

cc @kubernetes/steering-committee

**Comment by kartben** [comment]
I just signed the CLA. Thanks!

**Comment by idvoretskyi** [comment]
cc @kubernetes/steering-committee

**Comment by quinton-hoole** [comment]
Please add mention of the sponsoring sigs, then we can merge this.  I believe that sig-networking and sig-multicluster have agreed to sponsor this. I can approve on behalf of sig-multicluster.  @thockin has [expressed support](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/kubernetes-sig-apps/q1RFNb3LGlE/dFtS9OmRAwAJ) on behalf of sig-networking.  Further community support is also expressed in the aforemented thread.

**Comment by idvoretskyi** [comment]
@dejanb please, verify your CLA configuration.

**Comment by dejanb** [comment]
@quinton-hoole Thanks. I updated the text a bit with more info. Let me know if there's anything else missing.

@idvoretskyi it should be fixed now. Thanks

**Pull request merged**
