### PR TITLE
Create operator-sdk-maintainers slack group

### PR DESCRIPTION
**Pull request by asmacdo**

### CODE REVIEW

**Comment by asmacdo** [comment]
There was an email mismatch with the CLA. Hopefully that is now fixed.

**Comment by asmacdo** [comment]
The [doc](https://github.com/kubernetes/community/blob/588581e6049409ab5f3968f5ed8c5a34f1119cef/communication/slack-guidelines.md#requesting-a-user-group) requires me to ping the users who will be added here.

/cc estroz
/cc joelanford
/cc jmccormick2001
/cc jmrodri
/cc asmacdo
/cc marc-obrien
/cc theishshah
/cc camilamacedo86
/cc fabianvf
/cc varshaprasad96
/cc rashmigottipati
/cc jberkhahn

**Comment by markyjackson-taulia** [comment]
ok-to-test

**Review by markyjackson-taulia — APPROVED** [review]
/lgtm

**Comment by mrbobbytables** [comment]
Once we get some more acks, can get this merged 👍

**Review by idvoretskyi — APPROVED** [review]
/lgtm

**Pull request merged**
