### PR TITLE
sig-scalability chair change

### PR DESCRIPTION
**Pull request by shyamjvs**
As discussed on the [mailing list](https://groups.google.com/forum/#!topic/kubernetes-sig-scale/8p37cyGrWZA).

Opening for proposal and holding for lazy consensus per [governance roles doc](https://github.com/kubernetes/community/blob/master/committee-steering/governance/sig-governance.md#notes-on-roles).

/hold
/assign @wojtek-t @countspongebob
cc @kubernetes/sig-scalability-misc

### CODE REVIEW

**Comment by shyamjvs** [comment]
Leaving this open for few more days before merging, since there was kubecon this week. If there are any comments, please send them in by 18th Dec.

cc @cblecker (as discussed offline)

**Comment by cblecker** [comment]
/approve
/hold

Holding for lazy consensus to elapse :)

**Comment by wojtek-t** [comment]
I'm sorry for big latency. But LGTM from me too.

**Comment by shyamjvs** [comment]
Thanks all. I'm merging this since the date in https://github.com/kubernetes/community/pull/3017#issuecomment-447502943 is past.

/hold cancel

**Pull request merged**
