### PR TITLE
format index number from 1 and Unified Taxation Code

### PR DESCRIPTION
**Pull request by tim-zju**
Signed-off-by: tim-zju <21651152@zju.edu.cn>

### CODE REVIEW

**Comment by philips** [comment]
the numeral doesn't matter in markdown but I do agree it is confusing because it is weird.

But, what do you mean by "Unified Taxation Code"

**Comment by tim-zju** [comment]
Unified Taxation Code: In this file, it sometimes uses 1-9 to number ,sometimes uses * to number, so i think it should be uniformed.

**Comment by krzyzacy** [comment]
ref https://github.com/kubernetes/community/pull/210#issuecomment-268471990 which why it is a unified format here.

**Comment by philips** [comment]
I think we should fix this file to use all `1.`'s everywhere as suggested by @jonboulle in https://github.com/kubernetes/community/pull/210#issuecomment-268471990. I am going to close this PR and I look forward to a PR that moves to using `1.` everywhere.

**Pull request closed without merging**
