### PR TITLE
remove unwanted text

### PR DESCRIPTION
**Pull request by geoffcline**
The ["adding release notes page"](https://www.kubernetes.dev/docs/guide/release-notes/#applying-a-release-note) had unwanted text. This PR removes it. 

> Applying a Release Note
> 
> _slug: “adding-release-notes”_
> 
> On the kubernetes/kubernetes repository, release notes are required for any pull request with user-visible changes.

### CODE REVIEW

**Comment by geoffcline** [comment]
thanks for noticing @eddiezane :)

**Comment by eddiezane** [comment]
/ok-to-test
/lgtm

Thanks for fixing!

**Review by eddiezane — APPROVED** [review]

**Review by idvoretskyi — APPROVED** [review]
/lgtm

**Pull request merged**
