### PR TITLE
Fix azure meeting

### PR DESCRIPTION
**Pull request by craiglpeters**
Updating the meeting times and timezones for Azure Subproject of SIG Cloud Provider

### CODE REVIEW

**Comment by cblecker** [comment]
/lgtm
/approve

Needs a rebase though

**Comment by mrbobbytables** [comment]
@craiglpeters friendly ping on the rebase 👍

**Comment by jdumars** [comment]
paging @craiglpeters :)

**Comment by nikhita** [comment]
@craiglpeters friendly ping :)

Just needs a rebase but looks good to go otherwise.

**Comment by craiglpeters** [comment]
Oh my. Will take care of this tomorrow

**Comment by cblecker** [comment]
Still pending a rebase @craiglpeters

**Comment by craiglpeters** [comment]
Sorry for the noise. We're abandoning this change, and doing something else

**Pull request closed without merging**
