### PR TITLE
Add Ingress NGINX sub project meeting

### PR DESCRIPTION
**Pull request by strongjz**
Adding the Ingress NGINX sub project meeting details.

### CODE REVIEW

**Review by rikatz — APPROVED** [review]
/lgtm

Thanks!

**Comment by rikatz** [comment]
/ok-to-test
Though @strongjz was already org member :)

**Review by tao12345666333 — COMMENTED** [review]
/lgtm

**Review by idvoretskyi — APPROVED** [review]
/approve

**Pull request merged**
