### PR TITLE
add links for labels in sig-list.md

### PR DESCRIPTION
**Pull request by dims**
Add links that folks can click to view what the labels point to.

Signed-off-by: Davanum Srinivas <davanum@gmail.com>

### CODE REVIEW

**Review by nikhita — APPROVED** [review]
/lgtm


For the record, we use the k/community labels link in SIG/WG/UG readme but I think it would make sense to point to k/k since it leads to more meaningful issues:

https://github.com/kubernetes/community/blob/caed0813a0b53ec0d2fd3d62edf614133ab21db6/generator/sig_readme.tmpl#L58-L60

/hold
for @mrbobbytables to also confirm this sounds good to him

**Review by mrbobbytables — COMMENTED** [review]
I am generally okay with this, but a future improvement might be to update the generator to include an override. We should link steering to steering, contribex to k-community, ui to dashboard etc.

**Comment by dims** [comment]
> I am generally okay with this, but a future improvement might be to update the generator to include an override. We should link steering to steering, contribex to k-community, ui to dashboard etc.

+1 as a follow up!

**Comment by mrbobbytables** [comment]
> +1 as a follow up!

Follow up issue created: https://github.com/kubernetes/community/issues/6345

**Pull request merged**
