### PR TITLE
Add cluster-api-openstack-mentoring channel

### LINKED ISSUE #7325: REQUEST: New Slack channel cluster-api-openstack-mentoring
### GitHub Username

mdbooth

### Slack Username

Matthew Booth

### What Type of Request is it (Channel, User Group, Bot, Token, or Webhook)?

Channel

### Name of Requested Resource

cluster-api-openstack-mentoring

### Description of Request

We're mentoring a number of students over the summer who will be working on [cluster-api-provider-openstack](https://github.com/kubernetes-sigs/cluster-api-provider-openstack). We'd like to get them using Kubernetes Slack but avoid a deluge of messages to the [#cluster-api-openstack](https://kubernetes.slack.com/archives/CFKJB65G9) channel while they work through initial setup.

I've proposed the name `#cluster-api-openstack-mentoring` but would be open to suggestions. While both @mdbooth and I will be mentoring, I've requested @mdbooth be the contact [since he's a maintainer of CAPO](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/OWNERS_ALIASES).

### PR DESCRIPTION
**Pull request by stephenfin**
**Which issue(s) this PR fixes**:

Fixes #7325

### CODE REVIEW

**Comment by mrbobbytables** [comment]
Saw this rather late...but is this still desired? looking at the issue it was meant for something over the summer, but we're past that now :x

**Comment by stephenfin** [comment]
Yeah :sweat_smile: We ended up using a group chat to work around this. I'll abandon this for now and can resurrect it if we have a future group of students.

**Pull request closed without merging**
