### PR TITLE
Replace SIG/WG meeting placeholder references with Zoom links-2

### LINKED ISSUE #4588: Replace SIG/WG meeting placeholder references with Zoom links
Some time ago Zoom did not have sufficient moderation capabilities and the Zoom meeting links were removed from [sigs.yaml] and pointed towards this placeholder:
https://docs.google.com/document/d/1FQx0BPlkkl1Bn0c9ocVBxYIKojpmrS1CFP5h0DI68AE/edit

As a workaround to help mitigate trolls from causing problems in meetings. This has since been resolved and the entries in [sigs.yaml] should be updated with their correct link.

There are 53 references to the above placeholder as of 2020-03-09. Updated zoom links can be taken from either the SIG/WG's agenda or their calendar event from the [community calendar](https://calendar.google.com/calendar/embed?src=cgnt364vd8s86hr2phapfjc6uk%40group.calendar.google.com&ctz=America/Los_Angeles).

/area community-management
/sig contributor-experience
/help
/good-first-issue

[sigs.yaml]: https://github.com/kubernetes/community/blob/master/sigs.yaml

### PR DESCRIPTION
**Pull request by AGMETEOR**
**Which issue(s) this PR fixes**:
Fixes #4588

### CODE REVIEW

**Comment by markyjackson-taulia** [comment]
Also, the test failure is due to not running `make generate`

**Comment by AGMETEOR** [comment]
> Also, the test failure is due to not running `make generate`

**Comment by AGMETEOR** [comment]
Some notes
--------
* Regular Alibaba Cloud Subproject Meeting - Zoom link for time “12:00 UTC/ 5:00 am PST” not available in calendar

**Comment by AGMETEOR** [comment]
@mrbobbytables I haven't received any feedback about the missing zoom link for `Regular Alibaba Cloud Subproject Meeting` and therefore changed it back to the placeholder.

**Comment by mrbobbytables** [comment]
No worries, thanks for doing what you can!

**Comment by AGMETEOR** [comment]
Hello @mrbobbytables , I want to work on getting this merged today. Apart from the `Regular Alibaba Cloud Subproject Meeting`, I have updated all the placeholder links with zoom links. 

I will squash the commits as soon the reviews are done.

**Comment by AGMETEOR** [comment]
@mrbobbytables is it possible to do the squash on your side. I seem to run into errors locally that I have failed to solve because I made some merges earlier.

**Comment by mrbobbytables** [comment]
/lgtm
/hold cancel
Thanks!

**Pull request merged**
