### PR TITLE
Fix markdown formatting

### PR DESCRIPTION
**Pull request by davidxia**

### CODE REVIEW

**Comment by davidxia** [comment]
I signed it!

**Comment by davidxia** [comment]
cc @nikhiljindal @pires

**Comment by davidxia** [comment]
Hopefully this won't mess up formatting here http://janetkuo.github.io/kubernetes/v1.0/docs/getting-started-guides/docker.html.

**Comment by davidxia** [comment]
Just wondering what the next steps are.

**Comment by pires** [comment]
Hope it doesn't break anything but if it does, we'll just revert it 👍

**Pull request merged**
