### PR TITLE
sig-storage: add repos to nfs-provisioner subproject

### PR DESCRIPTION
**Pull request by nikhita**
Ref: https://github.com/kubernetes/org/issues/1744, https://github.com/kubernetes/org/issues/1743
cc @kmova 

/assign @saad-ali @xing-yang @msau42 @jsafrane 
/hold
for sign off from leads

### CODE REVIEW

**Comment by jsafrane** [comment]
lgtm, waiting for others

**Comment by xing-yang** [comment]
lgtm

**Pull request merged**
