### PR TITLE
Example of FUSE flexVolume.

### PR DESCRIPTION
**Pull request by adelton**

### CODE REVIEW

**Comment by adelton** [comment]
This is a more generic example of FUSE flexVolume, accompanying the secret-oriented proposal https://github.com/kubernetes/community/pull/1132.

**Comment by adelton** [comment]
The `allowedFlexVolumes` is currently proposed in https://github.com/kubernetes/kubernetes/pull/53179.

**Comment by castrojo** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/community/1147)

**Comment by adelton** [comment]
I don't seem to be able to add labels. Let's hope this comment will keep the PR open for a while.

**Comment by adelton** [comment]
@k8s-ci-robot, that's sad.

**Comment by adelton** [comment]
Rebased on master, fixed typo in the example gcc command -> db9754c2950ab8a45dcb55a5f2c9caf8fa5e5ad6.

**Comment by adelton** [comment]
I've copied the content of this pull request to https://github.com/adelton/kubernetes-flexvolume-fuse for easier consumption.

**Pull request closed without merging**
