### PR TITLE
add slack channel for csi-secrets-store

### LINKED ISSUE #4775: REQUEST: New Slack channel #csi-secrets-store
**GitHub Username:**

aramase
ritazh

**Slack Username:**

aramase
ritazh

**What Type of Request is it (Channel, User Group, Bot, Token, or Webhook)?**

Channel

**Name of Requested Resource:**
#csi-secrets-store

**Description of Request:**
Need a place to discuss [secrets-store-csi-driver](https://github.com/kubernetes-sigs/secrets-store-csi-driver) matters in the community

### PR DESCRIPTION
**Pull request by aramase**
Need a place to discuss [secrets-store-csi-driver](https://github.com/kubernetes-sigs/secrets-store-csi-driver) matters in the community

**Which issue(s) this PR fixes**:

Fixes #4775

### CODE REVIEW

**Comment by mrbobbytables** [comment]
/hold
this should go into the sig-storage directory with the other storage channels.

**Comment by aramase** [comment]
@mrbobbytables csi-secrets-store was sponsored by `sig-auth`. So would that mean it needs to be in sig-auth directory?

**Comment by mrbobbytables** [comment]
hm, its a little awkward because we've delegated channels with the csi-* prefix to sig-storage. It could still exist at the top level, but because it matches the regex for sig-storage it could inadvertently be moved there. It might be worth adding a comment next to the entry just saying that it is managed by sig-auth so no one touches it in the future.

**Comment by aramase** [comment]
>hm, its a little awkward because we've delegated channels with the csi-* prefix to sig-storage. It could still exist at the top level, but because it matches the regex for sig-storage it could inadvertently be moved there. It might be worth adding a comment next to the entry just saying that it is managed by sig-auth so no one touches it in the future.

@mrbobbytables Makes sense! Added a note to explicitly call that out. Let me know if that's good.

**Comment by mrbobbytables** [comment]
Thanks! 
/approve

**Comment by aramase** [comment]
@mrbobbytables Could also bless it with`lgtm`? :)

**Pull request merged**
