### PR TITLE
Add SIG Azure Charter

### PR DESCRIPTION
**Pull request by justaugustus**
Draft of the SIG Azure Charter. We're opening this up for comments!
Announcement on sig-azure mailing list to follow.

/cc @shubheksha @khenidak @colemickens @jdumars

### CODE REVIEW

**Comment by justaugustus** [comment]
Hey @sarahnovotny + @philips, this SIG charter has been [announced](https://groups.google.com/forum/#!topic/kubernetes-sig-azure/gfd_2X-vHpE) and accepted by lazy consensus.

Can we get a formal Steering Committee review to ratify and merge?

**Comment by philips** [comment]
Post paternity leave LGTM. Thanks!

**Pull request merged**
