### PR TITLE
sig-release: Add bom subproject

### PR DESCRIPTION
**Pull request by mrbobbytables**
ref: https://github.com/kubernetes/org/issues/3106
/assign @justaugustus @saschagrunert @puerco @cpanato @jeremyrickard

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
/lgtm

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Review by justaugustus — CHANGES_REQUESTED** [review]
@mrbobbytables — Can you instead add the owners file under Release Engineering? This will be managed within RelEng, as opposed to spinning a new subproject.

**Comment by mrbobbytables** [comment]
done 👍

**Comment by justaugustus** [comment]
> done 👍

@mrbobbytables -- not sure the changes took in https://github.com/kubernetes/community/commit/39d256bfc787f92f29933cd84eecc892de464131.

**Comment by mrbobbytables** [comment]
> @mrbobbytables -- not sure the changes took in 39d256b.

@justaugustus Woops, forgot to commit before amending and force pushing^^:;;;

Should be good now

**Comment by justaugustus** [comment]
> Should be good now

git, amirite?
Thanks for the updates, Bob!

/lgtm
/approve
/hold cancel

**Pull request merged**
