### PR TITLE
Update wg-multitenancy leads (davidopp -> srampal)

### PR DESCRIPTION
**Pull request by srampal**
Updated wg-multi-tenancy leads names (srampal instead of davidopp) 

Link to official wg announcement of this change is provided and both prior leads are cc'd for this PR review
https://groups.google.com/forum/#!topic/kubernetes-wg-multitenancy/ttdRICLnXp0

PTAL and approve @davidopp @tashimi @nikhita

### CODE REVIEW

**Comment by nikhita** [comment]
@srampal Sorry for the friction about the invalid owners file!

The prow plugin looks at the [patch](https://patch-diff.githubusercontent.com/raw/kubernetes/community/pull/3923.patch) to determine which GitHub usernames in OWNERS and OWNERS_ALIASES files should be verified to ensure that they are org members. The patch is used so that only folks who are being added to the OWNERS files in the current PR are verified, but unfortunately this might sometimes drag additional people/lines in the OWNERS files too. :/

@easeway It would be awesome if you could [apply for Kubernetes org membership](https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-membership&template=membership.md&title=REQUEST%3A+New+membership+for+%3Cyour-GH-handle%3E) since you are a WG lead.

I'll manually remove the label for now since @easeway's membership doesn't affect this change.

**Comment by tashimi** [comment]
/approve 

tenor-23914014

**Comment by srampal** [comment]
@grodrigues3 PTAL and approve this. The other assignees are not in the OWNERS file mentioned above hence cant approve it.

**Pull request merged**
