### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by michmike**

### CODE REVIEW

**Comment by michmike** [comment]
i do have a CLA through Apprenda

**Comment by michmike** [comment]
I signed it

**Comment by philips** [comment]
@michmike does your email match your apprenda email?

**Comment by michmike** [comment]
nope. my apprenda email is mmichael@apprenda.com

**Comment by philips** [comment]
@michmike you will need to fixup the commit then, sorry. `git commit --amend --author asdf`

**Comment by philips** [comment]
I am going to close this as you haven't responded in a month. I would love to have the contribution but I can't merge it without the CLA.

**Pull request closed without merging**
