### PR TITLE
Adding the section of contributor guide for sig-windows

### PR DESCRIPTION
**Pull request by michmike**

### CODE REVIEW

**Comment by michmike** [comment]
@nikopen can you please add this to 1.14 milestone?

**Comment by guineveresaenger** [comment]
Hi @michmike - thank you for this PR! I'm going to take a look at this tomorrow. For now, know that milestones are only enabled on kubernetes/kubernetes, so we won't need to follow release process here.
I'll probably ask you to move some of this content elsewhere to keep concerns streamlined and discoverable, but I'm so excited to see this kind of helpful content. <3

**Comment by nikopen** [comment]
Indeed milestones are only needed in the core repo.

Structure wise, I'd suggest the contributor guide to be moved within the SIG-Windows directory.

@guineveresaenger On the central 'contributors/guide/readme.md' there should be links to every single SIG's contributor guide so people can easily be directed to a more specific contributing resource.

**Comment by michmike** [comment]
/hold
until we figure out the structure

**Comment by michmike** [comment]
> Indeed milestones are only needed in the core repo.
> 
> Structure wise, I'd suggest the contributor guide to be moved within the SIG-Windows directory.
> 
> @guineveresaenger On the central 'contributors/guide/readme.md' there should be links to every single SIG's contributor guide so people can easily be directed to a more specific contributing resource.

that works for me if that's what the central guidance will be

**Comment by castrojo** [comment]
Wow thanks for this, agree with the rest, have `contributing-on-windows.md` live in the sig-windows directory. Remove the hold when this is done and then ping me on slack, I'd like to merge this asap before release.

**Comment by michmike** [comment]
> Wow thanks for this, agree with the rest, have `contributing-on-windows.md` live in the sig-windows directory. Remove the hold when this is done and then ping me on slack, I'd like to merge this asap before release.

i moved and re-arranged the files as requested. how does it look now?

**Comment by guineveresaenger** [comment]
Hi everyone! I have some different thoughts on this, and I literally just started my work day.

1. The SIG-specific contributing doc should be called CONTRIBUTING.md to standardize across the repo (see also: https://github.com/kubernetes/community/blob/master/sig-cli/CONTRIBUTING.md)

2. The _generic_ one-stop contributor guide should not specifically call out any one SIG or area of interest. We link to the SIGs within the guide, and point out that a SIG may have their own contributing guide. 

I'm completely open to making these SIG-specific guides more visible via @nikopen's comment, but the contributor guide should not cater to individual SIGs or technologies; it will result in too much clutter.

**Comment by parispittman** [comment]
@guineveresaenger 
#1 - 100% agree
#2 - i think it would be beneficial to have links to other contributing guides on the main one since we have a discoverability issue. This also may make it easier for folks to find a sig.

**Comment by michmike** [comment]
i agree with @parispittman  100% on 1 and 2. if you are all good with it, i can create a new PR to reflect the new changes

**Comment by guineveresaenger** [comment]
Hi friends! I'm just working on incorporating this feedback, a new PR will be up momentarily! Thank you for your patience, @michmike :)

**Comment by guineveresaenger** [comment]
Here it is: https://github.com/kubernetes/community/pull/3419

**Comment by nikopen** [comment]
:+1:

**Pull request merged**
