### PR TITLE
you can now add your sig's shared calendar explicitly in sigs.yaml

### PR DESCRIPTION
**Pull request by SergeyKanzhelev**
See commits:

1. Proper escaping of a time in templates
2. Add ability to specify the calendar link for meetings

Third commit is just regen of all files.

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
> please assign [kaslin](https://github.com/kaslin) for approval

/assign @kaslin

**Comment by pacoxu** [comment]
> 1. Proper escaping of a time in templates

Either link works for me.

**Comment by SergeyKanzhelev** [comment]
> > 1. Proper escaping of a time in templates
> 
> Either link works for me.

It doesn't work if you try to use time with "AM" suffix due to the space. Like "9:00 AM".

**Comment by chris-short** [comment]
@SergeyKanzhelev mind rebasing... again, please?

**Comment by chris-short** [comment]
@SergeyKanzhelev in `generator/app.go` could you update `calendar` to `calendar_url` to keep with the existing naming convention in the previous lines? Then update the templates accordingly please?

After that we can squash (on your own or via prow command) and I'll `lgtm` it

**Comment by SergeyKanzhelev** [comment]
> @SergeyKanzhelev in `generator/app.go` could you update `calendar` to `calendar_url` to keep with the existing naming convention in the previous lines? Then update the templates accordingly please?
> 
> After that we can squash (on your own or via prow command) and I'll `lgtm` it

@chris-short  done

**Comment by jberkus** [comment]
adding lgtm back after requested change
/lgtm

**Pull request merged**
