### PR TITLE
Update channels.yaml to include new slack channel.

### PR DESCRIPTION
**Pull request by AvvariSaiBharadwaj**
CRAFT is a project developed at Salesforce to facilitate easy operator creation. CRAFT declares Kubernetes Operators in a robust and generic way for any resource, letting developers focus on CRUD (create, read, update and delete) operations of resource management in a Dockerfile. With CRAFT you can create operators without a dependent layer and in the language of your choice. Further info: https://github.com/salesforce/craft#custom-resource-abstraction-fabrication-tool
We would like to create a channel in the Kubernetes community which can be used to raise and solve issues and suggest improvements on the existing framework and documentation.

**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Comment by AvvariSaiBharadwaj** [comment]
> Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
>  **Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.**
> 
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.
> 
> * If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check your existing CLA data and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> * If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.
> * If you have done the above and are still having issues with the CLA being reported as unsigned, please log a ticket with the Linux Foundation Helpdesk: https://support.linuxfoundation.org/
> * Should you encounter any issues with the Linux Foundation Helpdesk, send a message to the backup e-mail support address at: [login-issues@jira.linuxfoundation.org](mailto:login-issues@jira.linuxfoundation.org)
> 
> Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md). If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).

/check-cla

**Comment by AvvariSaiBharadwaj** [comment]
> Hi @AvvariSaiBharadwaj. Thanks for your PR.
> 
> I'm waiting for a [kubernetes](https://github.com/orgs/kubernetes/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://git.k8s.io/community/community-membership.md#member) to skip this step.
> 
> Once the patch is verified, the new status will be reflected by the `ok-to-test` label.
> 
> I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=kubernetes%2Fcommunity).

/ok-to-test

**Comment by jeefy** [comment]
/approve

Seems like a project OSS'd by Salesforce, repo is new but code base doesn't seem to be. :)

**Comment by AvvariSaiBharadwaj** [comment]
> /approve
> 
> Seems like a project OSS'd by Salesforce, repo is new but code base doesn't seem to be. :)

@jeefy The project is built making use of existing opensource projects Kubebuilder and Operatify. Hence the code base is not fully new, but the functionalities offered and the features available are new and more :)

**Comment by prakashrj** [comment]
@jeefy We were able to create several operators in quick time with this tool. We are hoping that open source community will also benefit from it.

**Comment by jdumars** [comment]
I'm on the fence about approving this channel for similar reasons as #5107 - this seems like a relatively small contributor base, and I am not sure why you'd need a Slack channel to support it, as opposed to GH issues until that is unwieldy and requires realtime interactions.

**Comment by jeefy** [comment]
@jdumars I'm happy to cancel my approve depending on your level of concern. I initially +1'd it because of its circumstances, but was also on the fence.

**Comment by jdumars** [comment]
This case is pretty different than the one I referenced. I think we can approve with a "to-do" - write more specific guidance for these situations.

**Comment by prakashrj** [comment]
@jdumars We will be glad to follow the guidelines in "to-do". We did our best to make the tool generic before open sourcing it. We still expect some handholding to be done, when community shows interest in using it. We are hoping that a channel in Kubernetes slack will be helpful. Soon we would like to create some good example use cases in different languages by working with the community.

**Comment by jdumars** [comment]
I trust that you'll do everything you can to serve the greater community with your project. I'm going to LGTM this request, and we'll get better guidance documented.

/lgtm

**Comment by prakashrj** [comment]
@jdumars Thank you very much for the approval and trust in us.

**Pull request merged**
