### PR TITLE
Rename COC file so that GitHub can identify it

### PR DESCRIPTION
**Pull request by nikhita**
@BenTheElder pointed out that our CoC is not identified by GitHub: https://github.com/kubernetes/community/community.

Looks like it needs to be named as `CODE_OF_CONDUCT.md`: https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/.

/sig contributor-experience
/kind bug

### CODE REVIEW

**Comment by nikhita** [comment]
/hold

Let's make sure it works in https://github.com/kubernetes-sigs/kind/pull/31.

**Comment by castrojo** [comment]
/approve

But we'll likely need to update links across the repo and docs?

**Comment by BenTheElder** [comment]
Unfortunately this change didn't work in two other repos we tested it in.
Probably we should move them back and contact GitHub

**Comment by nikhita** [comment]
We are reaching out to GitHub. I'll update here based on what we hear.

**Comment by nikhita** [comment]
From GitHub's reply:

> Currently, the tool will only check specifically for code of conduct files that we recognize, not just the existence of a CODE_OF_CONDUCT.md. This was an intentional choice made to avoid giving folks a checkmark if they've got a file full of content that is not actually a code of conduct.

Will let the CoC committee take it forward.

Closing this PR since this won't help.
/close

**Pull request closed without merging**
