### PR TITLE
Add Lachlan Evenson candidate bio for SC 2020 election

### PR DESCRIPTION
**Pull request by lachie83**
Signed-off-by: Lachlan Evenson <lachlan.evenson@microsoft.com>

/assign @jdumars @idvoretskyi @jberkus

### CODE REVIEW

**Comment by jdumars** [comment]
/lgtm
/hold 
holding for election committee review

**Comment by tpepper** [comment]
Should this PR also append the individual in events/elections/2020/README.md ?

**Comment by lachie83** [comment]
Yeah - nice catch. I will push another commit that adds to this table - https://github.com/kubernetes/community/tree/master/events/elections/2020#nominees

**Review by markyjackson-taulia — APPROVED** [review]
/lgtm

**Review by idvoretskyi — APPROVED** [review]
/lgtm

**Review by tpepper — COMMENTED** [review]
/lgtm

**Pull request merged**
