### PR TITLE
MultiCluster 2019 unconference notes

### PR DESCRIPTION
**Pull request by mattcary**
Notes taken during the k8s contributor summit unconference, Monday November 18 at 11:30am.

### CODE REVIEW

**Comment by mattcary** [comment]
Sorry about the CLA check failing---I thought I had registered myself correctly but something has gone awry. I'm working on sorting it out.

**Comment by tpepper** [comment]
> Sorry about the CLA check failing---I thought I had registered myself correctly but something has gone awry. I'm working on sorting it out.

Might be this: https://github.com/kubernetes-sigs/contributor-playground/blob/master/exercises/cla-vs-git-author.md

/ok-to-test

**Comment by tpepper** [comment]
Looks like CLA issue was resolved.

**Comment by mattcary** [comment]
/assign @mrbobbytables

I had missed a step in registering my git account with google, or something like that, in order to get the CLA worked out. I'm glad that was the only issue :)

**Comment by markyjackson-taulia** [comment]
cc: @thecrudge

**Comment by mrbobbytables** [comment]
Thanks!
/approve
/honk

**Pull request merged**
