### PR TITLE
Update channels.yaml to add azure-service-operator

### PR DESCRIPTION
**Pull request by matthchr**
A channel to discuss Azure Service Operator

See: https://azure.github.io/azure-service-operator/ and https://github.com/Azure/azure-service-operator

### CODE REVIEW

**Review by markyjackson-taulia — APPROVED** [review]
Adding lgtm and also holding for other slack admins to review
/lgtm
/hold

**Comment by jdumars** [comment]
Looks like a good healthy project/community.
/approve

**Comment by matthchr** [comment]
Rebased as requested by the bot

**Pull request merged**
