### PR TITLE
Propose Damien Grisonnet as new SIG Instrumentation TL

### PR DESCRIPTION
**Pull request by ehashman**
Lazy consensus period is one week (~Jan. 13~ Jan. 19, 2022). Email: https://groups.google.com/a/kubernetes.io/g/dev/c/EgLQ5ynIbaw
/hold

Frederic [stepped down](https://groups.google.com/g/kubernetes-sig-instrumentation/c/kWsG-3XHzoM/m/fEmkYlu9BwAJ) as SIG Instrumentation TL in December 2021.

[At today's meeting,](https://docs.google.com/document/d/1FE4AQ8B49fYbKhfg4Tx0cui1V0eI4o3PxoqQPUwNEiU/edit#heading=h.t61dmzcxx1g) the SIG Instrumentation leads have proposed Damien Grisonnet (@dgrisonnet) as our new Technical Lead. Congratulations, Damien! :tada: :cake: 

/assign @logicalhan @dashpole 
/cc @brancz 
/sig instrumentation

### CODE REVIEW

**Review by logicalhan — APPROVED** [review]
/lgtm
/approve

**Comment by dgrisonnet** [comment]
Thank you @ehashman :slightly_smiling_face:

/lgtm

**Comment by shuaich** [comment]
Congratulations! /cc @dgrisonnet

**Comment by ehashman** [comment]
/hold cancel

1 week of lazy consensus period reached :tada:

**Review by justaugustus — APPROVED** [review]
Thank you @brancz and welcome to TL life, @dgrisonnet!
/lgtm
/approve

**Pull request merged**
