### PR TITLE
Fix tallclair affiliation

### PR DESCRIPTION
**Pull request by tallclair**
s/Apple/Google/

### CODE REVIEW

**Review by mrbobbytables — COMMENTED** [review]
@tallclair you should update it in sigs.yaml, then run make and it will update it in all the locations that are needed 👍

**Comment by dims** [comment]
LGTM :)

**Comment by tallclair** [comment]
Whoops, that's what I get for doing a quick edit through the github UI. Fixed.

**Review by cblecker — APPROVED** [review]

**Pull request merged**
