### PR TITLE
Added rlenferink as slack moderator

### PR DESCRIPTION
**Pull request by rlenferink**
Related to https://github.com/kubernetes/community/issues/3373

/cc @jdumars 
/assign @castrojo

/area community-management
/sig contributor-experience

### CODE REVIEW

**Comment by rlenferink** [comment]
@idvoretskyi PR needed a rebase, can you check again?

**Comment by idvoretskyi** [comment]
@rlenferink yep - done.

**Comment by nikhita** [comment]
/hold

can you squash commits?

**Comment by rlenferink** [comment]
Done @nikhita

**Comment by rlenferink** [comment]
Thanks @lledru 

/hold cancel

**Pull request merged**
