### PR TITLE
Add slack channel #ephemeralcontainers

### PR DESCRIPTION
**Pull request by verb**
Ephemeral containers is a project sponsored by sig-node. Several people have volunteered to contribute, and I'd like to have a channel to communicate progress and coordinate contributions.

Ephemeral containers is [KEP-277](https://features.k8s.io/277)

**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Review by markyjackson-taulia — COMMENTED** [review]
Can this conversation not take place in the sid-node slack channel?

**Comment by verb** [comment]
I mean, we can do whatever the community wants. It wasn't clear to me from [the docs](https://github.com/kubernetes/community/blob/master/communication/slack-guidelines.md#requesting-a-channel) what qualifies for a channel. I can understand if you don't want to pollute the namespace for a project, even if it is a long running one.

sig-node has too high a volume to just discuss a single project in it, but I could probably create a persistent thread and just keep adding people to it. Is that the right way to slack?

**Comment by markyjackson-taulia** [comment]
@verb my vote would be to use the sig-node channel for a bit (say 90 days) to see if traction holds and we can revisit.
I would like for other slack-admins to add their input as well.

**Comment by verb** [comment]
SGTM

**Comment by coderanger** [comment]
+1 for that plan, but even if a dedicated channel is needed I would vote for `#sig-node-ephemeralcontainers` to make it clear its a sig subproject.

**Pull request closed without merging**
