### PR TITLE
Adding sub-project channels for Konveyor project.

### PR DESCRIPTION
**Pull request by tsanders-rh**
This PR adds a set of slack channels for the sub-projects of the Konveyor (konveyor.io) Migration and Modernization project.  

* Crane is focused on migrating applications between Kubernetes clusters.

* Forklift is focused on migrating virtual machines to Kubernetes/CNV.

* Move2Kube is a tool that uses source artifacts such as Docker Compose files or Cloud Foundry manifest files, and even source code, to generate Kubernetes deployment artifacts including object yaml, Helm charts, and operators.

* Tackle is focused on modernizing applications to run on Kubernetes.

Please let me know if you have any questions.

### CODE REVIEW

**Comment by jdumars** [comment]
I am not a +1 on these channels for a few reasons. First, the creation of additional sub-channels is typically for -dev or -users to disambiguate, not to represent sub-parts of the same project. Second, the #konveyor channel is not high membership or high traffic, so further fraction of the Konveyor community doesn't provide any clear benefit, versus the introduction of more confusion. My recommendation is to close this request and reopen when there is higher traffic in the existing channel.

**Comment by coderanger** [comment]
Agree with @jdumars, the channel has 163 members at time of writing and 1-3 messages per day at most. Chat load doesn't seem to be in a place to need additional segmentation.

**Pull request closed without merging**
