### PR TITLE
Fix broken link to meet our contributors page

### PR DESCRIPTION
**Pull request by gorbondiga**
**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Comment by gorbondiga** [comment]
Hi, 

I've signed the CLA, where can I double check it?

**Comment by markyjackson-taulia** [comment]
> Hi,
> 
> I've signed the CLA, where can I double check it?

Something appears incorrect with your CLA. Please reverify that it is signed. Also make sure to sign off on this PR

**Comment by gorbondiga** [comment]
Could be rerun the CLA check?

**Comment by markyjackson-taulia** [comment]
> Could be rerun the CLA check?

You'll need to sign off on the pr now `@thelinuxfoundation
cla/linuxfoundation — commit missing GitHub user`

Then if you can squash the commits in to 1

**Pull request merged**
