### PR TITLE
Archive #garden and #garden-dev

### LINKED ISSUE #7058: [SLACK-ADMIN] archive #garden
### GitHub Username

@worldofgeese

### Slack Username

@worldofgeese

### What Type of Request is it (Channel, User Group, Bot, Token, or Webhook)?

Channel

### Name of Requested Resource

#garden

### Description of Request

Garden has moved all community channels to our own Discord server. Please permanently archive the channel. If possible, with a notice we've moved to Discord so users don't think we've closed shop.

### PR DESCRIPTION
**Pull request by worldofgeese**
Fixes #7058. Garden has moved our community to Discord: we're unifying our channels so our community knows there's one place they can go for everything.

**Which issue(s) this PR fixes**:

### CODE REVIEW

**Comment by palnabarun** [comment]
@worldofgeese -- can you please sign the CLA?

**Comment by markyjackson-taulia** [comment]
@worldofgeese going to leave this open for another 24 hours and close if no response. 
CLA still needs to be signed before this can proceed through the review process.
Thank you kindly.

**Comment by worldofgeese** [comment]
@markyjackson-taulia I can't sign the CLA until the Linux Foundation merges my signatory email account with my primary as the signatory email account goes to a dead older employer's email. Sadly it's been more than a month and the LF has yet to merge this account.

I appreciate what the CLA is meant to accomplish but I'd greatly appreciate if someone just made this PR on my behalf so we're not at the mercy of waiting.

**Comment by markyjackson-taulia** [comment]
@worldofgeese link me to that PR and I will see if I can help there

**Comment by worldofgeese** [comment]
@markyjackson-taulia it's this one 🙂

I just want to archive our old Garden channels on Slack as our community has moved to Discord.

**Comment by markyjackson-taulia** [comment]
@worldofgeese standby, I understand now and apologize for making this take longer.

**Comment by markyjackson-taulia** [comment]
@worldofgeese I have opened this [pr](https://github.com/kubernetes/community/pull/7193). Once it goes through, you can close this pr. Will that handle it?

**Comment by worldofgeese** [comment]
@markyjackson-taulia yes it will, thanks so much for helping me out!

**Pull request closed without merging**
