### PR TITLE
Adding a slack channel for Falco

### PR DESCRIPTION
**Pull request by kris-nova**
Signed-off-by: Kris Nova <kris@nivenly.com>

As we look at building Falco integrations with various components in the Kubernetes ecosystem, folks will naturally be looking for a #falco channel if they have questions or want to get involved. Unsure if we still require moderators in these channels, but I am happy to help any way I can.

### CODE REVIEW

**Comment by kris-nova** [comment]
Hi friends :) can we please have a falco channel?

**Comment by mrbobbytables** [comment]
/hold
I'm not against adding a falco channel, but historically traffic has been steered to their slack. It's the primary link for their chat link on the [falco project page](https://falco.org/) and has been historically referenced when it's come up in k8s slack. Is splitting the traffic desired?

**Comment by kris-nova** [comment]
Yes this is intentional to have two slack channels - the purpose of this channel is for discovery and in the future we very well might move permanently to Kubernetes. Unsure why this is a concern for Kubernetes? The Falco maintainers are the ones dealing with any fallout, and this is deliberate.

**Comment by mrbobbytables** [comment]
Mostly just wanted to double check. ¯\\\_(ツ)\_/¯ 

/hold cancel
/approve

**Pull request merged**
