### PR TITLE
Update SIG-OpenStack Leadership and Meeting Time

### PR DESCRIPTION
**Pull request by hogepodge**

### CODE REVIEW

**Comment by chaosaffe** [comment]
/lgtm 
Congratulations @chrigl and @flaper87! It is an honor and a pleasure to work with both of you, and I look forward to supporting you both in your new roles!

**Comment by chrigl** [comment]
Thanks @hogepodge and @chaosaffe. lgtm as well!
@flaper87 could you please approve when everything is fine from your pov.

**Comment by cblecker** [comment]
/approve
/hold

@hogepodge Feel free to remove the hold when you have sign offs from everyone you want :)

**Comment by castrojo** [comment]
Ok, just waiting on a +1 from @flaper87.

**Comment by flaper87** [comment]
Hi folks,

sorry for taking so long to get back to y'all but I had to wait for some discussions to happen before being able to reply here.

Unfortunately, I won't have the time and focus to dedicate to this role due to some changes in my main focus area. As much as I would like to help with this role, I think it'd be unfair for me to take it on knowing that in the near future I won't be able to represent this SIG properly.

That said, @chrigl is an awesome human and I'm sure he'll do great :+1: 

Sorry again for the delay, thanks for the patience and the trust, and sorry for not being able to help with this role at this time.

**Comment by jaybatra26** [comment]
:+1:  Congratulations @chrigl . Do let me know if you need another helping hand.

**Comment by GeetikaBatra** [comment]
Congratulations @chrigl . Do let me know if you need a helping hand.

**Comment by hogepodge** [comment]
Thanks @flaper87. To round out the sig leadership, @adisky was nominated and has accepted. I've updated the patch to reflect that. @castrojo we should be good to go on this change once @adisky weighs in formally.

**Comment by chrigl** [comment]
Great! Congrats and welcome @adisky  :)

Thanks @GeetikaBatra, I am certain that I will come back to you!

**Comment by chrigl** [comment]
@hogepodge @adisky Sorry for asking this now, but could we do the meeting on any other day but Thursday? That would help me a lot, because of a conflict in the schedules of my Girlfriend, me, and handling the Kids this afternoon.

**Comment by adisky** [comment]
/lgtm
@hodgepodge @chrigl Thanks!!!
@chrigl I am fine with any day.

**Comment by dims** [comment]
/hold cancel
/lgtm

Thanks @chrigl @adisky for stepping up! let's merge this and then you can propose alternate date/time

**Pull request merged**
