### PR TITLE
Add better docs for generator

### PR DESCRIPTION
**Pull request by jamiehannaford**
cc/ @idvoretskyi

### CODE REVIEW

**Comment by idvoretskyi** [comment]
@jamiehannaford looks much better now, thanks!

**Comment by jamiehannaford** [comment]
@jbeda Would you mind reviewing this?

**Comment by cblecker** [comment]
@jamiehannaford Is this still relevant? It needs a rebase.

**Comment by jamiehannaford** [comment]
Superseded by #726

**Pull request closed without merging**
