### PR TITLE
Broken links on SIG-Contribex Charter

### LINKED ISSUE #5975: Broken links on SIG-Contribex Charter
While going through the [charter](https://github.com/kubernetes/community/blob/master/sig-contributor-experience/charter.md), I found the links on line `34-38` aren't working properly.

The lines in the source of the doc:
```
- Strategize, build, and execute on scalable [mentoring programs] for all contributor levels. These may include:
  - [Google Summer of Code]
  - [Outreachy]
  - [Meet Our Contributors]
  - [Group Mentoring - WIP]
  - [The 1:1 Hour - WIP]
```
Screenshot 2021-08-27 at 21-52-52 community charter md at master · kubernetes community

cc @parispittman @nikhita 

/sig contributor-experience

### PR DESCRIPTION
**Pull request by SmrutiSikha**
**Which issue(s) this PR fixes**:

Fixes #5975

### CODE REVIEW

**Comment by MadhavJivrajani** [comment]
/ok-to-test
Thanks!

**Comment by parispittman** [comment]
/lgtm
/hold 
For chair or tech lead approval since this touches the charter

**Pull request merged**
