### PR TITLE
Add official Nutanix CAPI Provider Slack Channel

### PR DESCRIPTION
**Pull request by tuxtof**
This PR adds a slack channel for The Nutanix CAPI Provider (CAPX) - https://github.com/nutanix-cloud-native/cluster-api-provider-nutanix

**Which issue(s) this PR fixes**:
NONE

### CODE REVIEW

**Review by markyjackson-taulia — APPROVED** [review]
Thank you for this PR. The process is as followed:
* I will add a LGTM
* I will place a hold on the PR so other slack admins can also review
* Note: This process can take a week or more due to availability of the other admins.. Please be patient 

Thank kindly.
/lgtm
/hold

**Comment by jdumars** [comment]
I am not sure this particular projects meets expectations in terms of community engagement. I am going to defer to the judgment of other moderators, but I think this may be premature to separate from the regular CAPI discussion.

**Comment by tuxtof** [comment]
Hello @jdumars , nice to meet you, the goal here is to federate and drive the community as for all other CAPI provider who already have their own dedicated channel. Can you please help us to understand which expectations in terms of community engagement are missing in your opinion and how to solve them ?

Can you also invite the other moderators you are talking about, because i see only @markyjackson-taulia and he already approve the request.

Thanks for your response

**Comment by jdumars** [comment]
@tuxtof first, thanks for the response and follow-up questions. There are certain parts of the moderator job that are challenging - the biggest of which is balancing the introduction of new things and the importance of doing it at the right time for the right reasons.  Slack, as a community tool is intended to facilitate discussion in ways that serve the community, and visibility is a key aspect of that. When we create new channels it should be with the intent of limiting unrelated conversations in another place, and in this case it would be away from core Cluster API conversations (or threads in that channel). From a philosophical angle, anyone requesting something _new_ bears the burden of explaining why it serves the broader community to have it, versus asking the community why it _shouldn't_. My concern is fundamentally: does the **current** level of conversation and unique discussion on this topic merit its own separate channel, since a new channel is not intended to serve as a validation or promotion tool. That would not be in the interest of the community, but in the interest of the requestor(s). 

All that said, the Cluster API provider communities pose a particular challenge for understanding activity/engagement. As a precedent, Oracle's provider is a similar scale and has already been approved. Based on that, I am willing to approve this request, but want to make the underlying motivations clear.

/approve

**Comment by jdumars** [comment]
If no other moderators are able to review tis by the end of the week, I will remove the hold.

**Comment by tuxtof** [comment]
hello @jdumars any news ? thanks

**Pull request merged**
