### PR TITLE
Update api-review label commands

### PR DESCRIPTION
**Pull request by liggitt**
`api-review` label commands added in https://github.com/kubernetes/test-infra/pull/11350

bot help commenting added in https://github.com/kubernetes/test-infra/pull/11351

### CODE REVIEW

**Comment by bgrant0607** [comment]
We've settled on the `/label` command? 

(I don't have a preference. I just am wondering whether it's settled.)

**Comment by liggitt** [comment]
> We've settled on the `/label` command?

That command is [already available](https://github.com/kubernetes/test-infra/pull/11350), which is attractive. Mostly waiting on @cblecker's feedback on https://github.com/kubernetes/test-infra/pull/11350#issuecomment-464842004 from a contribx perspective

**Pull request merged**
