### PR TITLE
Rename #k14s to #carvel

### PR DESCRIPTION
**Pull request by ewrenn8**

### CODE REVIEW

**Comment by coderanger** [comment]
Hi there, just for our records could you link the upstream project rename discussion?

**Comment by coderanger** [comment]
I've confirmed from the project blog that the rename is legit, though currently only partially complete. Good enough to move forward on our side though.

/lgtm
/approve

**Comment by ewrenn8** [comment]
Here is the referenced blog post detailing the rename: https://carvel.dev/blog

I have also signed the CLA, but I am not sure if the issue will autoupdate.

Thanks!
Eli

**Comment by ewrenn8** [comment]
Whoops, realized I didn't alphabetize! I will update the PR.

**Pull request merged**
