### PR TITLE
Update sig-auth leads

### PR DESCRIPTION
**Pull request by liggitt**
As discussed in the [20180207 sig-auth meeting](https://groups.google.com/forum/#!topic/kubernetes-sig-auth/Kd9fqQz7vtc) and on the [mailing list](https://groups.google.com/forum/#!topic/kubernetes-sig-auth/SqOJsdaG7CA)

* s/deads2k/tallclair/
* fixed sig-auth meeting playlist link
* added ability to list previous leads in the template, added previous sig-auth leads (emeritus term taken from https://github.com/kubernetes/community/pull/1650)

### CODE REVIEW

**Comment by liggitt** [comment]
cc @kubernetes/sig-auth-misc

**Comment by cblecker** [comment]
/assign @ericchiang @tallclair 
/approve
/hold

Approving for generator/template changes. Holding so that the other sig-auth leads can review the change.

**Comment by liggitt** [comment]
/assign @deads2k 
for ack on removal

**Comment by liggitt** [comment]
/hold cancel
reviewed by all leads

**Pull request merged**
