### PR TITLE
add schemahero channel

### PR DESCRIPTION
**Pull request by fshot**
Requesting a channel for discussion and support of the SchemaHero Open Source project. SchemaHero is a Kubernetes Operator that manages database schema migrations as code.

SchemaHero docs: https://schemahero.io/docs/
SchemaHero public repo: https://github.com/schemahero/schemahero

### CODE REVIEW

**Comment by alejandrox1** [comment]
SchemaHero looks interesting!
/ok-to-test
/lgtm

For a second review :)
/hold

**Comment by fshot** [comment]
Thanks, @alejandrox1 !  

What's our next step to get this reviewed/unheld/merged/etc?

**Comment by fshot** [comment]
Hi @alejandrox1 , @parispittman and @jeefy - any additional info we could provide to expedite getting this channel added?  Thanks in advance for your help!

**Pull request merged**
