### PR TITLE
removed deprecated munge script instructions

### PR DESCRIPTION
**Pull request by guineveresaenger**
There is no `hack/update-munge-docs.sh` script. Documentation should not refer to it.

### CODE REVIEW

**Comment by guineveresaenger** [comment]
Hoping the CLA bot likes me now...

**Comment by spiffxp** [comment]
@guineveresaenger Can you open a followup issue to remove the GENERATED_TOC tags from docs in this repo, mentioning this PR?  Alternatively, amend the PR to go ahead and remove those tags?

**Comment by guineveresaenger** [comment]
I'll go ahead and remove the tags from the repo

**Comment by spiffxp** [comment]
/lgtm
Removing GENERATED_ANALYTICS was more than I was asking for, but based on discussion https://github.com/kubernetes/community/pull/1112 I think we're safe nuking those tags

**Pull request merged**
