### PR TITLE
fix broken link : https://github.com/kubernetes/community/blob/master/contributors/devel/release.md

### PR DESCRIPTION
**Pull request by CriaHu**

### CODE REVIEW

**Comment by CriaHu** [comment]
@vishakhanihore

**Comment by vishakhanihore** [comment]
@nikhita

**Comment by tanjunchen** [comment]
@CriaHu  Can you help kk to fix broken urls?There are so many broken urls.Help.
ref:https://github.com/kubernetes/website/issues/17649

**Comment by nikhita** [comment]
Can you squash the commits into a single commit?

**Comment by CriaHu** [comment]
@tanjunchen  ok, I'll try my best. I'll do it after I work.

**Comment by tanjunchen** [comment]
@CriaHu squash five commits to one commit.

**Comment by tanjunchen** [comment]
@CriaHu what is up?can you reopen this pr?

**Comment by vishakhanihore** [comment]
I think he issues with squashing the commits

**Comment by tanjunchen** [comment]
@vishakhanihore  get it.

**Pull request closed without merging**
