### PR TITLE
Updating SIG Arch chairs

### PR DESCRIPTION
**Pull request by mattfarina**
/cc @bgrant0607 @jdumars

### CODE REVIEW

**Comment by cblecker** [comment]
Probably should go out to mailing list with lazy consensus period.

I am personally +1 on Matt's nomination.

**Comment by jdumars** [comment]
References: https://youtu.be/ffDeGtpOt3o and https://youtu.be/q7BNV99RyqY

**Comment by justaugustus** [comment]
+1

**Pull request merged**
