### PR TITLE
Move KEPs to top level directory

### PR DESCRIPTION
**Pull request by jbeda**

### CODE REVIEW

**Comment by dims** [comment]
LGTM 👍

**Comment by idvoretskyi** [comment]
LGTM

**Comment by mattfarina** [comment]
/lgtm

Though, doesn't mean much from me.

@idvoretskyi since you said LGTM can you use the `/lgtm` command so it can be merged. It appears you are a reviewer at the top level.

**Comment by mattfarina** [comment]
Well, it appears it did work for me.

**Comment by jbeda** [comment]
Thanks @mattfarina!

**Pull request merged**
