### PR TITLE
adding code-of-conduct.md

### PR DESCRIPTION
**Pull request by chrislovecnm**
closes https://github.com/kubernetes/community/issues/1414

We do not have this file in this repo.

/assign @cblecker

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
do we need such a file (if not existing) for all projects under kubernetes org?

**Comment by chrislovecnm** [comment]
@xiangpengzhao yes we do :)  It is part of the template project https://github.com/kubernetes/kubernetes-template-project

**Comment by chrislovecnm** [comment]
@xiangpengzhao we need that file for all our orgs ...

**Comment by xiangpengzhao** [comment]
>@xiangpengzhao we need that file for all our orgs ...

I guess most of the projects of all our orgs don't have that file...

**Pull request merged**
