### PR TITLE
Adding friday kubebuilder birds of a feather

### PR DESCRIPTION
**Pull request by shawn-hurley**
Adding an event for birds of a feather on Friday, December 14th for kubebuilder.

### CODE REVIEW

**Comment by jdumars** [comment]
/approve
It looks like this may be late.

**Comment by mrbobbytables** [comment]
Unfortunately this looks like it got missed in the last minute rush before KubeCon. :( Sorry about that @shawn-hurley. Would you mind if it gets closed out?

**Comment by shawn-hurley** [comment]
Not at all

**Pull request closed without merging**
