### PR TITLE
Add community meeting roles and update community meeting docs

### PR DESCRIPTION
**Pull request by nimbinatus**
Adding a roles doc as the community meeting is expanding some. Discussed in an [async retro thread in the Contribex Slack channel](https://kubernetes.slack.com/archives/C1TU9EB9S/p1647538893967319).

Note: I'm not sure if this is the precise place to put the roles doc, so please let me know if it's the wrong spot.

Relates to #6544

### CODE REVIEW

**Comment by parispittman** [comment]
my advice for rolebook placement is in the folder where the action will occur so that you can go into the owners file there for the thing instead of contribex chairs managing the role as it would be in the placement right now.

/lgtm
thanks a ton for your work here!

**Comment by nimbinatus** [comment]
Ahh, got it. So it would live next to the community meeting doc. I'll move it!

**Comment by nimbinatus** [comment]
Moved! @parispittman, was this where you were thinking of it belonging?

**Comment by nimbinatus** [comment]
ref: https://github.com/kubernetes/community/pull/7068

/close

**Pull request closed without merging**
