### PR TITLE
Add mission statement for sig-instrumentation

### PR DESCRIPTION
**Pull request by fabxc**
@kubernetes/sig-instrumentation-misc

### CODE REVIEW

**Comment by cblecker** [comment]
If this is approved by the sig, you will also need to run `make` to update all the related docs.

**Comment by piosz** [comment]
cc @sarahnovotny

**Comment by cblecker** [comment]
@fabxc Can you run a `make` to update all the other docs, and then commit the changes? Then this can merge. Thank you!

**Comment by fabxc** [comment]
PTAL

**Pull request merged**
