### PR TITLE
Add Eric Paris to Emeritus

### PR DESCRIPTION
**Pull request by eparis**
Not sure why I was forgotten given I was a founding member.

### CODE REVIEW

**Comment by mrbobbytables** [comment]
@eparis changes need to be made to sigs.yaml and then run make for it to update everything in all the right places^^;;

the list of CoCC emeritus folk are here:
https://github.com/kubernetes/community/blob/3220b0d33ca8ac3ad30071480e86d90081a5fa02/sigs.yaml#L3416-L3440

**Comment by mrbobbytables** [comment]
oh derp, nevermind! thats not using the generator, its in the custom content section - my bad^^;;;

**Comment by eparis** [comment]
@mrbobbytables I fixed it there as well.
@parispittman sorry, if you're willing to lgtm again

**Pull request merged**
