### PR TITLE
New slack channel for open-cluster-management

### PR DESCRIPTION
**Pull request by mikeshng**
open-cluster-management is a project focused on enabling end-to-end visibility and control across Kubernetes clusters.

https://github.com/open-cluster-management/community

The open-cluster-management architecture uses a hub - agent model. The hub centralizes control of all the managed clusters. An agent, which we call the klusterlet, resides on each managed cluster to manage registration to the hub and run instructions from the hub.

It is available under the Apache 2.0 license.

The channel name `open-cluster-mgmt` is chosen due to the character limit.

### CODE REVIEW

**Comment by markyjackson-taulia** [comment]
@mikeshng Your CLA needs to be signed, you can read more about that process [](https://github.com/kubernetes/community/blob/master/CLA.md)

/ok-to-test

**Comment by coderanger** [comment]
Is this associated with a SIG?

**Comment by mikeshng** [comment]
> Is this associated with a SIG?

yes this is associated with the `sig-multicluster`

**Comment by coderanger** [comment]
@mikeshng Should it be under `#sig-mutlicluster-open-cluster-mgmt` then?

**Comment by mikeshng** [comment]
> @mikeshng Should it be under `#sig-mutlicluster-open-cluster-mgmt` then?

Hi @coderanger We are associated with sig-multicluster but we are also partner with other groups such as submariner.io.
If possible we would like to use the channel name 'open-cluster-management' but if there is a character limit then 'open-cluster-mgmt'. Thanks.

**Pull request merged**
