### PR TITLE
Update channels.yaml

### PR DESCRIPTION
**Pull request by azarudeena**
New channel request for CKS-exam-prep

### CODE REVIEW

**Comment by idvoretskyi** [comment]
@azarudeena please sign the CLA first.

**Comment by azarudeena** [comment]
> @azarudeena please sign the CLA first.

**Comment by azarudeena** [comment]
CLA signed

**Review by idvoretskyi — APPROVED** [review]
/lgtm

CKS exam is not available yet, but already announced - https://training.linuxfoundation.org/certification/certified-kubernetes-security-specialist/

**Pull request merged**
