### PR TITLE
Add spiffxp as approver

### PR DESCRIPTION
**Pull request by spiffxp**
I'd like to request approver status for this repo based on:
- experience as steering emeritus
- prior review history (of the last 100 merged prs involving me, I authored 16 and commented on 53)
- experience with sigs.yaml tooling

### CODE REVIEW

**Comment by spiffxp** [comment]
/assign @cblecker @mrbobbytables @nikhita 
given the overlap of steering and contribex here

**Review by nikhita — APPROVED** [review]
I'm good with this.

/lgtm
/approve

/hold 
for @cblecker and @mrbobbytables

**Comment by mrbobbytables** [comment]
I'm good with this 👍 
/lgtm

**Review by idvoretskyi — APPROVED** [review]
/lgtm

+1

**Comment by cblecker** [comment]
No concerns.

**Pull request merged**
