### PR TITLE
[WG Naming] Update icons to use control plane

### PR DESCRIPTION
**Pull request by celestehorgan**
Signed-off-by: Celeste Horgan <celeste@cncf.io>

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/community/issues/4913

This PR updates the `master` icon to use the phrase `control plane` instead, per the [recommendation](https://github.com/kubernetes/community/blob/master/wg-naming/recommendations/001-master-control-plane.md).

### CODE REVIEW

**Review by gkarthiks — APPROVED** [review]
awesome!!!!

**Comment by nikhita** [comment]
/assign @thockin 
since this relates to icons

**Review by thockin — COMMENTED** [review]
/sig graphic-design

/lgtm
/approve

**Pull request merged**
