### PR TITLE
Add KEP for CNI traffic shaping support

### PR DESCRIPTION
**Pull request by Lion-Wei**
Add KEP for CNI traffic shaping support.

Much of the meat in the KEP was taken from the original proposal.
(https://github.com/kubernetes/community/pull/1893)

We have been discussed about this proposal for a while, and already have a pr for basic realization: 
https://github.com/kubernetes/kubernetes/pull/63194

### CODE REVIEW

**Comment by justaugustus** [comment]
REMINDER: KEPs are moving to [k/enhancements](https://github.com/kubernetes/enhancements) on November 30. Please attempt to merge this KEP before then to signal consensus.
For more details on this change, review [this thread](https://groups.google.com/d/msg/kubernetes-dev/LIkZoIqCT20/t515CV2mAgAJ).

Any questions regarding this move should be directed to that thread and not asked on GitHub.

**Comment by justaugustus** [comment]
KEPs [have moved](https://github.com/kubernetes/enhancements/pull/638) to [k/enhancements](https://github.com/kubernetes/enhancements). 
This PR will be closed and any additional changes to this KEP should be submitted to k/enhancements.
For more details on this change, review [this thread](https://groups.google.com/d/msg/kubernetes-dev/LIkZoIqCT20/t515CV2mAgAJ).

Any questions regarding this move should be directed to that thread and not asked on GitHub.
/close

**Comment by uablrek** [comment]
@thockin It looks like this KEP was never moved to k/enhancements. So there is no tracking for this function and it has been left in alpha/experimental for >3 years. How to proceed? Kan I make a PR to add it as-is to k/enhancements?

**Comment by thockin** [comment]
You can bring it to k/enhancements, sure.  The KEP template has evolved some, but sure.  With the caveat that we're trying to finish a bunch of in-flight work before actively staring new debates :)

**Comment by uablrek** [comment]
But this one has been in-flight for 3 years, but unfortunately in "stealth mode".

**Pull request closed without merging**
