### PR TITLE
Request pinniped Slack channel

### PR DESCRIPTION
**Pull request by ankeesler**
Hi there -

We (@cfryanr and @mattmoyer) would like to create a Kubernetes Slack channel for our project, Pinniped.
* Pinniped is an new project that will be open sourced in the coming weeks.
* Pinniped provides identity services to Kubernetes.
* We realize that we don't have any links to our project to share right now, but our hope is that we can go ahead and start the process of creating a Kubernetes Slack channel so that we can have a Slack channel as close to release as possible.
* Pinniped development is sponsored by VMware, Inc.

**Which issue(s) this PR fixes**:

None.

### CODE REVIEW

**Comment by markyjackson-taulia** [comment]
ok-to-test

**Comment by jdumars** [comment]
Typically I am opposed to creating Slack channels for projects that are not open source, as the purpose of our Slack as I see it is to _organize_ an existing community, not _seed_ it. When I approve Slack channels for external projects, I always look at contributor activity, adoption and so forth, otherwise this community becomes a vehicle for promotion instead of promulgation. Establishing and maintaining a Slack channel should be an inflection point in a projects adoption.

**Comment by jeefy** [comment]
100% agree with Jaice on this.

**Comment by neolit123** [comment]
fully agree with @jdumars.

the slack channel should be created only after the project is open source and once there is demand for such a channel.

**Comment by ankeesler** [comment]
Makes sense to me. We figured that might be the case, but wanted to test that assumption by opening up the PR anyway.

We will circle back once we have gone public.

**Comment by jdumars** [comment]
@ankeesler do you mind closing this PR and re-opening at a later time?

**Comment by ankeesler** [comment]
@jdumars sure, will do.

**Comment by ankeesler** [comment]
Hey again everyone! Our project (Pinniped) has gone public: https://pinniped.dev. We would like to resubmit this proposal for a Kubernetes channel. We appreciate your time and consideration.

**Pull request merged**
