### PR TITLE
fix: Rename kubernetes-docs-be to kubernetes-docs-bn

### PR DESCRIPTION
**Pull request by irvifa**
**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/community/issues/5210

### CODE REVIEW

**Comment by sftim** [comment]
Does this need to be merged before or after renaming https://kubernetes.slack.com/messages/kubernetes-docs-be ?

**Comment by sftim** [comment]
Ah, this might need to be 2 PRs:
https://github.com/kubernetes/community/tree/master/communication/slack-config#channels

> To rename a channel, set its id property to its current Slack ID, then change the name.

**Comment by sftim** [comment]
Won't this destroy the existing channel for Bengali? Is that what you wanted @irvifa ?

It seems that the bot _can_ do proper renames, I can help with that if you'd like.

**Comment by irvifa** [comment]
Probably we can rename the slack first, since the kubernetes-docs-be is still referenced if we don't change that first 👀 
```
2020/10/12 12:21:19 This configuration cannot be applied against the current reality:
2020/10/12 12:21:19 Error 1: channel kubernetes-docs-be (CQ0TD298C) not referenced in config.
2020/10/12 12:21:19 In dry run mode so taking no action, but this is what we would've done:
2020/10/12 12:21:19 Step 1: Create new channel: kubernetes-docs-bn.
2020/10/12 12:21:19 Reconciliation failed: there were configuration errors
```

**Comment by mrbobbytables** [comment]
You need the slack channel ID - here is an example commit where a channel was renamed:
https://github.com/kubernetes/community/commit/362f2f35db4391151ece134c983bcb0fd2fbc55a

**Review by sftim — COMMENTED** [review]
/lgtm

**Pull request merged**
