### PR TITLE
Make link to SIG creation procedure easier to find

### PR DESCRIPTION
**Pull request by pmorie**
It was at the very bottom of the README, after a very, very long list.

### CODE REVIEW

**Comment by idvoretskyi** [comment]
@pmorie I suppose, the goal of the order was the following: a person will review the list of the existing groups; if he/she won't find the desired one, he/she will start working on establishing the new one.

**Comment by pmorie** [comment]
@idvoretskyi that's cool - I'll make a change to make that a little more obvious, then.

**Comment by philips** [comment]
I am fine with this change but it conflicts now :(

**Comment by pmorie** [comment]
Whoops, I'll finish this.

**Comment by bgrant0607** [comment]
This is obsolete.

**Pull request closed without merging**
