### PR TITLE
Added Nick Turner as new sig cloud provider co-chair.

### PR DESCRIPTION
**Pull request by cheftako**
**Which issue(s) this PR fixes**:
Fixes # N/A

Adds Nick Turner as a new co-chair to sig cloud provider

### CODE REVIEW

**Comment by jdumars** [comment]
Is there any supporting documentation for this change?

**Comment by mrbobbytables** [comment]
/hold

leadership changes need to goto k-dev with a lazy consensus period

ref: https://github.com/kubernetes/community/blob/master/contributors/chairs-and-techleads/leadership-changes.md

**Comment by nckturner** [comment]
We have a recorded meeting with a vote but I just checked the [meeting notes](https://docs.google.com/document/d/1OZE-ub-v6B8y-GuaWejL-vU_f9jsjBbrim4LtTfxssw/) and we noted the election but not the result :D

**Comment by andrewsykim** [comment]
/lgtm 

Thanks @nckturner

**Comment by cheftako** [comment]
> > Is there any supporting documentation for this change?
> 
> We have a recorded meeting with a vote but I just checked the [meeting notes](https://docs.google.com/document/d/1OZE-ub-v6B8y-GuaWejL-vU_f9jsjBbrim4LtTfxssw/) and we noted the election but not the result :D

[Video of the meeting including the election](https://www.youtube.com/watch?v=Avv7jS8LPT8&list=PL69nYSiGNLP3dXLcYbRKCbpPCN-8CDFAB&index=49)

**Comment by cheftako** [comment]
> /hold
> 
> leadership changes need to goto k-dev with a lazy consensus period
> 
> ref: https://github.com/kubernetes/community/blob/master/contributors/chairs-and-techleads/leadership-changes.md

Thanks Bob :D I have now sent the email to k-dev (Sent Thu, Dec 16, 1:43 PM)

**Comment by jdumars** [comment]
Lazy consensus period has passed, no objections, and link to discussion above. Thanks everyone!
/approve

**Comment by jdumars** [comment]
@cheftako feel free to unhold at your convenience

**Comment by nckturner** [comment]
@cheftako, I completed the "Inclusive Open Source Community Orientation".

**Pull request merged**
