### PR TITLE
Fix timezone for SIG-VMware meetings

### PR DESCRIPTION
**Pull request by frapposelli**

### CODE REVIEW

**Comment by cblecker** [comment]
/approve
LGTM to a sig-vmware lead

**Comment by frapposelli** [comment]
/lgtm

as @cantbewong and I discussed this yesterday

**Comment by frapposelli** [comment]
duh, @cantbewong please lgtm this

**Comment by cblecker** [comment]
@cantbewong hint hint: https://github.com/kubernetes/community/blob/master/community-membership.md#member

/lgtm
:)

**Pull request merged**
