### PR TITLE
fix: update volume plugin link.

### PR DESCRIPTION
**Pull request by Colstuwjx**

### CODE REVIEW

**Comment by Colstuwjx** [comment]
fixes #4330 , Ping related doc owner @saad-ali .

**Comment by Colstuwjx** [comment]
Update background:

the strings pkg was moved to separate repo within [this PR](https://github.com/kubernetes/kubernetes/pull/73455), since the kubernetes integration of CSI is active developing feature, and our users still need to read the design proposal to know more about the details, I think update this out-dated link is meaningful.

Thanks.

**Comment by vishakhanihore** [comment]
/assign @childsb
cc: @mrbobbytables

**Comment by mrbobbytables** [comment]
Thanks all!
/ok-to-test
/approve

**Pull request merged**
