### PR TITLE
Update Sig-Security meeting to new time.

### PR DESCRIPTION
**Pull request by PurelyApplied**
* Monday 12:00 -> Thursday 9:00

----

With the new year, Sig-Security has moved its meeting time.

/sig security

### CODE REVIEW

**Comment by PurelyApplied** [comment]
Out of scope for the given commit message, but should we assign owners for the subteams as well?  I'll bring it up in tomorrow's meeting.

**Comment by mrbobbytables** [comment]
/assign @IanColdwater @tabbysable 
For sign off 👍

**Comment by tabbysable** [comment]
Looks good, thanks @PurelyApplied

**Pull request merged**
