### PR TITLE
sig-auth: Add sig-auth-tools repo

### PR DESCRIPTION
**Pull request by mrbobbytables**
ref: https://github.com/kubernetes/org/issues/3688

@enj should this be a new subproject? or is there another that would be better?

### CODE REVIEW

**Comment by enj** [comment]
We are currently only planning to use this repo to hold GitHub actions workflows to automate our project boards.  Does that count as a sub project?

**Comment by mrbobbytables** [comment]
Yes, essentially if there is a repo for it - there must be a sig/subproject for it to bubble up to for ownership.

**Comment by enj** [comment]
@mrbobbytables okay this PR is basically correct then.  Should we add a description for the section like "Tooling to automate the SIG Auth project boards" ?

**Comment by mrbobbytables** [comment]
@enj sorry, missed your response earlier - I'll update it the description

**Pull request merged**
