### PR TITLE
SIG-CL: promote vincepri to SIG chair; timothysc to emeritus

### PR DESCRIPTION
**Pull request by timothysc**
"Bowing out, to make way for all the good work that Vince has been doing!"

/assign @neolit123 @justinsb @fabriziopandini 
/cc @vincepri 
/hold

### CODE REVIEW

**Comment by dims** [comment]
thanks a ton for all your leadership and guidance over the years @timothysc !

**Comment by neolit123** [comment]
echoing what @dims says. a big thank you, @timothysc !
welcome to this new position @vincepri 

i will email the ML about this.

**Comment by vincepri** [comment]
Thank you @timothysc for your leadership and mentorship over these many years. I've learned tons from you and will make sure to uphold all your teachings.

**Comment by neolit123** [comment]
/retitle SIG-CL: promote vincepri to SIG chair; timothysc to emeritus

**Comment by neolit123** [comment]
notified the ML:
https://groups.google.com/g/kubernetes-sig-cluster-lifecycle/c/LDF5udJnrzI

applying lazy consensus until Monday next week.

**Comment by justaugustus** [comment]
Incredibly well-deserved.
Congrats @vincepri! 💕

**Comment by nikhita** [comment]
Congrats @vincepri! :)

@neolit123 Based on https://github.com/kubernetes/community/blob/master/contributors/chairs-and-techleads/leadership-changes.md, can you also forward the email to k-dev with a lazy consensus deadline of one week?

@vincepri can you comment on this PR once you've taken the [inclusive leadership course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)?

**Comment by fabriziopandini** [comment]
Thank you @timothysc for your leadership and mentorship!
Congrats @vincepri!
/lgtm
/approve

**Comment by neolit123** [comment]
@nikhita 

> @neolit123 Based on https://github.com/kubernetes/community/blob/master/contributors/chairs-and-techleads/leadership-changes.md, can you also forward the email to k-dev with a lazy consensus deadline of one week?

done, forwarded.
thanks for reminding me.

**Comment by vincepri** [comment]
Thank you @nikhita!
I'll carve out time today to complete LFC102, thanks!

**Comment by vincepri** [comment]
@nikhita Completed the course yesterday 😊

**Pull request merged**
