### PR TITLE
Advocate for running conformance tests in multiple architectures

### PR DESCRIPTION
**Pull request by dims**
We have been talking about and progressing towards multi-arch support for a long while now: https://github.com/kubernetes/kubernetes/issues/38067

We have active work being done to ensure that container images used in e2e test suite can run across multiple architectures. So we should make sure we don't add to this debt.

- https://github.com/kubernetes/kubernetes/issues/66626
- https://github.com/kubernetes/kubernetes/issues/66618

### CODE REVIEW

**Comment by jdumars** [comment]
/lgtm

Adding to the architecture agenda for next week.

**Comment by jdumars** [comment]
How did this get approved? @cblecker @dims

**Comment by liggitt** [comment]
> How did this get approved? @cblecker @dims

somehow 0 commits got pushed to the branch?

I assume it's because you added lgtm, and there were no unapproved files

**Comment by cblecker** [comment]
yeah. zero commits in the branch, so no files to look for owners in. Nothing got merged though, as if you push no commits to the branch, github closes the PR.

**Comment by dims** [comment]
Hmm ... scratching my head, why did i close this?

**Comment by dims** [comment]
never mind, starting again fresh

**Pull request closed without merging**
