### PR TITLE
take Phillip Wittrock out of contrib-x sig-leads

### PR DESCRIPTION
**Pull request by pwittrock**

### CODE REVIEW

**Comment by grodrigues3** [comment]
can you remove from [here](https://github.com/kubernetes/community/tree/master/sig-contributor-experience) too

**Comment by cblecker** [comment]
Please remove from sigs.yaml and run a `make` instead

**Comment by pwittrock** [comment]
updated PTAL

**Comment by grodrigues3** [comment]
Docs removal was on purpose too right?  If so,

/lgtm

**Pull request merged**
