### PR TITLE
Add Debanitrkl as shadow for Marketing Council

### PR DESCRIPTION
**Pull request by Debanitrkl**
**Which issue(s) this PR fixes**:

Related to #6399 

**Description**
Added a shadow under Marketing Council Promotional Lead

### CODE REVIEW

**Comment by chris-short** [comment]
Awesome stuff! I wonder if we should remove the "Shadow role is available." on this line though. I can't speak for @kaslin or the larger group. But, I know having multiple shadows doesn't always scale easily or linearly.

**Review by chris-short — CHANGES_REQUESTED** [review]
Remove "Shadow role is available." for now

**Comment by kaslin** [comment]
/lgtm
and sorry for delayed review!

**Pull request merged**
