### PR TITLE
Add alisondy as sig-contribex co-chair

### PR DESCRIPTION
**Pull request by nikhita**
Ref: https://github.com/kubernetes/community/issues/5442

Thanks for everything you've done for contribex over _so many years_, @castrojo! :heart: 

Welcome @alisondy! Super excited to have you as part of contribex leadership!! :rocket: :tada:  

Ref: https://groups.google.com/g/kubernetes-dev/c/TYwMb3lbuyE, https://groups.google.com/g/kubernetes-sig-contribex/c/KDenBAhiDxc

/hold
/cc @castrojo @mrbobbytables @cblecker @alisondy 
/assign @alisondy @castrojo

### CODE REVIEW

**Comment by nikhita** [comment]
@alisondy for the record -- can you confirm that you've completed the Inclusive Leadership Training?

**Comment by cblecker** [comment]
/lgtm
/approve

Welcome to the team, Alison!

**Comment by alisondy** [comment]
> @alisondy for the record -- can you confirm that you've completed the Inclusive Leadership Training?

Yes, I have done the training 😁

image

**Comment by nikhita** [comment]
Yay!

/hold cancel

**Pull request merged**
