### PR TITLE
Add channel for release notes team discussion, transparency and continuity

### PR DESCRIPTION
**Pull request by onyiny-ang**
To follow up from the discussion in [Slack:](
https://kubernetes.slack.com/archives/C1TU9EB9S/p1567608031060200)
I am proposing a new channel for release notes team discussion.

### CODE REVIEW

**Comment by jeefy** [comment]
Does it make sense to name it `relnotes` or should we use the full name of `release-notes`? I lean towards the latter as we've created `release-ci-signal` and `release-management` and consistency is 💯

**Comment by mrbobbytables** [comment]
> Does it make sense to name it `relnotes` or should we use the full name of `release-notes`? I lean towards the latter as we've created `release-ci-signal` and `release-management` and consistency is 💯

I'm in favor of spelling out for clarity and conforming with the other channels. That also means that it should be moved under `sig-release` config where the sig leads can approve 👍

**Comment by onyiny-ang** [comment]
Happy to move it under `sig-release` and spell out the full name of `release-notes` or `release-notes-discussion` as @tpepper suggested. I will change it to the former for now, pending further discussion :)

**Comment by idealhack** [comment]
/hold

for sig leads to review

**Comment by justaugustus** [comment]
`release-notes` seems like the right choice for consistency. Enjoy! :)
/lgtm
/approve
/hold cancel

**Pull request merged**
