### PR TITLE
guide for windows onboarding / contributing

### PR DESCRIPTION
**Pull request by jayunit100**
https://github.com/kubernetes/community/issues/5229

### CODE REVIEW

**Comment by jsturtevant** [comment]
we should include or link to the content in https://github.com/kubernetes/community/blob/master/sig-windows/CONTRIBUTING.md

**Comment by jayunit100** [comment]
want me to just move that file entirely?

**Review by mrbobbytables — COMMENTED** [review]
Some of this content might be better for your contributing.md file. In general the devel docs should focus on developer documentation and contributing.md is how you get on-ramped into the sig if it differs from the regular contributor guide. Theres definitely some bleed over between that for windows where you DO have a very different means to onramp/develop/test.

We have the intention of publishing the devel content on https://k8s.dev next to the contributor guide, so a better way of thinking about this doc might be what would you want to publish there next to the rest of the developer documentation.

**Comment by parispittman** [comment]
+1 to CONTRIBUTING.md in the sig-windows area

**Pull request closed without merging**
