### PR TITLE
Updated SIG-AWS leads

### PR DESCRIPTION
**Pull request by idvoretskyi**
Updated SIG-AWS leads according to https://github.com/kubernetes/community/blob/master/sig-aws/README.md

### CODE REVIEW

**Comment by idvoretskyi** [comment]
cc @kubernetes/sig-aws

**Comment by kris-nova** [comment]
Woo! This LGTM - Thanks for adding us.

**Comment by kris-nova** [comment]
CC: @chrislovecnm and @justinsb Not sure if the @kubernetes/sig-aws mention works or not.. I just happened upon the PR

**Comment by chrislovecnm** [comment]
@sarahnovotny was the decision to remove @mfburnett, don't think it was.  All for adding @kris-nova since she is assisting.

**Comment by mfburnett** [comment]
Hey all! With the Redspread-CoreOS transition, I've been pretty quiet as a SIG leader - I am interested in getting more involved again now that I've settled at CoreOS. :) Would love to remain as a SIG-AWS lead, if there's still room!

As a start, I recently sent out [this survey](https://docs.google.com/forms/d/e/1FAIpQLSf7rktZ_1QABIPkzYqxlMuGSE4W82ZFUYmyYk0ER7tqHMPBRg/viewform) and have a really good chunk of data so far. Will share with everyone once we get a few more responses.

**Comment by chrislovecnm** [comment]
@mfburnett love to have you.  Two ladies involved is INCREDIBLE!!!!  Two ladies that code that are involved ... mind blown

**Comment by kris-nova** [comment]
Actually it looks like I am already in the PR.. can we just add @mfburnett back?

**Comment by idvoretskyi** [comment]
As @mfburnett hasn't been mentioned here - https://github.com/kubernetes/community/blob/master/sig-aws/README.md, I decided to submit this PR with personas from the referenced README.

Anyway, fixed, @kris-nova @chrislovecnm @mfburnett @justinsb please, review.

**Comment by kris-nova** [comment]
Should we also add @mfburnett to the README [here](https://github.com/kubernetes/community/blob/master/sig-aws/README.md)?

I think we should.

**Comment by idvoretskyi** [comment]
@kris-nova yes, absolutely.

Created a PR https://github.com/kubernetes/community/pull/105

**Comment by kris-nova** [comment]
This LGTM - everyone else?

**Comment by kris-nova** [comment]
@chrislovecnm - can you review and merge if you have no other issues please?

**Comment by sarahnovotny** [comment]
I think @mfburnett is an open question.  i'll ping her again on chat and
see if we can get an answer.

**Pull request merged**
