### PR TITLE
Replace k/security with k/committee-security-response in k/community/sig-security

### PR DESCRIPTION
**Pull request by PushkarJ**
/sig security 

/hold for https://github.com/kubernetes/org/issues/2967

### CODE REVIEW

**Comment by mrbobbytables** [comment]
Can you also update this: 
https://github.com/kubernetes/community/blob/6685de2e4a993039f8e79582b6b4426c8cb03cb2/sigs.yaml#L3239

and re-run make?

**Comment by tabbysable** [comment]
re-adding hold because I think we are likely to upgrade master->main on `kubernetes/committee-security-response`
/hold
/lgtm

**Comment by mrbobbytables** [comment]
default branch has now been renamed 👍

**Comment by PushkarJ** [comment]
Switched `master` to `main`. 

Need review or `/lgtm` again

**Comment by PushkarJ** [comment]
/label tide/merge-method-squash

Trying again

**Pull request merged**
