### PR TITLE
updated contributors/guide/pull-requests.md

### LINKED ISSUE #6868: Broken link need to fix
**This is a Bug Report**

**Problem:**
visit this page [pull-requests](https://www.kubernetes.dev/docs/guide/pull-requests/)
when we click on this `Kubernetes Enhancement Proposal process` it returns 404 not found page,so this needs to be fix.

**Proposed Solution:**
correct link of md file require to provide.

**Page to Update:**
https://www.kubernetes.dev/docs/guide/pull-requests/

/sig docs
/assign
/kind bug

### PR DESCRIPTION
**Pull request by amolmote**
Signed-off-by: amolmote <amolmote201@gmail.com>
Fixes #6868

### CODE REVIEW

**Comment by jdumars** [comment]
/approve

Thanks for fixing the link!

**Comment by amolmote** [comment]
thank you @jdumars

**Comment by mtardy** [comment]
I came to this because of a similar issue in k/website, this fix is okay!
/lgtm

**Pull request merged**
