### PR TITLE
Add aws-service-operator channel

### PR DESCRIPTION
**Pull request by sfzylad**
Since #4362 seems to be stuck for some time now I decided to retry on proposing the change. Hopefully my CLA works fine.

**Which issue(s) this PR fixes**:
Doesn't fix but addresses: aws/aws-service-operator-k8s#12

### CODE REVIEW

**Comment by mrbobbytables** [comment]
hm..after reading more about it, I think it'd be more appropriate to use the current provider-aws channel. There doesn't seem to be anything in the project itself yet outside of some design docs =/

**Comment by jeefy** [comment]
I'm confused here a bit. The project docs already say to use the #provider-aws Slack channel. Is the intent to change this? Does the project have enough chatter that it makes logical sense to shift it over to its own channel?

**Comment by jdumars** [comment]
I'm a third on feeling like this request may not be needed. Could we close this PR in o(days)?

**Comment by mrbobbytables** [comment]
I'm +1 to close... @sfzylad if you'd like to discuss this further, please don't hesitate to reopen and we can pick up the conversation again. 👍 

With that, going to go ahead and close.

/close

**Pull request closed without merging**
