### PR TITLE
Update README.md to Reflect Correct Leads for SIG Windows and SIG UI

### PR DESCRIPTION
**Pull request by josephjacks**

### CODE REVIEW

**Comment by josephjacks** [comment]
@sarahnovotny please review, thanks!

**Comment by sarahnovotny** [comment]
is there another (outside of apprenda) person we can add as a co-lead?

**Comment by josephjacks** [comment]
Good question, @sarahnovotny -- I know @brendandburns has taken special interest in SIG Windows, of late. Perhaps he can co-lead. Thoughts? cc @michmike

**Comment by michmike** [comment]
I don't mind at all. @brendandburns would be a great addition to the team if he wants to co-lead and actively participate.

**Comment by sarahnovotny** [comment]
I've pinged @brendandburns out of band... asked if he has the time or a team member to contribute here.

**Comment by asultan001** [comment]
Any updates here? In the meantime it would be great to at least update the current information as it is incorrect.

Cheers
Abe

**Comment by sarahnovotny** [comment]
@josephjacks i don't see the rebase... was that a future yes?

**Comment by sarahnovotny** [comment]
closed in favor of kubernetes/community/pull/82

**Pull request closed without merging**
