### PR TITLE
Initialize contributing cheatsheet in Bahasa Indonesia.

### PR DESCRIPTION
**Pull request by irvifa**
This is an initial commit for contributor cheat sheet thus addressing https://github.com/kubernetes/website/issues/13996

### CODE REVIEW

**Comment by mrbobbytables** [comment]
@irvifa thank you for taking on the localization of the cheatsheet to Indonesian.  Really appreciate your efforts :)

**Comment by mrbobbytables** [comment]
@irvifa  would you mind squashing your commits down? Once that's done I'll lgtm 👍

**Comment by irvifa** [comment]
@mrbobbytables Done, thanks for reminding me 🙂

**Comment by mrbobbytables** [comment]
Awesome! Thanks so much :)

/lgtm

**Comment by irvifa** [comment]
@mrbobbytables so i'll still need approve from the owners right?

**Comment by mrbobbytables** [comment]
Yup, one should hop in soon :)

**Comment by castrojo** [comment]
/approve

Thanks for this, we appreciate it!

**Pull request merged**
