### PR TITLE
slack: create new channel for nginx-ingress development and rename the existing

### PR DESCRIPTION
**Pull request by cpanato**
- create new channel to use for nginx ingress development
- rename existing ingress-nginx to be ingress-nginx-users for
support/general chat and also match other channels name.

We would like to have a channel to discuss the future and current development of nginx-ingress but not in the existing channel that is being used for support/questions.

also, rename the existing channel to match other channels that the main idea is for users of the tool/service ask questions/socialize/support. 

**Which issue(s) this PR fixes**:

Fixes #

cc @rikatz @strongjz @ElvinEfendi

### CODE REVIEW

**Comment by rikatz** [comment]
/lgtm

Thanks Carlos!!!

**Comment by mrbobbytables** [comment]
/lgtm 
👍

**Pull request merged**
