### PR TITLE
Add bio for Quinton Hoole for 2018 steering committee election.

### PR DESCRIPTION
**Pull request by quinton-hoole**

### CODE REVIEW

**Comment by castrojo** [comment]
You're about 150 words over the 300 word limit. :)

**Comment by quinton-hoole** [comment]
@castrojo The number includes the linked URL's.  I'll try to trim it down a bit.

**Comment by quinton-hoole** [comment]
Here ya go @castrojo 

```
$ wc -w quintonhoole.md 
297 quintonhoole.md
```

**Pull request merged**
