### PR TITLE
Update SIG-Cloud-Provider leadership

### PR DESCRIPTION
**Pull request by hogepodge**
Move Chris Hoge to SIG-Cloud-Provider emeritus lead status.

### CODE REVIEW

**Comment by nikhita** [comment]
> /hold
>
> For closing of code freeze and new leader nominations.

/hold
to actually add the label

**Comment by nikhita** [comment]
Needs rebase.

> For closing of code freeze and new leader nominations.

@hogepodge Just want to double check...you'd like to move to emeritus now and new lead nominations would take place later. Would that be correct?

**Comment by hogepodge** [comment]
@nikhita yes, that is correct. I’ve moved on from the OpenStack Foundation to GitLab and while I’ll remain active in the Kubernetes community I will not be participating in cloud provider integration efforts any more.

**Comment by nikhita** [comment]
@hogepodge Thanks for the confirmation! Could you rebase the PR, will approve after that (since @cheftako already lgtm'd as well) :)

**Comment by andrewsykim** [comment]
LGTM as well :)

**Pull request merged**
