### PR TITLE
sig-instrumentation: add rexagod to leads

### PR DESCRIPTION
**Pull request by rexagod**
Refer: https://groups.google.com/g/kubernetes-sig-instrumentation/c/eXBbjS38J_Y/m/AMHi7tZjAQAJ

_Signed-off-by: Pranshu Srivastava <rexagod@gmail.com>_

cc @logicalhan

### CODE REVIEW

**Review by logicalhan — APPROVED** [review]
/lgtm
/approve

**Review by logicalhan — APPROVED** [review]
/lgtm
/approve

**Review by cblecker — APPROVED** [review]

**Pull request merged**
