### PR TITLE
details on versioned and unversioned clients

### PR DESCRIPTION
**Pull request by MHBauer**
@caesarxuchao @pmorie 

This can probably use some wordsmithing, along with an additional paragraph about WHY we want each of these types of clients. I do not know the answer.

I mainly wanted to get the warning about needing the trailing slash in, as it is an awkward user experience.

### CODE REVIEW

**Comment by MHBauer** [comment]
Is this awkwardness an issue in need of correction?

**Comment by MHBauer** [comment]
My attempt to 'fix the problem' is in https://github.com/kubernetes/kubernetes/pull/41094.

**Comment by bgrant0607** [comment]
cc @kubernetes/sig-api-machinery-pr-reviews

**Comment by smarterclayton** [comment]
I think if we add more paragraphs they'd probably be somewhere else.  However, note on it could be as simple as:

> Versioned clients are created to be compatible with a public, versioned endpoint.  Unversioned (internal) clients were historically used in some parts of the core codebase, and are gradually being replaced by the use of versioned clients.

**Comment by smarterclayton** [comment]
This otherwise LGTM

**Pull request closed without merging**
