### PR TITLE
Add contact info for Cluster API Add-on Provider for Helm

### PR DESCRIPTION
**Pull request by Jont828**
**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/lgtm
/approve

**Comment by neolit123** [comment]
```
1 mismatches were detected.
Do not manually edit sig-list.md or README.md files inside the sig folders.
Instead make your changes to sigs.yaml, then run `make`, and then
commit your changes to sigs.yaml and any generated docs.

```

try editing the sigs.yaml and then running `make generate` (or whatever rule generates the readme)

**Comment by Jont828** [comment]
@neolit123 Think that should do the trick!

**Review by neolit123 — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
