### PR TITLE
Update the branch name from master to main

### PR DESCRIPTION
**Pull request by vaibhav2107**
Update the link that references to [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### CODE REVIEW

**Comment by vaibhav2107** [comment]
Hi @jdumars , @justaugustus 
Could you please have a look

**Review by MadhavJivrajani — APPROVED** [review]
/ok-to-test
/lgtm
Thanks!
/assign @jdumars

**Comment by vaibhav2107** [comment]
Thanks @MadhavJivrajani

**Review by mrbobbytables — COMMENTED** [review]
/approve

**Pull request merged**
