### PR TITLE
Add token file reload to client library requirements

### PR DESCRIPTION
**Pull request by liggitt**
**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/kubernetes/issues/68164

Status of existing client libraries applying this change:

- [x] https://github.com/kubernetes-client/python/issues/616
- [x] https://github.com/kubernetes-client/javascript/issues/317
- [x] https://github.com/kubernetes-client/haskell/issues/54
- [x] https://github.com/kubernetes-client/csharp/issues/293
- [x] https://github.com/kubernetes-client/ruby/issues/47
- [x] https://github.com/kubernetes-client/java/issues/652
- [ ] https://github.com/kubernetes-client/perl/issues/12 (no inclusterconfig or tokenfile support yet)

/cc @mikedanese @zshihang @deads2k @lavalamp

### CODE REVIEW

**Comment by liggitt** [comment]
huh... is there a replacement location for this doc I'm missing?

**Comment by mrbobbytables** [comment]
@liggitt Theres a blockade rule for all of design-proposals as they've been deprecated and replaced by KEPs. Ideally information from there gets integrated into various documentation in the devel directory.

**Comment by liggitt** [comment]
I'd like to override the blockade for this update, since this file is still getting actively referenced for new clients (xref https://groups.google.com/g/kubernetes-sig-api-machinery/c/9TT-7_WMPCE/m/GV3VJNluBQAJ)

follow up to move it to a more visible / current location seems good as well.

**Comment by mrbobbytables** [comment]
Done :+1:

**Comment by ahmetb** [comment]
Is the reloading actually implemented in client-go? The [rest.InClusterConfig()](https://github.com/kubernetes/client-go/blob/v0.25.2/rest/config.go#L512) which is referenced from [some `client-go/examples`](https://github.com/kubernetes/client-go/tree/master/examples/in-cluster-client-configuration) seems to be still reading the token file only once.

**Comment by liggitt** [comment]
> Is the reloading actually implemented in client-go? The [rest.InClusterConfig()](https://github.com/kubernetes/client-go/blob/v0.25.2/rest/config.go#L512) which is referenced from [some `client-go/examples`](https://github.com/kubernetes/client-go/tree/master/examples/in-cluster-client-configuration) seems to be still reading the token file only once.

yes, it plumbs both the value read and BearerTokenFile into the resulting config. When BearerTokenFile is set, it drives reloading behavior

**Pull request merged**
