### PR TITLE
Add a charter for sig windows.

### PR DESCRIPTION
**Pull request by brendandburns**
@PatrickLang @michmike @spiffxp

### CODE REVIEW

**Comment by michmike** [comment]
/approve
/lgtm

thanks @brendanburns  for putting this together

**Comment by spiffxp** [comment]
this shouldn't have merged without SC review

**Comment by brendanburns** [comment]
Sorry that's my fault for not putting /hold on it...

Feel free to revert if you'd like...

**Comment by brendanburns** [comment]
There's no complete code module afaik. There's code in various components
(eg windows kube-proxy) but I think they're all owned by other SIGs that
this SIG contributes to, unless we want to go super fine grained.

**Comment by philips** [comment]
I think it would be helpful to list out those partial code modules and the SIGs you coordinate with. If only the top 5-10.

**Pull request merged**
