### PR TITLE
chore: add magnum-cluster-api channel

### PR DESCRIPTION
**Pull request by mnaser**
This is a request for the [Cluster API driver for Magnum](https://github.com/vexxhost/magnum-cluster-api) project to get a channel in the Kubernetes Slack.

The project allows you to deploy Kuberentes clusters using the Cluster API for OpenStack, it enables users of OpenStack to make use of the Cluster API to get a fully integrated cluster wtih the underlying cloud using the Cloud Provider for OpenStack (CCM), Cinder CSI, Manila CSI, etc.

The project is fully open sourced, there are several contributors from different organizations and with the increased volume of PRs, we wanted to have a  space that new users can talk and ask about it, but also a space for existing developers to discuss the project.

### CODE REVIEW

**Comment by mnaser** [comment]
is there someone around to give this a little kick in? :)

**Comment by coderanger** [comment]
Hi there, is there a reason to not follow the normal naming scheme here?

**Comment by mnaser** [comment]
Hi @coderanger — this in particular is not a provider for the Cluster API. it’s actually a driver for Magnum which uses the Cluster API. 

In this case Magnum supports multiple backends, this repo focused on the Cluster API backend in particular .. so it’s a bit reversed!

**Comment by coderanger** [comment]
Got it, would it be better to just make a `#magnum` channel then?

**Pull request merged**
