### PR TITLE
update references to KEP template

### PR DESCRIPTION
**Pull request by andrewsykim**
Following up on https://github.com/kubernetes/enhancements/pull/836 to update links to KEP template. 

/assign @justaugustus

### CODE REVIEW

**Comment by andrewsykim** [comment]
oops forgot about generated files, fixing

**Comment by andrewsykim** [comment]
Forgot keps were left in community repo, should the links be updated to reference the kep template in the enhnacement repo?

**Comment by andrewsykim** [comment]
@justaugustus done

**Comment by justaugustus** [comment]
/lgtm
/approve

For Steering + Arch:
/assign @bgrant0607

**Comment by bgrant0607** [comment]
That's cool. I didn't know we had that redirector. I verified that the link works

/lgtm
/approve

**Pull request merged**
