### PR TITLE
Make PRR approval required

### PR DESCRIPTION
**Pull request by johnbelamaric**
Update the PRR policy to make approval required in 1.21 and later.

### CODE REVIEW

**Comment by johnbelamaric** [comment]
Doh. @kubernetes/enhancements can someone PTAL, this has gone through the lazy consensus period

**Comment by coderanger** [comment]
Moving this here instead of k-dev but +1 for reverting this change. This is a very big change and I don't think it's appropriate to assume lazy consensus during a time when most people are unplugged.

**Pull request merged**
