### PR TITLE
add ingress provision proposal

### PR DESCRIPTION
**Pull request by mqliang**
This is a revised proposal of https://github.com/kubernetes/community/pull/275. It built upon the initial "loadbalancer provision" idea of  https://github.com/kubernetes/community/pull/275 , and combined with ideas and feedbacks from community.

cc @m1093782566 @haibinxie 
cc @kubernetes/sig-network-proposals

### CODE REVIEW

**Comment by m1093782566** [comment]
@kubernetes/huawei

**Comment by thockin** [comment]
We should not do anything with this until AFTER the sig deep-dive next week, which is particularly focused on Ingress, and the results of which could modify the landscape.

**Comment by m1093782566** [comment]
@thockin 

Would you please give us the feedback of sig deep-dive on this proposal?

**Comment by thockin** [comment]
The discussion is not done.  Unfortunately the deep-dive was not long enough to cover the whole topic.  Either @bowei or @nicksardo or I will be publishing the proposal in more detail soon.

**Comment by mqliang** [comment]
@thockin @bowei @nicksardo Any progress?

**Comment by m1093782566** [comment]
/assign @bowei 

for inputs :)

**Pull request closed without merging**
