### PR TITLE
Update cji's company affiliation

### PR DESCRIPTION
**Pull request by cji**
I have a new employer so I am updating my company affiliation for my PSC and wg-security-audit membership.

### CODE REVIEW

**Comment by mrbobbytables** [comment]
One small nit, would you mind updating the commit message to be something like "Update affiliation for cji" just so its clear from the commit history what occurred 👍

**Comment by cji** [comment]
thanks for the feedback @mrbobbytables @joelsmith - I've updated my related PRs in k/k8s.io and k/security accordingly as well.

**Pull request merged**
