### PR TITLE
Add apiserver-network-proxy to the cloud-provider-extraction-migration subproject

### PR DESCRIPTION
**Pull request by nikhita**
Ref: https://github.com/kubernetes/org/issues/715

/assign @andrewsykim @cheftako

### CODE REVIEW

**Comment by andrewsykim** [comment]
/lgtm 

Thank you @nikhita!

**Comment by nikhita** [comment]
/assign @cblecker 
for approval

**Comment by nikhita** [comment]
Updated to also include https://github.com/kubernetes/legacy-cloud-providers in this PR. Ref: https://github.com/kubernetes/org/issues/719

**Pull request merged**
