### PR TITLE
sig-testing: Add cloud-provider-kind repo

### PR DESCRIPTION
**Pull request by ameukam**
Ref:
  - https://github.com/kubernetes/org/issues/4052

### CODE REVIEW

**Comment by ameukam** [comment]
/hold
/assign @aojea @BenTheElder 
For LGTM

**Comment by ameukam** [comment]
cc @cblecker @mrbobbytables

**Review by BenTheElder — COMMENTED** [review]
/lgtm
/approve
/hold
thank you!

**Pull request merged**
