### PR TITLE
Add k8spin channel

### PR DESCRIPTION
**Pull request by angelbarrera92**
From k8spin.cloud we want to include a new channel in the kubernete slack group.

The channel will be used to share experiences between k8spin users.

K8Spin is a Kubernetes namespace as a service platform online.

In addition to the SaaS service, we are building some OSS tools related to kubernetes multi-tenant stuff: 

https://github.com/k8spin

Thanks!

### CODE REVIEW

**Comment by markyjackson-taulia** [comment]
@angelbarrera92 You will need to sign your CLA. You can find more details on that here: https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by angelbarrera92** [comment]
> @angelbarrera92 You will need to sign your CLA. You can find more details on that here: https://github.com/kubernetes/community/blob/master/CLA.md

Done! @markyjackson-taulia

**Comment by angelbarrera92** [comment]
Am I missing something to do?

**Comment by markyjackson-taulia** [comment]
> Am I missing something to do?

No, someone will add the approve label once there is a final review

**Pull request merged**
