### PR TITLE
Added base structure with example

### PR DESCRIPTION
**Pull request by mattfarina**
* Add contribution guidelines
* Updates readme with slack and SIG list
* Migrates available SIG missions
* Adds community meeting as basic example

Ping @sarahnovotny @spiffxp

### CODE REVIEW

**Comment by mattfarina** [comment]
@sarahnovotny Note, SIG Apps will come as a second pull request if this format is acceptable.

I noticed that SIG Network moved to the community project but is using the Wiki instead of the codebase. See https://github.com/kubernetes/community/wiki/SIG-Network. Would this be a better direction?

**Comment by mattfarina** [comment]
This relates to kubernetes/kubernetes#23146

**Comment by sarahnovotny** [comment]
@mattfarina i'm inclined toward md files for more audit-ability even if we are permissive with merge privileges in /community ... though, i think each SIG can choose for themselves (to some extent.)

**Comment by sarahnovotny** [comment]
also, thank you thank you thank you i owe you 🍫

**Comment by spiffxp** [comment]
lgtm, huge huge thanks

**Pull request merged**
