### PR TITLE
docs :Update election.md

### LINKED ISSUE #7355: docs: update election.md
### Describe the issue

image
will he held -> will be held
I will rise PR for this

### PR DESCRIPTION
**Pull request by Nitishupkr**
Fixes #7355
corrected the misspelled word

### CODE REVIEW

**Review by vaibhav2107 — COMMENTED** [review]
/lgtm

**Comment by Nitishupkr** [comment]
@detiber  check it once

**Comment by Nitishupkr** [comment]
@detiber review  the PR so it can be merged

**Pull request merged**
