### PR TITLE
Update SIG-UI meeting time

### PR DESCRIPTION
**Pull request by floreks**

### CODE REVIEW

**Comment by cblecker** [comment]
@floreks This should be updated here: https://github.com/kubernetes/community/blob/3d960a351c44594deda6b8c28b16b78ee76ec7f5/sigs.yaml#L1083-L1087

And then run `make`. You can also update the time zone if it would help keep it up to date with DST (many meetings are tracking in PT `tz: "PT (Pacific Time)"`)

**Comment by floreks** [comment]
Thanks for information. I'll do that.

**Comment by floreks** [comment]
Closing in favour of #1487

**Pull request closed without merging**
