### PR TITLE
Add a Slack channel for operator-builder from VMware

### PR DESCRIPTION
**Pull request by scottd018**
Add channel for operator-builder, an open source project created to enable those who wish to use the Kubernetes operator pattern to manage their Kubernetes distributions.  Based upon the plugin architecture from Kubebuilder, operator-builder creates a working operator for Kubernetes workloads given existing input YAML manifests.

https://github.com/vmware-tanzu-labs/operator-builder
https://flings.vmware.com/operator-builder-for-tanzu

Signed-off-by: Dustin Scott <sdustin@vmware.com>

### CODE REVIEW

**Comment by coderanger** [comment]
@scottd018 Given the very generic nature of the name, what do you think about `#tanzu-operator-builder`?

**Comment by scottd018** [comment]
> @scottd018 Given the very generic nature of the name, what do you think about `#tanzu-operator-builder`?

Hey @coderanger !  I want to be careful with the use of the name `tanzu` as this project is not part of the Tanzu product portfolio per se.  It was developed in house by Tanzu Labs (a services org within VMware focused on Tanzu).  I would prefer that we keep the channel name to match the project name (the actual project name is simply `operator-builder`) if at all possible to avoid confusion.

Let me know if that makes sense or if you have concerns there.

Thanks!

**Comment by coderanger** [comment]
@scottd018 That is fair, my worry is mostly that the Slack channel landscape for operator-y things is already rather muddied. So just be prepared for some confused users looking for OSDK or Kubebuilder help in your channel and probably hang out in `#kubernetes-operators` too which is both a general hub for operator-y things and also kind of still the main channel for OSDK.

/ok-to-test
/lgtm

**Comment by coderanger** [comment]
Discussed with OP in Slack, they are okay with the small risk of user confusion and know a bit more about the lay of the land.

/approve

**Pull request merged**
