### PR TITLE
tiny whitespace fix

### PR DESCRIPTION
**Pull request by dankenigsberg**
For the more compulsive among us, let's have a space just before a sentence begins.

**Which issue(s) this PR fixes**:

Fixes nothing much

### CODE REVIEW

**Comment by mrbobbytables** [comment]
@dankenigsberg can you sign the [cla](https://github.com/kubernetes/community/blob/master/CLA.md#how-do-i-sign)?

**Comment by dankenigsberg** [comment]
> @dankenigsberg can you sign the [cla](https://github.com/kubernetes/community/blob/master/CLA.md#how-do-i-sign)?

@mrbobbytables, I'm trying but I fail to find how I could associate my github identity with my long-existing Linux Foundation account. I can add Google and Facebook identities to it. Any idea what could be wrong?

**Comment by nikhita** [comment]
> @mrbobbytables, I'm trying but I fail to find how I could associate my github identity with my long-existing Linux Foundation account. I can add Google and Facebook identities to it. Any idea what could be wrong?

@dankenigsberg please reach out to Linux Foundation directly at https://github.com/kubernetes/community/blob/master/CLA.md#troubleshooting. Unfortunately, the Kubernetes project does not have insight into the CLA system so we won't know the right way to proceed here either. :(

**Comment by dankenigsberg** [comment]
Gasp. The github icon on LinuxFoundation is invisible in my Firefox.
What an effort for a little space.

**Pull request merged**
