### PR TITLE
Update the OWNERS for upstream marketing sub group

### LINKED ISSUE #5281: Update OWNERS for upstream marketing sub group
This is a little out of date: https://github.com/kubernetes/community/blob/master/communication/marketing-team/OWNERS

Should include: 
@Pensu 
@rajula96reddy 
@kaslin

### PR DESCRIPTION
**Pull request by championshuttler**
Signed-off-by: championshuttler <shivams2799@gmail.com>

**Which issue(s) this PR fixes**:

Fixes #5281

### CODE REVIEW

**Review by markyjackson-taulia — APPROVED** [review]
/assign @mbbroberg 
/lgtm
/hold

**Comment by mbbroberg** [comment]
Perfect, thank you! 

/approve

**Pull request merged**
