### PR TITLE
Update sig-aws leads

### PR DESCRIPTION
**Pull request by mfburnett**
Hey all, officially stepping down here -- sorry for not doing this earlier! @philips / @justinsb have my permission to remove my name from other sig-aws leadership-related files as needed.

### CODE REVIEW

**Comment by chrislovecnm** [comment]
@mfburnett you need to sign the CLA, or I can PR this for you.  Let me know :)

**Comment by philips** [comment]
Mackenzie is inactive so just go ahead and PR it @chrislovecnm

**Comment by chrislovecnm** [comment]
I will do that this week. Thanks

**Comment by chrislovecnm** [comment]
@mfburnett @philips we can close this now as I removed her in https://github.com/kubernetes/community/pull/1875

/close

**Comment by chrislovecnm** [comment]
actually I was able to close

**Pull request closed without merging**
