### PR TITLE
Update SIG Docs leads

### PR DESCRIPTION
**Pull request by zacharysarah**
This PR updates team info for SIG Docs:

- Adds Jim Angel as a lead 🎉 
- Promotes Jared Bhatti to emeritus lead (thanks for everything! 💛)

/sig docs
/assign @jimangel @kbarnard10 @Bradamant3 @jaredbhatti

### CODE REVIEW

**Comment by zacharysarah** [comment]
@jimangel 👋 I'm happy to close this in deference to your own PR.

**Comment by cblecker** [comment]
@zacharysarah Hi 👋 

Do you have it documented somewhere where consensus for this change was reached? I see in the agenda for your 8/13 that Jared was planning on stepping down but I don't see anything on the agenda/e-mail list discussing Jim's nomination.

**Comment by zacharysarah** [comment]
@cblecker Sorry, this is the first time we’ve changed chairs since adopting governance. We’ll do a proper nomination and vote/lazy consensus.

/hold

**Comment by cblecker** [comment]
Sounds good! When you have consensus from the sig, ping me back for approval :)

**Comment by zacharysarah** [comment]
@cblecker 👋 It's [official](https://github.com/kubernetes/website/issues/16106) on 9/15.

**Comment by zacharysarah** [comment]
@cblecker Had to resolve a merge conflict--can you please `/lgtm` again? Thanks in advance!

/hold cancel

**Pull request merged**
