### PR TITLE
Add cluster-api-ibmcloud information

### PR DESCRIPTION
**Pull request by mkumatag**
**Which issue(s) this PR fixes**:

This PR adds the missing information for the cluster-api-ibmcloud project
Fixes #

### CODE REVIEW

**Review by fabriziopandini — COMMENTED** [review]
/lgtm
/cc @neolit123

**Review by neolit123 — COMMENTED** [review]
/lgtm

**Comment by mkumatag** [comment]
can someone help me us merging this PR?
/assign @mrbobbytables @nikhita @cblecker

**Review by nikhita — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
