### PR TITLE
[zh] localzation README-zh.md

### PR DESCRIPTION
**Pull request by wuyanpinguniontech**
Signed-off-by:  WuYanping <wuyanping@uniontech.com>

### CODE REVIEW

**Comment by mahmut-Abi** [comment]
@justaugustus

**Comment by mahmut-Abi** [comment]
@parispittman

**Review by mrbobbytables — COMMENTED** [review]
/hold
if possible can we move this over to the [contributor site](https://github.com/kubernetes/contributor-site)? we can skaffold the entire site to support localization.

**Comment by wuyanpinguniontech** [comment]
> /hold if possible can we move this over to the [contributor site](https://github.com/kubernetes/contributor-site)? we can skaffold the entire site to support localization.

What should I need to do next?  Can you tell me some details? Thanks for your help.

**Pull request closed without merging**
