### PR TITLE
Added security audit final reports and updated README

### PR DESCRIPTION
**Pull request by aasmall**
This includes the final reports from Trail of Bits and Atredis Partners, as well as some ancillary content.

### CODE REVIEW

**Comment by dims** [comment]
@aasmall looks like a typo `wg-security-audit/ancillary-data/rapid-risk-assessments/etcd.md:47:20: "achived" is a misspelling of "achieved"`

Also the helpdesk for the CLA stuff is here - https://github.com/kubernetes/community/blob/master/CLA.md#troubleshooting

**Comment by cblecker** [comment]
Please rebase and squash

**Pull request closed without merging**
