### PR TITLE
Proposal for Alibaba Cloud Provider repository

### PR DESCRIPTION
**Pull request by aoxn**
This is a supplementary info for adding Alibaba Cloud Provider into kubernetes repository. 

See Also.
https://github.com/kubernetes/community/pull/2394
https://github.com/kubernetes/community/commit/aba21ccbc9d095607eb561b8ef42cb497ad6c668
https://github.com/kubernetes/community/commit/6ad7317d59906b0ade1df51a5bec11e26bf6cf94

Signed-off-by: yaoyao.xyy <yaoyao.xyy@alibaba-inc.com>

### CODE REVIEW

**Comment by aoxn** [comment]
@andrewsykim

**Comment by andrewsykim** [comment]
cc @calebamiles @hogepodge @jagosan

**Pull request merged**
