### PR TITLE
fix dead link

### PR DESCRIPTION
**Pull request by huxiaoliang**

### CODE REVIEW

**Comment by cblecker** [comment]
@huxiaoliang Please squash out the merge commit (https://github.com/kubernetes/community/pull/1485/commits), and reset the author on your commit to match your github user.

**Comment by huxiaoliang** [comment]
@cblecker, this is my first commit to k8s,  let me address your comments and push it again, thanks in advance.

**Comment by huxiaoliang** [comment]
check CLA

**Comment by huxiaoliang** [comment]
check CLA again

**Comment by huxiaoliang** [comment]
I am waitting for HelloSign and the CI servers to resolve the new agreement

**Comment by huxiaoliang** [comment]
bump to verify CLA

**Comment by huxiaoliang** [comment]
I think due to fix CLA issue, my git env is mess, so I close this one and open a new one.

**Pull request closed without merging**
