### PR TITLE
devel: add recommended time to release process

### PR DESCRIPTION
**Pull request by philips**
I am simply copying Golang which has selected a reasonable time: https://groups.google.com/forum/#!topic/golang-announce/YOqTqcJtiJI

### CODE REVIEW

**Comment by grodrigues3** [comment]
@kubernetes/sig-release-pr-reviews

**Comment by tallclair** [comment]
OK, but depending on the urgency the announcement shouldn't be delayed a day to hit that time. I guess that's why it's recommended.
/lgtm

**Pull request merged**
