### PR TITLE
Update `profiling to services to APIserver`

### PR DESCRIPTION
**Pull request by qzyse2017**
the current description for `Adding profiling to services to APIserver` is just outdated, there is no  `init(c *Config)` method in 'pkg/master/master.go'  now, this document should have been describing how to do it 4 years ago, see https://github.com/kubernetes/kubernetes/blob/6d94dd1a05b72b397458b642186864a033885b49/pkg/master/master.go and https://github.com/kubernetes/kubernetes/blob/f407700af91de685ce5aa7570f9f3d24b2c5790b/pkg/master/master.go

### CODE REVIEW

**Comment by qzyse2017** [comment]
signed cla

**Comment by qzyse2017** [comment]
Not quite sure my fix is proper, I referenced code 4 years ago

**Comment by spiffxp** [comment]
/ok-to-test

I'm not sure how much of this doc is relevant anymore.  It seems like it was written before we added flag-gated profiling to all kubernetes components.  In this case, today you can run `kube-apiserver --profile=true` to have these endpoints installed.

**Comment by spiffxp** [comment]
you are free to close yourself, or even better, remove the parts that are outdated/confusing to you

**Comment by qzyse2017** [comment]
I am not quite familiar with profiling kubernetes, going to close the pull request, thanks  a lot for your reply!

**Pull request closed without merging**
