### PR TITLE
Proposal to change meeting time for Sig Scalability #1602

### LINKED ISSUE #1602: Proposal to change meeting time for Sig Scalability
As of the last couple of meetings the lazy consensus is that the scalability SIG should be bumped later by 30 minutes to avoid conflicts with SIG architecture. This is a tracking issue for this change, I will work on a PR.

### PR DESCRIPTION
**Pull request by countspongebob**
Also fixed company affiliation for Bob Wise from Samsung to AWS.

Fixes #1602

### CODE REVIEW

**Comment by cblecker** [comment]
@countspongebob You need to run a `make` after updating sigs.yaml, and it will go and update all the autogenerated docs with your changes.

**Comment by castrojo** [comment]
Nit: Probably "Amazon Web Services" or whatever the canonical name is for clarity. Also noticed that we don't really explain to people how to change affiliation, I've filed #1636

**Comment by cblecker** [comment]
Fixed by #1710
/close

**Pull request closed without merging**
