### PR TITLE
add developer docs for source code tour guide

### PR DESCRIPTION
**Pull request by qas**
a quick tour guide of the K8s codebase makes it easier for new developers to get familiar with the source code

### CODE REVIEW

**Comment by qas** [comment]
I signed it

**Comment by qas** [comment]
I signed it

**Review by markyjackson-taulia — APPROVED** [review]
/hold

**Comment by mrbobbytables** [comment]
@qas Thanks for opening this PR :) 
There are a few items that should be addressed before this is merged that we'll follow up with on review. That I'll try and get a few more eyes on.
/lgtm-cancel

**Comment by nikhita** [comment]
@qas Love the idea! A few suggestions on how to structure the code tour guide:

- While the existing content is also very helpful, it mainly looks at the SIG API Machinery related directories in k/k. It would be great if could use the code tour guide to capture directories related to all SIGs. The new contributor workshop [videos](https://github.com/kubernetes/community/tree/master/mentoring/programs/new-contributor-workshop#previous-workshops) go into this in detail. Would be nice to have them codified in this doc.

- Since the source code can change, it would be better not to copy the code directly into this doc wherever possible. Since this is a k/k codebase tour guide, let's keep this broad and include the general concepts behind each directory.

- Having said that, it is still helpful to have a doc which walks through the actual code and talks about why it's written that way! :+1: Since you've mostly covered SIG API Machinery related code, I'd recommend reaching out to the SIG to get an idea of which parts of the codebase they'd like to cover in this manner and document them in a more structured way (the SIG would own these docs).

**Comment by qas** [comment]
@nikhita is the expectation to have each SIG listed own their code tour within this single document?
I made updates to the tour guide here and arranged them by SIG in this single document
I can reach out to these SIGs to see what they want added if you feel that's a good idea

**Comment by qas** [comment]
closing since SIGs should own their code tours if desired

**Pull request closed without merging**
