### PR TITLE
Adding markyjackson-taulia to reviewers

### LINKED ISSUE #6279: REQUEST: New communication reviewer added to owners
Adding markyjackson-taulia to comms reviewer per @parispittman

### PR DESCRIPTION
**Pull request by markyjackson-taulia**
**Which issue(s) this PR fixes**:

Fixes #6279 

cc @parispittman @coderanger

### CODE REVIEW

**Comment by parispittman** [comment]
/lgtm 

tysm!!!

**Comment by jdumars** [comment]
/lgtm

💖

**Comment by jdumars** [comment]
Going to approve this with a hold - feel free to remove if there's no objection by 12/18
/hold
/approve

**Comment by markyjackson-taulia** [comment]
There have been no objections, going to remove the hold.
/remove-hold

**Pull request merged**
