### PR TITLE
More SIG Arch co-chair updates

### PR DESCRIPTION
**Pull request by bgrant0607**
Remove Brian Grant and Jaice Du Mars as SIG Arch co-chairs.
Add John Belamaric as SIG Arch co-chair.

John has been a leader in the conformance subproject, is driving production readiness reviews, and has volunteered to help with SIG chair duties.

Jaice and I are oversubscribed, and are stepping down from the role. Thanks to John for starting to help over the past few weeks.

cc @dims @jdumars @derekwaynecarr

### CODE REVIEW

**Comment by jdumars** [comment]
Big +1 for John who has stepped up and done tremendous work for the SIG. 

Brian and I started this SIG back in Spring, 2017, so definitely time for new leadership.

/lgtm

**Comment by cblecker** [comment]
Thank you @jdumars and @bgrant0607 !

**Comment by timothysc** [comment]
Thank for all of your efforts! 
/lgtm

**Comment by dims** [comment]
Many thanks @jdumars and @bgrant0607 welcome @johnbelamaric !

-- Dims

**Comment by dims** [comment]
/hold

hmm, wait for @derekwaynecarr

**Comment by derekwaynecarr** [comment]
/approve

thanks all

**Pull request merged**
