### PR TITLE
KEP - Change existing clusters using kubeadm

### PR DESCRIPTION
**Pull request by fabriziopandini**
Kubeadm currently allows you to init a Kubernetes cluster, join nodes and upgrade the cluster
to a newer version, but there is no a dedicated workflow for changing cluster attributes (except with using some workarounds, all of them with risks and pitfalls...)

This KEP aims to address this gap by proposing to implement a new kubeadm top level command (name TBD) for changing cluster attributes in a more controlled way.

The document is not complete, but hopefully it will provide enough context for letting the sig decide if this should be part of the next cycle or not...

rif https://github.com/kubernetes/kubeadm/issues/970#issuecomment-402507153

/cc @kubernetes/sig-cluster-lifecycle-pr-reviews 
/cc @timothysc @neolit123 @detiber @chuckha @luxas

### CODE REVIEW

**Comment by neolit123** [comment]
@fabriziopandini sorry, for some reason i missed this last week.
i think this can work, but i need to think more about the usage of strategic-merge-patch and the go struct tags.

do you think it would be a good idea to initially expose this under `kubeadm alpha <some-command-name`?

**Comment by timothysc** [comment]
/hold 

This one pretty thorny.

**Comment by justaugustus** [comment]
REMINDER: KEPs are moving to [k/enhancements](https://github.com/kubernetes/enhancements) on November 30. Please attempt to merge this KEP before then to signal consensus.
For more details on this change, review [this thread](https://groups.google.com/d/msg/kubernetes-dev/LIkZoIqCT20/t515CV2mAgAJ).

Any questions regarding this move should be directed to that thread and not asked on GitHub.

**Comment by luxas** [comment]
@fabriziopandini @timothysc shall we close this one and bring the design/plan up for this in the next meeting instead?

**Comment by fabriziopandini** [comment]
@luxas I'd like to get this moving on the high-level assumption that some artifacts (like e.g. manifests, certs, plus well know config maps) are under kubeadm responsibility not only for create/upgrade but also for update.

**Comment by justaugustus** [comment]
KEPs [have moved](https://github.com/kubernetes/enhancements/pull/638) to [k/enhancements](https://github.com/kubernetes/enhancements). 
This PR will be closed and any additional changes to this KEP should be submitted to k/enhancements.
For more details on this change, review [this thread](https://groups.google.com/d/msg/kubernetes-dev/LIkZoIqCT20/t515CV2mAgAJ).

Any questions regarding this move should be directed to that thread and not asked on GitHub.
/close

**Pull request closed without merging**
