### PR TITLE
Add meeting recordings url for wg-etcd-operator

### PR DESCRIPTION
**Pull request by jmhbnz**
First meeting recording has now been uploaded and playlist created for future meetings.

cc @ahrtr,@jmhbnz,@hakman,@jberkus,@justinsb

### CODE REVIEW

**Comment by ahrtr** [comment]
It seems that there isn't a label `wg/etcd-operator`, does anyone know how to create it?

/sig etcd
/sig cluster-lifecycle

**Comment by ahrtr** [comment]
/lgtm
/approve

Thanks @jmhbnz

**Review by neolit123 — COMMENTED** [review]
/lgtm
thanks

**Comment by neolit123** [comment]
> please assign [kaslin](https://github.com/kaslin) for approval.

/assign @kaslin 
PTAL, thanks

**Comment by ahrtr** [comment]
Majority of the wg-etcd-operator organizers have already approved or thumbed up this PR.
@kaslin can you please approve this PR? Thanks

**Comment by ahrtr** [comment]
Thank you @kaslin

**Pull request merged**
