### PR TITLE
Update Slack URL

### PR DESCRIPTION
**Pull request by bbasata**
The previous URL does not appear to work

### CODE REVIEW

**Comment by dims** [comment]
Thanks for noticing. I'll get this merged as soon as the CLA is signed. thanks!

**Comment by idvoretskyi** [comment]
LGTM.

**Comment by philips** [comment]
@bbasata anything we can do to help with the CLA?

**Comment by philips** [comment]
@bbasata actually, I went ahead and fixed this in a separate PR since it is likely just causing people problems getting involved. We would love your contributions in the future!

**Pull request closed without merging**
