### PR TITLE
Add slack channel for metal-stack

### PR DESCRIPTION
**Pull request by mwindower**
This PR adds a slack channel for the open-source project [metal-stack](https://metal-stack.io) which can be used to produce Kubernetes clusters with the help of [gardener](https://gardener.cloud/) or in the near future with the cluster-api on bare-metal.

### CODE REVIEW

**Comment by jeefy** [comment]
Heya! Looks like you need the CLA signed. :) 

/ok-to-test

**Comment by mwindower** [comment]
Hi there! Indeed, I just signed the CLA.

**Comment by jeefy** [comment]
/approve
Need one more +1 from a slack admin :)

**Comment by mwindower** [comment]
@idvoretskyi @parispittman could you take a look at my PR?

**Review by idvoretskyi — APPROVED** [review]
/lgtm

**Pull request merged**
