### PR TITLE
create sig-azure

### PR DESCRIPTION
**Pull request by rootfs**
Creating sig-azure to focus on Microsoft Azure issues.

@colemickens @brendandburns

### CODE REVIEW

**Comment by sarahnovotny** [comment]
hai!  please check and follow this procedure for creating a SIG -- https://github.com/kubernetes/community/blob/master/README.md#how-to-start-a-sig.  There's a great example of a SIG creation in flight here - https://groups.google.com/forum/#!topic/kubernetes-dev/ou9f90kxSG0

**Comment by philips** [comment]
@rootfs I am going to close this out. @sarahnovotny's suggestion to follow the SIG starting guide is the way to get this done. Thank you!

**Comment by jpoon** [comment]
@rootfs If you haven't done so already, I can go through the process of SIG for Azure.

**Comment by idvoretskyi** [comment]
@jpoon @rootfs shouldn't SIG-Windows be a better place to start?

**Comment by rootfs** [comment]
@jpoon thanks, please proceed and help setup the sig.
@idvoretskyi it is yes and no. The charter of sig-azure is exclusively on azure while sig-windows can span to OS platforms (as the name suggests).

**Comment by sarahnovotny** [comment]
Thank you!  please be clear on the differences and start socializing your
proposal with SIG-Windows to make sure that their vision and yours align
(and diverge in agreement).

**Comment by michmike** [comment]
hi everyone, we discussed sig-azure briefly today in the kubernetes community meeting. the SIG-Windows team has already did some work on documenting how to run k8s on Azure. We propose that SIG-Windows can be used as the single forum to deal with everything from windows server containers, windows, and running k8s on Azure. My team already has ahead start on this :)

@rootfs , do you think we can use SIG-Windows for now and if we see there is really a big gap in terms of goals and interests, we can split the SIGs in the future.

cc: @sarahnovotny

**Comment by colemickens** [comment]
I've been working on Kubernetes on Azure for a while now and I'd personally
rather see a separate SIG. Azure and Windows are completely separate
concerns in my mind. Windows and Windows containers run just fine on other
cloud platforms and the problems to solve for Windows are a very different
set of things than what we need to improve for Azure in general.

(Also, what documentation are you referring to?)

**Comment by michmike** [comment]
@colemickens fair enough.
on the documentation, we are documenting in the sig the steps we took to run k8s on azure for the windows server container work.

**Comment by sarahnovotny** [comment]
could one of you make a proposal for the SIG-Azure charter and share it
with kubernetes-dev@  I believe that @jpoon offered to.

**Comment by jpoon** [comment]
I didn't get anywhere with this -- feel free to take it on @colemickens :)

**Comment by barrymac** [comment]
@colemickens agreed, +1 to start a sig-azure for azure related support and issues

**Comment by sarahnovotny** [comment]
also have a request for simply a #azure slack channel in https://github.com/kubernetes/community/issues/188.  Do we have a draft proposal somewhere for sig-azure?

**Pull request closed without merging**
