### PR TITLE
changed the marketing-team subdirectory name to contributor-comms

### PR DESCRIPTION
**Pull request by harshitasao**
**Which issue(s) this PR fixes**:

Fixes:  Part of #6641

### CODE REVIEW

**Comment by chris-short** [comment]
@mrbobbytables I think this is good to go.

**Comment by kaslin** [comment]
@tpepper could you take a look at this or suggest someone else to review it?

**Comment by kaslin** [comment]
Other PRs for this change are already in, waiting on this one. Unholding.
/hold cancel

**Pull request merged**
