### PR TITLE
Basic proposal for restricted nodes, including dedicated nodes

### PR DESCRIPTION
**Pull request by Q-Lee**
This is a proposal to implement restricted nodes with Taints, Tolerations, and PodSecurityPolicies. A restricted node with a single workload is a dedicated node.

Specifically, PodSecurityPolicies will allow certain Tolerations. This will permit placement on restricted nodes.

Unfortunately, this is insufficient, as one purpose for dedicated nodes is to permit privileged workloads. Granting a PodSecurityPolicy with privileged execution compromises the whole cluster, because the privileged workload could land anywhere.

The Taint/Toleration relationship must be reversed, so that nodes can tolerate pod taints. The recommended implementation is a new type of symmetric Taint/Toleration. The PodSecurityPolicy would then need a list of *required* Tolerations.

### CODE REVIEW

**Comment by Q-Lee** [comment]
@kubernetes/sig-auth-misc

**Comment by liggitt** [comment]
Limiting to a specific set of nodes is what node selectors are for... whitelisting tolerations allowed on the pod *and* requiring certain nodeSelector components on the pod both make sense

**Comment by Q-Lee** [comment]
@liggitt that would also work. I just wanted to try and limit the number of different features required to establish dedicated nodes.

**Comment by bgrant0607** [comment]
Related:
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/taint-toleration-dedicated.md
https://github.com/kubernetes/kubernetes/issues/17190
https://github.com/kubernetes/kubernetes/issues/17151
https://github.com/kubernetes/kubernetes/issues/14573

cc @davidopp

**Comment by bgrant0607** [comment]
@Q-Lee 

You want to divide nodes into nodes that can execute privileged containers and those that can't? Apply taints to all nodes: privileged=true or privileged=false, and then use an initializer to set tolerations based on whether the pods contain privileged containers or not.

https://github.com/kubernetes/community/blob/master/contributors/design-proposals/admission_control_extension.md

I can't foresee adding more features in this area at the current time. The focus is shifting to finishing existing APIs and project health:
https://groups.google.com/forum/#!topic/kubernetes-dev/PpgLgkffr3o

**Comment by davidopp** [comment]
Unfortunately I haven't had time to read this proposal yet.

We *do* need a way to limit who can add dedicated node group tolerations to pods, otherwise dedicated node groups are impossible to do securely, which makes them useless.

RBAC doesn't have that granularity, so it's not applicable.

A custom admission controller is the most obvious solution that comes to mind. For the feature to be usable, we need an admission controller to apply the tolerations anyway, and it could also check to make sure that there are no dedicated node tolerations already set on the pods it is receiving (or could enforce any other policy about who can set such tolerations). There's no standard taint name for dedicated node groups so something custom (or at least configurable) seems necessary anyway.

I don't want to discount @Q-Lee's proposal since I haven't read it yet, but I did want to at least write down an alternative to using PSP.

**Pull request closed without merging**
