### PR TITLE
Correcting mistake: accidentally kept Joel as a chair during WG-SIG transition

### PR DESCRIPTION
**Pull request by JayBeale**
Joel, a lead on wg-security-audit, did not want to lead on sig-security. His comment is referenced below. I mistakenly kept Joel on the chair list. This corrects that mistake.

### CODE REVIEW

**Comment by aasmall** [comment]
@dims @lachie83 I think we still need an lgtm from one of you to merge. Do you have any concerns we should address first?

**Comment by mrbobbytables** [comment]
/lgtm

If there is a problem, we can fix it in a follow up PR.

With all the zoom PRs in flight changes to sigs.yaml will quickly wind up needing to be rebased :(

**Pull request merged**
