### PR TITLE
scheduler.md: update policy section

### PR DESCRIPTION
**Pull request by hongchaodeng**
Minor update on "predicates and priorities policies" section.
Also move it from "extensibility" to "algorithm" section because we only needs to talk about how to modify it in "ext" section.

### CODE REVIEW

**Comment by hongchaodeng** [comment]
@jayunit100

**Comment by hongchaodeng** [comment]
@davidopp

**Comment by davidopp** [comment]
"sequentially" is not clear. It doesn't capture the idea that predicates are filtering and priorities are ranking.

**Comment by hongchaodeng** [comment]
@davidopp 
refined. PTAL

**Comment by davidopp** [comment]
please make it clearer that the nodes that are ranked by the priority functions are the ones that made it through the filter of the predicate functions

**Comment by hongchaodeng** [comment]
@davidopp fixed

**Comment by davidopp** [comment]
LGTM

**Pull request merged**
