### PR TITLE
Add KPNG APAC meeting

### PR DESCRIPTION
**Pull request by rajaskakodkar**
KPNG APAC meeting

**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Comment by rajaskakodkar** [comment]
cc: @jayunit100

**Comment by jayunit100** [comment]
Thanks!!! cc @caseydavenport

**Comment by jayunit100** [comment]
https://groups.google.com/g/kubernetes-sig-network/c/emqj37MWaWI xref

**Comment by jayunit100** [comment]
@nikhita can you help us green light this !

**Comment by jayunit100** [comment]
bumppppp :)

**Pull request merged**
