### PR TITLE
fix time/day of wg-policy meeting

### PR DESCRIPTION
**Pull request by duglin**
ws-policy meeting is on wed@4pm PT

Signed-off-by: Doug Davis <dug@us.ibm.com>

### CODE REVIEW

**Comment by duglin** [comment]
not sure if the ci failure is real - doesn't seem like its related

**Comment by cblecker** [comment]
@duglin CI failure is legitimate, as you're manually modifying an auto-generated doc:
```
I0815 22:57:33.151] Verifying verify-generated-docs.sh
I0815 22:57:38.545] /go/src/k8s.io/community/wg-policy/README.md does not match /tmp/tmp.t1tT8fjB1d/src/testgendocs/wg-policy/README.md
I0815 22:57:38.546] 
I0815 22:57:38.546] ====================================================================
I0815 22:57:38.546] 1 mismatches were detected.
I0815 22:57:38.546] Do not manually edit sig-list.md or README.md files inside the sig folders.
I0815 22:57:38.546] Instead make your changes to sigs.yaml, then run `make`, and then
I0815 22:57:38.547] commit your changes to sigs.yaml and any generated docs.
I0815 22:57:38.547] ====================================================================
I0815 22:57:38.570] FAILED   verify-generated-docs.sh	5s
```

**Comment by duglin** [comment]
@cblecker doi- thanks! fixing...

**Comment by duglin** [comment]
ok fixed! sorry about not noticing it was generated

**Comment by nikhita** [comment]
Closing because this change was made in https://github.com/kubernetes/community/pull/2373. Please reopen if needed.

/close

**Pull request closed without merging**
