### PR TITLE
Update membership sponsor requirements to be from different companies.

### PR DESCRIPTION
**Pull request by pwittrock**

### CODE REVIEW

**Comment by eparis** [comment]
Why? Membership isn't a position of power, authority, access, concern, etc. Who cares who pays the sponsor's paycheck? Those sponsors aren't going to be able to mis-use the system or hurt kubernetes in some way.

**Comment by cblecker** [comment]
I like the formatting changes, and the clarity that sponsors should be closely aligned with the potential member and their code -- mainly because granting membership will have CI auto-run a member's PRs. We need at least that base level of trust that the potential member isn't going to replace our tests with a bitcoin miner :)

No real position on the different company sponsor point.

**Comment by sarahnovotny** [comment]
> Why? Membership isn't a position of power, authority, access, concern, etc. Who cares who pays the sponsor's paycheck? Those sponsors aren't going to be able to mis-use the system or hurt kubernetes in some way.

I see it as an encouragement for people to engage in the community and work with more than their corporate team members or on company specific sections of the code.  org membership as a reward for crosspollination and (in a logical extreme) mentoring by meeting and interacting with more people.

**Comment by pwittrock** [comment]
Maybe "Member" shouldn't require x-org sponsorship, but higher bars should (reviewer, approver)

**Comment by pwittrock** [comment]
Updated to make x-org sponsors encouraged but not required.

**Comment by eparis** [comment]
I think that's quite reasonable!

**Comment by pwittrock** [comment]
Alright, self merging.  Effective changes:

- Formatting improvements
- Encourage x-org sponsorship, but don't require it
- Clarify that sponsors should appear in OWNERs files somewhere

**Comment by bgrant0607** [comment]
LGTM

**Comment by bgrant0607** [comment]
@eparis: Test case: How would the community feel about someone at some company sponsoring 30 other employees at the same company that are completely unknown to the community?

**Comment by eparis** [comment]
@bgrant0607 for nothing more than the ability to be assigned issues and run CI without others having to comment in the PR? I'd be ok with it. Is there more power involved? Membership is a pretty low bar and needs minimal roadblocks/hassles. Is there some advantage or risk we are trying to mitigate?

I'd probably yell at the sponsors for not following the guidelines. "completely unknown to the community" would be incongruent with the stated requirements:
- Authoring or reviewing PRs on GitHub
- Filing or commenting on issues on GitHub
- Contributing to SIG or community discussions

And it would have to be 2 someone's at said company who willingly flouted the rules. Both of whom should get a 'stern talking to' at least.

**Pull request merged**
