### PR TITLE
Add new devfile-devs user group

### PR DESCRIPTION
**Pull request by kim-tsao**
Signed-off-by: Kim Tsao <ktsao@redhat.com>

**Which issue(s) this PR fixes**:

Fixes #
N/A

We would like to add a new user group `devfile-devs` so our core team can be directly notified on our `#devfile` channel

### CODE REVIEW

**Review by markyjackson-taulia — CHANGES_REQUESTED** [review]
@kim-tsao Kindly sign the [CLA](https://github.com/kubernetes/community/blob/master/CLA.md)

**Comment by kim-tsao** [comment]
> @kim-tsao Kindly sign the [CLA](https://github.com/kubernetes/community/blob/master/CLA.md)

Thanks @markyjackson-taulia , I've signed the CLA

**Review by markyjackson-taulia — APPROVED** [review]
Going to add the lgtm label and hold for another admin to review. That may take a few days (and up to a week).
/lgtm
/hold

**Comment by jberkus** [comment]
seems fine.

/remove-hold
/approve

**Pull request merged**
