### PR TITLE
WG LTS: sunset

### PR DESCRIPTION
**Pull request by tpepper**
As per September 22, 2020 meeting of SIG Release, we've decided
that the working group's discussions have led to positive changes
and have run their course.  Remaining discussion and operational
points have reasonable ownership, for example in SIG Release and WG
Reliability.

Signed-off-by: Tim Pepper <tpepper@vmware.com>

### CODE REVIEW

**Comment by justaugustus** [comment]
Thank you to all of the WG LTS members for the work they've done!
Approved for archival from SIG Release!

**Comment by dims** [comment]
/approve
/lgtm

/hold for other steering folx

thanks a ton everyone!

**Comment by nikhita** [comment]
/lgtm

Thanks everyone!

**Comment by nikhita** [comment]
cc @kubernetes/steering-committee

**Comment by mrbobbytables** [comment]
/lgtm
Thanks all!

**Comment by liggitt** [comment]
> /hold for other steering folx

Looks like a majority weighed in.

/hold cancel

**Pull request merged**
