### PR TITLE
[Federation] Federated hpa design

### PR DESCRIPTION
**Pull request by irfanurrehman**
For reference, there already has been quite a lot of discussion over this design [here](https://docs.google.com/document/d/1Uacp99LskNHkJ6ZFFOVGorDivYKi4ySkI8E3tTFAZJ8).

A very readable version of this doc can be viewed on my fork [here](https://github.com/irfanurrehman/community/blob/federated-hpa-design/contributors/design-proposals/federated-hpa.md)

@kubernetes/sig-federation-feature-requests
@kubernetes/sig-federation-misc
@kubernetes/sig-autoscaling-feature-requests

### CODE REVIEW

**Comment by quinton-hoole** [comment]
@irfanurrehman Please clearly label the original Google Doc as deprecated, with a link to this PR as the new place to discuss the design.  Otherwise people who land at that document will be unaware of the conversation here.  Thanks.  Q

**Comment by irfanurrehman** [comment]
@quinton-hoole, Done!

**Comment by irfanurrehman** [comment]
@quinton-hoole 
@kubernetes/sig-federation-feature-requests
does this seem worthy to be merged, now?

**Comment by irfanurrehman** [comment]
@quinton-hoole, given the feature is implemented and merged too, can we please lgtm and merge this.

**Comment by warmchang** [comment]
👍

**Comment by quinton-hoole** [comment]
Wow, sorry for the long delay.  I wonder whether this belongs in kubernetes/federation, now that we have that new repo?

**Comment by irfanurrehman** [comment]
> Wow, sorry for the long delay. I wonder whether this belongs in kubernetes/federation, now that we have that new repo?

Thanks for checking this, I too did forget about this.
`sig-multicluster` design proposals are now maintained [here](https://github.com/kubernetes/community/tree/master/contributors/design-proposals/multicluster), which still remains in community repo. Updated this PR to place the proposal at the right location.

**Pull request merged**
