### PR TITLE
Add rajula to upstream marketing slack usergroup

### PR DESCRIPTION
**Pull request by rajula96reddy**
CC: @mbbroberg

### CODE REVIEW

**Review by mbbroberg — APPROVED** [review]
/lgtm 
/approve

**Review by mrbobbytables — CHANGES_REQUESTED** [review]
You also need to add yourself to the user list^^;;;;;
https://github.com/kubernetes/community/blob/master/communication/slack-config/users.yaml

It creates a mapping from your unique slackID to the handle that you specified.

**Pull request merged**
