### PR TITLE
add myself and remove Jared for sig-docs leads

### PR DESCRIPTION
**Pull request by Bradamant3**
Jared is stepping down. My first obligation as new lead appears to be the administrivia, so forthwith this PR.

### CODE REVIEW

**Comment by cblecker** [comment]
@Bradamant3 Is there a public record of this somewhere? I don't see anything by skimming in your meeting agenda or your mailing list.

**Comment by zacharysarah** [comment]
@Bradamant3 👋 Please update [sigs.yaml](https://github.com/kubernetes/community/blob/master/sigs.yaml) as well.

**Comment by zacharysarah** [comment]
@Bradamant3 👋 In order to avoid merge conflicts in #2753, I included the changes from this PR.

Are you OK with closing this PR in favor of #2753? Thanks in advance! 🙇

**Comment by Bradamant3** [comment]
closing at @zacharysarah's request, in favor of #2753

**Pull request closed without merging**
