### PR TITLE
fix stale link

### PR DESCRIPTION
**Pull request by u2takey**

### CODE REVIEW

**Comment by sebgoa** [comment]
the gold link is also broken and the client support as well.

Might as well fix them all in this PR, could you do that ?

**Comment by u2takey** [comment]
what is "gold link"? i don know.. @sebgoa

**Comment by xiangpengzhao** [comment]
The link in the section `Gold Requirements`. You fixed Bronze and Silver :)

**Comment by xiangpengzhao** [comment]
The links in chapter `Client Support Level` as well.

**Pull request merged**
