### PR TITLE
Add stakeholder SIGs for wg-policy

### PR DESCRIPTION
**Pull request by zjs**
Add SIG Architecture, SIG Auth, SIG Network, SIG Node, SIG Multicluster, SIG Scheduling, and SIG Storage as the stakeholder SIGs for the Policy working group based on the [working group's proposal email](https://groups.google.com/forum/#!topic/kubernetes-dev/_xQBGm7IYs8).

SIG On Premise was also listed in the email, but is not included in this list as the SIG has been archived.

The Multitenancy and Resource Management working groups were also listed in the email, but are not included in this list.

Towards #2176.

/kind documentation
/sig contributor-experience
/wg policy
/cc @hannibalhuang @tsandall @easeway @ericavonb @mdelder

### CODE REVIEW

**Comment by hannibalhuang** [comment]
+1, Multi-tenancy WG would be a very important WG for Policy WG to work with, would be great to add them as well.

**Comment by zjs** [comment]
> Multi-tenancy WG would be a very important WG for Policy WG to work with, would be great to add them as well.

The current format doesn't seem to allow for listing stakeholder WGs (or stakeholder committees). I'm not sure whether that's an intentional design decision or just functionality that has yet to be implemented.

@nikhita, was this considered as a part of #3096?

**Comment by nikhita** [comment]
> The current format doesn't seem to allow for listing stakeholder WGs (or stakeholder committees). I'm not sure whether that's an intentional design decision or just functionality that has yet to be implemented.

That was intentional because WGs are considered as groups that have cross-SIG boundaries and we require approval from these SIGs when a WG is created.  Ref: https://github.com/kubernetes/community/blob/master/committee-steering/governance/wg-governance.md#working-group-relationship-to-sigs

But... https://github.com/kubernetes/community/blob/master/committee-steering/governance/wg-governance.md#creation-process-description says:

> Who are all of the stakeholders involved in this problem this group is trying to solve (SIGs, steering committee, other Working Groups)?

Personally, I think we should limit this to SIG stakeholders since working groups are technically cross-SIGs since SIGs own code, though working groups can certainly work together (just as SIGs work together but might not have a working group defined for each such interaction). :grimacing: 

But if someone from steering can confirm that we should support WG and committees, I can update the generator. :)
Maybe @dims or @spiffxp?

**Comment by zjs** [comment]
Do we want to proceed with this for now as-is or wait until we have resolution on whether WGs can have other WGs or committees as stakeholders?

**Comment by nikhita** [comment]
> Do we want to proceed with this for now as-is or wait until we have resolution on whether WGs can have other WGs or committees as stakeholders?

Let me send this to the steering ML just to be sure.

**Comment by hannibalhuang** [comment]
LGTM

**Comment by spiffxp** [comment]
[steering@ thread](https://groups.google.com/a/kubernetes.io/d/msg/steering/sDIgMImNpgY/iWSYvgE_BQAJ)

**Comment by nikhita** [comment]
Needs rebase, but this looks good to go otherwise

**Comment by spiffxp** [comment]
/approve
/lgtm
based on the lgtm from @hannibalhuang above

**Pull request merged**
