### PR TITLE
Add alejandrox1 to Discuss admin

### PR DESCRIPTION
**Pull request by alejandrox1**

### CODE REVIEW

**Comment by alejandrox1** [comment]
Removing @parispittman in this PR as well
/assign @parispittman

**Comment by jeefy** [comment]
Oh yeah I'm a reviewer not an approver in Comms. Don't mind me~ Nothing to see here~

/pony oops

**Comment by alejandrox1** [comment]
While im here...
/joke

**Comment by alejandrox1** [comment]
For approval
/assign @castrojo @cblecker

**Comment by mrbobbytables** [comment]
I gotchu
/approve

**Pull request merged**
