### PR TITLE
SIG-scalability charter.

### PR DESCRIPTION
**Pull request by porridge**
SIG-scalability leads:
/cc @wojtek-t @countspongebob
Steering committee representatives:
/cc @thockin @smarterclayton @spiffxp

### CODE REVIEW

**Comment by thockin** [comment]
lgtm

**Comment by wojtek-t** [comment]
LGTM

@countspongebob - I agree that we may be able to tweak it in the future, but I think it's great starting point.

**Comment by porridge** [comment]
ping @smarterclayton @spiffxp

**Comment by wojtek-t** [comment]
@bgrant0607 @jdumars - FYI if you have any suggestions

**Comment by porridge** [comment]
@smarterclayton @spiffxp please comment
This is my last week working on kubernetes, so I'd like to get this submitted.

**Comment by porridge** [comment]
These are very good questions, none of which I know answers to.
@shyamjvs @wojtek-t @countspongebob can you comment on the above?
@wasylkowski-a FYI we'll probably need a new owner for this PR since it's unlikely we will be able to find an agreed upon answer to this question, get the final approvals and get it merged in the remaining 3 days.

**Comment by wasylkowski-a** [comment]
Re. the PR I will take it over if needed, but let's discuss the course of action offline.

**Comment by bgrant0607** [comment]
FYI, we're working on a SIG charter template here:
https://github.com/kubernetes/community/pull/1650

It's still missing things like scope of the SIG.

Please also make sure your subprojects are correctly identified in https://github.com/kubernetes/community/blob/master/sigs.yaml

**Comment by wasylkowski-a** [comment]
I have created a copy (#1829) where we should continue given that this PR will not be updated anymore (see @porridge's comment).

**Comment by bgrant0607** [comment]
cc @kubernetes/steering-committee

**Comment by wojtek-t** [comment]
I've openede https://github.com/kubernetes/community/pull/2149 as a replacement.

**Pull request closed without merging**
