### PR TITLE
Replace fejta with bentheelder as sig-testing chair

### PR DESCRIPTION
**Pull request by fejta**
/assign @BenTheElder @spiffxp @stevekuznetsov 
/hold

https://groups.google.com/d/msg/kubernetes-sig-testing/vnk-E_du6Qc/u-IDrG1sAAAJ

### CODE REVIEW

**Comment by aojea** [comment]
+1

**Comment by justaugustus** [comment]
+1!
/pony party

**Comment by markyjackson-taulia** [comment]
Strong +1
/honk

**Comment by oomichi** [comment]
+1

@BenTheElder helps a lot of people with his quick response in Slack and github.
@fejta Thank you so much for helping people as a chair in long-term.

**Comment by MHBauer** [comment]
congrats and thanks to both!

**Comment by tehcyx** [comment]
congrats @BenTheElder

**Comment by neolit123** [comment]
congrats @BenTheElder . thanks @fejta !
/meowvie space

**Pull request merged**
