### PR TITLE
[Sig-list] Update Redspread -> CoreOS

### PR DESCRIPTION
**Pull request by RobDolinMS**
Per https://coreos.com/blog/coreos-welcomes-redspread.html

### CODE REVIEW

**Comment by idvoretskyi** [comment]
cc @kubernetes/sig-aws-misc

**Comment by cblecker** [comment]
Also, this change should be made [here](https://github.com/kubernetes/community/blob/master/sigs.yaml#L109) and then "make" run to update the docs dynamically.

**Comment by RobDolinMS** [comment]
Closing this PR per @cblecker's [comment](https://github.com/kubernetes/community/pull/783#issuecomment-313425143): 

> this change should be made [here](https://github.com/kubernetes/community/blob/1663458c12bd5fe855fa237f6a41f56404d55e00/sigs.yaml#L130) and then "make" run to update the docs dynamically.

**Pull request closed without merging**
