### PR TITLE
Demo commit for SCALE16x - DO NOT MERGE

### PR DESCRIPTION
**Pull request by guintestdummy**
This is a pull request demonstation as part of a talk for new contributors!

### CODE REVIEW

**Comment by thesandlord** [comment]
Great Talk!

**Comment by cblecker** [comment]
@guineveresaenger is a rockstar! Hi SCaLE 👋

**Comment by tpepper** [comment]
Thank you @guineveresaenger for enhancing
/sig contributor-experience
and welcome to the SCALE folks!

**Comment by guineveresaenger** [comment]
This was lovely, folks.

To summarize: Only people assigned to the PR may `/lgtm`.
You may assign yourself if you're a member, using `/assign`.
Members may be `/assign`ed by anyone (as per bot suggestion).

One thing we didn't cover in depth was that a code owner must `/approve` a PR _in addition_ to an `/lgtm` by a member. Again, the bot suggestions will help you out here, unless you want to keep a specific code owner.

I'll be closing this PR so it won't clog the issues.

**Comment by guintestdummy** [comment]
Closing this pull request because it has served its purpose.

**Pull request closed without merging**
