### PR TITLE
Update regular meeting schedule for WG etcd-operator

### PR DESCRIPTION
**Pull request by ahrtr**
- For the `day`, we can choose from one of `Monday`, `Tuesday` and `Wednesday`. I am OK with any of them. Please feel free to feedback your preferred day on [Doodle](https://doodle.com/meeting/organize/id/b4YlnEVd)
- For the `time`, the organisers come from different time zones, 11:00 am PT is the best time I can think of. It's the same time as the existing etcd community meeting. 
  - @ahrtr (UTC+1)  **7:00 PM**
  - @jmhbnz (UTC+12) **6:00 AM**
  - @hakman and @neolit123  (UTC+3)  **9:00 PM**
  - @jberkus and @justinsb (UTC-7) **11:00 AM**
- Regarding the `archive_url`, we are still waiting for https://github.com/kubernetes/community/issues/7937 to be resolved.

cc @serathius and @wenjiaswe as well

Please feel free to feedback/comment. thx

### CODE REVIEW

**Comment by neolit123** [comment]
only monday works for me, but i'm not an organizer.
did you consider  a doodle? (doodle.com)

**Comment by ahrtr** [comment]
> did you consider a doodle? (doodle.com)

Yes, I considered. I was thinking that adding comments under a PR might be good enough. But anyway, created a doodle, https://doodle.com/meeting/participate/id/b4YlnEVd

**Comment by neolit123** [comment]
you can also share the doodle link in #sig-etcd slack

**Comment by kvaps** [comment]
All right, I'll also share it with our guys

**Comment by ahrtr** [comment]
> you can also share the doodle link in #sig-etcd slack

Done & thx

**Comment by ahrtr** [comment]
Based on the feedback on [doodle](https://doodle.com/meeting/organize/id/b4YlnEVd), we received almost the same number of votes for Monday, Tuesday, and Wednesday. But all organiers are available on Tuesday, so the first meeting will be Aug 6th (Tuesday).

Suggest to get this PR merged firstly so that everyone is well aware of the schedule. We can raise a separate PR to update the `archive_url` once https://github.com/kubernetes/community/issues/7937 is resolved.

**Comment by Priyankasaggu11929** [comment]
/lgtm
/approve

Keeping the hold for further SIG leads approval!

**Review by neolit123 — COMMENTED** [review]
/lgtm
/hold cancel

make sure to add:
```
    archive_url: TBD
    recordings_url: TBD
```
in a follow up.

**Comment by ahrtr** [comment]
> make sure to add:
> 
> ```
>     archive_url: TBD
>     recordings_url: TBD
> ```
> 
> in a follow up.

We will update `archive_url` once https://github.com/kubernetes/community/issues/7937 is resolved, and update the `recordings_url` once the first recording is uploaded to youtube. thx

**Pull request merged**
