### PR TITLE
Adding Janet Kuo to SIG Apps chairs

### PR DESCRIPTION
**Pull request by mattfarina**
This was announced in this past Monday's SIG Apps meeting.

Welcome @janetkuo.

/cc @kow3ns @prydonius

### CODE REVIEW

**Comment by cblecker** [comment]
@mattfarina Was there sig consensus on this? I don't see any mailing list postings, or items on the agenda other than the "announcement".

**Comment by mattfarina** [comment]
@cblecker I just spent a bunch of time re-reading the SIG Governance and the SIG Apps charter, to catch noted deviations. One thing that isn't clear is the selection of someone to a position that is already a Member.

A member as it is described in the section for adding people to positions and removing them is designated as:

> Within this section "member" refers to a member of a Chair, Tech Lead or Subproject Owner Role. (this different from a SIG or Organization Member).

Janet is a member already as she is a subproject owner (found in OWNERS files linked off of SIG Apps).

What the membership section does not do is talk about role changes among members. For example, what happens when a subproject owner becomes a tech lead or a SIG chair becomes a subproject owner?

Other SIGs have recently changed roles by a vote among people in that role. For example, a super-majority vote among existing SIG co-chairs to add a new one.

In this particular case:

* I proposed Janet
* A unanimous vote among existing co-chairs
* At the SIG Apps meeting it was asked  about and no issues were brought (lazy consensus)

I'm happy to take this to the mailing list as well. But, is that a requirement? I ask because I'd like to know the requirements more than anything.

**Comment by cblecker** [comment]
@mattfarina In sig-governance.md it mentions:
> This SHOULD be supported by a majority of SIG Members or Subproject Contributors (as applicable).

The way this has been typically done with other sigs is with a lazy consensus period via the mailing list. This gives an opportunity of contributors in all time zones to voice their support or concerns.

The mailing list consensus period not a strict requirement, but it's a common way for a sig to demonstrate the support that *is* required. I agree though, that sig-governance could be clearer in that regard. (cc: @kubernetes/steering-committee)

**Comment by mattfarina** [comment]
@cblecker What's interesting about the text is the way member is defined. Those who are on the mailing list or otherwise attend the meetings are not technically members for this particular point. I understand why it's defined this way; it would be incredibly difficult to track another definition of member.

**Comment by bgrant0607** [comment]
@cblecker @mattfarina 

There isn't a documented standard procedure. I agree it would be helpful for there to be one. It's typically hard to find people to do the job, so the lack of one hasn't been much of a problem in most SIGs.

Generally chair, TL, and subproject owner additions and removals have, by design, worked similarly to OWNERS file changes. This change looks consistent with that approach, and so looks fine to me.

I do agree that some SIGs announce such changes on their mailing lists to allow a few days for (non-binding) comments. I probably would have done so, if only to provide the opportunity for SIG participants to express support for Janet, who has worked on Kubernetes since prior to 1.0 and on the workload APIs and controllers since around 1.1.

**Comment by mattfarina** [comment]
I sent an email to the list. It's at https://groups.google.com/forum/#!topic/kubernetes-sig-apps/kMw2BwrHVSQ

**Comment by cblecker** [comment]
/approve
/hold

@mattfarina feel free to pull the hold whenever you feel that consensus has been reached :)

**Comment by cblecker** [comment]
Oh, and I’ll leave LGTM to one of your co-chairs

**Pull request merged**
