### PR TITLE
generator: add support for stakeholder SIGs for WGs

### PR DESCRIPTION
**Pull request by nikhita**
Tries to move https://github.com/kubernetes/community/issues/2176 forward.

https://github.com/kubernetes/community/blob/master/committee-steering/governance/wg-governance.md#creation-process-description specifies that WGs should have stakeholder SIGs. This PR adds support for mentioning the stakeholder SIGs in `sigs.yaml`. `make generate` will then automatically update `sig-list.md` and the relevant WGs' `README.md`s. 

/hold
Do we want to add some stakeholder SIGs in this PR and iterate later? Or do we want to mention all of them in this PR?
Note: if we don't mention _any_ stakeholder SIGs right now, but want to add support for stakeholder SIGs in the generator, then I can modify the template for `sig-list.md` such that the "Stakeholder SIGs" column in not shown if none of the WGs have that specified.

/committee steering
/sig contributor-experience
/kind feature

### CODE REVIEW

**Comment by parispittman** [comment]
lgtm but will hold for a tech review from cblecker or spiffxp

thank you so much @nikhita 🙇‍♀️ !! awesome

**Comment by spiffxp** [comment]
@nikhita can you rebase? at a glance this seems ok, I will ping steering today

**Comment by nikhita** [comment]
@spiffxp Thanks, rebased.

**Comment by spiffxp** [comment]
/approve
/lgtm
Steering is fine with this and felt like they don't need to be involved.  The larger generator PR is already at `needs-rebase` so I'd rather proceed with this.  We'll leave the column empty and solicit WG's to fill in (or can take a stab based on the awesome work done by @zjs)

**Comment by spiffxp** [comment]
/hold cancel
I wanna PR in SIG stakeholders for wg-k8s-infra :)

**Pull request merged**
