### PR TITLE
Update sig-docs README to point to the current meeting notes.

### PR DESCRIPTION
**Pull request by davidewatson**

### CODE REVIEW

**Comment by zacharysarah** [comment]
@davidewatson Thank you!

/lgtm
/approve

**Comment by mrbobbytables** [comment]
@davidewatson Those links are all auto-generated from  [sigs.yaml](https://github.com/kubernetes/community/blob/master/sigs.yaml#L1094). If you change it there, then run `make generate` or `make generate dockerized` it should update every place the link is referenced. :)

**Comment by nikhita** [comment]
:wave: @davidewatson could you update sigs.yaml as per https://github.com/kubernetes/community/pull/3485#issuecomment-477983266?

**Comment by zacharysarah** [comment]
@davidewatson Feel free to `/reopen` when you're ready to resume this PR!

Otherwise, I recommend that we:
/close

**Pull request closed without merging**
