### PR TITLE
Fixed url of wg's google group in community/wg-k8s-infra/charter.md

### PR DESCRIPTION
**Pull request by bartsmykla**
According to: https://github.com/kubernetes/k8s.io/issues/166

Signed-off-by: Bart Smykla <bsmykla@vmware.com>

### CODE REVIEW

**Comment by idealhack** [comment]
@bartsmykla Thank you for fixing this, could you sign the CLA?

**Comment by bartsmykla** [comment]
Hi @idealhack - I'm in the process of doing so. :-)

**Comment by bartsmykla** [comment]
Should be signed now. :-)

**Comment by bartsmykla** [comment]
Ah, I was wrong, but now it is :-D

**Comment by idealhack** [comment]
🎉

/ok-to-test
/assign @spiffxp

**Pull request merged**
