### PR TITLE
Add sig/pm label to SIG list

### PR DESCRIPTION
**Pull request by nikhita**
In the sig list, the current label for sig-product-management is "none". This is:
1. well, incorrect. :)
2. renders wrongly generated code in `sig-product-management/README.md`.

This PR updates the label as `sig/pm`.

Currently, we don't have `sig/pm` in the list of labels in the label configuration in test-infra. Also, the bot command `/sig pm` doesn't work.

See https://github.com/kubernetes/test-infra/pull/8336 which adds the label to the label configuration and allows the bot command to work. I think we should put an explicit hold on this PR until https://github.com/kubernetes/test-infra/pull/8336 is merged.
/hold

/cc cblecker idvoretskyi justaugustus

### CODE REVIEW

**Comment by nikhita** [comment]
Oh well, `sig/pm` was automatically added here. :)

**Comment by nikhita** [comment]
> Oh well, sig/pm was automatically added here. :)

That's due to https://github.com/kubernetes/community/blob/master/sig-product-management/OWNERS#L5

**Comment by idvoretskyi** [comment]
@nikhita can you please update the PR?

It could be broken by https://github.com/kubernetes/community/pull/2068

**Comment by cblecker** [comment]
This was completely obsoleted by #2068 :)
/close

**Comment by nikhita** [comment]
> This was completely obsoleted by #2068 :)

oops, should have checked the open PRs first :woman_facepalming:

**Pull request closed without merging**
