### PR TITLE
Rename security-context-constraints.md to pod-security-policy.md

### PR DESCRIPTION
**Pull request by php-coder**
It's counter intuitive that proposal about PSP has name `security-context-constraints.md`.

@pweil- Do you have objections against renaming a file?

CC @simo5

### CODE REVIEW

**Comment by php-coder** [comment]
This doc also has a link for Google Analytics that should be renamed too but I don't know which format it should have:
```
<!-- BEGIN MUNGE: GENERATED_ANALYTICS -->
[![Analytics](https://kubernetes-site.appspot.com/UA-36037335-10/GitHub/docs/proposals/security-context-constraints.md?pixel)]()
<!-- END MUNGE: GENERATED_ANALYTICS -->
```

**Comment by eparis** [comment]
Didn't we give up on GENERATED_ANALYTICS in the repos?  I know we did in core cube. I think all of the CI verifiers are gone. I think you can just delete it and everyone will be ok...

**Comment by php-coder** [comment]
> Didn't we give up on GENERATED_ANALYTICS in the repos?

I don't know, probably we didn't for this repo:
```console
$ fgrep -rc 'BEGIN MUNGE' contributors/ | awk -F: '{sum+=$2}END{print sum}'
204
```

**Comment by bgrant0607** [comment]
I don't think analytics matter for these docs, and we solve the problem a different way for kubernetes.io docs. I don't even know if anyone still has the credentials for the analytics account.

**Comment by bgrant0607** [comment]
I think that renaming the doc is a good idea, btw.

**Comment by php-coder** [comment]
PR has been updated to remove Google Analytics link.

**Pull request merged**
