### PR TITLE
2019 Survey Analysis Results

### PR DESCRIPTION
**Pull request by wilbry**
**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Comment by mrbobbytables** [comment]
@wilbry Thanks for putting all this together :)
if you could, please go ahead and [sign the cla](https://github.com/kubernetes/community/blob/master/CLA.md#how-do-i-sign).

After that, if you don't mind please squash your commits together. While not always achievable, we do try and keep a pretty clean git history^^:;;;

If you have questions, feel free to reach out here or directly to me (mrbobbytables) in slack :)

**Comment by parispittman** [comment]
@wilbry add the folder to the hack file in community, you'll see 2018 survey in there, too. 
[.spelling_failures](https://github.com/kubernetes/community/blob/master/hack/.spelling_failures)

**Comment by mrbobbytables** [comment]
Giving it a little closer look -- shouldn't the `__cache__/*.pyc` files not be included in a commit? Those are generated and often ignored 😬

**Comment by wilbry** [comment]
Yes you are correct, I will remove those from the commit now.

**Comment by mrbobbytables** [comment]
@wilbry would you mind taking a look at this? 

https://github.com/kubernetes/community/pull/4660

I've cleaned up all the commits. With your sign-off I can push over this branch and we should be able to get it merged 👍

**Comment by mrbobbytables** [comment]
Thanks for all your effort on this :)

This has been superseded by #4660 with the commits cleaned up.


With that I'm going to go ahead and close this out.

/close

**Pull request closed without merging**
