### PR TITLE
Kris Nova bio for steering committee

### PR DESCRIPTION
**Pull request by kris-nova**
Update description of my bio for the Kubernetes steering community.

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
@kris-nova please move your bio to dir `community/elections/2017` when you are ready. See: #1030 

cc @calebamiles

**Comment by xiangpengzhao** [comment]
ping @kris-nova :)

**Comment by kris-nova** [comment]
Updated - kindly merge whenever you'd like

**Comment by cblecker** [comment]
@kris-nova It looks like your bio is currently over 700 words which is unfortunately way over the guideline of less than 300. Would you mind trimming it down a bit? Also, when complete, please also remove the WIP from the PR title as currently the PR will not merge with it in.

Thanks!

**Comment by kris-nova** [comment]
Yep I'm on it!

**Comment by kris-nova** [comment]
@cblecker ready when you are

**Pull request merged**
