### PR TITLE
Add Operator Framework community channel for outreach and planning 

### PR DESCRIPTION
**Pull request by asmacdo**
Signed-off-by: Austin Macdonald <austin@redhat.com>

### CODE REVIEW

**Comment by castrojo** [comment]
/approve

Though maybe consider just #operator-framework with a good description to keep the name smaller in the UI?

**Comment by jberkus** [comment]
@asmacdo any reason not to just call it #operator-framework ?

**Comment by asmacdo** [comment]
we already use #kubernetes-operators for technical discussions, we wanted this channel for community planning (ie kubecon)

**Comment by jberkus** [comment]
OK then.

/lgtm

**Pull request merged**
