### PR TITLE
lister-gen documentation

### PR DESCRIPTION
**Pull request by MHBauer**
documentation based on reverse engineering of usage.

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
@ncdc - do we want to document this here or in the api_changes.md file?  I think it may help to also have a link to this file from coding-conventions.md just for discoverability.

**Comment by ncdc** [comment]
I think api_changes.md makes more sense.

**Comment by philips** [comment]
@MHBauer closing this based on @ncdc wanting to put it in api_changes.md

**Pull request closed without merging**
