### PR TITLE
Add the cluster lifecycle SIG to the Kubernetes community documentation.

### PR DESCRIPTION
**Pull request by roberthbailey**

### CODE REVIEW

**Comment by idvoretskyi** [comment]
LGTM except the SIG-leads field - haven't you selected them?

**Comment by roberthbailey** [comment]
Not that I know of.

**Comment by mikedanese** [comment]
LGTM

**Comment by roberthbailey** [comment]
@jbeda did you push directly (without a PR)? My PR had conflicts with the README placeholder that you added 2 days ago but I don't see a PR from you that added it.

**Comment by jbeda** [comment]
Yeah. I looked at commit history and there were other changes that didn't
use PRs. I was treating it like a wiki.

Did I do wrong? Are we doing PRs for quick updates here?

**Comment by roberthbailey** [comment]
I have no idea, but you could have just merged my PR instead of pushing changes :)

**Comment by jbeda** [comment]
I actually did it all from the web interface. Didn't see your PR. Sorry!

**Comment by roberthbailey** [comment]
No worries. Although the "how to start a sig" docs say "Submit a PR to add any SIG-related docs, schedules, roadmaps, etc. to your new kubernetes/community/SIG-foo directory."

**Comment by idvoretskyi** [comment]
@jbeda FYI, yeah, we've switched from the Wiki format to repo markdown files.

**Comment by sarahnovotny** [comment]
PR means some needs to review and merge.   Using the repo like a wiki
without PRs would be quicker.  any concerns?

**Pull request merged**
