### PR TITLE
Add French meetup cities channels

### PR DESCRIPTION
**Pull request by remyleone**

### CODE REVIEW

**Comment by jeefy** [comment]
@remyleone Are there already existing/established meetups in all the cities? If yes, huge +1 :)

**Comment by remyleone** [comment]
https://www.meetup.com/Cloud-Native-Computing-Paris/
https://www.meetup.com/Cloud-Native-Computing-Toulouse/
https://www.meetup.com/Cloud-Native-Computing-Bordeaux/

@rekcah78 @etiennecoutaud @rbenzair

**Comment by rbenzair** [comment]
yes @jeefy i confirm.

**Comment by jeefy** [comment]
Awesome!

/lgtm

**Comment by mrbobbytables** [comment]
Thanks!
/approve

**Pull request merged**
