### PR TITLE
Add 2 users to the dra-dev group

### PR DESCRIPTION
**Pull request by catblade**
Add Atanas and myself to the DRA user group.

**Which issue(s) this PR fixes**: None-just user addition.

### CODE REVIEW

**Review by mrbobbytables — CHANGES_REQUESTED** [review]
@catblade can you add the slack uid to github handle in [users.yaml](https://github.com/kubernetes/community/blob/master/communication/slack-config/users.yaml)? ([context](https://github.com/kubernetes/community/tree/master/communication/slack-config#users))

After that it should be good to go 👍

**Comment by catblade** [comment]
@mrbobbytables  Done!

**Comment by mrbobbytables** [comment]
Thanks!
/ok-to-test
/label tide/merge-method-squash

**Pull request merged**
