### PR TITLE
Publishing proposed metrics

### PR DESCRIPTION
**Pull request by Phillels**
I would welcome any feedback on this.

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
bump for CLA check

**Comment by sarahnovotny** [comment]
LGTM

**Comment by sarahnovotny** [comment]
@k8s-bot ok to test

**Comment by sarahnovotny** [comment]
@k8s-bot test this

**Comment by grodrigues3** [comment]
The CLA check is the problem, not our K8s CI.  Let's ask them to bump the check again.

@thelinuxfoundation

**Comment by Phillels** [comment]
I did sign it.

**Comment by sarahnovotny** [comment]
@dankohn @caniszczyk @thelinuxfoundation could one of you help this get through our CLA check?

**Comment by caniszczyk** [comment]
@sarahnovotny pinged helpdesk@lf, they should investigate today

@sarahnovotny is there a way to update the k8s bot message to also include a "If you run into issues with signing the CLA, email Linux Foundation Helpdesk <helpdesk@rt.linuxfoundation.org>"

**Comment by cmluciano** [comment]
Can we add details to the README about how a member would leverage these queries? Is there a plan to also add a chart with the results?

**Comment by caniszczyk** [comment]
From the LF/CNCF helpdesk

> Thanks for reaching out, it looks like the CLA wasn't signed by this user. I don't have a document record for her email, nor does her Linux Foundation ID note her as an authorized contributor. I'd recommend having her try to sign up to contribute as an employee again, and to let us know if/where she runs into an error or has any issues.

**Comment by Phillels** [comment]
Jordan Evans from the Linux Foundation reached out and I think we got it cleared up. Thanks @caniszczyk!

**Pull request closed without merging**
