### PR TITLE
verify that files were not removed without changing sig.yaml

### PR DESCRIPTION
**Pull request by SergeyKanzhelev**
/kind cleanup

Context: https://kubernetes.slack.com/archives/C1TU9EB9S/p1714768291414659

### CODE REVIEW

**Review by BenTheElder — COMMENTED** [review]
/lgtm
/approve
thanks!

**Comment by SergeyKanzhelev** [comment]
@cblecker is this one good to go?

**Comment by SergeyKanzhelev** [comment]
/unhold

this can be reverted if it will break anything

**Pull request merged**
