### PR TITLE
Setting up a slack channel for sig-storage subproject kubernetes-cosi

### PR DESCRIPTION
**Pull request by xing-yang**
This PR adds a slack channel for the kubernetes-cosi subproject under sig-storage. We are having weekly design meetings and working on prototyping. We'd like to have a slack channel for communication.

https://github.com/kubernetes/community/tree/master/sig-storage#kubernetes-cosi

CC @saad-ali @msau42 @jsafrane @jeffvance

### CODE REVIEW

**Comment by xing-yang** [comment]
I got an error:
    ```cannot define channel "sig-storage-cosi" in "sig-storage/*.yaml"```

So it looks like sig-storage-cosi is not an acceptable channel name.  Can we use "cosi" instead?

**Comment by jeffvance** [comment]
@xing-yang Yup, see that error. I'm wondering if changing _config.yaml_ is the right approach. I have no experience in this but was reading this [doc](https://github.com/kubernetes/community/tree/master/communication/slack-config#channels) on adding a new channel and there's no mention of config.yaml...

**Comment by brahmaroutu** [comment]
I think the restrictions are mentioned under communication/slack-config/restrictions.yaml  are as follows. We need to change them to allow the name.

  - path: "sig-storage/*.yaml"
    channels:
      - "^sig-storage$"
      - "^csi$"
      - "^csi-"

**Comment by coderanger** [comment]
Hi there! The subfolder config.yaml files are for delegated prefixes and names, so for example the sig-storage leads can directly approve things matching those regexps. I think I'm okay with changing the first one so that `^sig-storage` is a prefix check but we would need to discuss it between the Slack admin team. But you can also propose this in the main channels.yaml file, it will just need one or two of us to approve rather than the SIG leads :)

**Comment by xing-yang** [comment]
Thanks @coderanger!  Looks like all sig-storage channels are proposed directly in sig-storage/config.yaml.  I'll just follow the tradition to add all sig-storage channels in the same config file.

**Comment by jeffvance** [comment]
Looks good! Thanks Xing

**Pull request merged**
