### PR TITLE
Added "Kubernetes cluster on AWS with Terraform" repo

### PR DESCRIPTION
**Pull request by wombat**

### CODE REVIEW

**Comment by w0mbat** [comment]
@arun-gupta

**Comment by arun-gupta** [comment]
@w0mbat Can you please add it in the alphabetical order?

**Comment by w0mbat** [comment]
@arun-gupta done

**Comment by w0mbat** [comment]
@arun-gupta ok, no sorted in KAT correctly

**Comment by arun-gupta** [comment]
LGTM

/sig-aws

**Comment by arun-gupta** [comment]
@justinsb can you take a look at this?

**Pull request merged**
