### PR TITLE
Added dependancies and wrapper script for linkchecker

### LINKED ISSUE #359: Add a link checker for this repo
While looking at the API conventions docs this morning, I found that many of the links in that doc were broken.  We should add a link checker for this repo (and eventually other repos in the community).

### PR DESCRIPTION
**Pull request by chupman**
Signed-off-by: Chris Hupman <chupman@us.ibm.com>
fixes #359 

Took a first pass at adding the link checker. `hack/verify-links.sh` should get picked up in the make verify step. Everything else is just adding the dependancies for the link checker. It make sense to save the output somewhere so you can actually see what's failing. Right now I have an `$OUTPUT` variable just pointing to `/tmp/` that I would love to update before this is approved to run.  

I could find an example of anyone using any binaries from test-infra so I did my best to piece together a working solution. Please let me know if there is a better way to access the linkcheck binary i.e. is test-infra already accessible from where the tests are run making the extra vendor folders redundant. 

Other items of note, when I checked there were 5000 links. Of those 140 links 404 and anything going to reddit was giving me a 429 from my office network. The three 429s do a 100, 200, and then 400 second retry before failing adding 35 minutes to the run time. If they still 429 when it runs from CI I'll look into filtering them out.

### CODE REVIEW

**Comment by jdumars** [comment]
@chupman was there some discussion about this being a need? I'd love to know a little more about the provenance of the idea, especially with introduction of new dependencies. I am also wary of the issue with 429s.

**Comment by chupman** [comment]
@jdumar I forgot to add the open issue (#359) to the description. The discussion has been getting tagged/untagged as stale for the last year. I figured I would save myself a few emails and just fix it. 

I found a [hacky workaround](https://www.reddit.com/r/learnprogramming/comments/8r02jw/curlpostman_message_too_many_requests_error_429/) for the 429s. I'm going to rerun it today and see how many duplicate links there are, if it's significant I can rework it compile the list of links before checking them. Anything to get the number of links checked down from 5k will help run time.

**Comment by chupman** [comment]
nm. Looks like it's already only hitting each link once, there really are 4946 unique links in this repo's `md` files.

**Comment by chupman** [comment]
So the tests failing is actually validating that the wrapper script is working. Can someone tell me, maybe @spiffxp, where the output should go? Should I figure out how to add the output as an additional artifact (I'm guessing it's somewhere in prow)? I could have it output the failures so it shows up in the `build-log.txt`, but with the current number of failures that would be a lot of output.

**Comment by nikhita** [comment]
/cc

gonna add it to my review queue

**Comment by spiffxp** [comment]
@jdumars for context see https://github.com/kubernetes/community/issues/359#issuecomment-457764350 and the links that points to

@chupman thank you for doing this, two questions:
- can we redo this so it follows a pattern we've used in kubernetes/kubernetes for golint and shellcheck failures? A file is used to keep track of known offenders such that the verify job fails on new offenses, while allowing us to piecemeal address the existing failures  (eg: https://github.com/kubernetes/kubernetes/blob/master/hack/.golint_failures)
- can we get away with using `go.mod` instead of messing with `vendor`?

/retest
the current verify job link shows no artifacts

**Comment by chupman** [comment]
Thanks for the review @spiffxp. I'll add a failures file and get the artifacts added. I'm not sure if I can get it working with `go.mod` without adding to vendor, but I'll take a crack at it.

**Comment by spiffxp** [comment]
It will probably be helpful to have the script output which links failed in which files.  
```
I0618 16:41:24.122] Verifying verify-generated-docs.sh
I0618 16:41:25.652] SUCCESS  verify-generated-docs.sh	1s
I0618 16:41:25.654] Verifying verify-links.sh
I0618 18:30:40.281] FAILED   verify-links.sh	6555s
I0618 18:30:40.298] Verifying verify-spelling.sh
I0618 18:30:43.797] SUCCESS  verify-spelling.sh	3s
I0618 18:30:43.797] ========================
I0618 18:30:43.798] FAILED TESTS
I0618 18:30:43.798] ========================
I0618 18:30:43.798] hack/../hack/verify-links.sh
```

Also, given the amount of time this took to verify links, I suspect we may not want to run this as a presubmit.  kuberenetes/kubernetes has [some eye-watering bash](https://github.com/kubernetes/kubernetes/blob/fe895f04116637583639d5dcbae080f4419ac969/hack/make-rules/verify.sh) to decide which sets of verify scripts to run when, I wouldn't follow it line by line, but something to look at for ideas

**Comment by chupman** [comment]
I'm no longer covered by the CCLA I started this under and have no idea when I would be able to look at this. I'm going to close this out so I'm not blocking someone else from adding this.

**Pull request closed without merging**
