### PR TITLE
wg-k8s-infra: update zoom meeting link

### PR DESCRIPTION
**Pull request by ameukam**
Update zoom meeting link  with password : 77777
Ref: https://groups.google.com/a/kubernetes.io/g/community/c/c3ZSGVLBZuQ/m/UMFcHb8bAgAJ.

Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

### CODE REVIEW

**Comment by ameukam** [comment]
/assign @mrbobbytables @castrojo 
cc @dims @spiffxp @bartsmykla

**Comment by dims** [comment]
I have updated the calendar with the same zoom link as was here in this PR

/approve
/lgtm

**Comment by mrbobbytables** [comment]
Linking to tracking issue: https://github.com/kubernetes/community/issues/5146

**Pull request merged**
