### PR TITLE
Update sig-windows to re-add links that were lost in format change.

### PR DESCRIPTION
**Pull request by bsteciuk**

### CODE REVIEW

**Comment by bsteciuk** [comment]
I should be covered under the Apprenda CLA.

**Comment by cblecker** [comment]
@bsteciuk The CLA status check is still reporting that it cannot find a CLA for you. There are instructions in the [bot message](https://github.com/kubernetes/community/pull/861#issuecomment-318754532) of how to go about fixing it (including contacting the Linux Foundation for support).

**Comment by bsteciuk** [comment]
I believe this should be all set now.

**Comment by mattfarina** [comment]
@michmike you should be able to approve this so that it gets merged.

**Pull request merged**
