### PR TITLE
sig-network: migrate ip-masq-agent to kubernetes-sigs

### PR DESCRIPTION
**Pull request by nikhita**
Ref: https://github.com/kubernetes/org/issues/1154

/assign @caseydavenport @dcbw @thockin 

/hold
for explicit lgtm from sig leads

### CODE REVIEW

**Comment by nikhita** [comment]
/hold cancel

@thockin can you comment again with `/lgtm` on it's own line? :)

**Comment by thockin** [comment]
/lgtm

we should fix the bot to accept the rest as a comment :)

**Pull request merged**
