### PR TITLE
IoT Edge working group 2021 annual report

### PR DESCRIPTION
**Pull request by dejanb**
Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/community/issues/6389

### CODE REVIEW

**Review by parispittman — CHANGES_REQUESTED** [review]

**Comment by parispittman** [comment]
@dejanb here are the next steps for wind down: https://github.com/kubernetes/community/blob/master/sig-wg-lifecycle.md#prerequisites-for-wg-retirement

**Comment by dejanb** [comment]
@parispittman it definitely makes sense to find a good space within CNCF where this community can continue (as there are ~500 folks in the slack). We don't have any place yet, can you help us find one? IMHO it'd be good to have a new place before we shut everything down, so that people can move in time.

Please let me know what you think it's the best way to proceed.

**Comment by kate-goldenring** [comment]
@raravena80 with your experience on the CNCF Runtime TAG, do you have a sense where the K8s IoT Edge WG community could migrate to within the CNCF? We may have grown out of our charter in K8s, especially since IoT edge solutions expand beyond K8s.

**Comment by raravena80** [comment]
@kate-goldenring and all. This group is suitable to be migrated into TAG-Runtime.  You can get started by submitting a charter PR to the https://github.com/cncf/tag-runtime repo. The charter can include any IoT Edge existing and additional scope that the chair/leads intends to address.

**Comment by dejanb** [comment]
@raravena80 @parispittman Thanks a lot for your support. We'll start preparing necessary steps to do this transition.

**Comment by mrbobbytables** [comment]
/close
The IoT Edge WG is moving to the CNCF

**Pull request closed without merging**
