### PR TITLE
Adding aws-service-operator slack channel

### PR DESCRIPTION
**Pull request by sd0408**
Add the aws-service-operator channel to slack for better collaboration. 

https://github.com/aws/aws-service-operator-k8s/issues/12

https://github.com/aws/aws-service-operator-k8s

**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Comment by sd0408** [comment]
> please reply here with a new comment and we'll verify. Thanks.

I've filled out the form.

**Comment by vishakhanihore** [comment]
@sd0408 I think your CLA was not successful, Can you verify once again?
Thanks!

**Comment by sfzylad** [comment]
I opened #4468 that addresses exact the same change since this one is stuck for a bit. I hope you don't mind @sd0408 😄

**Comment by mrbobbytables** [comment]
@sd0408 - I'm going to go ahead and close this in favor of #4468. It looks like there's still an issue with the cla status. =/

If you need help with the CLA, please log a ticket with the LF Help desk here: https://support.linuxfoundation.org/

/close

**Pull request closed without merging**
