### PR TITLE
sig-cluster-lifecycle: add etcdadm office hours meeting

### PR DESCRIPTION
**Pull request by dlipovetsky**

### CODE REVIEW

**Comment by moshloop** [comment]
Any chance of not making this on a Friday?  9am PT is 6pm SAST which is the start of my sabbath and means I will never be able to attend. I fully understand if it isn't feasible though

**Comment by dlipovetsky** [comment]
@moshloop Thanks for bringing that to my attention! Come to think of it, others near your time zone have also expressed frustration with meetings that take place during their Friday evenings, since that's a time people often reserve for friends and family, or other occasions. I apologize for my oversight.

Given the Doodle votes, I could have flipped a coin between Monday 9am PST and Friday 9am PST, but then I thought that it would be easy to alternate times with the kops office hours. Reflecting on your comment, Monday 9am PST is the better choice.

I'll update the PR and the messages on discuss.kubernetes.io and the google group.

**Comment by dlipovetsky** [comment]
We've agreed on the time slot.

/hold cancel

**Pull request merged**
