### PR TITLE
add contributor-comms slack team for upstream marketing

### LINKED ISSUE #4515: create new slack team/user group for upstream marketing
need to create @contributor-comms as a team in slack so folks can reach out to us as one (out of many) methods, this one hitting our real time needs. this is a reminder PR for myself but if someone wants this as a good first issue or a friendly PR and it's still open - take it. :)

jonasrosland
chrisshort
tunde
simplytunde
onlydole
Rin Oliver
and me - paris

need to get ok to add from karthik, nzoueidi

https://slack.com/help/articles/212906697-Create-a-user-group

### PR DESCRIPTION
**Pull request by tao12345666333**
**Which issue(s) this PR fixes**:

Fixes #4515

cc @parispittman

### CODE REVIEW

**Comment by parispittman** [comment]
Oh no - this is supposed to be a slack team and not a slack channel

**Comment by tao12345666333** [comment]
@parispittman Don't worry, let me modify it.

**Comment by tao12345666333** [comment]
@parispittman PTAL, Thanks!

**Comment by parispittman** [comment]
Looks good thank you :)

**Comment by mrbobbytables** [comment]
/approve
👍

**Comment by tao12345666333** [comment]
still need LGTM label for merge 😄

**Comment by parispittman** [comment]
/lgtm

Could have sworn I saw the label already :)

**Comment by tao12345666333** [comment]
Thanks!

**Pull request merged**
