### PR TITLE
Update Cluster API Provider AWS office hours time

### PR DESCRIPTION
**Pull request by richardcase**
After consultation in the last 2 office hours calls we have decided to
move the call 1 hour earlier to make it more friendly in time for
contributors in European and APAC regions.

Signed-off-by: Richard Case <richard@weave.works>

**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Comment by fabriziopandini** [comment]
@neolit123

**Review by neolit123 — COMMENTED** [review]
/approve

**Review by mrbobbytables — COMMENTED** [review]
/approve

**Pull request merged**
