### PR TITLE
Request for a new slack channel to collaborate chaos engineering on K8S

### PR DESCRIPTION
**Pull request by umamukkara**
The open source chaos engineering project "Litmus" is a tool set for orchestrating chaos on Kubernetes. The project is at https://github.com/litmuschaos . As the users of this project will be in the Kubernetes community, we are requesting a separate channel to collaborate the communication.

Signed-off-by: Uma Mukkara <uma@mayadata.io>

### CODE REVIEW

**Comment by umamukkara** [comment]
@jeefy @mrbobbytables

**Comment by jeefy** [comment]
/approve

Waiting for another slack admin to lgtm

**Comment by mrbobbytables** [comment]
/lgtm 
+1 from other slack admin

**Comment by umamukkara** [comment]
Thank you @jeefy @mrbobbytables

**Pull request merged**
