### PR TITLE
Clarify the use of lgtm and approve labels

### LINKED ISSUE #2771: Update "Testing and Merge Workflow" to clarify /lgtm and /approve labels
Following up on the discussion about the behavior of /lgtm and /approve labels, update documentation to clarify purpose and behavior of each.

/sig docs

/assign hogepodge

@dims @parispittman 

https://groups.google.com/d/msg/kubernetes-sig-contribex/_FMoL0qAN_s/5ocHsC4RBQAJ
https://github.com/kubernetes/test-infra/pull/9151

### PR DESCRIPTION
**Pull request by hogepodge**
Clarify the use of lgtm and approve labels and call out special cases which may result in surprising behavior by the code review system.

Fixes #2771

### CODE REVIEW

**Comment by hogepodge** [comment]
/sig docs
/sig contributor-experience

cc: @parispittman @dims

**Comment by jdumars** [comment]
/approve

Thanks for this PR!

**Comment by hogepodge** [comment]
@spiffxp I sent this patch up a little while ago, but could reconcile with what you're presenting

**Pull request merged**
