### PR TITLE
channels: add cluster-api-cloudstack slack channel

### PR DESCRIPTION
**Pull request by rohityadavcloud**
This proposes to add a new cluster-api-cloudstack Slack channel for use of community building, participation and discussion around CAPI provider for Apache CloudStack (http://cloudstack.apache.org/), an opensource IaaS cloud computing platform. This is under the cluster-api sub-project of k8s cluster-lifecycle SIG. We're in process of proposing and donating this provider to the SIG.

### CODE REVIEW

**Comment by coderanger** [comment]
@rohityadavcloud Can you get someone from the SIG to sign off on this?

**Comment by rohityadavcloud** [comment]
@coderanger sure, we'll ask for support within the SIG in the next meeting or on mailing list.

**Comment by rohityadavcloud** [comment]
cc @fabriziopandini @sbueringer

**Comment by fabriziopandini** [comment]
@rohityadavcloud 
According to https://github.com/kubernetes/community/blob/master/communication/slack-guidelines.md#requesting-a-channel

> Channels should be dedicated to SIGs, WGs, UGs, sub-projects, community topics, or related Kubernetes programs/projects.

and

> Linking to resources such as the PR adding the subproject will speed in the validation and processing of the channel creation request.

So as far as I can understand we can unblock this issue as soon as we have the request for the new sub-project repository in kubernetes-sigs.

But hopefully, the slack admins will chime in and comment too.

**Comment by rohityadavcloud** [comment]
Thanks @fabriziopandini we'll join the next SIG call on Tues/22nd Feb and try to build support and get our project accepted. In the meanwhile, follow your guidance and open an issue for the new sub-project (repository migration).

**Comment by rohityadavcloud** [comment]
Requesting SIG chair and leads to add their support on this PR, in line with the repo creation request on https://github.com/kubernetes/org/issues/3279 cc @neolit123 @vincepri @fabriziopandini

**Comment by neolit123** [comment]
+1

**Review by markyjackson-taulia — APPROVED** [review]
/lgtm

**Comment by fabriziopandini** [comment]
+1

**Comment by vincepri** [comment]
+1

**Comment by rohityadavcloud** [comment]
cc @jdumars @markyjackson-taulia @idvoretskyi tests have passed, pl check and approve. Thanks.

**Comment by rohityadavcloud** [comment]
Fantastic, thanks @jdumars

**Pull request merged**
