### PR TITLE
sigs.yaml: remove Jess Frazelle from Security Committee

### PR DESCRIPTION
**Pull request by philips**
Jess helped to kick off the Security Committee over two years ago.
And has decided to step down. Thanks for everything!

### CODE REVIEW

**Comment by castrojo** [comment]
/lgtm

Consider adding an emeritus section so we can thank those who have contributed their time.

**Comment by dims** [comment]
+1 to list of emeritus members

**Comment by philips** [comment]
/lgtm

/assign @tallclair 

Tim- please approve.

**Pull request merged**
