### PR TITLE
Add discuss communication guidelines

### PR DESCRIPTION
**Pull request by mrbobbytables**
Adds discuss.k8s.io specific communication guidelines.

reference: #2884 

/cc @parispittman @castrojo

### CODE REVIEW

**Comment by parispittman** [comment]
/lgtm

thanks bob!! 💯

**Comment by parispittman** [comment]
thanks bob!! after jorge's review, he can hit the approve button :)

**Comment by castrojo** [comment]
/approve

Thanks for this Bob!

**Pull request merged**
