### PR TITLE
adding slack channel for Yelp

### PR DESCRIPTION
**Pull request by drmorr0**
We'd like to create a new slack channel for Yelpers working on Kubernetes, and where we can announce new things we've built on top of Kubernetes :)

### CODE REVIEW

**Comment by mrbobbytables** [comment]
@drmorr0 we really don't encourage company specific channels. If there is a yelp kubernetes centric open source project, that we can make a case for.

**Comment by drmorr0** [comment]
@mrbobbytables Oh, sorry, I didn't realize that, I just saw a few other companies with channels (linode/digitalocean, for example).  We will be open-sourcing our in-house autoscaler for kubernetes in the next 2 weeks or so, but I'm OK closing this PR if that's not appropriate (or we can wait until we've actually released that).

As an aside, maybe it's worth updating the docs to say something about discouraging company slack channels?  I didn't see anything about that in the existing docs, but also maybe I missed it.  :)

**Comment by mrbobbytables** [comment]
@drmorr0 theres a bit of wiggle room for those as they offer hosted kubernetes offerings -- similar to amazon, google etc.

**Comment by jdumars** [comment]
+1 to what @mrbobbytables said. Let's go ahead and close this and open another when your project is launched. :) Also, we're happy Yelp is Kubernetting

**Comment by drmorr0** [comment]
Got it, that makes sense.  Sorry for the spam!

**Pull request closed without merging**
