### PR TITLE
Add rlenferink as slack-config owner

### PR DESCRIPTION
**Pull request by rlenferink**
This adds myself as [slack-config/](https://github.com/kubernetes/community/tree/master/communication/slack-config) OWNER. I have been (pro tempore) moderator since #3374 and would like to help out with this as well.

This can also help with response times since Ihor is the only EMEA approver right now.

/cc @mrbobbytables @idvoretskyi

### CODE REVIEW

**Comment by rlenferink** [comment]
Any thoughts on this @mrbobbytables ?

**Comment by mrbobbytables** [comment]
Ah, sorry -- missed this one too -_-
I'm on-board - would you mind updating the list here too?
https://github.com/kubernetes/community/blob/master/communication/moderators.md#slack
It could also be a follow up PR if thats easier

**Comment by rlenferink** [comment]
@mrbobbytables no problem & done :)

**Comment by rlenferink** [comment]
_gentle ping at a second slack owner_ @castrojo

**Comment by jeefy** [comment]
/lgtm

@castrojo Just got back from vacation and is probably buried under emails :)

**Pull request merged**
